### ISSUE TITLE
Android build patches

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#100]
_From [tim.n.braun](https://code.google.com/u/116242509010032389221/) on November 06, 2013 07:44:45_

Explaination of new feature Android.mk and iperf_api.c changes to build for Android AOSP environment. Justification of new feature Useful utility on AOSP projects.

**Attachment:** [0001-More-standardish-header-file-locations.patch 0002-Initial-Android-port.patch 0003-Use-cache-for-temp-files-on-Android-stop-some-compil.patch 0004-Build-host-utility-build-static-not-shared-library.patch](http://code.google.com/p/iperf/issues/detail?id=100)

_Original issue: http://code.google.com/p/iperf/issues/detail?id=100_

**Comment by hamsterksu** [comment]
hi, do you have any instruction how to build android version of iperf3?
i googled but haven't got result ^(

**Comment by bmah888** [comment]
Android isn't one of our supported platforms.  We might be willing to take a non-disruptive pull request for build fixes.  Closing this issue for now.
