### ISSUE TITLE
the output of bandwidth can't match the parameter of -b 

### ISSUE THREAD

**Issue by FeiOrFei** [esnet/iperf#1020]
I run only a iperf client on Android with version 2.0.6
the command line is:
```iperf -c 192.168.1.1 -u -b 30m -i 1 -t 99999```

but the output is:
```
0.0 - 1.0 sec             4GBytes               34.4 Gbits/sec
```

the issue is random

**Comment by bmah888** [comment]
This GitHub project and issue tracker is for iperf3.  For current developments on iperf2, please see:

https://sourceforge.net/projects/iperf2/
