### ISSUE TITLE
Using -w (window) option of size too high results in empty error message

### ISSUE THREAD

**Issue by etki** [esnet/iperf#1022]
Hi!

I'm playing with my home wi-fi. I don't know network stuff good enough, and generally i guess iperf does everything right, except for error message, i just don't know what i have to tune on my system.

My shell looks like this:

```
etki@vortex:~$ iperf3 -c 192.168.1.144  -w 416k
Connecting to host 192.168.1.144, port 5201
[  4] local 192.168.1.41 port 58894 connected to 192.168.1.144 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-0.74   sec  31.3 MBytes   356 Mbits/sec    1    211 KBytes       
...

# so far so good

etki@vortex:~$ iperf3 -c 192.168.1.144  -w 417k
Connecting to host 192.168.1.144, port 5201
iperf3: error - 
```

# Context

* Version of iperf3:
```
iperf 3.1.3
Linux vortex 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing
```

* Hardware: Intel AX200 (Wi-Fi)

* Operating system: Kubuntu 18.04

# Bug Report

* Expected Behavior

Printing error when kernel doesn't allow to set user-provided value

* Actual Behavior

Empty error message

* Steps to Reproduce

I didn't tweak anything kernel-related in my system, so i guess it's enough to bring up Kubuntu 18.04 (or, likely, any other linux distro), then try to connect as client with absurdly high window size

**Comment by krgouveia** [comment]
Have tried to use some newer iperf version (3.8.1 is the last one)? https://downloads.es.net/pub/iperf/

**Comment by bmah888** [comment]
3.8.1 is indeed the latest version.  I'm not sure off-hand what might cause this problem...417K is not a ridiculously high buffer size (we routinely run tests with >1M buffers, although that sometimes requires some kernel sysctl tuning).

Even if you run out of buffer space, you should get an error message like this:
```
hattori:iperf% src/iperf3 --client localhost -w417m
Connecting to host localhost, port 5201
iperf3: error - unable to set socket buffer size: No buffer space available
```
(The above error message comes from my Macbook Pro but the behavior on Linux should be the same.)

**Comment by davidBar-On** [comment]
It seems that in `iperf_strerror(int int_errno)`, if `int_errno` is not one of the `switch (int_errno)` cases, the returned error string will be null as in this issue.  Suggest to **add a default case** with something like:
```
	default:
	    snprintf(errstr, len, "Errno=%d", int_errno);
	    perr = 1;
	    break;
```

**Comment by bmah888** [comment]
That's a good suggestion. I'm a little surprised there's no default case in this switch statement.

**Comment by bmah888** [comment]
OK, we have some slightly better diagnostics on the mainline now.  Leave this issue open, because we still haven't fixed the underlying cause of this problem yet.

**Comment by bmah888** [comment]
It's been quite awhile since we put some better diagnostics in place, and there haven't been any more reports of this problem. Closing this for now.
