### ISSUE TITLE
Leaks when using iperf_client API

### ISSUE THREAD

**Issue by oleh-yudin-ring** [esnet/iperf#1023]
# Context

* Version of iperf3:
3.7

* Operating system (and distribution, if any):
Linux

# Bug Report

* Expected Behavior
No file descriptor or memory leaks when using client API

* Actual Behavior
File descriptor and memory leaks per each test run via API

* Steps to Reproduce
Descriptors and memory leaks when using iperf_client API:
1. File
  a. When passing a logfile to the API with iperf_set_test_logfile() during iperf_free_test() corresponding test->outfile file descriptor is not being closed leading to a FD leak.
  b. There is no free() call for test->logfile string whih causes memory leak after each test run.

2. Sockets
Under normal circumstances when iperf client test is finalized successfully iperf_client_end() is being called within the API when entered DISPLAY_RESULTS state.
In case of a failure and early exit (for example with IECTRLCLOSE error) iperf_client_end() is not being called leaving stream sockets file descriptors opened forever.

3. Memory
Few more memory leaks were detected:
  a. the one mentioned in 1.
  b. iperf_auth.c load_pubkey_from_base64, there should be free(key) to release memory allocated by Base64Decode
  c. in case of API use with json_output if there was an error during the test (return -1) corresponding cJSON structures allocated with iperf_json_start() are not freed in iperf_run_client().

* Possible Solution
1. In iperf_free_test()  fclose(test->outfile) and free(test->logfile) (watch out for default case when test->outfile=stdout)
2. Call iperf_client_end() in case of test failure to close opened sockets. 
3. Call iperf_json_finish() in case of test failure to release all preallocated json output results.

Example:
```   
void
iperf_free_test(struct iperf_test *test)
{
    ...
    if (test->logfile)
    {
        free(test->logfile);
        if (test->outfile)
            fclose(test->outfile);
    }
    ...
}
```

```
int
iperf_run_client(struct iperf_test * test)
{
    ...
    //return -1;
    goto cleanup_and_fail; // in every place with failure return
    ...
cleanup_and_fail:
    iperf_client_end(test);
    if (test->json_output)
        iperf_json_finish(test);
    iflush(test);
    return -1;
}
```

```
EVP_PKEY *load_pubkey_from_base64(const char *buffer) 
{
    ...
    Base64Decode(buffer, &key, &key_len);
    ...
    BIO_write(bio, key, key_len);
    free(key);
    ...
}
```

**Comment by bmah888** [comment]
@oleh-yudin-ring : Oops.  OK when I committed the pull request I made based on your suggested changes, I neglected to credit you in the commit message, and I don't know a reasonable way to fix this.  My apologies!

**Comment by oleh-yudin-ring** [comment]
@bmah888, not a problem

**Comment by xygwfxu** [comment]
Confirmed at 3.9.1 that there is NO fd leak.

Came here because see this issue on ubuntu 18 (it uses 3.1.3-1) like:
  File "/home/whoami/.local/lib/python3.6/site-packages/iperf3/iperf3.py", line 418, in __init__
  File "/home/whoami/.local/lib/python3.6/site-packages/iperf3/iperf3.py", line 100, in __init__
  File "/usr/lib/python3.6/ctypes/util.py", line 314, in find_library
  File "/usr/lib/python3.6/ctypes/util.py", line 101, in _findLib_gcc
  File "/usr/lib/python3.6/tempfile.py", line 690, in NamedTemporaryFile
  File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
OSError: [Errno 24] Too many open files: '/tmp/tmpe2_zsazt'
