### ISSUE TITLE
iperf3: parameter error - no error

### ISSUE THREAD

**Issue by HLeithner** [esnet/iperf#1024]
# Authentication doesn't provide a useful error message in a container without real TTY

* Version of iperf3: 3.8.1

* Hardware: 
Docker

* Operating system (and distribution, if any): 
Debian Buster in docker container

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
Non TTY environment

# Bug Report

* Expected Behavior
An error message that tells me I didn't provided a password for authentication.

* Actual Behavior
iperf3: parameter error - no error

* Steps to Reproduce
In a docker container without pseudo TTY (you don't need real values, fake file,username and servername is enough)
```bash
docker run -i debian:buster
apt-get update && apt-get -y install iperf3
iperf3 --rsa-public-key-path public.pem --username username -c servername
``` 
You get the error message above, doing the same with a pseudo tty 
```bash
docker run -it debian:buster
apt-get update && apt-get -y install iperf3
iperf3 --rsa-public-key-path public.pem --username username -c servername
```
this gives you a password prompt. It costs me a lot of time because debian buster version doesn't support environment variable IPERF3_PASSWORD and the error message was useless.

* Possible Solution

Add an error number in before returning at 
https://github.com/esnet/iperf/blob/3888e044c33f155fda319a904bfaa9edfc57a5c5/src/iperf_api.c#L1294-L1295

**Comment by bmah888** [comment]
Here's another way to reproduce this that is OS-independent and doesn't require a container setup:
```
% iperf3 --public-key-path public.pem --username foo --server 192.168.56.102 < /dev/null
```

**Comment by HLeithner** [comment]
Thanks for fixing this.
