### ISSUE TITLE
Recommendations for handling very throughput issues

### ISSUE THREAD

**Issue by davidBar-On** [esnet/iperf#1029]
# Context

* Version of iperf3:
NA
* Hardware:
NA
* Operating system (and distribution, if any):
NA

# Suggested documentation or FAQ Enhancement
Based on recommendations given for solving issue #1021 about throughput drop to almost zero, following is a suggested addition to the iperf3 documentation or FAQ for handling such issues.  Although this is not iperf3 SW issue, the recommendation can help iperf3 users to solve similar issues.  For example, it seems that issue #703 and maybe #453, #303 happened because of similar problems.

Note that there is a related pull request #921 for iperf3 to support UDP Generic Segmentation Offload (GSO) on Linux (see also https://man7.org/linux/man-pages/man3/cmsg.3.html).

### The suggested addition to the documentation:

**TCP Offload issues or what to do when throughput drops to almost zero**
Throughput drop to almost zero, except maybe for the first reported interval(s), may be related to problems in **_NIC TCP Off load_**, which is used to offload TCP functionality to the NIC (see https://en.wikipedia.org/wiki/TCP_offload_engine).  _TCP Offload_ target is to save main CPU performance, mainly of un/segmentation of large packets and checksum computation.

When TCP packets are sent with "_Don't Fragment_" flag set, which is the recommended settings, segmentation is done by the TCP stack based on the reported next hope _MSS_ in the _ICMP Fragmentation Needed_ message.  With _TCP Offload_ active segmentation is done by the NIC of the sending side which is known as **_TCP Segmentation offload (TSO)_** or in Windows as **_Large Send Offload (LSO)_**.  It seems that there are _TSO/LSO_ implementations which for some reason ignore the reported _MSS_ and therefore don’t perform segmentation. In these cases, when large packets are sent, e.g. the default _iperf3_ 128KB (131,072 bytes), _iperf3_ will show that data was sent in the first interval, but since the packets don’t get to the server, no ack is received and therefore no data is sent in the following intervals.  It may happen that after certain timeout the main CPU will re-send the packet by re-segmenting it, and in these cases data will get to the server after a while.  However, it seems that segmentation is not automatically continued with the next packet, so data transfer rate be very low. 

The **recommended solution** in such case is to **disable _TSO/LSO_**, at least on the relevant port. See for example: https://atomicit.ca/kb/articles/slow-network-speed-windows-10/.   If that doesn’t help then **"_Don't Fragment_" TCP flag may be disabled**.  See for example: https://support.microsoft.com/en-us/help/900926/recommended-tcp-ip-settings-for-wan-links-with-a-mtu-size-of-less-than.  However, note that disabling the “_Don’t Fragment_” flag may cause other issue.

To **test whether _TSO/LSO_ may be the problem**, do the following:

•	If different machine configurations are used for the client and server, try the **_iperf3_ reverse mode** (_-R_).  With _TSO/LSO_ issue only on the client machine this test should succeed.
•	**Reduce buffer length to a small value** that should not require segmentation, using the _iperf3 -l_ option, e.g. "_-l 512_".   It may also help to _reduce the MTU_ by using the _iperf3 -M_ option, e.g. "_-M 1460_".   With _TSO/LSO_ issue this test should succeed.
•	Using tools like Wireshark **identify the required _MSS_** in the _ICMP_ Fragmentation Needed messages (if reported).  Run tests with the “_-l_” value set to 2 times the MSS and the 4 times, 6 times, etc.  With _TSO/LSO_ issue in each test the throughput should be reduced more.  It may help to increase these tests time beyond the default 10 seconds to better see the behavior (_iperf3 -t_ option).

**Comment by bmah888** [comment]
Thanks for the text!  I'm going to commit a slightly edited version of this.
