### ISSUE TITLE
Client doesn't send traffic in bi-directional UDP test

### ISSUE THREAD

**Issue by andrepuschmann** [esnet/iperf#1045]
# Context

* Version of iperf3:

Current (August 26 2020) git HEAD 52d0de3bfcd37

* Hardware:

x86, iperf session over virtual LTE network over TUN devices

* Operating system (and distribution, if any):

Ubuntu 20.04

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

I am running tests in a scenario where iperf traffic goes over a TUN device through a virtual LTE network using [srsLTE](https://github.com/srsLTE/srsLTE). An app-note on how to set this app can be found [here](https://docs.srslte.com/en/latest/app_notes/source/zeromq/source/index.html#zeromq-appnote). I couldn't reproduce the issue on a traditional network.

# Bug Report

The issue I am seeing is when bi-directional UDP traffic is generated at a very large rate. This rate is well above the capacity of the channel so packets are expected to be dropped, but it should not be zero. If I lower the expected UDP rate, the test runs ok. I assumed that the issue may arise due to dropped TCP packets from the control link (they are equally dropped like the UDP datagrams). However, since the issue arises on the client side and the server side works fine, I am thinking it might be something else.

* Expected Behavior

Both client and server shall start to generate and send UDP traffic at the requested rate.

* Actual Behavior

The client instructs the server to generate traffic. The server does so and I see traffic arriving at the client. However, the client itself does not send traffic (stops after first call to `iperf_udp_send()`).

* Steps to Reproduce

I am unable to reproduce this on a normal network. However, using the above mentioned virtual LTE network the issue can be reproduced with:
```
$ sudo ip netns exec ue1 iperf3 -c 192.168.3.1 --bidir -u -b 500M --debug --verbose -t 1
iperf 3.9+
Linux andre-xps15 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
Control connection MSS 1448
Setting UDP block size to 1448
send_parameters:
{
        "udp":  true,
        "omit": 0,
        "time": 1,
        "parallel":     1,
        "bidirectional":        true,
        "len":  1448,
        "bandwidth":    500000000,
        "pacing_timer": 1000,
        "client_version":       "3.9+"
}
Time: Wed, 26 Aug 2020 10:54:42 GMT
Connecting to host 192.168.3.1, port 5201
      Cookie: bsdwbqufga62k3prewx2oxduqinc36b4fsji
      Target Bitrate: 500000000
SNDBUF is 212992, expecting 0
RCVBUF is 212992, expecting 0
Setting application pacing to 62500000
[  5] local 192.168.3.2 port 37764 connected to 192.168.3.1 port 5201
SNDBUF is 212992, expecting 0
RCVBUF is 212992, expecting 0
Setting application pacing to 62500000
[  7] local 192.168.3.2 port 39512 connected to 192.168.3.1 port 5201
Starting Test: protocol: UDP, 1 streams, 1448 byte blocks, omitting 0 seconds, 1 second test, tos 0


sent 1448 bytes of 1448, total 1448
pcount 1 packet_count 0
interval_len 62.150672 bytes_transferred 1448
interval forces keep
interval_len 62.150674 bytes_transferred 1448
interval forces keep
[ ID][Role] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5][TX-C]   0.00-62.15  sec  1.41 KBytes   186 bits/sec            1
[  7][RX-C]   0.00-62.15  sec  1.41 KBytes   186 bits/sec  0.000 ms  0/1 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID][Role] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5][TX-C]   0.00-62.15  sec  1.41 KBytes   186 bits/sec  0.000 ms  0/1 (0%)  sender
[  5][TX-C]   0.00-62.15  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  receiver
CPU Utilization: local/sender 99.6% (17.6%u/82.0%s), remote/receiver 0.0% (0.0%u/0.0%s)
CPU Utilization: local/receiver 99.6% (17.6%u/82.0%s), remote/sender 0.0% (0.0%u/0.0%s)
[  7][RX-C]   0.00-62.15  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  sender
[  7][RX-C]   0.00-62.15  sec  1.41 KBytes   186 bits/sec  0.000 ms  0/1 (0%)  receiver
iperf3: error - control socket has closed unexpectedly
```

Iperf server is started with the below command and finished as expected:
```
$ iperf3 -s --debug --verbose
....
sent 1448 bytes of 1448, total 2562450304
sent 1448 bytes of 1448, total 2562451752
sent 1448 bytes of 1448, total 2562453200
sent 1448 bytes of 1448, total 2562454648
sent 1448 bytes of 1448, total 2562456096
sent 1448 bytes of 1448, total 2562457544
iperf3: error - select failed: Bad file descriptor
iperf 3.9+
Linux andre-xps15 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64
```

Note that in the example the client runs in the netns and the server not (it runs in the default netns). This is needed to run both on the same machine. However, the same also happens if I swap client and server netns, i.e., run the server in the `ue1` netns and client in the default one.

* Possible Solution

I am currently debugging the stalled send on the client-side but wanted to post the issue anyway to receive any possible pointer in case this happened before. I am aware that this might be difficult to reproduce for third-parties in the current form and I am not even sure it's an iperf3 issue.

**Comment by andrepuschmann** [comment]
I've done some more debugging and it seems that in the case the client traffic isn't generated, the client never enters the running state, i.e. the check for `if (test->state == TEST_RUNNING)` never is true so traffic is not generated. I can't seem to find where the test state is updated on the client side though.

**Comment by andrepuschmann** [comment]
Sorry for the noise on this issue and the discussion with myself. I've realized the server sends the new send state in `iperf_set_send_state()` but the client doesn't receive the message so it never starts transmitting itself.
The server itself starts transmitting immediately after this call itself. Considering the fact that the rate is very high and the channel capacity very low, I guess it's possible that we drop the TCP packets on the control socket.

**Comment by andrepuschmann** [comment]
A little bit more debugging revealed the issue, basically, the TCP socket setting the client test state isn't flushed immediately due to typical TCP buffering. However, since the UDP stream is started immediatly after this `set_send_state()` call, the UDP packets would already overwhelm the link, thus causing high packet drop rates on the link that is shared between control and data sockets.

In my particular scenario, I could solve the issue by enabling the `TCP_NODELAY` flag on the server's control socket. See #1046. I've opened a PR for that but feel free to drop it of course in case you don't see need for it.

In the past I was using nuttcp and made use of the function to have control and data over different interfaces, thus avoiding the above issue.

**Comment by bmah888** [comment]
No worries, this isn't noise.  I think your theory about the UDP traffic interfering with the TCP control channel is at least partly correct.  I haven't finished thinking through everything that's going on with a bidirectional UDP test.  

It feels like `TCP_NODELAY` would be good on both the client and server ends of the control connection (or at the very least it shouldn't hurt).  (As an aside we already have an command-line flag to set `TCP_NODELAY` on TCP connections used for test data.)

**Comment by andrepuschmann** [comment]
Thanks for the feedback. I just wanted to report back that we haven't seen the issue anymore after setting the `TCP_NODELAY` flag. So at least for the described use-case the patch seemed to have worked. I'd close the issue from my side but leave the PR up to you. Thanks again
