### ISSUE TITLE
Enhancement request - iperf command requires 3 to run basic iperf, suggesting change of command default if possible.

### ISSUE THREAD

**Issue by cengbrecht** [esnet/iperf#1050]
# Context

* Version of iperf3: 
iperf 3.1.3
CYGWIN_NT-10.0 BC-W1001 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64
Optional features available: None

&& 

iperf 3.6 (cJSON 1.5.2)
Linux BC-PM01 5.4.34-1-pve #1 SMP PVE 5.4.34-2 (Thu, 07 May 2020 10:02:02 +0200) x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication

* Hardware:
iperf Server:
i7-4930k, 32GB ram, 10Gbps SFP+ Mellanox ConnectX-2
iperf Client
Dual E5-2620 v2, 64GB ram, 10Gbps SFP+ Mellanox ConnectX-2
Testing Jumbo Frames - Not enabled atm.

* Operating system (and distribution, if any):
iperf Server:
Windows 10, 1909
iperf Client
Proxmox 6.2-4

# Enhancement Request

* Current behavior
Running iperf on Linux runs older version iperf 2 something.

* Desired behavior
Running iperf on Linux defaults to latest version, (I may need to reinstall, infact let me try that first)
Tested after purging iperf, no change in desired behavior. (I do know that I can make a shortcut to the proper iperf command)

**Comment by bmah888** [comment]
The iperf3 executable is named `iperf3` to allow it to co-exist with the older version of iperf.  There are no plans to change this.
