### ISSUE TITLE
Enhancement request - Version mismatch on new to older (Server to client)

### ISSUE THREAD

**Issue by cengbrecht** [esnet/iperf#1051]
* Version of iperf3 Server:
iperf 3.1.3
CYGWIN_NT-10.0 BC-W1001 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64
Optional features available: None

* Version of iperf3 Client:
Was iperf v2.0.2 at the time.

Hardware:
iperf Server:
i7-4930k, 32GB ram, 10Gbps SFP+ Mellanox ConnectX-2
iperf Client
Dual E5-2620 v2, 64GB ram, 10Gbps SFP+ Mellanox ConnectX-2
Testing Jumbo Frames - Not enabled atm.

Operating system (and distribution, if any):
iperf Server:
Windows 10, 1909
iperf Client
Proxmox 6.2-4

# Enhancement Request

* Current behavior
Outdated, or wrong client connects, transfers one time, and errors out with a command issue.

* Desired behavior
Newer versions detect older/not recognized client, and suggest checking versions in logfile.

**Comment by bmah888** [comment]
This is very similar (or closely related anyway) to #221. Going to close this as a duplicate.
