### ISSUE TITLE
Jitter values missing in iperf 3.1.3

### ISSUE THREAD

**Issue by laxman479** [esnet/iperf#1053]
What is the command to get jitter values in iperf 3.1.3

**Comment by bmah888** [comment]
Jitter values are only available (but generated automatically) for UDP tests.  This is true for every version of iperf3.  Also note that there are various definitions of jitter; iperf3 implements the algorithm in RFC 1889 (Appendix A.8).  For more information, read the file `iperf_udp.c` in the iperf3 source distribution.

You should be aware that iperf-3.1.3 is quite old.  The current version as of this writing is 3.9.
