### ISSUE TITLE
Fix documentation: --timestamps with user-defined format needs "="

### ISSUE THREAD

**Issue by lbsou** [esnet/iperf#1055]
iperf 3.9+ (cJSON 1.7.13) (Github latest master commit)
VMWare virtual machine
Red Hat Enterprise Linux Server release 7.8 (Maipo)

Since https://github.com/esnet/iperf/issues/909, we can activate the line by line timestamps but I'm unable to specify the format.

--timestamps    <format>  emit a timestamp at the start of each output line
                            (using optional format string as per strftime(3))

I know it is not caused by my system because I was able to change it by manually editing src/iperf_api.c, around line 4332 by replacing :

strftime(iperf_timestr, sizeof(iperf_timestr), iperf_get_test_timestamp_format(test), ltm);
by
strftime(iperf_timestr, sizeof(iperf_timestr), "%F %T ", ltm);

* Expected Behavior

Specify a format with the --timestamp 

* Actual Behavior

Stay with default format

* Steps to Reproduce

Try to add optional format

Thanks!

**Comment by bmah888** [comment]
Works from here.  Can you say what command-line arguments you used?
```
bmah-centos7:iperf% src/iperf3 --client localhost --timestamps="%s " -t 5
1601064278 Connecting to host localhost, port 5201
1601064278 [  5] local ::1 port 50518 connected to ::1 port 5201
1601064279 [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
1601064279 [  5]   0.00-1.00   sec  3.76 GBytes  32.3 Gbits/sec    0   2.00 MBytes
1601064280 [  5]   1.00-2.00   sec  3.59 GBytes  30.9 Gbits/sec    0   2.00 MBytes
1601064281 [  5]   2.00-3.00   sec  3.33 GBytes  28.6 Gbits/sec    0   2.00 MBytes
1601064282 [  5]   3.00-4.00   sec  3.55 GBytes  30.5 Gbits/sec    0   2.00 MBytes
1601064283 [  5]   4.00-5.00   sec  3.70 GBytes  31.7 Gbits/sec    0   2.00 MBytes
1601064283 - - - - - - - - - - - - - - - - - - - - - - - - -
1601064283 [ ID] Interval           Transfer     Bitrate         Retr
1601064283 [  5]   0.00-5.00   sec  17.9 GBytes  30.8 Gbits/sec    0             sender
1601064283 [  5]   0.00-5.04   sec  17.9 GBytes  30.6 Gbits/sec                  receiver
1601064283
1601064283 iperf Done.
```

**Comment by lbsou** [comment]
Hi!

Thank you for your answer.

I was missing the "=" sign. I was using a space instead.

Maybe it should be written in the help?

Thank you again!
