### ISSUE TITLE
Unable to get ToS/DSCP markings working on windows server 2016

### ISSUE THREAD

**Issue by rwestengage** [esnet/iperf#1060]
# Context
iperf3 -S flag not working

* Version of iperf3:
3.1.3-win64 (but have tried all other version 2.0.9 and 3.0.11 also same result

* Hardware:
vmware

* Operating system (and distribution, if any):
Windows server 2016

# Bug Report
Using the following command
iperf3.exe -c server.server.com -l 1000 -u -p 5060 -f m -b 50Mb -S 184 -t 30
No Packets are ToS/DSCP marked

* Expected Behavior
Capturing with wireshark both on the outgoing client and the server expect to see DSCP marked packets

* Actual Behavior
All packets are 0x0 unmarked

**Comment by rwestengage** [comment]
Actually apologies this is due to windows behaviour

fixed it using group policy as per article here:
http://www.iperfwindows.com/IPERF-QoS-tests2.html

**Comment by bmah888** [comment]
I'm going to close this issue on the assumption there's nothing for me to do here from the iperf3 standpoint.  Feel free to re-open if this isn't the case.
