### ISSUE TITLE
iperf running time limitation

### ISSUE THREAD

**Issue by Doron458** [esnet/iperf#1062]
Hello,
I saw the iPerf running time limitation is set to 86400 in the src/iperf.h file. Is there any option of override this limitation and run iPerf for a longer time than 1 day? 

Thanks

**Comment by bmah888** [comment]
That limit exists as a kind of a sanity check to prevent naïve users from doing something they (or others) might regret. If you really have a need to run iperf3 longer than that, you can modify the constant and recompile the program.
