### ISSUE TITLE
Update documentation with instructions for how to build for Windows

### ISSUE THREAD

**Issue by cypherstream** [esnet/iperf#1067]
There are many people who just need to get the latest version of iperf to run network testing between two windows endpoints.  The latest compiled version on the internet is 3.1.3-win64 which has a nasty issue on the server side crashing with repeating "Bad file descriptor" if a tester uses many threads (32 or more) once the test is complete.  The iperf3 code on github is newer and easy to build in Linux, but some users do not want the overhead or complexity of running a linux vm on their windows laptop or desktop endpoints.

Please consider updating documentation with full instructions how to build for Windows, or enlist some handy volunteers to host prebuilt windows builds.

**Comment by olekstomek** [comment]
Ad hoc solution in case you need the current exe version is [here](https://www.neowin.net/forum/topic/1234695-iperf-39-windows-build/#comments).
Of course, that doesn't solve the problem of building the image yourself.

**Comment by cypherstream** [comment]
Cool
That's a big help.

I tried the latest but get Cannot send control message: bad file descriptor.  I'll back off a version or two until I get one that works.

**Comment by cypherstream** [comment]
Cool 3.7 with the updated Cygwin dll's works great so far.  Thanks for the link!

**Comment by olekstomek** [comment]
That's great. :)

**Comment by davidBar-On** [comment]
Note @olekstomek comment in #1069 after successfully building iperf3 for Windows:
> I think issues #1067 and #1073 can be closed, the documentation for me was sufficient and simple ...

**Comment by bmah888** [comment]
Closing per https://github.com/esnet/iperf/issues/1069#issuecomment-729082216
