### ISSUE TITLE
Allow 'UDP secure mode' by only allowing UDP test to commence after TCP has run.

### ISSUE THREAD

**Issue by nizedk** [esnet/iperf#1072]
# Enhancement Request

* Current behavior

iperf3 when publicly exposed in UDP mode can be used to DoS with little effort from an attacker; this would allow the attacker to get the iperf3 server to send a large amount of UDP trafifc towards a third party.

* Desired behavior

Implement an option in iperf, to have the server run in a 'udp secure' mode, where the server  - for at set duration - caches the source IP addresses that have performed a TCP test and allow them to UDP test as well afterwards.

The secure mode could also set a max limit of UDP bandwidth/length etc, so that requesting 20G of UDP at 50byte length does not happen.

With the above mentioned changes, it would be possible for someone to provide a relatively open iperf3 service without risking being a DoS enabler.

Thank you for a utility that I couldn't live without.

Kind regards,
Martin

**Comment by bmah888** [comment]
iperf3 already requires some interaction on the TCP control connection between the source and destination, before any test packets are run. This is true for both TCP and UDP tests. I'm not sure what would be gained by forcing the iperf3 server to support a TCP test from a given address first.

Please note there is already a rate-limiting option (added fairly recently) that will end a test (or not allow it to start) if too large of a bitrate is specified by the client. That's probably a good idea whenever untrusted clients are involved.

Finally, it's not really possible with an unmodified iperf3 server to make it send data to a third party, at least as far as I'm aware. The server will only send traffic back towards the client that requested the connection in the first place.
