### ISSUE TITLE
iperf server should start measuring CPU utilization after the client connects not earlier

### ISSUE THREAD

**Issue by jtluka** [esnet/iperf#1076]
# Context

* Version of iperf3:

I used a build from https://github.com/olichtne/iperf/tree/fix_burst_mode, but I believe this is bug is present in latest iperf code as well. This branch is based on commit c47e43d5a3e222318e5c7fd17178c57e5b10c9a3.

* Hardware:
Any

* Operating system (and distribution, if any):
Linux

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

# Bug Report

The iperf server reports CPU utilization since the launching of the iperf server process and not since the actuall test start.

* Expected Behavior

The iperf server should report CPU utilization after the iperf client connects and starts the test.

* Actual Behavior

The iperf server CPU utilization depends on how long the server runs before the client connects and starts the test.

* Steps to Reproduce

Simply compare the CPU utilization in json output of server for following test scenarios:
1. start iperf server with json output format, wait 2 seconds, run iperf client that connects to the server
```
                "cpu_utilization_percent":      {
                        "host_total":   28.56335027483129,
                        "host_user":    6.18877428988225,
                        "host_system":  22.374568343317126,
                        "remote_total": 0,
                        "remote_user":  0,
                        "remote_system":        0
                },
```

2. start iperf server with json output format, wait 10 seconds, run iperf client that connects to the server
```
                "cpu_utilization_percent":      {
                        "host_total":   18.155508141151934,
                        "host_user":    4.0793554618947807,
                        "host_system":  14.076152679257154,
                        "remote_total": 0,
                        "remote_user":  0,
                        "remote_system":        0
                },
```

* Possible Solution

The initialization call to `cpu_util()` should be done after the connection from client is accepted.

**Comment by olichtne** [comment]
Optionally, it would be interesting if cpu utilization was sampled at the same rate as the streams.
