### ISSUE TITLE
UDP out of order with very large received packet identification

### ISSUE THREAD

**Issue by sheep94lion** [esnet/iperf#1083]
# Context

* Version of iperf3: 3.1.3

* Hardware: 

* Operating system (and distribution, if any): 
server - ubuntu
client - windows 10

When I test udp transmission with iperf3, I met following error message:
`iperf3: OUT OF ORDER - incoming packet = 57267 and received packet = 122720 AND SP = 4`
According to my understanding, the number reported is the identification which is two bytes, however, 122720 is too large for a two-byte int. Is this a bug or my understanding wrong?

**Comment by bmah888** [comment]
UDP sequence numbers are 32-bit integers unless the `--udp-counters-64bit` flag is given, in which case they're 64-bit integers.  So a value of 122720 is perfectly reasonable.

I see you're using iperf-3.1.3, you should be aware that this is a very old version...there are newer versions of iperf3 that are, basically better. The latest version as of this writing is 3.9.
