### ISSUE TITLE
Iperf Bidir Stuck before it finishes when -t is set

### ISSUE THREAD

**Issue by abraaocaldas** [esnet/iperf#1085]
# Context

* Version of iperf3: Iperf 3.9 - bd1437791a63579d589e9bea7de9250a876a5c97 

* Hardware:
Intel(R) Xeon(R) Platinum 8171M / 8GB RAM

* Operating system (and distribution, if any):
Centos 8

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

None

# Bug Report
Set Bi-directional test, set a time flag for 600 seconds

iperf3 -c host -p 5209 --bidir -t 600

* Expected Behavior
When timer hits 600 , iperf should finish 

* Actual Behavior
It hangs on 599 seconds and the output is not show or iperf done is not show

* Steps to Reproduce
iperf3 -c host -p 5209 --bidir -t 600

**Comment by bmah888** [comment]
Have not been able to reproduce this on tip of master. Does the "context" information (thanks for providing that by the way, it's useful information) apply to both sides of the iperf3 test? Does the problem still exist with a shorter time (smaller `-t` value)?
