### ISSUE TITLE
Superfluous authentication output in server JSON mode

### ISSUE THREAD

**Issue by mfeit-internet2** [esnet/iperf#1086]
# Context

* Version of iperf3: 3.7 and later

* Hardware: VM

* Operating system (and distribution, if any):  CentOS 7/8

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):  Nada.

# Bug Report

* Expected Behavior

```
{ ... JSON Output ... }
```

* Actual Behavior

```
Authentication successed for user 'zzz' ts 1606770991
{ ... JSON Output ... }
```

* Steps to Reproduce

```
host1$ iperf3 -s -1 --json -p 5201 --authorized-users-path xxx --rsa-private-key-path yyy 
```
```
host2$ IPERF3_PASSWORD="xxx" /usr/bin/iperf3 -p 5201 -c host1 -t 10 --json --rsa-public-key-path yyy --username zzz
```

* Possible Solution

Don't write messages to stdout when producing JSON

**Comment by bmah888** [comment]
Yep, this is a bug, confirmed.
