### ISSUE TITLE
Building Iperf3 (cloning latest) installs iperf 3.1.3 on Ubuntu 18.04

### ISSUE THREAD

**Issue by edgar-costa** [esnet/iperf#1104]
# Context

I am trying to build the latest version of iperf3 in my ubuntu 18.04 machine. For that I follow the steps in the main readme of this repository. Latest version should be 3.9+ however `iperf3 -v` reports `3.1.3`. The same process in ubuntu 16.04 results into 3.9 being installed.

* Operating system (and distribution, if any): Ubuntu 18.04, kernel 4.20

**Comment by bmah888** [comment]
My guess would be that on the Ubuntu 18.04, you're picking up an iperf3 executable that's not the one you compiled. Is it possible there's an iperf3 package that was installed as a part of the OS? (Ubuntu 18.04 does ship with iperf-3.1.3 so there's some precedent for that.) You might need to explicitly give the path to the executable that you built.

**Comment by francisyyan** [comment]
I can confirm that the issue still persists -- `iperf3 v3.1.3` will be installed at `/usr/local/bin` on Ubuntu 18.04 even after the APT-managed package `iperf3` is not installed.

In fact, the compiled binary at `iperf/src/.libs/iperf3` will show a version of `3.1.3`, contradicting with the binary `iperf/src/iperf3` that has a correct version. To force the system to use the version that is intended to install, I have to manually copy _both_ `iperf/src/iperf3` and the folder `iperf/src/.libs` to `/usr/local/bin`.

I did not get a chance to look into what was wrong in iperf's Makefile, but I presume this should be a quick fix.
