### ISSUE TITLE
Unable to send control message: Bad file descriptor

### ISSUE THREAD

**Issue by Meonardo** [esnet/iperf#1105]
# Context

* Version of iperf3:
iperf 3.9 (cJSON 1.7.13)
* Hardware:
Mac mini (M1, 2020)
* Operating system (and distribution, if any):
macOS 11.1 (20C69)

# Bug Report

* Expected Behavior
macOS is the Client
run iperf3 -c 192.168.6.17:9991 on mac
* Actual Behavior
`iperf3: error - unable to send control message: Bad file descriptor`

**Comment by bmah888** [comment]
Hrm, first report of using iperf3 on Apple Silicon!

The `:9991` probably doesn't do what you want, however. Perhaps you mean something like `iperf3 -c 192.168.6.17 -p 9991`?

**Comment by Meonardo** [comment]
> Hrm, first report of using iperf3 on Apple Silicon!
> 
> The `:9991` probably doesn't do what you want, however. Perhaps you mean something like `iperf3 -c 192.168.6.17 -p 9991`?

Works great, Thanks for reply.

**Comment by devondragon** [comment]
I am having this same issue, same iperf version, same hardware, same error.

[devon:~]$ iperf3 -c 192.168.1.60
iperf3: error - unable to send control message: Bad file descriptor

[devon:~]$ iperf3 -c 192.168.1.60 -p 5201
iperf3: error - unable to send control message: Bad file descriptor

[devon:~]$ iperf3 -c 192.168.1.60 -p 5201 -t 5
iperf3: error - unable to send control message: Bad file descriptor
