### ISSUE TITLE
packet  size  is the same in multiple  clients

### ISSUE THREAD

**Issue by ilyosbekibrohimov** [esnet/iperf#1106]
Hi,  I am trying to test network bandwidth with iperf.
1. I installed  iperf
2. Tested in  one  client
3. Tested in 10 clients
4. but in (2) and in (3) cases overall bandwidths (Sum) were almost the same and when I  compared 1-st bandwidth (2) with each bandwidth in  (3) 1-st  bandwidth was much greater than each partial bandwidth of (3). But I did not understand why?

![Capture](https://user-images.githubusercontent.com/46449085/105673659-b3d04200-5f29-11eb-9f73-40d185e08e53.PNG)
![Capture1](https://user-images.githubusercontent.com/46449085/105673664-b59a0580-5f29-11eb-8682-7ef5c26129f0.PNG)

**Comment by davidBar-On** [comment]
Hi,
It seems that the network bandwidth between the client and server is about 95Mbps.  When the client opened only one stream to the server in (2), that stream could use the full network bandwidth. In (3) the client opened 10 streams to the server, so each of them got about 10th of the bandwidth, i.e. 9.5Mbps.

To make sure this is the case, try for example with 3 streams.  In this case each stream should get about third of the bandwidth, i.e. about 32Mbps.

**Comment by ilyosbekibrohimov** [comment]
Thanks, and when I tested it with 100,200 and more clients I got some errors like "connection reset by peer".  What should be done to eliminate this error?
Thanks

**Comment by davidBar-On** [comment]
These errors may be related to system limitations related to 100 streams in parallel with about 100Mbps network bandwidth. To understand what is causing the errors, network traffic log is required, i.e. using Wireshark.

Part of the issue may be that the packets length is too large for that configuration.  iperf3 default TCP packet size is 128KB, and with 100 parallel streams you get about 120KB/sec per stream.  I suggest to try with much smaller packets using the `-l` option - e.g. `-l 512`.
