### ISSUE TITLE
iperf  multiple  clients

### ISSUE THREAD

**Issue by ilyosbekibrohimov** [esnet/iperf#1111]
Hi everyone,  I am trying to check the network bandwidth with multiple clients. iPerf is working well with 10,50 and 100 clients but when I tested with 200 or more than  200 clients I got some errors like  'connection timed out' or  'network error connection reset by peer'.  What may  be the possible problem?
Thank  you:)

**Comment by davidBar-On** [comment]
If you are using the same environment as in issue #1106, then it may be that the 95Mbps network is overloaded.  To test if this is the case, try to limit the bandwidth for each stream (client) and the message length, so the total bandwidth required will be within the network limits.  Also, the message length should be reduced, as the default 128KB message is too large.

E.g. set bandwidth to 8Kbps by `-b 8K` and set message length to 512 bytes by `-l 512`.
If that helps, try different values to these two parameters to see what is the maximum that can be achieved (probably bandwidth cannot be  beyond 95Mbps/200=450Kbps - about 50KB/sec).

**Comment by ilyosbekibrohimov** [comment]
I am still getting Connection timed out error...

![image](https://user-images.githubusercontent.com/46449085/106457173-ebaf2a80-64d1-11eb-8f1f-7c7de07a6a5e.png)
![Capture](https://user-images.githubusercontent.com/46449085/106457179-efdb4800-64d1-11eb-8c5b-4891acde6aa2.PNG)

**Comment by davidBar-On** [comment]
Seems that you are using **iperf2** (version 2.08b), while the issue was opened for iper3 (by the way, iperf3 is currently limited to 128 parallel streams).  You should probably start a "discussion" under [https://sourceforge.net/projects/iperf2/](https://sourceforge.net/projects/iperf2/).

Also, it seems that you are using old version of iperf2 (version 2.1), so you may first try the test with the latest release from the above site.

**Comment by lealog** [comment]
🤦‍♂️

A segunda, 1/02/2021, 12:42, David Bar-On <notifications@github.com>
escreveu:

**Comment by bmah888** [comment]
Not an iperf3 issue, closing.  Thanks to @davidBar-On for issue triage!

**Comment by ilyosbekibrohimov** [comment]
thanks everyone
