### ISSUE TITLE
在哪可以下载到Windows的编译二进制版本？

### ISSUE THREAD

**Issue by 1265578519** [esnet/iperf#1124]
在哪可以下载到Windows的编译二进制版本？
https://github.com/esnet/iperf/releases
这里只有源代码下载，有没有编译好的

**Comment by 1265578519** [comment]
Binary Distributions¶
Note that ESnet does not distribute binary packages of iperf3. All of the packages listed in this section are provided by third parties, who are solely responsible for their contents. This is an incomplete list of binary packages:

FreeBSD: benchmarks/iperf3 in the FreeBSD Ports Collection

Fedora / CentOS: iperf3 and iperf3-devel in Fedora 19 and 20 and in Fedora EPEL 5, 6, and 7. iperf3 is included as a part of RedHat Enterprise Linux 7.4 and later (as well as CentOS 7.4 and later).

Ubuntu: iperf3, is available in Trusty (backports), and as a part of the main release in Vivid and newer.

macOS: via HomeBrew.

Windows: iperf3 binaries for Windows are available from iperf.fr (and other sources).

**Comment by 1265578519** [comment]
[iperf-3.1.3-win64.zip](https://github.com/esnet/iperf/files/5993695/iperf-3.1.3-win64.zip)

**Comment by shiwenwang** [comment]
A non-official but reliable site: https://files.budman.pw/
