### ISSUE TITLE
Non JSON error message at the end of JSON output at the client-side of the measurement

### ISSUE THREAD

**Issue by zokl** [esnet/iperf#1143]
* Version of iperf3: master, 787919c4b3614b28f45587753f3a778a0157110c

* Hardware: x86_64

* Operating system (and distribution, if any): Linux, OpenWRT, iperf compiler from github repo

# Bug Report

* Expected Behavior

* Actual Behavior

Non JSON error message at the end of JSON output at the client-side of the measurement. For now, I found only described behavior for this message: "iperf3: error - unable to send control message: Broken pipe". Server-side produces valid JSON output. 

## Wrong JSON output on client-side
[client-4.iperf3.gz](https://github.com/esnet/iperf/files/6350988/client-4.iperf3.gz)

```
			"remote_total":	0,
			"remote_user":	0,
			"remote_system":	0
		},
		"sender_tcp_congestion":	"cubic"
	}
}
iperf3: error - unable to send control message: Broken pipe
```

## Good JSON output on server-side
[server-4.iperf3.gz](https://github.com/esnet/iperf/files/6350992/server-4.iperf3.gz)

```
				"bytes":	0,
				"bits_per_second":	0,
				"omitted":	false,
				"sender":	false
			}
		}],
	"end":	{
	},
	"error":	"error - select failed: Bad file descriptor"
}
```

* Steps to Reproduce

/usr/bin/iperf3 -c 1.2.3.4 --connect-timeout 1000 -t 3600 --logfile test-4.iperf3 -p 5201 -J --parallel 5 -i 1 --window 32k --set-mss 1400
/usr/bin/iperf3 -c 1.2.3.4 --connect-timeout 1000 -t 3600 --logfile test-2.iperf3 -p 5200 -J -R --parallel 5 -i 1 --window 32k --set-mss 1400

**Comment by davidBar-On** [comment]
I tried to run the non-reverse test ("test-4.iperf3" log) on my local machine and there was no problem.  **Maybe try running using the latest iperf3 code** (lately some changes were done that that may be related).  If that won't help, maybe debug info (`-V -d`) can help.

The error probably happened in client when for some reason when [trying to send IPERF_DONE state](https://github.com/esnet/iperf/blob/787919c4b3614b28f45587753f3a778a0157110c/src/iperf_client_api.c#L449-L453) to the server fails.  Since this is done [after the JSON output is created](https://github.com/esnet/iperf/blob/787919c4b3614b28f45587753f3a778a0157110c/src/iperf_client_api.c#L446-L447), the error is shown outside of the JSON.

**Comment by zokl** [comment]
The described problem occures if during the connection interface goes down during the test. Typicall situation is a mobile interface and its restart because of problem with signal etc. 

For testing is good to use following scenarios:

1) On server: iperf3 -s
2) On client: /usr/bin/iperf3 -c 1.2.3.4 --connect-timeout 1000 -t 60 --logfile test.iperf3 -p 5201 -J --parallel 5 -i 1 --window 32k --set-mss 1400
3) On client: wait 5 seconds for test start
4) On client: ifconfig wwan0 down
5) Wait for ending iperf3 (it take several minutes)
 
JSON output in test.iperf3 is not correct because it end by 

```
                            "host_total":   0.32808521971039462,
                        "host_user":    0.065823820341056063,
                        "host_system":  0.26226304830393965,
                        "remote_total": 0,
                        "remote_user":  0,
                        "remote_system":        0
                }​​​​​,
                "sender_tcp_congestion":        "cubic"
        }​​​​​
}​​​​​
iperf3: error - unable to send control message: Broken pipe
```

and this is not a correct JSON format.

The same JSON format problem occures if test ends by „iperf3: error - idle timeout for receiving data”. This could be reproduced by following scenario:

1) On server: iperf3 -s 
2) On client: /usr/bin/iperf3 -c 1.2.3.4 --connect-timeout 1000 -t 60 --logfile test.iperf3 -p 5201 -J --parallel 5 -i 1 --window 32k --set-mss 1400 -R --rcv-timeout 5000
3) On client: wait 5 seconds for test start
4) On client: ifconfig wwan0 down
5) Wait for ending iperf3 (it take several seconds)

JSON output in test.iperf3 is not correct too:

```
                                "end":  11.001215,
                                "seconds":      0.999882996082306,
                                "bytes":        0,
                                "bits_per_second":      0,
                                "omitted":      false,
                                "sender":       false
                        }
                }],
        "end":  {
        }
}
iperf3: error - idle timeout for receiving data
```

**Comment by davidBar-On** [comment]
Thanks for the additional information - helped to understand what is the problem.  Submitted PR #1146 with a suggested fix.

**Comment by zokl** [comment]
> Thanks for the additional information - helped to understand what is the problem. Submitted PR #1146 with a suggested fix.

Thank you for fix.

**Comment by bmah888** [comment]
Another way to reproduce this problem is just to kill the server side during the test.
