### ISSUE TITLE
Iperf3 udp silent gap

### ISSUE THREAD

**Issue by nicke7676** [esnet/iperf#1145]
I have an annoying problem I’d like to discuss if you have any idea or recommendation.

I use iperf3.7 to measure the throughput of a system that is capable of around max 4 Gbps.

The iperf3 server is running on a Linux machine.
I start the traffic with this command on the client side with the following flags, -R option to let the server send to the client:
iperf3 -c 32.0.161.84 -u -l 1360 -b 550M -P 8 -w 16M -R -t 3000

Most of the times everything works as expected, I receive around 4 Gbps.
But on some occasions, like 1-2 times of 10 iterations I receive lower throughput than expected. How much lower seem to be random, could be 2 Gbps or 3 or 3.5.
When I get the low throughput scenario, it usually stays low for several minutes. Sometimes, after a couple of minutes it could recover by itself up to max speed and sometimes it stays low longer time.
When I get this low throughput scenario, I can get a good throughput scenario if stopping the traffic and starting again and in this case the client side have received a new ip address as it’s dynamically assigned to the client on each iteration.

Looking at the printouts from sending server side it says it’s sending 8x550M and I have also checked with ifstat that also shows it sends 4400 Mbps.

Still receiving side receive lower speed.

Mirroring the ethernet card of the machine that the iperf client (sending side) is running on into wireshark shows there is a silent gap of 10.8 ms from time to time which can explain the received lower rate.

![120F9D14-5050-4016-8F9E-C6D51F368143](https://user-images.githubusercontent.com/84095934/118087880-815a3000-b3c6-11eb-8234-97389c5811ae.jpeg)

In this example with wireshark, the traffic is 4.4 Gbps and then suddenly, it seems to be a silence gap for 10.8 ms and we lose 4486 ip frames with 1360 bytes.
That can explain why the traffic decrease to below 4 Gbps for a while. 

Does anybody know if why this happens and if it is a known problem potentially fixed in later versions, 3.8 or 3.9?
Any additional flag you recommend to try with to avoid this scenario?
I have tried to run the server on a different Linux machine, but same problem occur, so I don’t think it’s a problem on the machine itself.

BR Niklas

**Comment by davidBar-On** [comment]
> In this example with wireshark, the traffic is 4.4 Gbps and then suddenly, it seems to be a silence gap for 10.8 ms and we lose 4486 ip frames with 1360 bytes.

How did you conclude that 4486 frames were lost?  The point is that iperf3 is sending the packets in a kind of "interval burst" mode.  That is, it sends all the data for the interval (1 sec in this case) and then waits until the interval ends. Therefore, practically only the byte sequence in the iperf3 packet header can really tell how much data was sent.

It would be helpful if you can provide wireshark files for both the sending and the receiving side.  This will allow to evaluate how much data is really sent and if and how many packets got lost on the way.

**Comment by nicke7676** [comment]
Hi @davidBar-On 
Thanks for your reply.
I was calculating the gap in frame id 34371-29885 = 4486.
4486 frames x 1360 bytes = 6 100 960 bytes x 8 = 48 807 680 bits.
Calculating the number of transmitted bits for a certain period before the gap (not visible in the picture) and taking an average over several seconds result in ~4.4 Gbps transmitted.
During the gap time 0.039192076 - 0.028458713 = 0.010733363 seconds, 
48 807 680 bits / 0.010733363 seconds show that the speed during the gap is also at around the same speed ~ 4.5 Gbps, but if the gap is real, packets are not transmitted, causing lower average throughput at the receiving side.
I'm trying to investigate now if the gap is due to the Wireshark logging not being able to log everything or if it's actually a real gap.
I can see if I'm able to capture also the receiving side as you suggested.
BR Niklas

**Comment by nicke7676** [comment]
Hi again,
We changed the logging technique to something called net-sniff and then we cannot see the gap anymore when the lower throughput happens. So the gap I referred to initially was no real gap, more likely a bug in the logging.
So we consider iperf3 to work as it should and think the lower throughput is due to something in the network instead.
Closing the issue.
BR Niklas
