### ISSUE TITLE
A few questions about parameters

### ISSUE THREAD

**Issue by fantasy4335** [esnet/iperf#1147]
(1) How to use  "--rsa-private-key-path" and "--authorized-users-path" in server, and how to use "--username" and "--rsa-public-key-path" in client?
I saw these parameters in "invoking.rst", but I do not know how to use them?
(2) How to test the upstream or downstream bandwidth only on the client, instead of testing both bandwidths at the same time？
client output:
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  12.9 GBytes  11.1 Gbits/sec    2             sender
[  5]   0.00-10.00  sec  12.9 GBytes  11.1 Gbits/sec                  receiver
But I  only want "sender Bitrate", how could I do?

**Comment by fantasy4335** [comment]
when I run "./iperf3 -s --rsa-private-key-path /share/iperf3_yunduan/iperf/iperf3/builds/private_not_protected.pem --authorized-users-path /share/iperf3_yunduan/iperf/iperf3/builds/credentials.csv ", 
it turns out "./iperf3: unrecognized option '--rsa-private-key-path'
Usage: iperf3 [-s|-c host] [options]
       iperf3 [-h|--help] [-v|--version] ..."

**Comment by davidBar-On** [comment]
> it turns out "./iperf3: unrecognized option '--rsa-private-key-path'

Per the code, `--rsa-private-key-path` is supported only when SSL is supported.  Do you know is SSL is supported on your system (or actually on the system where iperf3 was compiled)?  Can you send the output of `iperf3 -v`?

> (2) How to test the upstream or downstream bandwidth only on the client, instead of testing both bandwidths at the same time？

By default only the client sends the data (`-R` is used for sending by the server and `--bidir` for sending by both sides).  What you see is the report of what the client sent and what the server received.  If packets were lost (e.g. when UDP is used), there are network delays, etc. the reports may not be the same.

**Comment by fantasy4335** [comment]
Thans for your reply. Based on your hint, I have solved the problems.

**Comment by bmah888** [comment]
Looks like this has been resolved, thanks @davidBar-On for the help!
