### ISSUE TITLE
iperf3 3.10, bad configure with AC_CHECK_INCLUDES_DEFAULT

### ISSUE THREAD

**Issue by abelbeck** [esnet/iperf#1154]
Building `iperf3 3.10`, cross-compiling via Buildroot, with `autoconf 2.69`

it generates a `./configure` error:
```
checking TCP_CONGESTION socket option... ./configure: line 11278: CPP: command not found
checking how to run the C preprocessor... /home/dev/astlinux/trunk/output/host/usr/bin/x86_64-unknown-linux-gnu-cpp
./configure: line 11404: ac_fn_c_try_cpp: command not found
./configure: line 11404: ac_fn_c_try_cpp: command not found
configure: error: in `/home/dev/astlinux/trunk/output/build/iperf3-3.10':
configure: error: C preprocessor "/home/dev/astlinux/trunk/output/host/usr/bin/x86_64-unknown-linux-gnu-cpp" fails sanity check
See `config.log' for more details
make: *** [package/Makefile.package.in:282: /home/dev/astlinux/trunk/output/build/iperf3-3.10/.stamp_configured] Error 1
```

I can fix the problem with this patch, commenting out `AC_CHECK_INCLUDES_DEFAULT`:
```
--- iperf3-3.10/configure.ac.orig	2021-05-28 14:05:44.717597927 -0500
+++ iperf3-3.10/configure.ac	2021-05-28 14:06:28.283511949 -0500
@@ -68,7 +68,7 @@
   ISO C90 headers unconditionally.])dnl
 # Autoupdate added the next two lines to ensure that your configure
 # script's behavior did not change.  They are probably safe to remove.
-AC_CHECK_INCLUDES_DEFAULT
+#AC_CHECK_INCLUDES_DEFAULT
 AC_PROG_EGREP
 
 
 ```
and rebuilding the `configure` script.

**Comment by bmah888** [comment]
I guess I should have checked the new issues filed before finalizing the 3.10 release. Ran into this problem with the FreeBSD ports build. Will investigate...hopefully your patch fixes the problem. Thanks for the report!

**Comment by bmah888** [comment]
Grf, problems in this area are related to the change from using autoconf-2.69 to autoconf-2.71. Still working on things.

**Comment by abelbeck** [comment]
@bmah888 : Closing the loop ... `3.10.1`'s `./configure` script now works for us.

FYI, by requiring newer than `autoconf 2.69` currently prevents Buildroot from rebuilding `configure.ac` if ever needed, but the default `./configure` script works.  All good for now.

Thanks much for the timely fix.

**Comment by bmah888** [comment]
Glad that's better, or at least unbroken. Sorry for the hassle! I severely underestimated the differences between autoconf-2.69 and autoconf-2.70/2.71.
