### ISSUE TITLE
Support address%interface syntax

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#1157]
Enhancement request prompted by an email from Bob McMahon (iperf2 maintainer):

We used the %<dev> for both tx and and rx device binding in iperf 2. Just something to consider for consistency between the two tools.

To affect the physical output interface (e.g. dual homed systems) either use -c <host>%<dev> (requires root) which bypasses this host route table lookup, or configure policy routing per each -B source address and set the output interface appropriately in the policy routes. On the server or receive, only packets destined to -B IP address will be received. It's also useful for multicast. For example, iperf -s -B 224.0.0.1%eth0 will only accept ip multicast packets with dest ip 224.0.0.1 that are received on the eth0 interface, while iperf -s -B 224.0.0.1 will receive those packets on any interface, Finally, the device specifier is required for v6 link-local, e.g. -c [v6addr]%<dev> -V, to select the output interface.

**Comment by davidBar-On** [comment]
I am trying to understand what this change request means and I have some questions:

1. As far as I understand, the main change is an alternative to defining the `--bind-dev` value by defining it as `%` extension to the `--bind` or `-c` IP address.  Is this correct?

2. Looking briefly at iperf2 code, it seems that the main functionality change is for IPv6, in case the IP addr is **linklocal**.  In this case, the `--bind-dev` (if defined) is appended to the IP addr, following a `%`.

3. I didn't understand what the following means and if it requires further changes:
> .... use -c % (requires root) which bypasses this host route table lookup ...
