### ISSUE TITLE
UDP summary transfer and bandwidth always 0 (windows, iperf3)

### ISSUE THREAD

**Issue by lovelysuman** [esnet/iperf#1164]
Observing this issue on windows vms for iperf3 UDP traffic

* Version of iperf3:
iperf 3.1.3
CYGWIN_NT-10.0 DESKTOP-JJCDNP3 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64
Optional features available: None

Server listening on 8088                                                                                                        
-----------------------------------------------------------                                                                     
Accepted connection from 10.48.130.113, port 50078                                                                              
[  5] local 10.48.130.114 port 8088 connected to 10.48.130.113 port 58060                                                       
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams                                            
[  5]   0.00-1.01   sec   117 KBytes   954 Kbits/sec  2645.136 ms  0/100 (0%)                                                   
[  5]   1.01-2.01   sec   128 KBytes  1.05 Mbits/sec  2.370 ms  0/109 (0%)                                                      
[  5]   2.01-3.01   sec   128 KBytes  1.05 Mbits/sec  0.040 ms  0/109 (0%)                                                      
[  5]   3.01-4.01   sec   128 KBytes  1.05 Mbits/sec  0.032 ms  0/109 (0%)                                                      
[  5]   4.01-5.01   sec   128 KBytes  1.05 Mbits/sec  0.031 ms  0/109 (0%)                                                      
[  5]   5.01-6.01   sec   129 KBytes  1.06 Mbits/sec  0.030 ms  0/110 (0%)                                                      
[  5]   6.01-7.01   sec   128 KBytes  1.05 Mbits/sec  0.035 ms  0/109 (0%)                                                      
[  5]   7.01-8.01   sec   128 KBytes  1.05 Mbits/sec  0.039 ms  0/109 (0%)                                                      
[  5]   8.01-9.01   sec   128 KBytes  1.05 Mbits/sec  0.034 ms  0/109 (0%)                                                      
[  5]   9.01-10.01  sec   129 KBytes  1.06 Mbits/sec  0.037 ms  0/110 (0%)                                                      
[  5]  10.01-10.04  sec  3.52 KBytes   903 Kbits/sec  0.045 ms  0/3 (0%)                                                        
- - - - - - - - - - - - - - - - - - - - - - - - -                                                                               
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams                                            
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec  0.045 ms  0/1086 (0%)

**Comment by davidBar-On** [comment]
Can you try with a newer iperf3 version?  The one you are using is 5 years old.  New iperf3 versions executable for Windows are available at  [https://files.budman.pw/](https://files.budman.pw/) or [https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/](https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/)  (in both download is from the same site).  Note that this is **not an official iperf3** site and I didn't try to use executable from it, but I saw some recommendations about using it.

**Comment by lovelysuman** [comment]
It's working. Thanks @davidBar-On 

[  5] local <> port 56757 connected to <> port 8088                                                       
[ ID] Interval           Transfer     Bitrate         Total Datagrams                                                           
[  5]   0.00-1.00   sec   127 KBytes  1.04 Mbits/sec  89                                                                        
[  5]   1.00-2.00   sec   128 KBytes  1.05 Mbits/sec  90                                                                        
[  5]   2.00-3.00   sec   128 KBytes  1.05 Mbits/sec  90                                                                        
[  5]   3.00-4.00   sec   127 KBytes  1.04 Mbits/sec  89                                                                        
[  5]   4.00-5.00   sec   128 KBytes  1.05 Mbits/sec  90                                                                        
[  5]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  90                                                                        
[  5]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  90                                                                        
[  5]   7.00-8.00   sec   128 KBytes  1.05 Mbits/sec  90                                                                        
[  5]   8.00-9.00   sec   127 KBytes  1.04 Mbits/sec  89                                                                        
[  5]   9.00-10.00  sec   128 KBytes  1.05 Mbits/sec  90                                                                        
- - - - - - - - - - - - - - - - - - - - - - - - -                                                                               
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams                                            
[  5]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.000 ms  0/897 (0%)  sender                                              
[  5]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.085 ms  0/897 (0%)  receiver

**Comment by lovelysuman** [comment]
@davidBar-On When I send UDP traffic on a specific port, am also seeing TCP traffic on the same port. Is iperf3 creating connection using TCP before sending UDP data?

**Comment by davidBar-On** [comment]
> Is iperf3 creating connection using TCP before sending UDP data?

Yes, the control messages between the client and server use a TCP stream (independent of the UDP orTCP data streams).
