### ISSUE TITLE
Windows RPC Issue: remote iperf ends reports not in real-time

### ISSUE THREAD

**Issue by shiwenwang** [esnet/iperf#1172]
# Context
**Scenario:** Using PsExec call iPerf3(on a remote PC) on a local PC.
**Issue:** The Remote iPerf3 ends(whether client or server) will not print any message until the iPerf done.

* Version of iperf3: 3.1.3

* Hardware: HP ProDesk 600G5MT (Intel i5-9500)

* Operating system (and distribution, if any): Windows 10(1809)

Commands:
`iperf3 -s -i 1`      // _real-time printing_
`psexec -accepteula -n 120000 -s \\remote "iperf3.exe" -c local -i 1`   // _not print until iperf done_

**Comment by davidBar-On** [comment]
I am not familiar with `PsEcec`, but according  to its [documentation](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) you **may be missing the `-i`** interactive option.  I.e. the command may have to be: `psexec -i -accepteula -n 120000 -s \\remote "iperf3.exe" -c local -i 1`.

**Comment by shiwenwang** [comment]
My major goal is getting the real-time output of remote iPerf via the local machine's PIPE for an automation tool. 

The interactive option `-i` will prompt a window on the remote machine for interactions, thus the output of iPerf will direction to the remote machine's standard IO, I would never get that.

In PsExec non-interactive mode, iPerf2 works fine. It's puzzling that iPerf3 blocks output.

As the answer from `[iperf3 FAQ](https://software.es.net/iperf/faq.html)`: 
> iperf3 is not officially supported on Windows, but iperf2 is. We recommend you use iperf2.

I will close this issue and use iperf2 instead.

**Comment by davidBar-On** [comment]
@shiwenwang, can you try running **iperf3** using **`--forceflush`**?  I see that iperf2 is flushing the interval reports output unconditionally, while iperf3 does that only if `--forceflush` is set, so that may solve the issue.

**Comment by shiwenwang** [comment]
Thanks a lot, @davidBar-On.

Version 3.1.3(I got the binary from [https://iperf.fr/iperf-download.php](https://iperf.fr/iperf-download.php)) does not support `--forceflush` option. 

It seems likely `--forceflush` is the answer, but building a newer version of iPerf on windows is tricky, I will try later.

**Comment by davidBar-On** [comment]
Thanks for your patience.  
There is a site that distributes new iperf3 executable for Windows. This is not an iperf3 official site it seem to be reliable: [https://files.budman.pw/](https://files.budman.pw/) or [https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/](https://www.neowin.net/forum/topic/1234695-iperf-3101-windows-build/page/3/) (in both download is done from the same site).
