### ISSUE TITLE
Window size doesn't appear to be honored

### ISSUE THREAD

**Issue by mfeit-internet2** [esnet/iperf#1175]
# Context

* Version of iperf3:  Uncertain, likely 3.9.  (It's a perfSONAR system.)

* Hardware:  Unknown x86 box

* Operating system (and distribution, if any):  Linux, likely CentOS 7

# Bug Report

This behavior was observed by Hans Addleman at IU and reported to me because pScheduler was involved.  A complete diagnostic dump from a typical pScheduler run is attached.

* Expected Behavior - Reported window size of less than or equal to value specified using the `-w` switch.

* Actual Behavior - Reported window size of greater than  value specified using the `-w` switch.

* Steps to Reproduce - 
  * Client:  `/usr/bin/iperf3 -p 5201 -B xxx.xxx.xxx.xxx -c yyy.yyy.yyy.yyy -t 10 --json -w 56000000`
  * Server:  `numactl -N 0 /usr/bin/iperf3 -s -1 --json -p 5201 -B yyy.yyy.yyy.yyy`

* Possible Solution - No idea without spelunking in the sources.

[bruce.txt](https://github.com/esnet/iperf/files/6734120/bruce.txt)

**Comment by bmah888** [comment]
`-w` is probably misnamed...it really sets the socket buffer sizes (iperf3 sets both the sending and receiving buffer sizes to the same value), which indirectly sets the maximum window size for TCP tests.

That being said...this is semi-expected (or at least known) behavior for Linux kernels. From tcp(7):
```
       The maximum sizes for socket buffers declared  via  the  SO_SNDBUF  and
       SO_RCVBUF    mechanisms    are   limited   by   the   values   in   the
       /proc/sys/net/core/rmem_max  and   /proc/sys/net/core/wmem_max   files.
       Note that TCP actually allocates twice the size of the buffer requested
       in the setsockopt(2) call, and so a succeeding getsockopt(2) call  will
       not  return  the  same size of buffer as requested in the setsockopt(2)
       call.  TCP uses the extra space for administrative purposes and  inter‐
       nal  kernel  structures,  and  the /proc file values reflect the larger
       sizes compared to the actual TCP windows.  On  individual  connections,
       the socket buffer size must be set prior to the listen(2) or connect(2)
       calls in order to have it take effect.  See socket(7) for more informa‐
       tion.
```
The socket(7) manpage talks about this as well, but I'm not sure how this works with UDP or SCTP sockets.

**Comment by davidBar-On** [comment]
> `-w` is probably misnamed...

It may help to change the `-w` help text from "set window size / socket buffer size" to something like "set send and receive socket buffer size".

**Comment by mfeit-internet2** [comment]
Nuttcp has a suitable clarification that's worth stealing:

```
       -wwindow_size
              Indicates the window size in KB of the transmitter (for "nuttcp -t") or receiver (for "nuttcp -r").  Actually,  to
              be  technically  correct,  it  sets the sender or receiver TCP socket buffer size, which then effectively sets the
              window size.  For client/server mode, both the transmitter and receiver window sizes are set.  The default  window
              size  is  architecture  and system dependent.  Note recent Linux systems, out of a misguided desire to be helpful,
              double whatever window size is actually specified by the user (this is not a bug with nuttcp but a bug/feature  of
              the Linux kernel).  Also, with these Linux systems, the actual window size that's used on the intervening network,
              as observed with tcpdump, is greater than the requested window size, but less than the doubled value set by Linux.
```

Three of the four pScheduler throughput plugins (iperf2, iperf3, nuttcp) support this option and, obviously, behave the same way.   I'll make corresponding adjustments.

**Comment by bmah888** [comment]
Thanks @davidBar-On and @mfeit-internet2 ... these are good ideas. I'll rework the documentation in this area.
