### ISSUE TITLE
Does server send data to client during a tcp connection?

### ISSUE THREAD

**Issue by Jiangrijin** [esnet/iperf#1181]
Hi all, 
I want to use iperf3 to generate some network traffic, here is what I did:
I ran **iperf3 -s** on one machine(192.168.12.23) act as server, then I ran **iperf3 -c 192.168.12.23 -t 300** on another machine to connect to the server.
I want to figure out whether server transport any data besides ack during this tcp connection? And what will the server do with the data it recieved?

**Comment by bmah888** [comment]
In the transfer you described, there are actually two TCP connections. The first is a control connection, which the client and server use to exchange parameters, control the start/stop of the test, exchange results, etc. This one has data going both directions. 

The other connection is the actual data transfer being timed for the test...in your example the transfer data is going from client to server and the server only sends ACKs.
