### ISSUE TITLE
Timed server-side abort for no client connection

### ISSUE THREAD

**Issue by mfeit-internet2** [esnet/iperf#1187]
# Context

* Version of iperf3: All

* Hardware: All

* Operating system (and distribution, if any):  All

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):  None

# Enhancement Request

Background:  We had an instance today where pScheduler managed to orphan an iperf3 server process.  It dutifully kept waiting for someone to authenticate with its expected credentials while newer iperf3s failed to run because the old one kept the control port occupied.

* Current behavior - With `-1` in effect, iperf3 will wait forever for a client to connect and properly authenticate itself.

* Desired behavior - I'd like to have a server-side option called `--listen-timeout` that will cause iperf3 to abort with a failure if a successful connection hasn't happened within a specified number of seconds from the time the program started.  This would provide a fail-safe by not letting the process continue to run beyond the measurement's intended time slot. 

* Implementation notes - None.

**Comment by davidBar-On** [comment]
@mfeit-internet2 what is the use case for using the `-1`?

I am asking as there is a `--idle-timeout` option that restarts the server if it is idle for the specified number of seconds.  Instead of adding a new option, the behavior of `--idle-timeout` can be changed when `-1` is set to terminate the server instead of restarting it.  That may actually be the desired functionality and a "bug" fix to the current implementation.

**Comment by mfeit-internet2** [comment]
@davidBar-On pScheduler uses `-1`  because the server only runs during the time there's a measurement scheduled and only services a single request in its lifetime.

`--idle-timeout` determines what the server does it the client stops sending data after a test has been started.  I'm looking for a server listening for a client to exit if a connection isn't established within _x_ seconds of startup.

Making the server exit with the idle timeout expires with `-1` in effect would probably be useful, but isn't what I'm asking for here.

**Comment by davidBar-On** [comment]
@mfeit-internet2 regarding
> `--idle-timeout` determines what the server does it the client stops sending data after a test has been started

Running  `iperf3 -s -d --idle-timeout 5` shows that the server starts every 5 seconds without receiving any client connection first (the `-d` is for showing the restart messages).  Therefore, if I understand your your asking for,  `--idle-timeout` can be used if the behavior is modified to terminate the server in case of `-1`.

**Comment by mfeit-internet2** [comment]
@davidBar-On That's fairly close.  The only thing missing is that the server doesn't exit if `-1` is in effect.  I wrote a patch to make it exit and added PR #1197 .
