### ISSUE TITLE
Iperf client with out iperf server

### ISSUE THREAD

**Issue by VjshPol** [esnet/iperf#1188]
I am using iperf v2.0.5 in Rasberyy PI as client. For server i have a windows pc with iperf v2.0.8

Q1. does iperf -c <server ip> command work w/o server instance not being running on server ?
       For me, it is running in Rasberry PI client. and i don't think it is normal. 
       It is not running on windows Client. 
any thoughts will be helpful.

Q2. as per iperf documentation -b is to set bandwidth over UDP (for iperf2). 
      Can we set bandwidth over TCP using iperf v 2.0.5 
      -b is working over TCP port with iperf 2.0.8 on a windows pc (windows pc as iperf client)

**Comment by bmah888** [comment]
This GitHub project/repository is for iperf3. You are using iperf2, which is actively maintained by a different set of developers. You probably want to raise your question on the Web site for iperf2, which is:

https://sourceforge.net/projects/iperf2/
