### ISSUE TITLE
how calculate latency from iperf3 output

### ISSUE THREAD

**Issue by ipvirg** [esnet/iperf#1191]
# Context
Is there a way to calculate latency from iperf3 given output as follows -
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-300.00 sec   416 GBytes  11.9 Gbits/sec    0             sender
[  5]   0.00-300.04 sec   416 GBytes  11.9 Gbits/sec                  receiver

If latency calculation is not possible, maybe it is a good feature to include in future iperf releases, just like speedtest tool.

   Speedtest by Ookla

     Server: redacted
        ISP: redacted
    Latency:    13.89 ms   (1.50 ms jitter)
   Download:   283.58 Mbps (data used: 388.9 MB)                               
     Upload:   490.22 Mbps (data used: 481.8 MB)                               
Packet Loss:     0.0%

* Version of iperf3:
iperf3

* Hardware:
Azure E8s_v4

* Operating system (and distribution, if any):
RHEL8.3

**Comment by bmah888** [comment]
Basically, no. iperf3 is a throughput tester. Testing latency is out of scope for this project. To test latency between two hosts, you could use something like ping or owamp.
