### ISSUE TITLE
Iperf bidirectional JSON tests produce duplicate keys

### ISSUE THREAD

**Issue by pdunning-xilinx** [esnet/iperf#1196]
# Context

* Version of iperf3:
3.10.1 or 709f552c (top of master)

* Operating system (and distribution, if any):
Linux

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
Built on RHEL 7

# Bug Report

* Expected Behavior
JSON output should be clear with no ambiguity

* Actual Behavior
`sum*` keys are repeated in JSON output.

* Steps to Reproduce
Any iperf commands with `-J` on the server and `--bidir -J` on the client.
For example:
`iperf3 -c 127.0.0.1 -t 1 --bidir -J` with `iperf3 --one-off -s -J` on the same host.

The following were present in the client output's `"end"` section:
```
...
                "sum_sent":     {
                        "start":        0,
                        "end":  1.000012,
                        "seconds":      1.000012,
                        "bytes":        3903324160,
                        "bits_per_second":      31226218565.37722,
                        "retransmits":  0,
                        "sender":       true
                },
                "sum_received": {
                        "start":        0,
                        "end":  1.000027,
                        "seconds":      1.000027,
                        "bytes":        3903324160,
                        "bits_per_second":      31225750184.74501,
                        "sender":       true
                },
                "sum_sent":     {
                        "start":        0,
                        "end":  1.000012,
                        "seconds":      1.000012,
                        "bytes":        399769600,
                        "bits_per_second":      3198118422.57893,
                        "retransmits":  0,
                        "sender":       false
                },
                "sum_received": {
                        "start":        0,
                        "end":  1.000027,
                        "seconds":      1.000027,
                        "bytes":        390266880,
                        "bits_per_second":      3122050744.6298952,
                        "sender":       false
                },
...
```
The server had the same data except that one of the `"sum_sent"` and one of the `"sum_received"` sections show zero bytes.

This makes it difficult to use all the information. For example Python will drop at one of each of the duplicated keys when reading this in.

* Possible Solution

I'm not sure as it depends on the intention as to what the output "should" report.

**Comment by bmah888** [comment]
This is the same as #952.
