### ISSUE TITLE
TCP congestion control algorithm support for client

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#121]
_From [susant.sahani](https://code.google.com/u/susant.sahani/) on December 05, 2013 09:38:49_

Explanation of new feature
 Added TCP Congestion control support.
  -C, --linux-congestion <algo>  set TCP congestion control algorithm (Linux only)

 Attached patch

Thanks,
Susant

**Attachment:** [tcp_congestion.patch](http://code.google.com/p/iperf/issues/detail?id=121)

_Original issue: http://code.google.com/p/iperf/issues/detail?id=121_

**Comment by rayfoss** [comment]
`iperf3: error - unable to set TCP_CONGESTION: Supplied congestion control algorithm not supported on this host`

Windows WSL with debian lacks the feature... there is no way to disable it... iperf client becomes useless :/

**Comment by r-or** [comment]
> 
> 
> `iperf3: error - unable to set TCP_CONGESTION: Supplied congestion control algorithm not supported on this host`
> 
> Windows WSL with debian lacks the feature... there is no way to disable it... iperf client becomes useless :/

It works, if you enable WSL2 and install a new distro / convert your distro to WSL2: https://docs.microsoft.com/en-us/windows/wsl/install-win10#step-2---update-to-wsl-2

**Comment by CanadianJeff** [comment]
is upgrading to WSL2 required or can this be fixed to also support legact WSL1?

**Comment by Foxtaur** [comment]
Why is inability to set TCP_CONGESTION considered a fatal error?  It seems friendlier to issue a warning, instead.

I don't think the response ought to be "get rid of your current Linux (WSL1) in order to use our app."  As it seems like the app should work just fine if the option wasn't set.

**Comment by davidBar-On** [comment]
@Foxtaur, see the discussion in issue #1061 (that is still open about this issue) for why why WSL1 no-congestion is not properly supported by iperf3.
