### ISSUE TITLE
When logfile is not created, iperf loop indefinitely

### ISSUE THREAD

**Issue by mruprich** [esnet/iperf#1225]
# Context
* Version of iperf3:
  iperf3-3.10.1
  kernel-5.14.0

* Operating system (and distribution, if any):
  Fedora Rawhide

# Bug Report
Hi,
when running iperf3 with --logfile and using a path that does not exist, iperf3 won't stop with an error but will actually just loop in the run() function. 

* Expected Behavior
  Stop with an error

* Actual Behavior
  Loops indefinitely

* Steps to Reproduce
  $ iperf3 -s 127.0.0.1 --logfile /this/path/is/nonsense/iperf3-log --forceflush
  iperf3: error - unable to open log file: No such file or directory
  iperf3: error - unable to open log file: No such file or directory
  iperf3: error - unable to open log file: No such file or directory
  iperf3: error - unable to open log file: No such file or directory
  iperf3: error - unable to open log file: No such file or directory
  iperf3: error - unable to open log file: No such file or directory
  iperf3: error - unable to open log file: No such file or directory
  iperf3: error - unable to open log file: No such file or directory
  ...

* Possible Solution
  I think there are two options here:
  a. either the run() function under the daemon part in main.c should test for negative rc like this -  (rc <= -1) on line 155
  or
  b. if the (rc < -1) is intentional to filter out errors where function returns -1 and iperf3 should keep going, 
      but stop when function returns anything lower, the function iperf_open_logfile in iperf_api.c should 
      probably return -2

# Additional question
I ran into this when trying to figure out why the default location for the logfile changed when you don't use absolute path. Since the introduction of https://github.com/esnet/iperf/pull/871 when using --logfile some_file, the file is created in root directory as /some_file. Before this PR, the file was created in the directory where you run the iperf3 command. I was wondering if it would make sense to actually create the logfile before running the daemon() and thus before changing directory to '/' ? Maybe keep the iperf_open_logfile function but call it sooner rather than after the context has changed?

Just a thought, thanks for any insight on this.

Regards,
Michal Ruprich

**Comment by bmah888** [comment]
Thanks for the bug report! I confirm this is a bug that we can reproduce (very much appreciate the example).

**Comment by bmah888** [comment]
This slightly shorter command-line also seems to trigger the problem (at least on my macOS laptop):

`iperf3 -s --logfile /this/path/is/nonsense/iperf3-log`

**Comment by bmah888** [comment]
OK,of the two options you gave, (b) is the one that makes more sense. I'm testing that. Thinking about your other comment about the location of the log file with relative paths.

**Comment by bmah888** [comment]
Opened #1250 for the relative paths issue. I'm going to treat this issue as just dealing with the looping problem.
