### ISSUE TITLE
why I can't specify the TCP maximum segment size?

### ISSUE THREAD

**Issue by liuhycn** [esnet/iperf#1252]
* Version of iperf3: `iperf version 2.0.5 (2 June 2018) pthreads`

* Hardware:  `Linux dl25 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

* Operating system (and distribution, if any): `ubuntu 18.04`

Hi, I try to use the parameter `-M` to specify the TCP maximum segment size. e.g.,:

```
sudo iperf -c 172.16.112.22 -M 128 -t 20 -i 2
```
But I get warning like:

```
WARNING: attempt to set TCP maximum segment size to 128, but got 536
------------------------------------------------------------
Client connecting to 172.16.112.22, TCP port 5001
TCP window size: 25.0 KByte (default)
------------------------------------------------------------
```
What's wrong?

Thank you!

**Comment by lealog** [comment]
This is iperf3 project. It seems that you are using iperf3.
