### ISSUE TITLE
Input argument check between -t and -O needed

### ISSUE THREAD

**Issue by drws** [esnet/iperf#1262]
# Context

* Version of iperf3: 3.10.1

* Hardware: x86_64

* Operating system (and distribution, if any): Linux 5.10

# Enhancement Request

* Current behavior

Currently this is possible to run while it makes no sense:

    > iperf3 -c localhost -t 1 -O 1
    > iperf3 -c localhost -t 1 -O 2

What is even more strange, such input arguments actually produce results. That should be considered a bug, probably related to #1261 and covered there.

* Desired behavior

There should be a "`-O < -t`" input argument check built-in to prevent nonsense input arguments.

**Comment by davidBar-On** [comment]
The problem seem to be the documentation/ help message.  Test duration is the **sum** of the `-t` and `-O` values.  See [comment in #1261](https://github.com/esnet/iperf/issues/1261#issuecomment-1012446601).

**Comment by bmah888** [comment]
This is covered by #1261. Closing.
