### ISSUE TITLE
Summary report not consistent

### ISSUE THREAD

**Issue by MariuszJanczura** [esnet/iperf#1264]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the Discussions section for this project at
https://github.com/esnet/iperf/discussions
or to the iperf3 mailing list at iperf-dev@googlegroups.com.
A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context
Testing UE calls (OnePlus) using Robot framework and VM with ubuntu.

* Version of iperf3: 3.9

* Hardware: OnePlus 8T

* Operating system (and distribution, if any): Debian GNU/Linux 10 (buster)

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate. Note that submissions of bug fixes, new
features, etc. should be done as a pull request at
https://github.com/esnet/iperf/pulls_

# Bug Report

* Expected Behavior
Summary is consistent, it's visible and it's always the same.

* Actual Behavior
Summary is not consistent or it's not existent.

Executed commands for server:
/usr/bin/iperf3 -sD -B 10.0.0.10 -i 1 -p 6666 --format m --one-off --logfile serv.log --debug --forceflush

Executed commands for client:
adb -s X shell -t "su -c /data/data/com.nextdoordeveloper.miperf.miperf/files/iperf3 -R -c 10.0.0.10 -i 1 -t 60s -b 0M -p 6666 -O 5 --format m -u > client.log"

1. Summary is not consistent (lacking "sender" word):
```
Connecting to host 10.0.0.10, port 6666
Reverse mode, remote host 10.0.0.10 is sending
[  4] local 1.7.255.250 port 42142 connected to 10.0.0.10 port 6666
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-1.00   sec   112 KBytes  0.92 Mbits/sec  44260133838.438 ms  0/14 (0%)  (omitted)
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 Mbits/sec  44260133838.438 ms  0/0 (nan%)  (omitted)
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 Mbits/sec  44260133838.438 ms  0/0 (nan%)  (omitted)
[  4]   3.00-4.00   sec  0.00 Bytes  0.00 Mbits/sec  44260133838.438 ms  0/0 (nan%)  (omitted)
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 Mbits/sec  44260133838.438 ms  0/0 (nan%)  (omitted)
[  4]   0.00-1.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   3.00-4.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   6.00-7.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   7.00-8.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   8.00-9.00   sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]   9.00-10.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  10.00-11.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  11.00-12.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  12.00-13.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  13.00-14.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  14.00-15.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  15.00-16.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  16.00-17.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  17.00-18.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  18.00-19.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  19.00-20.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  20.00-21.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  21.00-22.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  22.00-23.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  23.00-24.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  24.00-25.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  25.00-26.00  sec  0.00 Bytes  0.00 Mbits/sec  0.000 ms  0/0 (nan%)  
[  4]  26.00-27.00  sec  6.90 MBytes  57.9 Mbits/sec  0.902 ms  2664683/2665566 (1e+02%)  
[  4]  27.00-28.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  28.00-29.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  29.00-30.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  30.00-31.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  31.00-32.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  32.00-33.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  33.00-34.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  34.00-35.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  35.00-36.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  36.00-37.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  37.00-38.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  38.00-39.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  39.00-40.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  40.00-41.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  41.00-42.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  42.00-43.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  43.00-44.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  44.00-45.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  45.00-46.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  46.00-47.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  47.00-48.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  48.00-49.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  49.00-50.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  50.00-51.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  51.00-52.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  52.00-53.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  53.00-54.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  54.00-55.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  55.00-56.00  sec  0.00 Bytes  0.00 Mbits/sec  0.902 ms  0/0 (nan%)  
[  4]  56.00-57.00  sec  4.38 MBytes  36.8 Mbits/sec  0.460 ms  2617551/2618112 (1e+02%)  
[  4]  57.00-58.00  sec   512 KBytes  4.19 Mbits/sec  0.548 ms  1807/1871 (97%)  
[  4]  58.00-59.00  sec  0.00 Bytes  0.00 Mbits/sec  0.548 ms  0/0 (nan%)  
[  4]  59.00-60.00  sec  0.00 Bytes  0.00 Mbits/sec  0.548 ms  0/0 (nan%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-60.00  sec  39.4 GBytes  5640 Mbits/sec  0.548 ms  5284041/5285549 (1e+02%)  
[  4] Sent 5285549 datagrams
```
(at the end after Lost/Total Datagrams the word "sender" is visible most of the times, but somethimes it's lacking).

2. Summary report is not existent
```
Connecting to host 10.0.0.10, port 6666
Reverse mode, remote host 10.0.0.10 is sending
[  4] local 1.7.255.250 port 38362 connected to 10.0.0.10 port 6666
[  6]  80.00-81.00  sec   160 MBytes  1346 Mbits/sec  20490  
[  6]  81.00-82.00  sec   171 MBytes  1436 Mbits/sec  21910  
[  6]  82.00-83.00  sec   176 MBytes  1475 Mbits/sec  22510  
[  6]  83.00-84.00  sec   181 MBytes  1517 Mbits/sec  23150  
[  6]  84.00-85.00  sec   222 MBytes  1866 Mbits/sec  28470  
[  6]  85.00-86.00  sec   180 MBytes  1507 Mbits/sec  23040  
[  6]  86.00-87.00  sec   172 MBytes  1445 Mbits/sec  22010  
[  6]  87.00-88.00  sec   181 MBytes  1518 Mbits/sec  23170  
[  6]  88.00-89.00  sec   193 MBytes  1619 Mbits/sec  24710  
[  6]  89.00-90.00  sec   191 MBytes  1600 Mbits/sec  24410  
```  
<prints ended here>

There's no summary report.

* Steps to Reproduce
It's occasional, so many tests are needed, but should be eventually visible.

* Possible Solution

# Enhancement Request

* Current behavior

* Desired behavior

* Implementation notes

**Comment by davidBar-On** [comment]
Hi @MariuszJanczura, some questions about your report:

1. By the `adb` command I assume that the the client is running on Android.  However you wrote "Operating system (and distribution, if any): Debian GNU/Linux 10".  Do you run a Linux built iperf3 on Android?
2. The client iperf3 command set `-t 60`, but the second test results are from 90 secs test.  What command did you use for the second test?
3. Can you also share the logs from the server side?

**Comment by TheRealDJ** [comment]
Why are you using UDP?

**Comment by MariuszJanczura** [comment]
> Why are you using UDP?
Yes, as you can see I've executed the command with "-u"

**Comment by MariuszJanczura** [comment]
> Hi @MariuszJanczura, some questions about your report:
> 
>     1. By the `adb` command I assume that the the client is running on Android.  However you wrote "Operating system (and distribution, if any): Debian GNU/Linux 10".  Do you run a Linux built iperf3 on Android?
> 
>     2. The client iperf3 command set `-t 60`, but the second test results are from 90 secs test.  What command did you use for the second test?
> 
>     3. Can you also share the logs from the server side?

1. I had a problem with describing it, but here's how it's executed:
I have client executed on android (smartphone):
-c /data/data/com.nextdoordeveloper.miperf.miperf/files/iperf3 
and sever on Linux:
/usr/bin/iperf3 -sD

If you wanted to ask about builds: the one used on linux is dedicated for linux, and the second run on android is dedicated for android. I think it wouldn't run at all if it was different :)

2. The "second" test is a server part run and it's longer because client run 60s and server was closed separately later (after 90s).

3.  The point "Summary report is not existent" is showing server logs.

I hope I've responded in good fashion and it would help with missing phrases in report.

**Comment by bmah888** [comment]
@swlars and I were trying to understand what the problem is and try to reproduce it. We've discovered something strange.

Output 1 in the original bug report is very perplexing. The (broken) summary code prints out a string `Sent 5285549 datagrams`. This used to be printed by a printf-style format string called `report_datagrams`, but in iperf-3.9, we define _but don't use_ this string. I don't think a string with that form could be emitted by iperf-3.2 or anything newer (when we improved and fixed up some of the UDP support). So my first question is...are you sure the client code is really iperf-3.9?

I understand that the summary code problem you see is intermittent, but for a given version of iperf3, the formatting of the summary reports only depends on whether it's a client or server process, the direction of the test, and the network protocol (i.e. UDP or TCP). There's no room for randomness in that aspect of the output.

As an aside, the test run in Output 1 is perplexing as well. Almost no data is getting through according to the interval reports, and the summary reports are not even consistent with the interval reports.

**Comment by TheRealDJ** [comment]
Could not find an official source of Magic IPerf ... I downloaded from https://apkpure.com/magic-iperf-including-iperf3/com.nextdoordeveloper.miperf.miperf, extracted and inspected the iperf3 binary with `strings` ... I found the string `iperf 3.1` leading me to believe the version is indeed iperf 3.1

**Comment by bmah888** [comment]
Thanks @TheRealDJ for the research.

@MariuszJanczura If that's really something based on iperf-3.1, that's really too old for us to do anything with it. Can you confirm what version you're running? You might need to take this up with whomever built the binary you're running, particularly if they modified the sources from the originals that we distribute.

**Comment by MariuszJanczura** [comment]
Hello, thanks for replying!
Unfortunately I haven't got the env to check it again, so in case of uncertainty I will close the ticket.
Thanks anyway :)
