### ISSUE TITLE
invalid stream indexing (skipping value "2")

### ISSUE THREAD

**Issue by Yaribz** [esnet/iperf#1265]
https://github.com/esnet/iperf/blob/481cbd0969d29cb0e3a78580c2e8ab0bb894006d/src/iperf_api.c#L4338

this line should be `i = 1;`

**Comment by swlars** [comment]
This is correct, but we're reluctant to change it because it would break multi-stream tests between old and new iperf3 versions and it doesn't seem to be causing any major problems.

**Comment by Yaribz** [comment]
Yes I was expecting that, I mainly opened this issue because I came across it during interoperability tests and just wanted to make sure devs are aware of it (to avoid potential bugs or waste of time in the future, if related code is modified by someone unaware of this oddity...).
