### ISSUE TITLE
Better testing procedures / test harness

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#127]
_From [bltierney@es.net](https://code.google.com/u/117296441546344075535/) on December 18, 2013 14:42:06_

It would be good to have some scripts, or at least a wiki page with a list of things to test, for each release.

_Original issue: http://code.google.com/p/iperf/issues/detail?id=127_

**Comment by sovietbits** [comment]
Is this still under consideration?
I'd be happy to add support for a unit test framework like Unity.
I can consolidate your currently written unit test under Unity as well.
If you had a different framework in mind, I can look into that. I think Unity might be the simplest to use without resorting to compiling with c++.
