### ISSUE TITLE
software.es.net subdomain can't be found

### ISSUE THREAD

**Issue by SolidKalium** [esnet/iperf#1289]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the Discussions section for this project at
https://github.com/esnet/iperf/discussions
or to the iperf3 mailing list at iperf-dev@googlegroups.com.
A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

The link in the GitHub issue template, above, to software.es.net does not work because the subdomain can't be found.
Other references and links to the subdomain are also found through `iperf3 --help`, on the README.md for this repository, and at https://fasterdata.es.net/performance-testing/network-troubleshooting-tools/iperf/.

Archive.org shows the site was working a month ago: https://web.archive.org/web/20220207121232/http://software.es.net/
Today, when I try to save this page to archive.org to show that it isn't working, it says "Sorry" "Cannot resolve host software.es.net." https://web.archive.org/save/https://software.es.net/iperf
Domains normally don't go entirely offline during maintenance, so I'm guessing it's not an intentional or transient change.

I tried a website I found via Google that claims to enumerate subdomains and it did not find the `software` subdomain of `es.net`: https://pentest-tools.com/information-gathering/find-subdomains-of-domain

# Bug Report

* Expected Behavior: Links in the README or --help output lead to servers that are accessible from the public internet

* Actual Behavior: Chrome on MacOS gives DNS_PROBE_FINISHED_NXDOMAIN. Desktop and mobile Safari give similar error messages, as does archive.org.

* Steps to Reproduce: Try to visit the link: http://software.es.net/iperf/faq.html

* Possible Solutions:
    * Change the link in the documentation and elsewhere
    * Put the server and DNS information online again

**Comment by bmah888** [comment]
Sorry for the inconvenience! We're aware of the problem and this is being worked on.

**Comment by bmah888** [comment]
Should be fixed now, thanks!
