### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#13]
_From [jdugan.esnet](https://code.google.com/u/101218594482759686213/) on December 09, 2009 22:55:50_

Explaination of new feature Add windows support Justification of new feature Should be done, but I don't want to do it.

_Original issue: http://code.google.com/p/iperf/issues/detail?id=13_

**Comment by scurrier03** [comment]
+1

**Comment by ralcini** [comment]
I think that this ticket can be considered obsolete. The version on branch master has no problem on configure. The only problem is related to the temporary directory choosen (/tmp/iperf3.XXXXXX), but a simple approach that solve the problem was implemented in https://github.com/esnet/iperf/pull/517

**Comment by bmah888** [comment]
Closing due to previous comment.
