### ISSUE TITLE
OpenSSL 3.0 support (deprecated APIs)

### ISSUE THREAD

**Issue by rwmacleod** [esnet/iperf#1300]
Cross-compile build using poky + meta-oe

* Version of iperf3: 3.11
* Hardware: x86-64
* Operating system (and distribution, if any): Host is ubuntu-18.04.3
* Other relevant information (for example, non-default compilers,  libraries, cross-compiling, etc.):
x-compile is master branch

# Bug Report

* Expected Behavior
There are no build warnings
* Actual Behavior
Many warnings, mostly about openssl-3 deprecated APIs.

libtool: compile:  x86_64-poky-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/ala-lpgg
p31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-p
oky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0=
/usr/src/debug/iperf3/3.11-r0 -fdebug-prefix-map=/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0=/usr/src/debug/iperf3/3.11-r0 -fdebug-prefix-map=/ala-lpggp31/rmac
leod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot= -fdebug-prefix-map=/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/r
ecipe-sysroot-native= -D_GNU_SOURCE -Wall -c ../../git/src/units.c  -fPIC -DPIC -o .libs/units.o
libtool: compile:  x86_64-poky-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/ala-lpgg
p31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-p
oky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0=
/usr/src/debug/iperf3/3.11-r0 -fdebug-prefix-map=/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0=/usr/src/debug/iperf3/3.11-r0 -fdebug-prefix-map=/ala-lpggp31/rmac
leod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot= -fdebug-prefix-map=/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/r
ecipe-sysroot-native= -D_GNU_SOURCE -Wall -c ../../git/src/iperf_locale.c  -fPIC -DPIC -o .libs/iperf_locale.o
../../git/src/iperf_auth.c: In function 'sha256':
../../git/src/iperf_auth.c:56:5: warning: 'SHA256_Init' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   56 |     SHA256_Init(&sha256);
      |     ^~~~~~~~~~~
In file included from /ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include/openssl/x509.h:41,
                 from /ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include/openssl/pem.h:23,
                 from ../../git/src/iperf_auth.c:45:
/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include/openssl/sha.h:73:27: note: declared here
   73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
      |                           ^~~~~~~~~~~
../../git/src/iperf_auth.c:57:5: warning: 'SHA256_Update' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   57 |     SHA256_Update(&sha256, string, strlen(string));
      |     ^~~~~~~~~~~~~
In file included from /ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include/openssl/x509.h:41,
                 from /ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include/openssl/pem.h:23,
                 from ../../git/src/iperf_auth.c:45:
/ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include/openssl/sha.h:74:27: note: declared here
   74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
      |                           ^~~~~~~~~~~~~
../../git/src/iperf_auth.c:58:5: warning: 'SHA256_Final' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   58 |     SHA256_Final(hash, &sha256);
      |     ^~~~~~~~~~~~
In file included from /ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include/openssl/x509.h:41,
                 from /ala-lpggp31/rmacleod/src/distro/yocto/b/up-march22/tmp/work/core2-64-poky-linux/iperf3/3.11-r0/recipe-sysroot/usr/include/openssl/pem.h:23,
                 from ../../git/src/iperf_auth.c:45:
 ...

* Steps to Reproduce

$ mkdir yocto && cd yocto
$ git clone git://git.yoctoproject.org/poky
$ git clone git://git.openembedded.org/meta-openembedded
$ . poky/oe-init-build-env test-build-dir
# add all the layers in meta-openembedded
$ bitbake-layers add-layer <full-path>/meta-openembedded/*
$ bitbake iperf3
$ less tmp/work/core2-64-poky-linux/iperf3/3.11-r0/temp/log.do_compile

This builds the cross-compiler and all iperf3 dependencies so it'll take some time.

* Possible Solution

I'm not sure but I expect that openssl-3.x release notes have documented the deprecation.
I may be able to work on the fix and can certainly test as needed.

# Enhancement Request

* Current behavior

* Desired behavior

* Implementation notes

**Comment by swlars** [comment]
Thank you for bringing this to our attention, we're currently discussing it.

**Comment by bmah888** [comment]
I'm starting to chip away at this. There aren't any known breakages at this point (only deprecation warnings at compile-time).
