### ISSUE TITLE
Timestamps not added to interval when outputting to json

### ISSUE THREAD

**Issue by oneofthemany** [esnet/iperf#1324]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the Discussions section for this project at
https://github.com/esnet/iperf/discussions
or to the iperf3 mailing list at iperf-dev@googlegroups.com.
A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

* Version of iperf3: 3.11

* Hardware: Apple MacBook Pro 2021 & HP Z2

* Operating system (and distribution, if any): macOS Monterey, Fedora 35

# Enhancement Request

* Current behavior - when using the --timestamp option in conjunction with -J there is an expectation for the intervals to have a timestamp value per interval, as per the output when running without -J. Command used is as follows:
`iperf % iperf3 -c 192.168.1.1 -w 128K -i 1 -p 5201 --timestamps="%d-%m-%Y %H:%M:%S" -J`

The output of which is:
```
	"intervals":	[{
			"streams":	[{
					"socket":	5,
					"start":	0,
					"end":	1.000027,
					"seconds":	1.0000269412994385,
					"bytes":	117197136,
					"bits_per_second":	937551829.135432,
					"omitted":	false,
					"sender":	true
				}],
			"sum":	{
				"start":	0,
				"end":	1.000027,
				"seconds":	1.0000269412994385,
				"bytes":	117197136,
				"bits_per_second":	937551829.135432,
				"omitted":	false,
				"sender":	true
			}
		}
```

* Desired behavior - add a timestamp value to the json output:
```
"start":	0,
"timestamp-start": <value>
"end":	1.000027,
"timestamp-end":<value>
"seconds":	1.0000269412994385,
```
as per how we see it when running without -J:

```
26-04-2022 13:04:15Connecting to host 192.168.1.1, port 5201
26-04-2022 13:04:15[  5] local 192.168.1.242 port 63019 connected to 192.168.1.1 port 5201
26-04-2022 13:04:16[ ID] Interval           Transfer     Bitrate
26-04-2022 13:04:16[  5]   0.00-1.00   sec   111 MBytes   932 Mbits/sec                  
26-04-2022 13:04:17[  5]   1.00-2.00   sec   112 MBytes   938 Mbits/sec                  
26-04-2022 13:04:18[  5]   2.00-3.00   sec   112 MBytes   939 Mbits/sec                  
26-04-2022 13:04:19[  5]   3.00-4.00   sec   112 MBytes   940 Mbits/sec 
```
* Desired behavior option - map the timestamp to the interval
```
Connecting to host 192.168.1.1, port 5201
[  5] local 192.168.1.242 port 63019 connected to 192.168.1.1 port 5201
[ ID] Interval                                  Transfer        Bitrate
26-04-2022 13:04:16-26-04-2022 13:04:17   sec   111 MBytes   932 Mbits/sec                  
26-04-2022 13:04:17-26-04-2022 13:04:18   sec   112 MBytes   938 Mbits/sec                  
26-04-2022 13:04:18-26-04-2022 13:04:19   sec   112 MBytes   939 Mbits/sec

**Comment by bmah888** [comment]
Thanks for the request...the `--timestamp` option was really designed to apply to each physical line in the human-readable output, and there really isn't a 1-to-1 correspondence between each line and a JSON interval record.

**Comment by oneofthemany** [comment]
> Thanks for the request...the `--timestamp` option was really designed to apply to each physical line in the human-readable output, and there really isn't a 1-to-1 correspondence between each line and a JSON interval record.
> 

Are you saying that you're not considering this improvement and have therefore closed the request?

If you were to output the timestamp to the interval you could ingest the data at intervals rather than just a singular useless value.
