### ISSUE TITLE
OpenRISC: iperf3: error - select failed: Bad file descriptor

### ISSUE THREAD

**Issue by zx2c4** [esnet/iperf#1326]
On OpenRISC (or1k) running in QEMU with or1k-sim, I get this when I try to listen using iperf3. I don't see this on any other architecture.

```
$ iperf3 -s -1 -B 192.168.241.2
-----------------------------------------------------------
Server listening on 5201 (test #1)
-----------------------------------------------------------
iperf3: error - select failed: Bad file descriptor
```

Any clues as to what's up?

CC @stffrdhrn

**Comment by zx2c4** [comment]
Ahh, looks like a musl bug.

Replacing the two calls to select() with

```
        result = syscall(413, test->max_fd + 1, &read_set, &write_set, NULL, timeout, NULL);
```

"fixes" the problem. It looks like musl is invoking the wrong syscall number on or1k.

@richfelker

**Comment by stffrdhrn** [comment]
Hi @zx2c4,  What 2 calls to select do you refer to?  Do you have a patch to give more context?

**Comment by stffrdhrn** [comment]
I guess I should read more of the comment, it seems you tracked it down to an incorrect syscall number.

**Comment by zx2c4** [comment]
> Hi @zx2c4,  What 2 calls to select do you refer to?  Do you have a patch to give more context?  

https://github.com/esnet/iperf/blob/3a8e21f33aa3b997bcc6e3a38adab401456eed9a/src/iperf_client_api.c#L587
https://github.com/esnet/iperf/blob/3a8e21f33aa3b997bcc6e3a38adab401456eed9a/src/iperf_server_api.c#L518

**Comment by zx2c4** [comment]
> I guess I should read more of the comment, it seems you tracked it down to an incorrect syscall number.

Yes, though not yet sure why or what's happening in musl, if you want to look into it too...

**Comment by stffrdhrn** [comment]
I see, must has defined in https://git.musl-libc.org/cgit/musl/tree/arch/or1k/bits/syscall.h.in

#define __NR_pselect6 72
#define __NR_pselect6_time64 413

Linux has in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/asm-generic/unistd.h?h=v5.18-rc4


/* fs/select.c */
#if defined(__ARCH_WANT_TIME32_SYSCALLS) || __BITS_PER_LONG != 32
#define __NR_pselect6 72
__SC_COMP_3264(__NR_pselect6, sys_pselect6_time32, sys_pselect6, compat_sys_pselect6_time32)
#define __NR_ppoll 73
__SC_COMP_3264(__NR_ppoll, sys_ppoll_time32, sys_ppoll, compat_sys_ppoll_time32)
#endif

I can't tell right now if this has changed on the Linux side recently.  I am not on my computer. But I think openrisc is just providing the 64 bit api's.  That is what we did in glibc.  So I think we can remove them from or1k musl. For ppoll too.

**Comment by richfelker** [comment]
The problem is that you built your kernel with `CONFIG_COMPAT_32BIT_TIME` off, which is not properly labeled in `Kconfig`, but is an experimental-use-only option that breaks kernel ABI stability guarantee. Fix that and everything will work.

**Comment by zx2c4** [comment]
Ahh, yes, I see that _enabling_ `CONFIG_COMPAT_32BIT_TIME=y` "fixed" the problem. So I think your comment was directed toward @stffrdhrn, suggesting that he do something or another with sending a patch to musl to fix the API stability issue here?

**Comment by richfelker** [comment]
musl supports all kernels back to the earliest one the arch was added in or 2.6.0, whichever came later. And it has always depended on the kernel ABI stability policy ("don't break userspace" - Linus) as the principle on which it makes this work. That is, we always use the oldest syscall that can achieve the operation requested.

In theory we could do things the other way around, trying the newer one first and falling back, but that would put a performance hit on older systems and most of the time it doesn't even have any usefulness - for example, the timeout passed to select is relative, so unless you're trying to wait 70 years (in which case we *do* perform the time64 syscall and error if it's not available) the old syscall is perfectly acceptable. For operations where it can't be known in advance whether the time fits in 32 bits - for example, `stat`, `clock_gettime`, etc. - we do have to try the time64 one first. (Note that vdso, where present, greatly reduces the cost of having to do that for `clock_gettime`.)

**Comment by zx2c4** [comment]
Oh, sorry, I misunderstood your first message. That makes sense. I suppose this is another casualty from trying to build minimal configs upward from allnoconfig. Thanks for the explanation. I'll close this issue here.
