### ISSUE TITLE
Subsequent iperf tcp runs yield much less throughput

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#134]
_From [nsrirao](https://code.google.com/u/116076856318821058885/) on January 16, 2014 13:59:20_

What steps will reproduce the problem? 1. iperf3 -s -V on srv1;iperf3 -c srv1 -V on srv2; (Note srv2 has just been rebooted.)
2. Note the TCP throughput. On my setup (10Gb link) it shows about 9.41Gbps after the first test
3. Run the client again. The throughput shown is about 300Mbps. 
4. Run the client again and see that the throughput does not change ; still is aroung 300Mbps What is the expected output? What do you see instead? Expected to see the pipe being filled - about 9.41Gbps always. What version of the product are you using? On what operating system? 3.0.1 Please provide any additional information below. iperf version 3.0.1 (10 January 2014)
Linux srv2 3.8.0-35-generic #50~precise1-Ubuntu SMP Wed Dec 4 17:25:51 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

_Original issue: http://code.google.com/p/iperf/issues/detail?id=134_

**Comment by Satboy** [comment]
im having the same problem. Using iperf to test a satelite conection which is supossed to give 4 Mb/s, when i tried to use iperf more than once it didnt show me the same bandwidth. i know it could be a enviromental troubble, but if its not the case what whould it be?

**Comment by joyceliuExaai** [comment]
Hi Experts,

I am not sure if there is any improve or not. Now I hit the same isssue. 
My system:
centos 7.4
Infiniband 100Gbps.

I used iperf -P 8.

the output is different for every iteration, is there any idea to fix it? looking forward to hearing from you!

thanks,
Jocye
