### ISSUE TITLE
Windows ethernet adapter disconnects when bandwidth is unlimited

### ISSUE THREAD

**Issue by beatfarm7** [esnet/iperf#1348]
I'm sure this is an adapter issue but can't find a fix. 

If I run iperf3 -c IP

It will run for a few seconds then transfer goes to zero. When this happens I notice the server adapter disconnects and reconnects. 

[  4] local 192.168.40.2 port 8314 connected to 192.168.40.3 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  11.6 MBytes  97.3 Mbits/sec
[  4]   1.00-2.01   sec  11.2 MBytes  93.3 Mbits/sec
[  4]   2.01-3.01   sec  0.00 Bytes  0.00 bits/sec
[  4]   3.01-4.00   sec  0.00 Bytes  0.00 bits/sec
[  4]   4.00-5.01   sec  0.00 Bytes  0.00 bits/sec

If I limit the bandwidth I don't have an issue 

iperf3 -c IP -b 10m 

When I get to 90m the adapter starts crashing. 

Its a 1g interface. Any ideas?

**Comment by davidBar-On** [comment]
Can you provide more information:
1. What version of iperf3 you are using (both for client and server)?
2. What do you mean by "ethernet adaptor" and can you describe what do you mean by "disconnects"?
3. Can you provide also the logs from the server side?
4. Can you run both client and server with `-V` (verbose)  and provide the logs?

**Comment by beatfarm7** [comment]
I upgraded to Windows 11 and the problem is fixed. Weird..maybe it was a driver issue with the network adapter.

**Comment by bmah888** [comment]
Seems to be no issue at this point, so closing this issue.
