### ISSUE TITLE
file descriptor leak in server when using --logfile

### ISSUE THREAD

**Issue by crazyfermions** [esnet/iperf#1360]
# Context

* Version of iperf3: 3.11 (7d21cd554d371b7c348e2c5a98b97cf9bb0001f4), but also occurs earlier versions

* Hardware: x86_64

* Operating system (and distribution, if any): `Linux 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1`

# Bug Report

When using the `--logfile` parameter, the iperf3 server leaks a file descriptor to the log file every time a test is finished.

* Expected Behavior

Don't leak fd.

* Actual Behavior

fd is leaked. Server quits after fd limit is reached.

* Steps to Reproduce

Use `--logfile` option with the server and run several tests. E.g. start server

```bash
./iperf3 -s --logfile /tmp/tmp &
PID=$!
while true; do iperf3 -c localhost -t 1; sleep 1; done
```

Check open file descriptors with 
```bash
ls -l /proc/${PID}/fd/
```

* Possible Solution

Culprit is [iperf_run_server(struct iperf_test *test)](https://github.com/esnet/iperf/blob/7d21cd554d371b7c348e2c5a98b97cf9bb0001f4/src/iperf_server_api.c#L428) which calls [iperf_open_logfile(test)](https://github.com/esnet/iperf/blob/7d21cd554d371b7c348e2c5a98b97cf9bb0001f4/src/iperf_server_api.c#L449) but does not close it. Since this function is called in a [loop](https://github.com/esnet/iperf/blob/7d21cd554d371b7c348e2c5a98b97cf9bb0001f4/src/main.c#L151), the fd will leak everytime the loop is repeated.

I can think of a few solutions:

1. Call iperf_open_logfile only if `(test->outfile == stdout)`
2. Call iperf_open_logfile only once in `run` outside of the loop
3. Make iperf_open_logfile a noop if `(test->outfile != stdout)`
4. Close log file at the end of iperf_run_server.

I can implement the solution, but I would like to know what is considered the canonical way before making a PR.

Note: Currently, the outfile is cleaned up in [iperf_free_test](https://github.com/esnet/iperf/blob/c14053114b54f80c7e4c32deaf91988ba6c75e6b/src/iperf_api.c#L2954-L2961) (also compare #1023), but this does not fix the leak in the server.

**Comment by bmah888** [comment]
Thanks for the bug report! I confirm your results, and thank you very much for the easy recipe for recreating them.

I'm not sure yet what's the best way to deal with this. I know that relocating calls to `iperf_open_logfile` need to be done carefully (see for example some comments I made on #1250).

**Comment by crazyfermions** [comment]
Keeping in mind what you said (and also what is considered good coding practice), I think 4) is the way to go, because it keeps the scope of the logfile ressource local and does not require other parts of the code to have knowledge about what happens during iperf_fun_server().

However, when looking at the error handling in iperf_fun_server(), I found several problems the way it is implemented right now and the file descriptor leak is only one of them. There are side effects if the function fails; for example, the cpu affinity might not be reset, or the json output creates a memory leak (note that the json output is freed up in main() again, but this does not apply if the function is used by the API). Then, since there is no proper unrolling of the state, and the cleanup is either not done at all or everything at once by the cleanup_server() function. There is also a minor problem with this function, because filedescriptors are not handled correctly (some of them are checked for 0, but they should be checked for > -1, and they are also not properly initialized as -1 by iperf_new_test) and hence it does not close a socket if its fd is 0 (which can happen if an API user closes fd 0 and then calls run, because the fd is reused). I guess there needs to be proper refactoring done for this function, maybe similar to what you did in #1033 for the client API. On the other hand, this function is already very long so I guess that implies even more refactoring.

**Comment by bmah888** [comment]
@crazyfermions : Thanks...I'm a little worried about 4) because there are so darn many exit points out of `iperf_run_server()` (almost all of them are for error cases). That's admittedly not a great way to have structured the code, and it's going to make solving this harder. I wonder if putting something in `cleanup_server()` might be a start...it should handle most of the cases (not all of them though).

**Comment by bmah888** [comment]
> I made a pull request with your suggested fix and now I see you did the same yesterday. 😄
> 
> Anyhow, I think both PRs are quite similar; I did a little bit more in terms of making the cleanup function handle the other fds correctly (use -1 for an invalid fd and not 0) which was done almost everywhere correctly but not in the server part.

@crazyfermions Thanks for PR #1369! I haven't had a chance to review it yet, but I am looking forwarding to seeing how much "great minds think alike". :-)
