### ISSUE TITLE
--blockcount or --bytes kills reverse mode

### ISSUE THREAD

**Issue by michellabbe** [esnet/iperf#1363]
# Context
When the server is hit by a very small packet (I use 1 packet tests as healthcheck in my docker image to keep performance impact lowest on actual tests), then tests in reverse mode always return around 0 Mbits/sec until the server is restarted.

* Version of iperf3:
3.11 (ubuntu 22.04, compiled from sources)
3.11-r0 (from alpine 3.16.1 apk)
3.10.1-r0 (from alpine 3.14.1 apk)
note: 3.9-r1-hc (from alpine 3.13 apk) and earlier is **not** affected by this issue

* Hardware:
intel amd64

# Bug Report

* Expected Behavior
Small tests shouldn't tilt the server.

* Actual Behavior
After receiving a small test, all tests in reverse mode report around 0 bits/sec until the server is restarted:

```
Reverse mode, remote host linux.server.lan is sending
[  5] local 192.168.0.10 port 61075 connected to 192.168.0.33 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   128 KBytes  1.04 Mbits/sec
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   2.00-3.01   sec  0.00 Bytes  0.00 bits/sec
[  5]   3.01-4.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec
[  5]   7.00-8.01   sec  0.00 Bytes  0.00 bits/sec
[  5]   8.01-9.02   sec  0.00 Bytes  0.00 bits/sec
[  5]   9.02-10.01  sec  0.00 Bytes  0.00 bits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.01  sec   128 KBytes   105 Kbits/sec    0             sender
[  5]   0.00-10.01  sec   128 KBytes   105 Kbits/sec                  receiver
```

* Steps to Reproduce

server:
`iperf3 -s`

client:
`iperf3 -c server`  = 944 Mbits/sec
`iperf3 -R -c server`  = 944 Mbits/sec
`iperf3 -c server -k 1` or `iperf3 -c server -n 1` (also tried different values like -k 64)

from now on:
`iperf3 -c server`  = 944 Mbits/sec
`iperf3 -R -c server`  = **0 Mbits/sec**
until you restart the server.

-edit-
If you play with different -k/-n values, the result changes.

It's like when you hit the server with a -k/-n value, it becomes the new default value on server for tests in reverse mode.

**Comment by bmah888** [comment]
Yep, we tried this out and it's definitely a bug (testing on macOS from tip of `master`). Thanks for the reproduction recipe. We'll need to fix this.

**Comment by bmah888** [comment]
Testing a fix for this.
