### ISSUE TITLE
Exit Value of iperf while using --json output

### ISSUE THREAD

**Issue by hajoha** [esnet/iperf#1405]
# Context

* Version of iperf3:
since version 3.11

* Hardware:
any

* Operating system (and distribution, if any):
any

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
nothing just plain ./configure;sudo make;sudo make install

# Bug Report

* Expected Behavior
when calling iperf (and the server is not reachable) with `iperf3 -c localhost --json` it's exit value should be 1
when calling iperf (and the server is not reachable) with `iperf3 -c localhost` it's exit value is 1

* Actual Behavior
when calling iperf (and the server is not reachable) with `iperf3 -c localhost --json` it's exit value is 0
when calling iperf (and the server is not reachable) with `iperf3 -c localhost` it's exit value is 1

* Possible Solution
change the cleanup_and_fail in `iperf_client_api.c` to 
```
cleanup_and_fail:
    iperf_client_end(test);
    iflush(test);
    return -1;
```

**Comment by bmah888** [comment]
Reproduced this behavior on iperf-3.12, and you're right, it shouldn't do that.
