### ISSUE TITLE
add bidir flag to json

### ISSUE THREAD

**Issue by hajoha** [esnet/iperf#1428]
# Context

* Version of iperf3:
all
* Hardware:
none
* Operating system (and distribution, if any):
none
* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
none

# Enhancement Request

* Current behavior
running `iperf3 -c localhost --bidir --json` returns
```
{
	"start":	{
               [...]
		"test_start":	{
			"protocol":	"TCP",
			"num_streams":	1,
			"blksize":	131072,
			"omit":	0,
			"duration":	10,
			"bytes":	0,
			"blocks":	0,
			"reverse":	0,
			"tos":	0,
			"target_bitrate":	0
		}
	}, [...]
}
```
* Desired behavior
it would be nice to add a flag which says if bidir is true or not, f.e.
```
{
	"start":	{
               [...]
		"test_start":	{
			"protocol":	"TCP",
			"num_streams":	1,
			"blksize":	131072,
			"omit":	0,
			"duration":	10,
			"bytes":	0,
			"blocks":	0,
			"reverse":	0,
			"tos":	0,
                        "bidir": "true",
			"target_bitrate":	0
		}
	}, [...]
}
```
* Implementation notes
See [PR 1429](https://github.com/esnet/iperf/pull/1429)

**Comment by swlars** [comment]
Fixed, thank you for the issue!

**Comment by bmah888** [comment]
Code was committed that solves this, so closing the issue.
