### ISSUE TITLE
-w option doesn't work in server-mode

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#143]
_From [chris.welti](https://code.google.com/u/118346682937319726865/) on February 21, 2014 06:29:21_

What steps will reproduce the problem? 1. iperf -s -w 1M 2. 3. What is the expected output? What do you see instead? TCP receive buffers should be able to be changed in server mode (-s -w).
Instead iperf reports this command is only supported in client mode:
iperf3: parameter error - some option you are trying to set is client only What version of the product are you using? On what operating system? welti@ezmp3:~/iperf301/iperf-3.0.1/src$ ./iperf3 -v
iperf version 3.0.1 (10 January 2014)
Linux ezmp3 3.12-0.bpo.1-amd64 #1 SMP Debian 3.12.6-2~bpo70+1 (2014-01-07) x86_64 GNU/Linux Please provide any additional information below. It doesn't make sense that one can not set the TCP window in server mode (which is by default the receiving host). This makes debugging performance issues difficult.

_Original issue: http://code.google.com/p/iperf/issues/detail?id=143_

**Comment by xamwm** [comment]
Could you please double-check that '-w' setting works correctly in '-R' mode (reverse). I am specifying 5 MB tcp window, and it works as expected in "client sends to server" mode, I am seeing 434 Mbits/sec on 1 Gbit/sec pipe with 90 ms roundtrip (UK<->US). But if I use -R (reverse option, server sends to client), I am getting 23.1 Mbits/sec (i.e. as if deafult window size is used). Trading placing (switching where iperf client and iperf server are) result in same exact outcome, as if -R ignores -w. I.e. network is sure capable of 434 Mbits/sec both ways. I would expect same exact results with and without -R when -w is specified
