### ISSUE TITLE
iperf doesn't seem to work on the server with eBPF mounted

### ISSUE THREAD

**Issue by hungryzzz** [esnet/iperf#1431]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the Discussions section for this project at
https://github.com/esnet/iperf/discussions
or to the iperf3 mailing list at iperf-dev@googlegroups.com.
A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

* Version of iperf3:
server: iperf3.7
client: iperf3.9

* Hardware:
server: Intel(R) Core(TM) i5-9500T CPU @ 2.20GH
client: Intel(R) Core(TM) i7-10700F CPU @ 2.90GH

* Operating system (and distribution, if any):
server: Linux 5.15.0-53-generic #59~20.04.1-Ubuntu 
client: Linux  5.15.0-53-generic #59-Ubuntu 20.04.1

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
using apt to install iperf3

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate. Note that submissions of bug fixes, new
features, etc. should be done as a pull request at
https://github.com/esnet/iperf/pulls_

# Bug Report
I don't know whether it is a bug...

* Expected Behavior
I load an XDP eBPF bytecodes in server, which changes the UDP packet's source and destination MAC, IP and port and sends back to the client. I've tested it manually, and it really works.

I use the cmd below in server and client respectively, want to test the throughput of the server with XDP eBPF:
```
# server
iperf3 -s -i 1 -p 8000

# client
iperf3 -u -c 10.177.44.198 -t 60 -p 8000 -l 512
```

* Actual Behavior
Both the client and server hang out, like below:
**server:**
```
-----------------------------------------------------------
Server listening on 8000
-----------------------------------------------------------
Accepted connection from 10.177.74.151, port 55388
```

**client:**
```
Connecting to host 10.177.44.198, port 8000
[  5] local 10.177.74.151 port 54111 connected to 10.177.44.198 port 8000
```

And I use tcpdump to trace the process, there is only two records:
```
00:55:08.055035 IP unicornt.54111 > 10.177.44.198.8000: UDP, length 4
00:55:08.055333 IP 10.177.44.198.8000 > unicornt.54111: UDP, length 4
```

* Steps to Reproduce
1. Compile the C code to eBPF bytecode using Clang, and load it in server.
   - run the compile.sh
   - run the load.sh (update the network device name)
3. Start iperf3 in server.
4. Start iperf3 in client.

[ebpf.zip](https://github.com/esnet/iperf/files/10098803/ebpf.zip)

**Comment by bmah888** [comment]
Closing this issue. We can take this up in the discussion item you started (#1432).
