### ISSUE TITLE
iperf3 not running on TS-932PX

### ISSUE THREAD

**Issue by The-Jarmanator** [esnet/iperf#1444]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the Discussions section for this project at
https://github.com/esnet/iperf/discussions
or to the iperf3 mailing list at iperf-dev@googlegroups.com.
A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

* Version of iperf3:

* Hardware:

* Operating system (and distribution, if any):

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate. Note that submissions of bug fixes, new
features, etc. should be done as a pull request at
https://github.com/esnet/iperf/pulls_

# Bug Report

* Expected Behavior

* Actual Behavior

* Steps to Reproduce

* Possible Solution

# Enhancement Request

* Current behavior

* Desired behavior

* Implementation notes

**Comment by The-Jarmanator** [comment]
I have successfully installed iPerf3_3.11.0_arm_64.qpkg✅

QTS informs that it is running, but it is not👎 Like any normal app within QTS, it can be stopped and started, but it does not actually do anything when "supposedly" started☹️.

When going in via SSH, the executable will not run and likely why iperf3 is not working:

Where it is installed, and its group rights (notice "execute" throughout):

    [/share/CACHEDEV1_DATA/.qpkg/iPerf3/bin] # ls -lh
    total 8.2M
    -rwxrwxr-x 1 admin administrators 8.2M 2022-06-20 16:19 iperf3*

However, unable to execute - as per:

    [/share/CACHEDEV1_DATA/.qpkg/iPerf3/bin] # iperf3
    -sh: /usr/bin/iperf3: cannot execute binary file

Please tell me how to get iperf3 (a standard Linux utility for testing socket-to-socket network throughput) to run on my ARM-based QNAP NAS.

Regards,

The Jarmanator

**Comment by davidBar-On** [comment]
I am not familiar with QTS/QNAS, but it seems that there is installation issue (note that sh is looking for iperf3 in `/usr/bin/`.  Therefore, the question should probably be sent to [one of the QNAS forums](https://forum.qnap.com/).

**Comment by The-Jarmanator** [comment]
Hello David, and thank you for your feedback - oh and "Happy New Year" to you too.
I had already raised a ticket with QNAP, and posted to this forum because upon investigating QNAPClub's link for using iperf3 _[note, I already use iperf3 on my Linux firewall and Windows Server devices without any issue]_ they linked to what probably turned out to be a generic iperf3 explanation of what it is and how to use it.
Sorry to have bothered you and, hopefully, QNAP may have a resolution.
![iperf3](https://user-images.githubusercontent.com/102186445/210172828-cc8f7609-8fb2-4e62-92f3-b4f9dd9effbb.jpg)
![iperf3](https://user-images.githubusercontent.com/102186445/210172845-552105dd-d851-4277-946c-e0ff1bda7757.jpg)
It may be that iperf3 3.11.0 has issues on ARM processors.
