### ISSUE TITLE
iperf3 server crash with --logfile and --json and --rcv-timeout after receiving rcv-timeout

### ISSUE THREAD

**Issue by zokl** [esnet/iperf#1460]
Hello,

I found a bug when iperf3 crashed with a segmentation fault on the server site.

iperf3 3.12+ - commit: ce98be37d0c89cc440287761fc131c303b891aea

Reproduction of the bug:
```
Server side
iperf3 -J -1 -s -p 6666 -i 1 --rcv-timeout 10000 --snd-timeout 10000 --logfile test.txt

Client side
iperf3 -c XYZ -p 6666 -i 1 -t 300 --rcv-timeout 10000 --snd-timeout 10000

wait few seconds

shutdown interface (mobile, eth etc.)

Wait for iperf3 crash on server side, server crash after rcv-timeout ...
```

**Comment by davidBar-On** [comment]
Submitted PR #1463 with a fix for the problem.

**Comment by zokl** [comment]
> Submitted PR #1463 with a fix for the problem.

Thank you, I will test it.

**Comment by zokl** [comment]
Thank you, PR #1463 works.
