### ISSUE TITLE
big endian bug

### ISSUE THREAD

**Issue by BrainSlayer** [esnet/iperf#1467]
https://github.com/esnet/iperf/blob/758bfd8f36e33bbdfa565456635e602f39bbe2e1/src/iperf.h#L434

all udp messages are transmitted in host endian format. so iperf3 will not work if server and client are with different endian types. i verified this issue using a big endian power pc router and a little endian arm router as client and server

fix is trivial (i will make a pull request if required)
`

**Comment by bmah888** [comment]
Also see #1414 and #1415.

**Comment by sokarax** [comment]
> https://github.com/esnet/iperf/blob/758bfd8f36e33bbdfa565456635e602f39bbe2e1/src/iperf.h#L434
> 
> 
> 
> all udp messages are transmitted in host endian format. so iperf3 will not work if server and client are with different endian types. i verified this issue using a big endian power pc router and a little endian arm router as client and server
> 
> 
> 
> fix is trivial (i will make a pull request if required)
> 
> `
