### ISSUE TITLE
Update or obsolete https://iperf.fr/iperf-download.php

### ISSUE THREAD

**Issue by maettu-this** [esnet/iperf#1475]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the Discussions section for this project at
https://github.com/esnet/iperf/discussions
or to the iperf3 mailing list at iperf-dev@googlegroups.com.
A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

* Version of iperf3: 3.13

* Hardware: https://iperf.fr/iperf-download.php

* Operating system (and distribution, if any): n/a

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.): n/a

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate. Note that submissions of bug fixes, new
features, etc. should be done as a pull request at
https://github.com/esnet/iperf/pulls_

# Bug Report

* Expected Behavior
[Web page](https://iperf.fr/iperf-download.php) reflects latest state of iperf3. Or clearly gives a note that web page is outdated/obsolete.

* Actual Behavior
Most packages not updated since 2016.

* Steps to Reproduce
Go to https://iperf.fr/iperf-download.php.

* Possible Solution
Update web page.

**Comment by bmah888** [comment]
Unfortunately the iperf3 developers have no control over iperf.fr, which was started by someone completely unrelated to the project as kind of a fan site. Attempts to contact the site's maintainer over the past several years have not been successful.

**Comment by cschar** [comment]
Can you please add a note on the main README of this repo to specify the confusion about iperf.fr
