### ISSUE TITLE
Iperf3 command is not working with UDP option

### ISSUE THREAD

**Issue by h89varshne** [esnet/iperf#1493]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the Discussions section for this project at
https://github.com/esnet/iperf/discussions
or to the iperf3 mailing list at iperf-dev@googlegroups.com.
A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

* Version of iperf3:  iperf 3.1
 
root@asc-0a:~ >iperf3 -v
iperf 3.1
Linux asc-0a 5.10.154-916376883c-nokia_sm_x86 #1 SMP PREEMPT Tue Dec 27 13:46:33 UTC 2022 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy

* Hardware: HP

* Operating system (and distribution, if any): Linux OS

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate. Note that submissions of bug fixes, new
features, etc. should be done as a pull request at
https://github.com/esnet/iperf/pulls_

# Bug Report

iperf3 command with option "udp (-u)" is not working in our network for BW testing in client and server mode.

* Expected Behavior

iperf3 command with option "udp (-u)" should work in both client and server mode.

* Actual Behavior
iperf3 command with option "udp (-u)" is not working

* Steps to Reproduce

We are running below command for client mode.

root@asc-0a:~ >iperf3 -c 2405:200:310:C677:4::19 -fm -t1000 -p5002 -B 2405:200:5115:143::1:45e -l1400 -b 50M -u
Connecting to host 2405:200:310:C677:4::19, port 5002
^C- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
iperf3: interrupt - the client has terminated

We are running below command for server mode.

root@asc-0a:~ >iperf3 -c 2405:200:310:C677:4::19 -fm -t1000 -p5002 -B 2405:200:5115:143::1:45e -l1400 -b 50M -u -R
Connecting to host 2405:200:310:C677:4::19, port 5002
Reverse mode, remote host 2405:200:310:C677:4::19 is sending
^C- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
iperf3: interrupt - the client has terminated

* Possible Solution: Not available

# Enhancement Request : 

* Current behavior :  iperf3 command with option "udp (-u)" is not working 

* Desired behavior : iperf3 command with option "udp (-u)" should work properly.

* Implementation notes

**Comment by davidBar-On** [comment]
iperf3 version 3.1 is very old. Suggest to upgrade to a new version and retry the test.

**Comment by h89varshne** [comment]
Can you please share me .exe download link for latest version.  I found version 3.1.3 latest one.

**Comment by davidBar-On** [comment]
try here: https://files.budman.pw/ (not an official site)

**Comment by h89varshne** [comment]
> try here: https://files.budman.pw/ (not an official site)

Thanks, Let me download, Is there any known sw bug with UDP option in older 3.x iperf release ?

**Comment by davidBar-On** [comment]
>  Is there any known sw bug with UDP option in older 3.x iperf release ?

Not sure if it is related, but PR #648 fixed an issue related to `--time 0` around version 3.3.

**Comment by bmah888** [comment]
On the server side, you basically just want to run `iperf3 -s` with no other command-line options. That said, I agree with @davidBar-On's comment about getting an up-to-date version of iperf3.

**Comment by bmah888** [comment]
> > try here: https://files.budman.pw/ (not an official site)
> 
> Thanks, Let me download, Is there any known sw bug with UDP option in older 3.x iperf release ?

UDP has always worked, although not always well. In 3.1.x and earlier, iperf3 had a huge default UDP payload size that automatically caused fragmentation on almost every network path except for jumbo frame Ethernet. This could be overwritten by setting a more sane value for the send size using the `-l` command-line flag. iperf-3.2 and later have a better default UDP payload size.

**Comment by swlars** [comment]
There hasn't been activity on this issue for a while, so we'll close it for now.
