### ISSUE TITLE
IPv6/UDP/Loopback : unable to write to stream socket: Invalid argument

### ISSUE THREAD

**Issue by jfgiorgi** [esnet/iperf#1540]
# Context

* Version of iperf3
```
iperf 3.13 (cJSON 1.7.15)
Linux penguin 5.15.117-19604-g4ddccf76b5e8 #1 SMP PREEMPT Thu Jun 15 18:30:43 PDT 2023 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, 
socket pacing, authentication, bind to device, support IPv4 don't fragment

```
built from source (commit cc108975dfd69863657443d55057ccf0365bcf8e)

tried also with iperf3 3.9 from Debian package, same issue.

* Hardware:
Intel(R) Core(TM) i5-7Y57 CPU @ 1.20GHz

* Operating system (and distribution, if any):

a Debian Bullseye container inside LXD inside QEmu on ChromeOS
Linux penguin 5.15.117-19604-g4ddccf76b5e8
Machine has a Wifi connection with IPv4 and IPv6 (native)

# Bug Report
same machine, 2 terminals:
1st terminal (server):
`iperf3 -s`
2nd terminal (client):
`iperf3 -V -c ::1 -u -b 0
`
point is to mesure max udp performance over loopback using IPv6.

* Expected Behavior
same as IPv4 (using `127.0.0.1` instead of` ::1`)

* Actual Behavior

```
$ iperf3 -V -c ::1 -u -b 0
iperf 3.13
Linux penguin 5.15.117-19604-g4ddccf76b5e8 #1 SMP PREEMPT Thu Jun 15 18:30:43 PDT 2023 x86_64
Control connection MSS 32768
Setting UDP block size to 32768
Time: Tue, 04 Jul 2023 13:05:25 GMT
Connecting to host ::1, port 5201
      Cookie: k3kql4peufju3takmw57kiiznkbimnbxnvyf
[  5] local ::1 port 46948 connected to ::1 port 5201
Starting Test: protocol: UDP, 1 streams, 32768 byte blocks, omitting 0 seconds, 10 second test, tos 0
iperf3: error - unable to write to stream socket: Invalid argument
```

* Possible Solution
It seems the UDP block size is wrong (32768)

If we  add `-l 15991` or less it works.

```
Starting Test: protocol: UDP, 1 streams, 15991 byte blocks, omitting 0 seconds, 10 second test, tos 0
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-1.00   sec  2.50 GBytes  21.4 Gbits/sec  167670  
[  5]   1.00-2.00   sec  2.48 GBytes  21.3 Gbits/sec  166330  
...

```
With `-l 15992` or higher or no `-l `option, it fails:

```
Starting Test: protocol: UDP, 1 streams, 15992 byte blocks, omitting 0 seconds, 10 second test, tos 0
iperf3: error - unable to write to stream socket: Invalid argument

```

why 15992 ? no idea !
and why only with IPv6 ? all tests work fine with IPv4.

# what we also tried

- using `-R` to reverse the stream: the server on terminal 1 displays the same error
- using the public or link-local IPv6 address of  `eth0`, instead of `::1` : same error.
- over lan / wan it works fine but the computed UDP block size is 1428. If we force the size over 15991, it works too:

```
iperf3 -c 2001:xxxxxxxxxxxxxxxx   -u -b 0 -V -l 32768
iperf 3.9
Linux penguin 5.15.117-19604-g4ddccf76b5e8 #1 SMP PREEMPT Thu Jun 15 18:30:43 PDT 2023 x86_64
Control connection MSS 1428
warning: UDP block size 32768 exceeds TCP MSS 1428, may result in fragmentation / drops
Time: Tue, 04 Jul 2023 13:15:00 GMT
Connecting to host 2001:xxxxxxxxxxxxxxxx, port 5201
      Cookie: ifwz3yt7etoefrrsmlr7vvmzigicekxpaotz
[  5] local 2001:xxxxxxxxxxxxxxxxxx  port 37599 connected to 2001:xxxxxxxxxxxx port 5201
Starting Test: protocol: UDP, 1 streams, 32768 byte blocks, omitting 0 seconds, 10 second test, tos 0
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-1.00   sec   276 MBytes  2.31 Gbits/sec  8820  
^C[  5]   1.00-1.77   sec   249 MBytes  2.71 Gbits/sec  7984

```
so with IPv6 "leaving the machine" it's fine. It's just on localhost.

# summary
UDP issue
IPv4: ok
remote destination: ok
localhost: not ok for IPv6 and block size > 15991
error = `unable to write to stream socket: Invalid argument
`

**Comment by davidBar-On** [comment]
Can it be that the IPv6 localhost interface ("lo" probably) MTU is 16,000 bytes (not 16K)?  I am asking, as 15,992 = 16,000 - "UDP Header size".

If this is not the case, some possible further tests that may help to understand the root cause:
1. Test whether ping can use large packets (although it is using ICMP and not UDP).  E.g. `ping ::1 -s 32000`.
2. Make sure that the error happens when trying to send the first UDP packet.  This can be done by adding `-d -n1` options to the client.  Please chare the output of this test.
3. Remove the `-b0` from the test.  I don't know why this may change anything, but it is worth trying.

**Comment by jfgiorgi** [comment]
@davidBar-On thx for checking in

yes it seems the issue is that the MTU is 16000 with IPv6.

1.  `ping ::1 -s N` fails (=hangs) if `N>15991`
2 and 3. iperf3, same error with -d -n1 and without -b0

```
./src/iperf3 -V -d -n1 -c ::1 -u 
noparse
iperf 3.13
Linux penguin 5.15.117-19604-g4ddccf76b5e8 #1 SMP PREEMPT Thu Jun 15 18:30:43 PDT 2023 x86_64
Control connection MSS 32768
Setting UDP block size to 32768
send_parameters:
{
        "udp":  true,
        "omit": 0,
        "time": 0,
        "num":  1,
        "blockcount":   0,
        "parallel":     1,
        "len":  32768,
        "bandwidth":    1048576,
        "pacing_timer": 1000,
        "client_version":       "3.13"
}
Time: Wed, 05 Jul 2023 13:37:55 GMT
Connecting to host ::1, port 5201
      Cookie: q4i5plp3jrxetts2jnb6mcqogeh2duk7edt2
      Target Bitrate: 1048576
SNDBUF is 212992, expecting 0
RCVBUF is 212992, expecting 0
Setting application pacing to 131072
Sending Connect message to Socket 5
Connect received for Socket 5, sz=4, buf=39383736, i=0, max_len_wait_for_reply=4
[  5] local ::1 port 54004 connected to ::1 port 5201
Starting Test: protocol: UDP, 1 streams, 32768 byte blocks, omitting 0 seconds, 1 bytes to send, tos 0
ignoring short interval with no data
iperf3: error - unable to write to stream socket: Invalid argument
```

also:

```
ip link show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

```
some tests with traceroute:
```
$ traceroute -V
Modern traceroute for Linux, version 2.1.0
Copyright (c) 2016  Dmitry Butskoy,   License: GPL v2 or any later

$ traceroute --mtu ::1
traceroute to ::1 (::1), 30 hops max, 65000 byte packets
send: Invalid argument

traceroute --mtu ::1 16040
traceroute to ::1 (::1), 30 hops max, 16040 byte packets
send: Invalid argument

traceroute --mtu ::1 16039
traceroute to ::1 (::1), 30 hops max, 16039 byte packets
 1  localhost (::1)  0.676 ms  0.080 ms  0.047 ms
```

we found a fix:

```
cat /proc/sys/net/ipv6/conf/all/mtu
1280
user@penguin:~/iperf$ cat /proc/sys/net/ipv6/conf/lo/mtu
65536
```
we tried to change it. The biggest value that makes iperf3 works is:
`sudo sysctl net.ipv6.conf.lo.mtu=16063
which makes it  select 15991 as block size.

oddly , all our other Linux systems have `/proc/sys/net/ipv6/conf/lo/mtu` at 65536 and they all work fine.

**Comment by davidBar-On** [comment]
This is strange. Also in my Linux, the mtu settings are the same and there is no such issue.  If somehow you will identify the root cause of the problem, it will help if you can report it.  This is in case it is a condition that iperf3 can check.  Thanks.

**Comment by jfgiorgi** [comment]
Thx. Will do if we find the root cause.
Do I close this issue ?

**Comment by davidBar-On** [comment]
I believe the issue can be closed.  If the root cause will be found and it can be detected by iperf3, a new issue (or PR with a fix) can be opened.  If it will be turned out that this is a system bug/issue, then a comment can be added to this PR (even if it is closed).
