### ISSUE TITLE
ability to do user-level checksums

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#157]
Idea for discussion:

There are known cases where the TCP checksum does not catch certain types of packet corruption. The ability to do a user-level checksum could be useful.

**Comment by xzhu70** [comment]
Any update?  I can do it if it has not been done.

**Comment by zmichael** [comment]
it will be good to obtain such ability

**Comment by bmah888** [comment]
Closing...while it can be a useful feature it's unusual and not a part of what we view as the core functionality.

**Comment by fholzer** [comment]
Would also really like to see this feature. Wouldn't it make more sense for client and server to share some sort of seed in the initial control connection, then each node can generate the same data based on that seed independently?
