### ISSUE TITLE
Failing to bind to interface when multiple interfaces are present

### ISSUE THREAD

**Issue by bOsowski** [esnet/iperf#1572]
# Context

* Version of iperf3:

Both client and server are using the following docker image: https://hub.docker.com/r/networkstatic/iperf3

iperf 3.9 (cJSON 1.7.13)
Linux 893c486a2ac3 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication

* Hardware:
Client has two interfaces connected - an eth0 cabled connection and usb0 (LTE modem)

Server is a standard AWS EC2 instance with one network connection

* Operating system (and distribution, if any):
As per the docker image above.

Also tried to install iperf3 on the underlying OS (same results):

```$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

Internet connectivity via the usb0 interface works:

```
usb0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1430
        inet 192.168.225.28  netmask 255.255.255.0  broadcast 192.168.225.255
        inet6 fe80::416f:fe8:6320:c48a  prefixlen 64  scopeid 0x20<link>
        ether 72:9a:72:49:24:fd  txqueuelen 1000  (Ethernet)
        RX packets 672  bytes 91071 (88.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 836  bytes 143284 (139.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
ping -I usb0 8.8.8.8
PING 8.8.8.8 (8.8.8.8) from 192.168.225.28 usb0: 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=59 time=137 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=59 time=106 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=59 time=116 ms
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 106.325/119.694/136.660/12.642 ms
```

```
$ curl --interface usb0 google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

# Bug Report

* Expected Behavior
Speedtest results when running
`iperf3 -c serveraddress.com --bind 192.168.225.28`

* Actual Behavior
iperf3: error - unable to send control message: Bad file descriptor

* Steps to Reproduce
Run iperf3 client from a linux machine that has multiple network interfaces with internet connectivity and try to bind to them.

From my testing, it seems that iperf3 runs fine if bound to the interface that has the very first default route, but it doesn't for other interfaces. This is surprising since other tools such as ping, or curl work fine for both interfaces, as shown above.

* Possible Solution

**Comment by bOsowski** [comment]
Thank you, specifying the additional `--bind-dev` parameter did work as expected!

**Comment by geerlingguy** [comment]
Just wanted to provide a second round of thanks—I was trying to use `--bind [ip]` and all requests were routing through the default interface on my Pi running Debian. After using `--bind [device]` it properly routed through the correct device!

**Comment by bretmlw** [comment]
An additional round of thanks as I was just investigating this too! Building from source and using --bind-dev has this working for me finally too!
