### ISSUE TITLE
iperf does not know --permit-key

### ISSUE THREAD

**Issue by m4rtin234234** [esnet/iperf#1573]
_NOTE: The iperf3 issue tracker is for registering bugs, enhancement
requests, or submissions of code.  It is not a means for asking
questions about building or using iperf3.  Those are best directed
towards the Discussions section for this project at
https://github.com/esnet/iperf/discussions
or to the iperf3 mailing list at iperf-dev@googlegroups.com.
A list of frequently-asked questions
regarding iperf3 can be found at http://software.es.net/iperf/faq.html._

# Context

* Version of iperf3:

```
iperf3 --version
iperf 3.5 (cJSON 1.5.2)
Linux Fileserver-Backup 6.1.20-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 17 Mar 2023 13:31:00 +0000 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing
```

* Hardware:
Supermicro server

* Operating system (and distribution, if any):
OpenSUSE 15.4

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

# Bug Report

```
iperf3 -p 5001 -c 10.0.0.99 --permit-key=asdf33
iperf3: unrecognized option '--permit-key=asdf33'
```

**Comment by bmah888** [comment]
Hmmm...there is no `--permit-key` option in any version of iperf3. What functionality are you looking for?

**Comment by WatcherOfTheSkies** [comment]
It was an iperf2 option...

_--permit-key [=<value>]
Set a key value that must match for the server to accept traffic on a connection. If the option is given without a value on the server a key value will be autogenerated and displayed in its initial settings report. The lifetime of the key is set using --permit-key-timeout and defaults to twenty seconds. The value on clients required the use of '=', e.g. --permit-key=password (even though it's required command line option.) The server will auto-generate a value if '=password' is not given. The value will also be used as part of the transfer id in reports. The option set on the client but not the server will also cause the server to reject the client's traffic. TCP only, no UDP support._

**Comment by m4rtin234234** [comment]
Hallo, I could solve it by using iperf3 on both client and server. Thanks!
