### ISSUE TITLE
iperf3: unrecognized option '--json-stream'

### ISSUE THREAD

**Issue by Shaun-3adesign** [esnet/iperf#1647]
iperf3 3.16 reports --json-stream is not a valid option

iperf3: unrecognized option '--json-stream'

Usage: iperf3 [-s|-c host] [options]
Try `iperf3 --help' for more information.

**Comment by Shaun-3adesign** [comment]
this works as expected if I build from source on master branch

**Comment by swlars** [comment]
Hi, 

--json-stream will be included in the next release (3.17). It was merged after 3.16 was released, so that behavior is expected.
