### ISSUE TITLE
1-hour run limitation and stats interval in JSON output

### ISSUE THREAD

**Issue by fefone** [esnet/iperf#166]
Hi,
I am trying to run an iperf3 test between several (up to 70 once properly working) hosts in a full-meshed fashion. I want it to run for a day, but at this stage the max running time is 1 hour. Unfortunately due to the server limitation of max one simultaneous iperf3 instance/run per port I am not able to get the result I need for a complete daily test. Is there a way to change this limit? I'm afraid I'm not into programming.

Another question is about the stats output (jitter for example) in a JSON file: it is printed only at the end of the run and not as frequent as the interval. Is there a way to change this behaviour? As above I don't have any programming skills.

Thanks so much.
Regards
Federico

**Comment by Yakkity** [comment]
Can I politely ask why set an upper limit on test duration at all?

**Comment by bmah888** [comment]
@Yakkity:  We wanted to avoid the danger of having high-bitrate streams run essentially forever.  Someone who has a real need for this should be able to modify the code (it's trivial).
