### ISSUE TITLE
iperf 3.0.3 fails launch on non-existent shared library libiperf.so

### ISSUE THREAD

**Issue by johlym** [esnet/iperf#168]
Tried this on multiple systems with two versions of ubuntu (12.04.4 x64 & 14.04 x64) with the same result. After building from source, iperf3 cannot access libperf.so for reason: no such file or directory.

**Comment by codergr** [comment]
Also on SLES12 SP1 had same issue was resolved with libz1-32bit thanks @jrnker

**Comment by ABPAM** [comment]
Installing lib32z1 solved the problem on elementaryOS 0.4.1 Loki also. Thanks, @jrnker :)

**Comment by lmai95** [comment]
I've ran into the same problem on my Pi4 while make installing 3.10.1. The sudo apt-get install lib32z1 comand isn't working Raspberry OS. I asume that the reson is the different processor architecture. Is there a different fix?

**Comment by tropappar** [comment]
Try installing the `libiperf0` via `apt` and them remove again (cf. https://forums.raspberrypi.com/viewtopic.php?t=313629).
