### ISSUE TITLE
10gbit iperf3 shows like half speed but files copying is fine

### ISSUE THREAD

**Issue by Ariloum** [esnet/iperf#1718]
# Context
Hello, subj happens on my lan, iperf3 shows speed 4-5gbps, direct smb files copying from nvme to nvme ssd's is 1.064gigabytes/sec:
server is running iperf3: iperf3 -s
client is running iperf3: iperf3 -t 60 -c server-ipv4

* Version of iperf3:
iperf-3.17.1-win64

* Hardware:
2x Intel 82599 10gbe (Intel X520) adapters connected by multimode optics (works at full duplex).
 -- both connected to x8 pci-e slots and working in gen2 mode.
 -- tried to connect them directly and with switch (Mikrotik CRS309-1G-8S IN with routeros)
 -- both machines am5 chipset, AMD 7950x and 7900x cpu's and fast nvme Samsung 990pro ssd's
 -- both machines has disabled firewall & antivirus
 -- ipv6 is disabled at both machines

* Operating system (and distribution, if any):
Windows 10 x64 both machines

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
nothing special here

# Bug Report
iperf3 shows wrong speed on 10gbit fiber-lan

* Expected Behavior
iperf3 works at full speed like files copying - ~1gigabyte/sec

* Actual Behavior
iperf3 shows ~half speed

* Steps to Reproduce
have no idea what's wrong here, I just downloaded latest iperf3 for testing when installed new hardware and spent ~2+ hours trying to hit 10ggbit with iperf3 but suddenly discovered that copying files just works and hits full speed.

![2024-06-19 01_59_13-Total Commander](https://github.com/esnet/iperf/assets/6816952/f5949ffc-b2ce-4eba-bc69-3194e8bef4a9)
![2024-06-19 02_00_09-cmd - iperf3  -t 60 -c 192 168 1 123 (Admin)](https://github.com/esnet/iperf/assets/6816952/f3dcd1d4-1d10-410b-97d4-e759230a6fce)

**Comment by davidBar-On** [comment]
Try using `--zerocopy`.  Does it help?
If it helps, also try using this flag for the file copy.  Does it help in this case?

**Comment by Ariloum** [comment]
> Try using `--zerocopy`. Does it help? If it helps, also try using this flag for the file copy. Does it help in this case?

# iperf3 -c 192.168.1.121 --zerocopy
iperf3: parameter error - this OS does not support sendfile

**Comment by davidBar-On** [comment]
> iperf3: parameter error - this OS does not support sendfile

This is one possible reason for the difference.  `sendfile()` (when implemented) reduces the amount of copies between buffers  which in many cases increase throughput a lot, and is probably more close to the way file copy is implemented.  Note the that the reason `--zerocopy` is not implemented is because Cygwin, which is used for iperf3 under Windows, does not support it.

Increasing the message size by `-l `M` should help, but not as much as `--zerocopy`.

To find if there are other reasons for the lower throughput, probably the traffic should be analyzed, using Wireshark, tcpdump, etc.

**Comment by Ariloum** [comment]
> To find if there are other reasons for the lower throughput, probably the traffic should be analyzed, using Wireshark, tcpdump, etc.

looks like some Win10 drivers issues with Intel X520 cards, I switched to Mellanox connectX-3 10gbE adapters and it works fine.
