### ISSUE TITLE
possible bug re: use of 1000 vs 1024?

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#173]
When requesting a 1Mbps UDP flow, we consistently see results reported of 1.05Mbps

Might this be a confusion multiplying / dividing by 1000 is some places, and 1024 is others?

**Comment by DanLipsitt** [comment]
It would clarify things if [binary prefixes](https://en.wikipedia.org/wiki/Binary_prefix) (`Ki`, `Mi`, `Gi`) could be used for specifying and outputting binary magnitudes. For example, `--bandwidth 10Mi`.
