### ISSUE TITLE
[feature] Would like to support keeping the phone screen never turned off during speed tests

### ISSUE THREAD

**Issue by qwertyue** [esnet/iperf#1739]

**Comment by davidBar-On** [comment]
How do you run iperf3 on your phone?  Are you using some application?  Can you attach a screen shot of the screen while running iperf3?

Native iperf3 does not support a user-interface, so e.g. to run it on Android phones requires using ADB through a USB connection, running "shell" app on Android, using an app that wraps iperf3, etc.

**Comment by qwertyue** [comment]
> How do you run iperf3 on your phone? Are you using some application? Can you attach a screen shot of the screen while running iperf3?
> 
> Native iperf3 does not support a user-interface, so e.g. to run it on Android phones requires using ADB through a USB connection, running "shell" app on Android, using an app that wraps iperf3, etc.

Sorry for the mistake. But I'm using iperf on my iPhone 13, downloaded from the App Store
