### ISSUE TITLE
Why it shows different between adding --logfile and not

### ISSUE THREAD

**Issue by xuankeyu** [esnet/iperf#1772]
Dear all, 
I wonder if you also have this situation that when i use command like ```iperf3 -s``` on server, it will return:
![Screenshot from 2024-09-19 14-25-59](https://github.com/user-attachments/assets/ee0f5ce8-c00e-407c-b101-f01f758259c7)

However if i add ```--logfile result.text``` in the command, it returns nothing.
![Screenshot from 2024-09-19 14-27-39](https://github.com/user-attachments/assets/673d77db-577f-4585-ae8d-f878a3ed20d7)
Is it normal or somehow?

BW
Keyu

**Comment by davidBar-On** [comment]
Yes, this is the functionality, as all the output is going into the logfile.  If you stop the server the result.xtx file should include the output you see without the `--logfile` option.

(By the way, this should have been opened as a discussion, not an issue, using the "Discussions" tab.)

**Comment by xuankeyu** [comment]
Super clear, thank you.
Since I am currently facing the problem that the results are not showed in the txt file, so I would like to ask, in normal situation, will the Iperf measurement results be showed up in the file only after stopping the server, or will they be showed during the measurement line by line?

**Comment by davidBar-On** [comment]
> will the Iperf measurement results be showed up in the file only after stopping the server, or will they be showed during the measurement line by line?

I my Linux machine, it is shown before stopping the server.  As @d3cxxxx suggested in #1769 (I suggest that you will close wither of these issues), when using `iperf3 -s --foceflush` the server's output is shown in the log file even before any test is running.  Without using this option, just run several tests and some of the output should be shown, as the write to the file is in appends mode.

By the was which iperf3 version are you using (use `iperf3 -v` to see the version)?  If it is old version, then there may be issues with the `--logfile` or the `--forceflush` option may not exist.

**Comment by xuankeyu** [comment]
I am using Ubuntu 22.04 and Iperf 3.9. And I used ```sudo apt install iperf3``` to install it. May I have a look how do you perform iperf measurement and let output show in txt.file. In order to better understand your steps and identify the error, I hope you could either take a screenshot or copy all the commands and outputs for me. I would greatly appreciate it.

**Comment by davidBar-On** [comment]
I am running both the server and the client on the same machine, and `localhost` (IP address127.0.0.1) is used as the server's IP.  The server's command:
```
rm result.txt
iperf3 -s --logfile result.txt --forceflush
```

The output of `cat result.txt` (done from another window) at that point is:
```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

I then run `iperf3 -c localhost -t5` and I see on the client's windows:
```
Connecting to host localhost, port 5201
[  5] local 127.0.0.1 port 52434 connected to 127.0.0.1 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  6.30 GBytes  54.1 Gbits/sec    0   2.25 MBytes
[  5]   1.00-2.00   sec  5.79 GBytes  49.7 Gbits/sec    0   2.25 MBytes
[  5]   2.00-3.00   sec  6.27 GBytes  53.9 Gbits/sec    2   2.25 MBytes
[  5]   3.00-4.00   sec  5.81 GBytes  49.9 Gbits/sec    0   2.25 MBytes
[  5]   4.00-5.00   sec  5.13 GBytes  44.0 Gbits/sec    0   2.25 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-5.00   sec  29.3 GBytes  50.3 Gbits/sec    2             sender
[  5]   0.00-5.05   sec  29.3 GBytes  49.9 Gbits/sec                  receiver

iperf Done.
```

` cat result.txt` now outputs:
```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 127.0.0.1, port 52420
[  6] local 127.0.0.1 port 5201 connected to 127.0.0.1 port 52434
[ ID] Interval           Transfer     Bitrate
[  6]   0.00-1.00   sec  6.02 GBytes  51.7 Gbits/sec
[  6]   1.00-2.00   sec  5.79 GBytes  49.7 Gbits/sec
[  6]   2.00-3.00   sec  6.31 GBytes  54.2 Gbits/sec
[  6]   3.00-4.00   sec  5.79 GBytes  49.7 Gbits/sec
[  6]   4.00-5.00   sec  5.18 GBytes  44.5 Gbits/sec
[  6]   5.00-5.05   sec   214 MBytes  39.3 Gbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  6]   0.00-5.05   sec  29.3 GBytes  49.9 Gbits/sec                  receiver
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

If the client is running again (and again, ...) the output of the server for each test is **appended** to the file.  After terminating the server, the log file includes all the results.  If the server is run again without removing the log file first, the new output will continue to be appended to the file.

**Comment by xuankeyu** [comment]
I know what things went wrong. It's my issue. Thanks so much sir!

**Comment by davidBar-On** [comment]
Glad I could help :smile:. As a cleanup, can you please **close** this and #1769 issues?  Use the "Close issue" button at the bottom of the issues pages. Thanks.
