### ISSUE TITLE
 If -P, --get-server-output, and -J options are specified on the client side, measurement is not performed correctly.

### ISSUE THREAD

**Issue by KenYMG** [esnet/iperf#1776]
# Bug Report
Use iperf, which was built from the source after commit "dab301f163a078b5a6931d973972efdfcc857659", on both the server and client sides.
iperf built with sources prior to this commit works fine.

When I measured the upstream speed as shown below
> $ iperf3 -c 192.168.3.101 -t3 -P6 --get-server-output -J

The following error was output
> warning: JSON data length overflow
> Segmentation fault (core dumped)

And I measure the download speed as shown below, a warning is output at the beginning of the result, and then the client result is output to json, but the server side log outputs the error below.

command:
> $ iperf3 -c 192.168.3.101 -t3 -P4 --get-server-output -JR

warning:
> warning: JSON data length overflow

json excerpt:
  },
        "error":        "unable to receive results: "
}

* Version of iperf3:
From 3.17.1-dab301f163a078b5a6931d973972efdfcc857659

* Hardware:
asus NUC13BRFA4000

* Operating system (and distribution, if any):
Ubuntu 24.04.1LTS Kernel 6.11

* Actual Behavior
**UP**
$ iperf3 -c 192.168.3.101 -t3 -P6 --get-server-output -J
warning: JSON data length overflow
Segmentation fault (core dumped)

**Down**
$ iperf3 -c 192.168.3.101 -t3 -P4 --get-server-output -JR
{
        "start":        {
                "connected":    [{
                                "socket":       5,
                                "local_host":   "192.168.3.3",
                                "local_port":   46416,
                                "remote_host":  "192.168.3.101",
                                "remote_port":  5201
                        }, {
                                "socket":       7,
                                "local_host":   "192.168.3.3",
                                "local_port":   46430,
                                "remote_host":  "192.168.3.101",
                                "remote_port":  5201
                        }, {
                                "socket":       9,
                                "local_host":   "192.168.3.3",
                                "local_port":   46434,
                                "remote_host":  "192.168.3.101",
                                "remote_port":  5201
                        }, {
                                "socket":       11,
                                "local_host":   "192.168.3.3",
                                "local_port":   46440,
                                "remote_host":  "192.168.3.101",
                                "remote_port":  5201
                        }],
                "version":      "iperf 3.17.1+",
                "system_info":  "Linux asus-nuc13 6.11.0-061100-generic #202409151536 SMP PREEMPT_DYNAMIC Sun Sep 15 16:01:12 UTC 2024 x86_64",
                "timestamp":    {
                        "time": "Wed, 25 Sep 2024 03:45:38 GMT",
                        "timesecs":     1727235938
                },
                "connecting_to":        {
                        "host": "192.168.3.101",
                        "port": 5201
                },
                "cookie":       "zukiqu2ap4rqyylsilf7jhssbss4e7q5zoet",
                "tcp_mss_default":      1448,
                "target_bitrate":       0,
                "fq_rate":      0,
                "sock_bufsize": 0,
                "sndbuf_actual":        16384,
                "rcvbuf_actual":        131072,
                "test_start":   {
                        "protocol":     "TCP",
                        "num_streams":  4,
                        "blksize":      131072,
                        "omit": 0,
                        "duration":     3,
                        "bytes":        0,
                        "blocks":       0,
                        "reverse":      1,
                        "tos":  0,
                        "target_bitrate":       0,
                        "bidir":        0,
                        "fqrate":       0,
                        "interval":     1
                }
        },
        "intervals":    [{
                        "streams":      [{
                                        "socket":       5,
                                        "start":        0,
                                        "end":  1.000636,
                                        "seconds":      1.0006359815597534,
                                        "bytes":        22282240,
                                        "bits_per_second":      178144623.30460906,
                                        "omitted":      false,
                                        "sender":       false
                                }, {
                                        "socket":       7,
                                        "start":        0,
                                        "end":  1.000661,
                                        "seconds":      1.0006610155105591,
                                        "bytes":        81002496,
                                        "bits_per_second":      647591899.70977938,
                                        "omitted":      false,
                                        "sender":       false
                                }, {
                                        "socket":       9,
                                        "start":        0,
                                        "end":  1.000663,
                                        "seconds":      1.0006630420684814,
                                        "bytes":        92536832,
                                        "bits_per_second":      739804134.73623335,
                                        "omitted":      false,
                                        "sender":       false
                                }, {
                                        "socket":       11,
                                        "start":        0,
                                        "end":  1.000681,
                                        "seconds":      1.0006810426712036,
                                        "bytes":        90177536,
                                        "bits_per_second":      720929304.3807956,
                                        "omitted":      false,
                                        "sender":       false
                                }],
                        "sum":  {
                                "start":        0,
                                "end":  1.000636,
                                "seconds":      1.0006359815597534,
                                "bytes":        285999104,
                                "bits_per_second":      2286538635.5921,
                                "omitted":      false,
                                "sender":       false
                        }
                }, {
                        "streams":      [{
                                        "socket":       5,
                                        "start":        1.000636,
                                        "end":  2.00081,
                                        "seconds":      1.0001740455627441,
                                        "bytes":        70647808,
                                        "bits_per_second":      565084113.61744773,
                                        "omitted":      false,
                                        "sender":       false
                                }, {
                                        "socket":       7,
                                        "start":        1.000661,
                                        "end":  2.000825,
                                        "seconds":      1.0001640319824219,
                                        "bytes":        68943872,
                                        "bits_per_second":      551460518.83786762,
                                        "omitted":      false,
                                        "sender":       false
                                }, {
                                        "socket":       9,
                                        "start":        1.000663,
                                        "end":  2.000828,
                                        "seconds":      1.0001649856567383,
                                        "bytes":        76546048,
                                        "bits_per_second":      612267368.66608119,
                                        "omitted":      false,
                                        "sender":       false
                                }, {
                                        "socket":       11,
                                        "start":        1.000681,
                                        "end":  2.00083,
                                        "seconds":      1.0001490116119385,
                                        "bytes":        78381056,
                                        "bits_per_second":      626955024.421198,
                                        "omitted":      false,
                                        "sender":       false
                                }],
                        "sum":  {
                                "start":        1.000636,
                                "end":  2.00081,
                                "seconds":      1.0001740455627441,
                                "bytes":        294518784,
                                "bits_per_second":      2355740265.85975,
                                "omitted":      false,
                                "sender":       false
                        }
                }],
        "end":  {
        },
        "error":        "unable to receive results: "
}

**Comment by davidBar-On** [comment]
Submitted PR #1779 with a suggested fix (fixing my previous PR #1709 ...).

**Comment by KenYMG** [comment]
I have confirmed that the issue has been fixed. thank you.

**Comment by swlars** [comment]
Note: there was still an overflow warning which has stopped being an issue with: https://github.com/esnet/iperf/pull/1779
