### ISSUE TITLE
warning: JSON data length overflow

### ISSUE THREAD

**Issue by O-ring** [esnet/iperf#1782]
# Context

* Version of iperf3:

git-current (8 october)

* Hardware:

x86_64

* Operating system (and distribution, if any):

slackware linux 15 (64 bit)

When I run a tcp test in reverse mode with the "get-server-output" parameter, I get this message (and no server output is displayed). The duration of the test is 10 minutes.

[  5] 589.00-590.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 590.00-591.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 591.00-592.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 592.00-593.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 593.00-594.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 594.00-595.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 595.00-596.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 596.00-597.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 597.00-598.00 sec   128 KBytes  1.05 Mbits/sec                  
[  5] 598.00-599.00 sec   128 KBytes  1.05 Mbits/sec                  
warning: JSON data length overflow
iperf3: error - unable to receive results:

**Comment by davidBar-On** [comment]
This is probably the same issues as in #1776.  PR #1779 is a fix for this issue.

**Comment by O-ring** [comment]
Hello David,

Thanks for the reply. Your patch works. I hope it will be applied to git current.

I'll close this ticket.

Thanks again,
Marco
