### ISSUE TITLE
Client hangs if it is running in the same process as the server (libiperf)

### ISSUE THREAD

**Issue by BlackPhantomCoder** [esnet/iperf#1785]
# Context
Using libiperf I run the client and server in the same process on localhost (in different threads) with the -R flag and at some point the client hangs. (Relatively random, in my example on 1-10 test)

* Version of iperf3: 3.17.1
* Operating system (and distribution, if any): Ubuntu 22.04.1

# Bug Report

* Expected Behavior  
Client does not hang

* Actual Behavior  
Client hangs on some test

* Steps to Reproduce
A simple C++ program to reproduce (iperf_main is main from iperf itself)
```
void iperf_run(std::vector<std::string> args) {
  args.insert(args.begin(), "iperf"); // program name
  std::vector<char *> varg;
  std::transform(args.begin(), args.end(), std::back_inserter(varg),
                 [](auto &str) { return str.data(); });

  iperf_main(varg.size(), varg.data());
  std::cout << "done" << std::endl;
}

auto launch(std::vector<std::string> args) {
  return std::async(std::launch::async, iperf_run, std::move(args));
}

int main() {
  auto server = launch({"-s"});
  sleep(5);
  for (size_t i = 0; i != 100; ++i) {
    auto client = launch({"-c", "127.0.0.1", "-t", "1", "-R"});
  }
}
```

**Comment by davidBar-On** [comment]
I do **not** see `iperf_main()` in the iperf3 code (and also not in iperf2 code).  Also note that iperf3 (and iperf2) is written in C, not C++.  **Were is the `iperf_main()` you are using is defined?**

**Comment by bmah888** [comment]
To be honest I wouldn't expect this to work, libiperf wasn't designed to be used by multiple threads in this way.

**Comment by BlackPhantomCoder** [comment]
Thank you very much for the answers,
Then I will use a different approach, and I will close this issue.
