### ISSUE TITLE
[sles 12 sp5] iperf3 error: iperf3: error - unable to send control message - port may not be available, the other side may have stopped running, etc.: Broken pipe

### ISSUE THREAD

**Issue by LiliDeng** [esnet/iperf#1786]
Build iperf3 from master branch.
Run `iperf3  -s -D` on machine A.
Run `iperf3 -t 30 -c 10.0.0.5 -P 128` on machine B.

It is related with the parameter `P`
When the parallel value is 50, it works, when it is 55, it starts to show this failure.
Expected to see no error code but see below errors.
A
```
[252]   0.00-30.01  sec   158 MBytes  44.2 Mbits/sec                  receiver
[254]   0.00-30.01  sec   157 MBytes  43.8 Mbits/sec                  receiver
[256]   0.00-30.01  sec   173 MBytes  48.5 Mbits/sec                  receiver
[258]   0.00-30.01  sec   202 MBytes  56.4 Mbits/sec                  receiver
[260]   0.00-30.01  sec   140 MBytes  39.1 Mbits/sec                  receiver
[SUM]   0.00-30.01  sec  20.1 GBytes  5.76 Gbits/sec                  receiver
warning: JSON data length overflow
iperf3: error - unable to receive results: Bad file descriptor
-----------------------------------------------------------
Server listening on 5201 (test #2)
-----------------------------------------------------------
```

B
```
[255]  28.00-29.00  sec  5.62 MBytes  47.2 Mbits/sec    8   36.9 KBytes
[257]  28.00-29.00  sec  5.62 MBytes  47.2 Mbits/sec    8   21.8 KBytes
[259]  28.00-29.00  sec  5.50 MBytes  46.1 Mbits/sec    5   23.2 KBytes
[SUM]  28.00-29.00  sec   684 MBytes  5.74 Gbits/sec  869
warning: Failed to read JSON data size
iperf3: error - unable to send control message - port may not be available, the other side may have stopped running, etc.: Broken pipe
```

**Comment by davidBar-On** [comment]
At least A is a known issue that is supposed to be fixed by PR #1779 (that was not merged yet into the master branch).  Try using the code from this PR to see if it resolves both issues.

**Comment by LiliDeng** [comment]
@davidBar-On with above change, I encounter a different crash
iperf client output segment
```
[SUM]  28.00-29.00  sec   682 MBytes  5.73 Gbits/sec    0
warning: Failed to read JSON data size
Segmentation fault (core dumped)
```

dmesg segment
```
[ 1251.041615] iperf3[4388]: segfault at 7f4583cff9d0 ip 00007f4584fb52f1 sp 00007fff8c631830 error 4 in libpthread-2.22.so[7f4584fa6000+18000]
[ 1344.265343] iperf3[4883]: segfault at 7fef7bfe79d0 ip 00007fef7d29d2f1 sp 00007ffe6dfdf320 error 4 in libpthread-2.22.so[7fef7d28e000+18000]
```

**Comment by davidBar-On** [comment]
The segmentation fault is a different issue related to duplicate canceling of a thread.  Fortunately, it was already fixed by PR #1761 (see [this comment](https://github.com/esnet/iperf/issues/1760#issuecomment-2345186929) by @answer9030 that explains the issue).

@LiliDeng, I have rebased PR #1779 so it now includes PR #1761 fix.  Can you retest to make sure the segmentation fault is resolved?

**Comment by LiliDeng** [comment]
@davidBar-On the issue has been resolved with the latest fix.

**Comment by davidBar-On** [comment]
@LiliDeng, great.  Note that you can close the issue and go back to use iperf3 master branch, as the change was merged into iperf3.

**Comment by LiliDeng** [comment]
@davidBar-On thanks.
