### ISSUE TITLE
Feature Request - Specify local client source port and/or ability to measure throughput from server, rather than measuring how much the can client push

### ISSUE THREAD

**Issue by Dawsonmoondew** [esnet/iperf#189]
When testing traffic shaping throughput on firewalls, direction of initiated connections, as well as local client source port matters for rule pattern matching.
Being able to specify a source port on the client would be nice(and reasonably low in difficultly?) 
Being able to connect into a server and then measure throughput from server to client, from a client established session, rather than building a new one with -r switch would be amazing. 

Regards
James.

**Comment by bmah888** [comment]
After an issue triage, we think that the remaining part of this issue is covered by #201.  Closing this bug as as duplicate.
