### ISSUE TITLE
packet counter wrapping

### ISSUE THREAD

**Issue by aaronmbr** [esnet/iperf#191]
Initially reported at https://bugzilla.redhat.com/show_bug.cgi?id=1108805 . This is an issue that applies to iperf, but as noted at the bottom of the issue, also applies to iperf3.

"it is possible to overflow the 32-bit packet counter within iperf causing the test to "prematurely" finish.

At 1Gbps, using full-sized UDP packets, it's possible to reach a 2^31 signed 32-bit Integer counter wrap within about 6 hours. This makes it difficult to use iperf to soak test a system for an extended period, even more so if the interface runs at 10Gbps or more."

"To reproduce the problem, run a 1Gbps UDP test between two iperfs for at least 7 hours ==~ 25000 seconds. ( or run for longer at slower speeds to trigger the same 32-bit wrap )."

**Comment by bmah888** [comment]
Declare victory for now.
