### ISSUE TITLE
"Serverless client" UDP test

### ISSUE THREAD

**Issue by blakedotfr** [esnet/iperf#194]
Greetings,

Thanks so much for re-igniting iPerf development.

In iPerf 2, we often use the client mode (bound to a specific source IP) to do a one-way UDP throughput test to routers at remote sites.  iPerf 2 in UDP client mode will simply bind locally & connect to any open UDP port on the remote router (in our case we use 162 snmp trap) and send a UDP stream to it.  By running this test for one minute & checking the router's interface counters, we can determine the bandwidth of the line without requiring any server on-site.

iPerf 3 seems to have (& require) a separate out-of-band client-server TCP control socket.  Any option to forgo a successful client server connection & simply bind locally & send UDP packets at a certain rate would be highly appreciated.

Alternatively, I suppose there's always Ostinato that's more suited for this kind of usage...

Thanks very much for your time & best regards,
Blake Willis
Network Architecture Consultant

**Comment by jose205** [comment]
I need this feature too.

**Comment by edgarcosta92** [comment]
Was this feature included ? Its quite annoying to have a server when you only want to do a UDP test.

**Comment by bmah888** [comment]
The client-server architecture of iperf3 makes this impossible without a major change to the design and implementation.  At this point we acknowledge its usefulness, but have no plans to do this.  If this is needed, it's probably best to try using a different tool such as iperf2.
