### ISSUE TITLE
server dies on very long test

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#200]
Running this:

iperf3 -c 10.10.0.2 -t3000

I get this error after about 10 minutes:
iperf3: error - control socket has closed unexpectedly

perhaps some counter is wrapping?

**Comment by bltierney** [comment]
I have not seen this in a long time, so closing

**Comment by michaelfranzl** [comment]
I keep getting this too, always after 14 seconds (using commit f1415a0).

Client: 

`iperf3 -n 1000000 -u -b 100K`

```
...
[  4]  11.00-12.00  sec  12.6 KBytes   103 Kbits/sec  9  
[  4]  12.00-13.00  sec  11.2 KBytes  91.4 Kbits/sec  8  
[  4]  13.00-14.00  sec  12.6 KBytes   103 Kbits/sec  9 
iperf3: error - control socket has closed unexpectedly
```

Server:

`iperf3 -s`

```
...
[  5]  11.00-12.00  sec  12.6 KBytes   103 Kbits/sec  1.082 ms  0/9 (0%)  
[  5]  12.00-13.00  sec  12.6 KBytes   103 Kbits/sec  0.833 ms  0/9 (0%)  
[  5]  13.00-14.00  sec  11.2 KBytes  91.4 Kbits/sec  0.807 ms  0/8 (0%)
iperf3: error - select failed: Bad file descriptor
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
```

Same with TCP testing.

**Comment by bltierney** [comment]
the command above is working fine for me between 2 linux hosts.

What OS are you using?

**Comment by michaelfranzl** [comment]
Debian 9 for client, Ubuntu 14 for server.

It could be my local network load balancer though...

**Comment by bltierney** [comment]
yeah, I suspect that is more likely.
