### ISSUE TITLE
simultaneous bidirectional test in Iperf3

### ISSUE THREAD

**Issue by tonusoo** [esnet/iperf#201]
I am aware that simultaneous bidirectional test feature, which was present in Iperf 2.x, is dropped in Iperf3. Is there a good technical reason to deprecate this feature? For example the ISP I work for often asks clients to run 600 second Iperf bandwidth test in both directions simultaneously in order to ensure that generated traffic is seen on graphs. It would be time-consuming and troublesome to run Iperf3 command at first without the "-R" flag and then in reverse mode. Please add "--dualtest" feature.

**Comment by FernandoMiguel** [comment]
I've open #250 for the --tradeoff. feel free to mark as dupe to this, if developed at the same time

**Comment by Badevil** [comment]
I also would like to get the dualtest as it is needed as ultimate stress test for the Network equipment to test the full duplex capacity and performance.

**Comment by drws** [comment]
Dual test is a very useful feature, and actually iperf2 has a small problem with it - it does not display the measured uplink (client->server) throughput, only downlink. The upload measurement is printed to stdout  only by server, which doesn't work if one uses some public iperf server (where console output cannot be observed).

**Comment by jackRogers** [comment]
I would also like to see this for voip simulation

**Comment by dylan-clear** [comment]
One more person who needs this. Love iperf3 in lots of ways, but a simultaneous bidirectional test is very important in testing simplex/half-duplex media like wireless links, and setting up two servers and two clients to test one link seems like needless complexity.

**Comment by andris** [comment]
+1 - Sad to see the dual test option missing in iperf3.  Would love to see it added.

**Comment by taismi** [comment]
I really need this freature!

**Comment by bmah888** [comment]
I agree that having a simultaneous bidirectional test would be a Good Thing (tm).  That being said, the amount of development time this would take, and the fact that it's not really a use case for my employer, make it unlikely that I or anyone from the original development team would be working on this anytime soon.  If someone from the community wants to step in and try to implement this, well, all the code is on GitHub!

I think doing this is likely to change the code flow considerably, so I'd suggest in the name of not breaking existing functionality to make this some kind of run-time option that defaults to "off" (particularly on the server).

**Comment by MrStonedOne** [comment]
>the amount of development time this would take

kek. You are talking to developers, don't bullshit us.

Spawn a new thread, call the client function with the connected client as the server argument, and bam, issue solved.

If you are abusing globals, and can't call a client function with a server arg, well, thats your bed, you made it, now you lie in it. Don't abuse globals.

**Comment by csagar** [comment]
Unfortunately, the bidirectional test '-r' in iPerf2 crashes if the client IP 'bind' option is enabled along with enabling multiple parallel TCP connections.

`e.g. iperf.exe -c 192.168.1.10 -B 192.168.1.100 -P 10 -t 10 -r` 
fails!

**Comment by bltierney** [comment]
iperf3 design makes this pretty impossible.

**Comment by MrStonedOne** [comment]
You are talking to developers, don't bullshit us.

Spawn a new thread, call the client function with the connected client as the server argument, and bam, issue solved.

If you are abusing globals, and can't call a client function with a server arg, well, that's your bed, you made it, now you lie in it. Don't abuse globals.

**Comment by bmah888** [comment]
Abuse or vulgar language will not be tolerated here.

**Comment by bmah888** [comment]
We'd like to point out also that iperf2 has apparently improved considerably over the past couple years.  People who haven't looked at it recently are encouraged to re-evaluate to see if recent iperf2 releases (which are maintained completely independently from iperf3 by a different set of developers) might work for their needs.

**Comment by Paul17041993** [comment]
@bltierney where exactly does the design block the bi-directional implementation? we already have reverse mode so what's preventing threads from being spawned in forward and reverse?

**Comment by ebarrere** [comment]
+1

**Comment by jaikumarm** [comment]
+1

**Comment by bdknight** [comment]
+1

**Comment by mo8Zomo0** [comment]
+1

thx for the handy tool, but I also see that a bi directional (parallel as well as serial) would be very handy.

**Comment by drws** [comment]
Not only it would be very handy, but unsupported bidirectional tests are an ugly handicap which should prevent iperf3 to replace iperf2 in any repository in my opinion. Unfortunately people don't like real world tests, because they show problems. Synthetic tests, synthetic results.

**Comment by melikyuksel** [comment]
+1, it's been years.

**Comment by marty90** [comment]
+1

**Comment by evaldasou** [comment]
please re-open the issue @bmah888  , it's not fixed... 

Why You guys did complete rewrite with iperf3? as You see we still need iperf2 anyway... 
Rewrite from scratch is never good idea : https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/

**Comment by Sveeeeeen** [comment]
Over 5 years old and still waiting....we still have to use iperf2 and iperf3... I don't think this was your idea behind the rewrite.

**Comment by bmah888** [comment]
Please see release notes for iperf-3.7 and the `--bidir` flag, which has been released for six months now.  That's the implementation of a bidirectional test.
