### ISSUE TITLE
iperf3 jitter calculation

### ISSUE THREAD

**Issue by aaronmbr** [esnet/iperf#204]
A report from the iperf2 mailing list:

> In measuring jitter using Iperf 2.0.5 and Iperf 3, I have
> noticed a marked difference in the calculations up to an
> order of magnitude.  Could you explain the differences
> in calculation of jitter between 2.0.5 and 3 and the
> accuracy.  Which should I rely upon?

I'm not sure if this is related, but there's a comment in the iperf_udp.c in iperf3:

```
// XXX: This is NOT the way to calculate jitter
//      J = |(R1 - S1) - (R0 - S0)| [/ number of packets, for average]
sp->jitter += (d - sp->jitter) / 16.0;
```

**Comment by codyhanson** [comment]
I believe that this is the algorithm used to compute the 'Jitter' metric in iperf3 udp tests: http://tools.ietf.org/html/rfc1889#appendix-A.8

I haven't peaked at iperf2 to see what it is using.

**Comment by bmah888** [comment]
Thanks for that.  It look roughly equivalent to what iperf3 does.

I admit to being a little mystified by the comment "This is NOT the way to calculate jitter"...in particular I'm wondering to what "this" refers.  (These lines of code pre-date my involvement with iperf3, by a lot.)

**Comment by onkarkundargi** [comment]
How can we consider jitter as input in Iperf ???

**Comment by virqin** [comment]
In `Reporter.c` of Iperf 2.0.3 , the "jitter" designed to follow `RFC 1889, Real Time Protocol (RTP) `:

```
            // from RFC 1889, Real Time Protocol (RTP) 
            // J = J + ( | D(i-1,i) | - J ) / 16 
            transit = TimeDifference( packet->packetTime, packet->sentTime );
            if ( data->lastTransit != 0.0 ) {
                deltaTransit = transit - data->lastTransit;
                if ( deltaTransit < 0.0 ) {
                    deltaTransit = -deltaTransit;
                }
                stats->jitter += (deltaTransit - stats->jitter) / (16.0);
            }
            data->lastTransit = transit;
```
so the key is "RFC 1889, Real Time Protocol (RTP)"

**Comment by bltierney** [comment]
I get the same value for jitter now in iperf3 and iperf2, so closing this.
