### ISSUE TITLE
Unable to control Bandwidth while using SCTP as protocol

### ISSUE THREAD

**Issue by renoldsingh** [esnet/iperf#214]
While using iperf to generate ICMP traffic to a server with protocol set as SCTP the assigned bandwidth is not being used.I executed below mentioned command to generate SCTP traffic.

iperf3 -c xxx.222.4.231 --sctp -P 1 -i 1 -p 5001 -f k -b 50M -t 5
output:
renold@bluegene:~$ iperf3 -c xxx.222.4.231 --sctp -P 1 -i 1 -p 5001 -f k -b 50M -t 5
Connecting to host xx.222.4.231, port 5001
[  4] local xxx.222.4.100 port 51259 connected to xxx.222.4.231 port 5001
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec   128 KBytes  1048 Kbits/sec  
[  4]   1.00-2.00   sec  64.0 KBytes   524 Kbits/sec  
[  4]   2.00-3.00   sec   192 KBytes  1573 Kbits/sec  
[  4]   3.00-4.00   sec  64.0 KBytes   524 Kbits/sec  
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 Kbits/sec                  

---

[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-5.00   sec   448 KBytes   734 Kbits/sec                  sender
[  4]   0.00-5.00   sec   320 KBytes   524 Kbits/sec                  receiver

iperf Done.

While using TCP as protocol then i'm able to generate traffic in the required rate.
output:
renold@bluegene:~$ iperf3 -c xxx.222.4.231 -P 1 -i 1 -p 5001 -f k -b 5M -t 5Connecting to host xxx.222.4.231, port 5001
[  4] local xxx.222.4.100 port 55588 connected to xxx.222.4.231 port 5001
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   560 KBytes  4587 Kbits/sec   52   5.66 KBytes  
[  4]   1.00-2.00   sec   607 KBytes  4970 Kbits/sec   39   5.66 KBytes  
[  4]   2.00-3.00   sec   608 KBytes  4981 Kbits/sec   38   2.83 KBytes  
[  4]   3.00-4.00   sec   617 KBytes  5051 Kbits/sec   35   4.24 KBytes  
[  4]   4.00-5.00   sec   604 KBytes  4946 Kbits/sec   41   2.83 KBytes       

---

[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-5.00   sec  2.92 MBytes  4907 Kbits/sec  205             sender
[  4]   0.00-5.00   sec  2.92 MBytes  4907 Kbits/sec                  receiver

iperf Done.
renold@bluegene:~$ 

I'm aware that SCTP protocol isn't rolled out to any of the official release and only available in Master copy.It would be really great if you guys can fix this issue.

Please let me know if you require more info about the same.

**Comment by mafrost** [comment]
No news on this?

**Comment by bltierney** [comment]
if setting FQ using setsockopt, does this now work?

**Comment by bmah888** [comment]
@bmah888 needs to retest this on modern code.

**Comment by bmah888** [comment]
I tried this on FreeBSD 11.  Application-level pacing with `--bandwidth` seems to work correctly with SCTP across a range of bitrates in the hundreds of Mbps range.

```
bmah-freebsd11:iperf% src/iperf3 -4 --client localhost --sctp --bandwidth=200m --time=5
Connecting to host localhost, port 5201
[  4] local 127.0.0.1 port 23807 connected to 127.0.0.1 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.04   sec  23.8 MBytes   193 Mbits/sec                  
[  4]   1.04-2.01   sec  23.7 MBytes   204 Mbits/sec                  
[  4]   2.01-3.02   sec  23.6 MBytes   196 Mbits/sec                  
[  4]   3.02-4.03   sec  24.1 MBytes   200 Mbits/sec                  
[  4]   4.03-5.02   sec  24.1 MBytes   205 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-5.02   sec   119 MBytes   199 Mbits/sec                  sender
[  4]   0.00-5.02   sec   119 MBytes   199 Mbits/sec                  receiver

iperf Done.
```
I note the original bug report shows the iperf3 client sending data much slower than was actually requested.  Is that the perceived bug?  Perhaps there was an actual network error at work here?

Is this still a problem?  If not we should close this bug as I've seen it functioning correctly.

**Comment by bmah888** [comment]
Closing this issue for now.  It seems to be working for me.  Please re-open if you see this problem again.
