### ISSUE TITLE
Add timeout when client connect to server

### ISSUE THREAD

**Issue by kyanite** [esnet/iperf#216]
when the network is not good, the client side will be pending long time to connect to server. whether iperf can add time out feature for processing such like situation?

**Comment by bmah888** [comment]
The TCP connection establishment timer should take care of this right?

**Comment by bltierney** [comment]
thinking something similar to nc '-w' flag.

**Comment by bmah888** [comment]
nc makes the connecting socket non-blocking with fcntl(2), then does a connect(2) and poll(2) with a timeout.  It looks like we could do something similar, maybe even reuse some code from nc (the code I'm looking at is in FreeBSD, originally from OpenBSD).

**Comment by bmah888** [comment]
I'm using the issue-216 branch in Github for work on this issue.  So far so good after light testing.
