### ISSUE TITLE
shutdown server

### ISSUE THREAD

**Issue by jalopezsuarez** [esnet/iperf#217]
Hello,

any way to shutdown the server? I have no success trying to shutdown iPerf in server mode, using it in API mode inside my Application.

**Comment by bmah888** [comment]
It sounds like there isn't anything else that needs to be done in the iperf3 codebase.  Closing this issue, we can reopen if necessary.

**Comment by kalyanih29** [comment]
Just as mentioned above on a toggle button or on close of my application/ dialog:

I am not able to shutdown Iperf.exe in server mode. I run this through a process in C++ code.

Code Snippet:
exeFileName value is: cmd.exe /C [PATH]\IPerf.exe -s -p 5020 -y C >[PATH]\temp.txt
runProgram(CString &exeFileName)
{
//exeFileName value is: cmd.exe /C [PATH]\IPerf.exe -s -p 5020 -y C >[PATH]\temp.txt
//and PATH is location for these files.
DWORD code,dwError;
try
{
int Result = 0;

STARTUPINFO si = {0};
PROCESS_INFORMATION pi = {0};

si.lpReserved = NULL;
si.lpDesktop = NULL;
si.lpTitle = NULL;
si.dwFlags = STARTF_USESHOWWINDOW;
si.cbReserved2 = NULL;
si.lpReserved2 = NULL;
si.hStdInput = GetStdHandle(STD_INPUT_HANDLE);
si.hStdOutput = GetStdHandle(STD_OUTPUT_HANDLE);
si.hStdError = GetStdHandle(STD_ERROR_HANDLE);
si.wShowWindow = false;
si.cb = sizeof(si);
BOOL ret = CreateProcess(NULL, (LPWSTR) exeFileName.asChar(),NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi);
if(ret == TRUE)
{
GetExitCodeProcess(pi.hProcess, &code);
CloseHandle(pi.hProcess);
CloseHandle(pi.hThread);
}
else
{
GetExitCodeProcess(pi.hProcess, &code);
}
}
catch(…)
{

}
return code;
}

I am looking for some help or guidance for this issue
Thanks in advance.
