### ISSUE TITLE
iperf3 in ipv6 (tcp mode), performance unstable

### ISSUE THREAD

**Issue by sixiao-ms** [esnet/iperf#220]
Hi, I am running iperf 3.0.5 on 2 machines with a 10Gb networking with 40 connections:
Server: iperf -s
Client: iperf -c fd00::1:37 -P 40 -t 18000

In my test with iPerf 3.05, the bandwidth reported by iPerf is very unstable. (maxiumn could be 9.4Gbps but the minimal is low like 4 Gbps. See attached pic).
![iperf3](https://cloud.githubusercontent.com/assets/6785553/5021817/2407db40-6a90-11e4-9827-eb16bde4fc4a.jpg)

I also tried the latest iperf3.0.9. the ipv6 result is also very low (about 3Gbps consiatently).

In the exact same environment, with iPerf2.0.5, the ipv6 reports 8.51 Gbps consistently.

**Comment by bmah888** [comment]
Would you be able to provide some results with doing 1 or 2 streams (rather than 40)?  Also, what's the X axis of the graph?  I had assumed it was time (i.e. a time series of throughput for the intervals of a single run), but during a recent issue triage we realized we didn't know.

**Comment by bmah888** [comment]
Feedback timeout.  Will re-open if we hear anything back from submitter.
