### ISSUE TITLE
A test request from an older client can permanently freeze the server

### ISSUE THREAD

**Issue by annualp** [esnet/iperf#221]
I have found that an older client sending a test request will make the iperf3 server (version 3.0.9) completely unresponsive.  The test request from the client does not work and the server will no longer answer any more test requests.  When I do an strace and attach to the server when this problem is happening I see that it is stuck in a read attempt.

strace -p 792
Process 792 attached - interrupt to quit
read(4,

I have tested this with the server running on two different machines.

first machine:
Linux dev-ftp 3.2.0-40-generic-pae #64-Ubuntu SMP Mon Mar 25 21:44:41 UTC 2013 i686 i686 i386 GNU/Linux

second machine:
Linux G06079 2.6.32.13-0 #1 SMP Fri May 14 10:01:26 CDT 2010 i686 i686 i386 GNU/Linux

The older client I am using is a Windows port.  I am aware that Windows is not a supported platform, but if you Google "iperf3 windows" the result on sourceforge.net (http://sourceforge.net/projects/iperf3cygwingui/) is one of the top results.  It is quite likely someone would try and use this.  I downloaded iperf3cygwingui-trunk318-03-src.zip and this is the version information it reports when I run iperf3 from the Windows command line:

iperf version 3.0b4-trunk318-03-20120720 (2 Aug 2010)

Note: this problem seems similar to the (closed) problem #202 (Connecting to server process during an existing test freezes the server).  However, with that problem the server's functionality was restored after the connection attempt failed.  With this problem the server remains unresponsive.

**Comment by rpodgorny** [comment]
any progress on this?

**Comment by bmah888** [comment]
Not really.  On a marginally related note, we do know that there was "something" that happened between the iperf3 betas and the GA release that broke compatibility.

**Comment by bmah888** [comment]
This is still an issue...trivially easy to do by firing up an iperf3 server and then connecting to the server's port (i.e. with telnet or nc) and then not doing anything.  One thing that's a little complicated is that the client can stop talking to the server at any point and cause the server to stall out.

**Comment by loxK** [comment]
I have this issue too. I have scheduled bandwidth monitoring between two nodes. When the connection fails during a bandwidth measurement the iperf3 server node just hangs forever.

**Comment by davidBar-On** [comment]
`iperf_udp_connect()` sets timeout for reading from the socket:
```c
    #ifdef SO_RCVTIMEO
        /* 30 sec timeout for a case when there is a network problem. */
        tv.tv_sec = 30;
        tv.tv_usec = 0;
        setsockopt(s, SOL_SOCKET, SO_RCVTIMEO, (struct timeval *)&tv, sizeof(struct timeval));
    #endif
```
Won't doing the same for TCP and the Control sockets solve the issue (maybe with different timeouts)?

**Comment by davidBar-On** [comment]
Submitted PR #1101 with proposed fix to the issue that should prevent the server from getting stack because of client or network problems.

**Comment by annualp** [comment]
Thank you for addressing this!
