### ISSUE TITLE
TOS value in output

### ISSUE THREAD

**Issue by vvpoloskin** [esnet/iperf#226]
Hello. Is there any way to add value of TOS to output in server and client mode?

**Comment by bmah888** [comment]
Would it be sufficient for your purposes to get this value into the JSON-style output?  The human-readable output is a little crowded.

**Comment by vvpoloskin** [comment]
Usually not trained network engineers uses old methods and send reports in standart style output. It would be great if TOS value displays on standart output.
It is common issue in many service providers. Now engineers uses ping, iperf and tcpdump to check TOS value.

**Comment by bltierney** [comment]
suggest it get added to JSON 'test_start' object, and in --debug output.

**Comment by bmah888** [comment]
I found a place to wedge this value in the human-readable output.

**Comment by bltierney** [comment]
and in the JSON too? or was it already there?

**Comment by bmah888** [comment]
I added it to the JSON too.  It's in the commit message for 7f996b5.  My prior comment was because we were both saying "there's no place to put it in the human readable output", but in the end, I found a place to put it that makes sense and was easy to add.
