### ISSUE TITLE
Iperf3 - UDP - OUT OF ORDER

### ISSUE THREAD

**Issue by huvar** [esnet/iperf#227]
Hi,

I am running iperf3 using bwctl. I am getting this output which does not make much sense I think...
How come the received packet have always the same number? 
Anyone has any ideas to debug or understand the issue?

iperf3: OUT OF ORDER - incoming packet = 3 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 4 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 5 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 6 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 7 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 8 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 9 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 10 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 11 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 12 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 13 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 14 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 15 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 16 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 17 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 18 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 19 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 20 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 21 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 22 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 23 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 24 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 25 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 26 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 27 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 28 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 29 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 30 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 31 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 32 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 33 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 34 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 35 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 36 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 37 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 38 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 39 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 40 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 41 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 42 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 43 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 44 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 45 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 46 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 47 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 48 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 49 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 50 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 51 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 52 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 53 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 54 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 55 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 56 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 57 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 58 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 59 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 60 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 61 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 62 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 63 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 64 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 65 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 66 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 67 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 68 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 69 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 70 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 71 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 72 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 73 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 74 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 75 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 76 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 77 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 78 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 79 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 80 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 81 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 82 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 83 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 84 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 85 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 86 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 87 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 88 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 89 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 90 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 91 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 92 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 93 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 94 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 95 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 96 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 97 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 98 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 99 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 100 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 101 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 102 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 103 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 104 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 105 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 106 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 107 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 108 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 109 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 110 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 111 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 112 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 113 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 114 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 115 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 116 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 117 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 118 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 119 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 120 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 121 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 122 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 123 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 124 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 125 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 126 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 127 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 128 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 129 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 130 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 131 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 132 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 133 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 134 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 135 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 136 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 137 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 138 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 139 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 140 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 141 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 142 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 143 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 144 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 145 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 146 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 147 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 148 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 149 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 150 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 151 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 152 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 153 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 154 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 155 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 156 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 157 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 158 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 159 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 160 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 161 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 162 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 163 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 164 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 165 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 166 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 167 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 168 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 169 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 170 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 171 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 172 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 173 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 174 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 175 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 176 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 177 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 178 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 179 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 180 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 181 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 182 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 183 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 184 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 185 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 186 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 187 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 188 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 189 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 190 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 191 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 192 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 193 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 194 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 195 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 196 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 197 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 198 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 199 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 200 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 201 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 202 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 203 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 204 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 205 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 206 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 207 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 208 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 209 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 210 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 211 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 212 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 213 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 214 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 215 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 216 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 217 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 218 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 219 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 220 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 221 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 222 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 223 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 224 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 225 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 226 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 227 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 228 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 229 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 230 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 231 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 232 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 233 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 234 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 235 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 236 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 237 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 238 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 239 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 240 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 241 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 242 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 243 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 244 and received packet = 415266 AND SP = 12
iperf3: OUT OF ORDER - incoming packet = 245 and received packet = 415266 AND SP = 12
Connecting to host X.X.X.X, port 5901
Reverse mode, remote host X.X.X.X is sending
[ 12] local 192.168.1.66 port 46451 connected to X.X.X.X port 5901
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[ 12]   0.00-1.00   sec   122 KBytes   999 Kbits/sec  143543660.230 ms  415265/415266 (1e+02%)
[ 12]   1.00-2.00   sec   122 KBytes   999 Kbits/sec  54636.316 ms  0/0 (nan%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[ 12]   0.00-2.00   sec   245 KBytes  1.00 Mbits/sec  54636.316 ms  415265/415266 (1e+02%)
[ 12] Sent 415266 datagrams
[SUM]  0.0- 2.0 sec  415265 datagrams received out-of-order

iperf Done.

**Comment by bmah888** [comment]
Feedback timeout.  Will re-open if we hear anything back from submitter.

**Comment by Snarf42** [comment]
Hi,

I got the same or similar issue with udp out of order packets

root@alpha:~ # iperf3 -s -i 1 -fm
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 10.42.42.2, port 27890
[  5] local 10.42.42.1 port 5201 connected to 10.42.42.2 port 35719
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  1000 KBytes  8.15 Mbits/sec  619.344 ms  0/125 (0%)
[  5]   1.00-2.00   sec  1.20 MBytes  10.0 Mbits/sec  0.116 ms  0/153 (0%)
iperf3: OUT OF ORDER - incoming packet = 298 and received packet = 299 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 313 and received packet = 317 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 314 and received packet = 318 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 315 and received packet = 319 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 316 and received packet = 320 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 360 and received packet = 362 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 361 and received packet = 363 AND SP = 5
[  5]   2.00-3.01   sec  1.20 MBytes  10.0 Mbits/sec  0.105 ms  7/153 (4.6%)
[  5]   3.01-4.00   sec  1.19 MBytes  9.96 Mbits/sec  0.089 ms  0/152 (0%)
iperf3: OUT OF ORDER - incoming packet = 682 and received packet = 687 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 683 and received packet = 688 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 684 and received packet = 688 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 685 and received packet = 688 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 686 and received packet = 688 AND SP = 5
[  5]   4.00-5.01   sec  1.20 MBytes  10.0 Mbits/sec  0.105 ms  5/153 (3.3%)
[  5]   5.01-6.00   sec  1.17 MBytes  9.87 Mbits/sec  0.068 ms  0/150 (0%)
iperf3: OUT OF ORDER - incoming packet = 1034 and received packet = 1038 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1035 and received packet = 1039 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1036 and received packet = 1039 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1037 and received packet = 1039 AND SP = 5
[  5]   6.00-7.00   sec  1.21 MBytes  10.1 Mbits/sec  0.130 ms  4/155 (2.6%)
iperf3: OUT OF ORDER - incoming packet = 1187 and received packet = 1192 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1188 and received packet = 1192 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1189 and received packet = 1192 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1190 and received packet = 1192 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1191 and received packet = 1192 AND SP = 5
[  5]   7.00-8.01   sec  1.20 MBytes  10.0 Mbits/sec  0.112 ms  5/153 (3.3%)
iperf3: OUT OF ORDER - incoming packet = 1217 and received packet = 1221 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1218 and received packet = 1222 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1219 and received packet = 1222 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1220 and received packet = 1222 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1308 and received packet = 1312 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1309 and received packet = 1313 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1310 and received packet = 1314 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1311 and received packet = 1314 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1323 and received packet = 1329 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1324 and received packet = 1329 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1325 and received packet = 1329 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1326 and received packet = 1329 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1327 and received packet = 1329 AND SP = 5
iperf3: OUT OF ORDER - incoming packet = 1328 and received packet = 1329 AND SP = 5
[  5]   8.01-9.00   sec  1.19 MBytes  9.96 Mbits/sec  0.096 ms  14/152 (9.2%)
[  5]   9.00-10.00  sec  1.20 MBytes  10.0 Mbits/sec  0.089 ms  0/153 (0%)
[  5]  10.00-10.10  sec   104 KBytes  8.53 Mbits/sec  0.067 ms  0/13 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-10.10  sec  0.00 Bytes  0.00 Mbits/sec  0.067 ms  35/1512 (2.3%)
[SUM]  0.0-10.1 sec  35 datagrams received out-of-order

root@beta:~ # iperf3 -c 10.42.42.1 -u -b 10000000
Connecting to host 10.42.42.1, port 5201
[  4] local 10.42.42.2 port 35719 connected to 10.42.42.1 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec  1.09 MBytes  9.10 Mbits/sec  139
[  4]   1.00-2.01   sec  1.19 MBytes  9.90 Mbits/sec  152
[  4]   2.01-3.01   sec  1.20 MBytes  10.0 Mbits/sec  153
[  4]   3.01-4.01   sec  1.20 MBytes  10.0 Mbits/sec  153
[  4]   4.01-5.01   sec  1.19 MBytes  9.96 Mbits/sec  152
[  4]   5.01-6.01   sec  1.20 MBytes  10.0 Mbits/sec  153
[  4]   6.01-7.01   sec  1.19 MBytes  9.96 Mbits/sec  152
[  4]   7.01-8.01   sec  1.20 MBytes  10.0 Mbits/sec  153
[  4]   8.01-9.01   sec  1.20 MBytes  10.0 Mbits/sec  153
[  4]   9.01-10.01  sec  1.19 MBytes  9.96 Mbits/sec  152
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.01  sec  11.8 MBytes  9.90 Mbits/sec  0.067 ms  35/1512 (2.3%)
[  4] Sent 1512 datagrams

iperf Done.

systems are freshly installed FreeBSD 10.3-RELEASE with iperf3 via pkg and are connected directly via a cable.

let me know if more information is required

**Comment by Snarf42** [comment]
appears this is related to http://lists.freebsd.org/pipermail/freebsd-bugs/2014-March/055647.html

**Comment by nhed** [comment]
@bmah888
- I am seeing similar behavior running on OSX (Darwin ver sender:15.0.0 receiver:15.4.0 ) iperf 3.0.11
- While my current test case uses `iperf3 -c 10.223.1.4 -fm -w512k -i1 -u -P 8 -b 75000000`  I am pretty user I saw it on a much simpler test case
