### ISSUE TITLE
iperf3 one-off mode

### ISSUE THREAD

**Issue by i2aaron** [esnet/iperf#230]
For bwctl, we'd like to be able to spawn iperf3 such that the server exits when it finishes the test instead of going through the loop again. This looping behavior causes problems with the JSON output since we'll get two bits of JSON (the results of the 1st test, along with the results for the non-test that gets killed). I threw together a simple patch to implement the semantics with a "-1" parameter. It probably needs more work (e.g. documentation, making sure that it's not used for client mode, etc), but it at least causes the server to exit after one test.

You can grab it from http://ndb1.internet2.edu/~aaron/iperf3_one_off.patch

**Comment by bmah888** [comment]
I merged this, should have closed the issue at the same time.
