### ISSUE TITLE
non-blocking being sent on send tests

### ISSUE THREAD

**Issue by candlerb** [esnet/iperf#232]
I can see that when running `iperf -c x.x.x.x -Z`:

1. sendfile() is often returning zero bytes sent; in effect it's being called repeatedly in a spinloop, leading to very high CPU utilisation
2. the send socket is being put into non-blocking mode

This appears to be done in src/iperf_client_api.c for all non-UDP tests, regardless of whether we are sender or receiver.

Was it intended to call select() before sendfile(), or to leave the socket in blocking state when sending TCP?

If the latter, the fix might be something like this:

~~~
--- a/src/iperf_client_api.c
+++ b/src/iperf_client_api.c
@@ -402,7 +402,7 @@ iperf_run_client(struct iperf_test * test)
                startup = 0;

                // Set non-blocking for non-UDP tests
-               if (test->protocol->id != Pudp) {
+               if (test->protocol->id != Pudp && !test->sender) {
                    SLIST_FOREACH(sp, &test->streams, streams) {
                        setnonblocking(sp->socket, 1);
                    }
~~~

Note that there is similar logic in iperf_run_server:

~~~
                        if (test->protocol->id != Pudp ||
                            !test->sender) {
                            setnonblocking(s, 1);
                        }
~~~

However I would have thought this should have `&&` not `||` if the intention was to leave sockets blocking when sending over TCP.

**Comment by bmah888** [comment]
Thanks.  I intend to pull the code from [candlerb-multisend](https://github.com/candlerb/iperf/tree/candlerb-multisend) into the iperf3 mainline as soon as I remember the right Github fu to do this.

I agree with your comments about the logic in the multisend loop.  There's some wrong stuff going on here, although I'm not sure how serious the problems are or how to fix them.

**Comment by bmah888** [comment]
Merged this to master.  Possible merge candidate for 3.0.x.

**Comment by bmah888** [comment]
I merged this, should have closed the issue.
