### ISSUE TITLE
Cross Compile fail with uClibc due to profiling "-pg" compiler/linker option

### ISSUE THREAD

**Issue by richud** [esnet/iperf#235]
When cross compiling with uClibc 0.9.29 I get the error

"ld: cannot find gcrt1.o: No such file or directory"

Removing  -pg  in src/Makefile.in fixes it as it doesn't support it.

``` patch
--- iperf-3.0.10/src/Makefile.in.orig
+++ iperf-3.0.10/src/Makefile.in
@@ -593,9 +593,9 @@
 iperf3_profile_SOURCES = main.c \
                          $(libiperf_la_SOURCES)

-iperf3_profile_CFLAGS = -pg -g
+iperf3_profile_CFLAGS =  -g
 iperf3_profile_LDADD = libiperf.la
-iperf3_profile_LDFLAGS = -pg -g
+iperf3_profile_LDFLAGS =  -g

 # Specify the sources and various flags for the test cases
 t_timer_SOURCES = t_timer.c
```

**Comment by bmah888** [comment]
Thanks for the report.  Does the normal (non-profiled) iperf3 executable build and run with uClibc?  I'd be interested to know how one goes about setting up that build environment.

**Comment by richud** [comment]
Hi bmah,
Thank you for your reply - I wasn't trying to build it profiled [didn't realise you could choose]  this happens by default  when doing a simple  ./configure --host=mips-linux && make

I just googled it now and came across on buildroot that seems to explain it.

http://git.buildroot.net/buildroot/commit/?id=6cf9c2b8309bad23b6badde81712517f6b1df7de

(specifically 0001-disable-profiling.patch)

**Comment by bmah888** [comment]
I'm not sure what to do with this...if we make the change in the patch, this breaks profiling on all platforms.

Going to close this for now because I don't know how we'd fix this in the mainline sources.
