### ISSUE TITLE
Omit [-O] option giving over-optimistic figures

### ISSUE THREAD

**Issue by candlerb** [esnet/iperf#236]
This is iperf3 3.0.9 running from a CentOS perfsonar node (pb-perf-1) to an OSX node (pb-client-1) over a gigabit ethernet link. The OSX end is running iperf3 -s.

With a basic test:

```
pb-perf-1 ~]$ iperf3 -c pb-client-1 -4 -t 5
Connecting to host pb-client-1, port 5201
[  4] local 192.0.2.2 port 57397 connected to 192.0.2.30 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   113 MBytes   947 Mbits/sec   49    276 KBytes
[  4]   1.00-2.00   sec   112 MBytes   941 Mbits/sec    0    342 KBytes
[  4]   2.00-3.00   sec   112 MBytes   942 Mbits/sec    0    397 KBytes
[  4]   3.00-4.00   sec   112 MBytes   940 Mbits/sec    2    255 KBytes
[  4]   4.00-5.00   sec   112 MBytes   941 Mbits/sec    0    325 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-5.00   sec   562 MBytes   942 Mbits/sec   51             sender
[  4]   0.00-5.00   sec   561 MBytes   942 Mbits/sec                  receiver

iperf Done.
```

This is good. Note that the theoretical maximum bandwidth of this link is

```
1448/1536 * 1_000_000_000 = 942.7 Mbps
```

which agrees with the figures measured.

But with `-O 2` the "receiver" measured bandwidth is consistently slightly too high:

```
pb-perf-1 ~]$ iperf3 -c pb-client-1 -4 -t 5 -O 2
Connecting to host pb-client-1, port 5201
[  4] local 192.0.2.2 port 57399 connected to 192.0.2.30 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   113 MBytes   946 Mbits/sec   28    270 KBytes       (omitted)
[  4]   1.00-2.00   sec   112 MBytes   941 Mbits/sec    0    337 KBytes       (omitted)
[  4]   0.00-1.00   sec   112 MBytes   942 Mbits/sec    0    393 KBytes
[  4]   1.00-2.00   sec   112 MBytes   943 Mbits/sec    2    240 KBytes
[  4]   2.00-3.00   sec   112 MBytes   942 Mbits/sec    0    314 KBytes
[  4]   3.00-4.00   sec   112 MBytes   941 Mbits/sec    0    375 KBytes
[  4]   4.00-5.00   sec   112 MBytes   942 Mbits/sec    2    208 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-5.00   sec   562 MBytes   942 Mbits/sec    4             sender
[  4]   0.00-5.00   sec   566 MBytes   949 Mbits/sec                  receiver
                                       ^^^^^^^^^^^^^ NOTE1

iperf Done.
```

The server side shows:

```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.0.2.2, port 57398
[  5] local 192.0.2.30 port 5201 connected to 192.0.2.2 port 57399
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   108 MBytes   903 Mbits/sec                  (omitted)
[  5]   1.00-1.00   sec   112 MBytes   471 Mbits/sec   << NOTE2
[  5]   1.00-2.00   sec   112 MBytes   942 Mbits/sec
[  5]   2.00-3.00   sec   112 MBytes   942 Mbits/sec
[  5]   3.00-4.00   sec   112 MBytes   941 Mbits/sec
[  5]   4.00-5.00   sec   112 MBytes   942 Mbits/sec
[  5]   5.00-5.04   sec  4.46 MBytes   944 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  5]   0.00-5.04   sec   562 MBytes   935 Mbits/sec    4             sender   << NOTE2
[  5]   0.00-5.04   sec   566 MBytes   942 Mbits/sec                  receiver
```

Looking at esmond data, it appears perfsonar is collecting the "receiver" figure. If I configure perfsonar with `omit_interval 2` the recorded data is consistently too high, which I would like to fix.

I don't believe this is related to #231:
1. That ticket resulted in figures on OSX being too low (although see NOTE2 above)
2. In this case I believe the receiver throughput measurement is being done at the Linux end

**Comment by bltierney** [comment]
Finally doing some more testing on this, and agree there seems to be some bugs in the way this is calculated, and perhaps also some bugs in how the throughput results are passed between client and server.

For example, see the results below:

Server side:

[  5]   0.00-1.00   sec  80.5 MBytes   676 Mbits/sec  506    667 KBytes       (omitted)
[  5]   1.00-2.00   sec  86.2 MBytes   724 Mbits/sec   79    427 KBytes       (omitted)
[  5]   2.00-3.00   sec  67.5 MBytes   566 Mbits/sec    0    614 KBytes       (omitted)
[  5]   3.00-4.00   sec  86.2 MBytes   724 Mbits/sec    0    790 KBytes       (omitted)
[  5]   4.00-5.00   sec  97.5 MBytes   818 Mbits/sec    0    986 KBytes       (omitted)
[  5]   0.00-1.00   sec   111 MBytes   933 Mbits/sec    0   1.18 MBytes
[  5]   1.00-2.00   sec   112 MBytes   944 Mbits/sec    0   1.20 MBytes
[  5]   2.00-3.00   sec   112 MBytes   944 Mbits/sec    0   1.20 MBytes
[  5]   3.00-4.00   sec   112 MBytes   944 Mbits/sec    0   1.21 MBytes
[  5]   4.00-5.00   sec   111 MBytes   933 Mbits/sec    0   1.22 MBytes
[  5]   5.00-6.00   sec   112 MBytes   944 Mbits/sec    0   1.22 MBytes
[  5]   6.00-7.00   sec   112 MBytes   944 Mbits/sec    0   1.22 MBytes
[  5]   7.00-8.00   sec   111 MBytes   933 Mbits/sec    0   1.22 MBytes
[  5]   8.00-9.00   sec   112 MBytes   944 Mbits/sec    0   1.23 MBytes
[  5]   9.00-10.00  sec   112 MBytes   944 Mbits/sec    0   1.23 MBytes
[  5]  10.00-10.04  sec  3.75 MBytes   817 Mbits/sec    0   1.23 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  5]   0.00-10.04  sec  1.10 GBytes   940 Mbits/sec    0             sender
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec                  receiver

Problems: 
  why is receiver throughput reported as 0?
  should probably throw out that last short interval from the report
  note: average of intervals after the omit window, not including the last short interval, is  940.7, so looks like its truncated, not rounded.

Client side:

[  4]   0.00-1.00   sec  80.0 MBytes   671 Mbits/sec                  (omitted)
[  4]   1.00-2.00   sec  84.1 MBytes   705 Mbits/sec                  (omitted)
[  4]   2.00-3.00   sec  68.9 MBytes   578 Mbits/sec                  (omitted)
[  4]   3.00-4.00   sec  87.6 MBytes   735 Mbits/sec                  (omitted)
[  4]   4.00-5.00   sec  97.1 MBytes   814 Mbits/sec                  (omitted)
[  4]   0.00-1.00   sec   112 MBytes   941 Mbits/sec
[  4]   1.00-2.00   sec   112 MBytes   941 Mbits/sec
[  4]   2.00-3.00   sec   112 MBytes   941 Mbits/sec
[  4]   3.00-4.00   sec   112 MBytes   941 Mbits/sec
[  4]   4.00-5.00   sec   112 MBytes   937 Mbits/sec
[  4]   5.00-6.00   sec   112 MBytes   942 Mbits/sec
[  4]   6.00-7.00   sec   112 MBytes   941 Mbits/sec
[  4]   7.00-8.00   sec   112 MBytes   941 Mbits/sec
[  4]   8.00-9.00   sec   112 MBytes   941 Mbits/sec
[  4]   9.00-10.00  sec   112 MBytes   941 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  1.10 GBytes   944 Mbits/sec    0             sender
[  4]   0.00-10.00  sec  1.10 GBytes   942 Mbits/sec                  receiver

Problems: 
    reported speed is 944Mbps, but if you do the math on those numbers, the average comes out to 940.7, so where does the value of 944 come from?  And why does that number not agree with the 'sender' speed as reported by the receiver?

**Comment by bmah888** [comment]
All of the test runs above were done before the fixes in #560 (which fixed some problems with statistics computation and printing), and the original test runs in this bug report were before the fixes in #414 (which addressed problems in `--omit` related to pacing).  From the tip of master I get this on the client:
```
[bmah@antg-staging iperf]$ src/iperf3 -4 --client antg-dev --port 5202 --omit 4 --time 10
Connecting to host antg-dev, port 5202
[  4] local 198.128.151.25 port 52564 connected to 198.128.151.17 port 5202
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   451 MBytes  3.78 Gbits/sec    0   1.20 MBytes       (omitted)
[  4]   1.00-2.00   sec   560 MBytes  4.70 Gbits/sec  307   1.25 MBytes       (omitted)
[  4]   2.00-3.00   sec   685 MBytes  5.75 Gbits/sec    9   1.14 MBytes       (omitted)
[  4]   3.00-4.00   sec   824 MBytes  6.91 Gbits/sec  294   1.12 MBytes       (omitted)
[  4]   0.00-1.00   sec   758 MBytes  6.35 Gbits/sec    0   1.23 MBytes
[  4]   1.00-2.00   sec   582 MBytes  4.89 Gbits/sec  159   1.17 MBytes
[  4]   2.00-3.00   sec   871 MBytes  7.31 Gbits/sec    0   1.22 MBytes
[  4]   3.00-4.00   sec   871 MBytes  7.31 Gbits/sec    0   1.25 MBytes
[  4]   4.00-5.00   sec   852 MBytes  7.15 Gbits/sec    0   1.26 MBytes
[  4]   5.00-6.00   sec   855 MBytes  7.18 Gbits/sec    0   1.29 MBytes
[  4]   6.00-7.00   sec   802 MBytes  6.73 Gbits/sec   93   1024 KBytes
[  4]   7.00-8.00   sec   779 MBytes  6.53 Gbits/sec    0   1.04 MBytes
[  4]   8.00-9.00   sec   841 MBytes  7.06 Gbits/sec    0   1.06 MBytes
[  4]   9.00-10.00  sec   851 MBytes  7.15 Gbits/sec   17    732 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  7.87 GBytes  6.76 Gbits/sec  269             sender
[  4]   0.00-10.03  sec  7.91 GBytes  6.77 Gbits/sec                  receiver

iperf Done.
```
If we sum up the transfers (after the omit interval), we see that 7.87GB is correct.  Dividing that by a 10-second test and converting gigabytes to gigabits per second yields 6.30Gbits/sec, which isn't the 6.76Gbits/sec reported on the sender (client) side.  So there's something odd here.

And this on the server:
```
Accepted connection from 198.128.151.25, port 52854
[  5] local 198.128.151.17 port 5202 connected to 198.128.151.25 port 52856
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   544 MBytes  4.56 Gbits/sec                  (omitted)
[  5]   1.00-2.00   sec   619 MBytes  5.19 Gbits/sec                  (omitted)
[  5]   2.00-3.00   sec   606 MBytes  5.08 Gbits/sec                  (omitted)
[  5]   3.00-4.00   sec   643 MBytes  5.39 Gbits/sec                  (omitted)
[  5]   0.00-1.00   sec   656 MBytes  5.51 Gbits/sec
[  5]   1.00-2.00   sec   881 MBytes  7.39 Gbits/sec
[  5]   2.00-3.00   sec   801 MBytes  6.72 Gbits/sec
[  5]   3.00-4.00   sec   774 MBytes  6.49 Gbits/sec
[  5]   4.00-5.00   sec   681 MBytes  5.71 Gbits/sec
[  5]   5.00-6.00   sec   836 MBytes  7.02 Gbits/sec
[  5]   6.00-7.00   sec   792 MBytes  6.64 Gbits/sec
[  5]   7.00-8.00   sec   824 MBytes  6.92 Gbits/sec
[  5]   8.00-9.00   sec   799 MBytes  6.70 Gbits/sec
[  5]   9.00-10.00  sec   755 MBytes  6.34 Gbits/sec
[  5]  10.00-10.03  sec  23.9 MBytes  6.27 Gbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.03  sec  7.64 GBytes  6.54 Gbits/sec                  receiver```
```
The total transfer size is correct on the receiver side.  Note that it's different from what the client sent, I think this is because they have different ideas of when the omit interval ended.

There's also something weird in that the receiver stats from the server aren't the same as the receiver stats reported on the client (in theory they should be the same).  This works correctly in the non-`--omit` case, so there's likely something to do with the `--omit` processing logic that doesn't work.

Need to investigate this weirdness.

**Comment by bmah888** [comment]
There's something weird going on but I don't have a handle on it yet.  This is not helped by the fact that the statistics computation is intertwined with the code that emits the report output, and there are multiple code paths involved depending on protocols, test role, number of parallel streams, etc.  It's basically a maze of twisty little C statements, all different.

**Comment by bmah888** [comment]
OK.  I think it's actually doing at least halfway the right thing.  The changes in c76107c actually have no bearing on the test cases above, so we can ignore that commit for now (although I will say this commit should eventually go to master because it does fix several bugs).

Let's look at the data in my post from about five days ago.  If we sum up the ten non-omit intervals in the client/sender output, we get 8062 MB.  8062/1024 = 7.87, so that accounts for the `7.87 GBytes/s` total.  If we convert the 8062 MB to Bytes (there's some rounding error) we get about 8453619712 Bytes.  8453619712 Bytes / 10 seconds * 8 bits/Byte / 1000000000 = 6.762 Gbps.  Note that bitrates use SI prefixes that are base 10 (e.g. 1000), while storage amounts use SI prefixes that are base 2 (e.g. 1024).  My earlier computation didn't take that into account.

On the server side, we have 7823 MB, or 7.64 GB.  7823 MB received in 10 seconds is 8203010048 Bytes / 10.03 seconds * 8 bits/Byte / 1000000000 = 6.542 Gbits/sec.  So from what I can tell in the above example (and other similar cases I've run), the computations are now being done correctly.

There's the issue that the receiver statistics as presented on the client and server don't match.  I believe those have been all addressed by various code changes within the past week.

The original issue dealt with the bandwidth measurement being a little too high.  I hypothesize (but without being able to prove it) that having data in flight at the omit interval, plus the fact that the test data transmission isn't synchronized with control channel activity, might have caused some data that was originally transmitted during an "omit" interval on the sender to be received during a "transfer" interval on the sender.  This is similar to a (again, hypothesized) problem where a message on the control connection might stop a test with data still in flight (see commentary in #252).  I'm not sure if this (decoupling between the control and data connections) is really happening or not, and if so, whether this is a bug to be fixed.

I'm going to keep this open to think about it a little bit.  If don't hear any objections by the end of this week I'm going to do a pull request to merge c76107c to master and close this issue.

**Comment by bmah888** [comment]
OK I jumped the gun a little bit on the pull request / merge of c76107c.  That merge was 35ec9e5 / #575.

**Comment by bmah888** [comment]
After some discussion we've tentatively concluded that this bug has been fixed by recent code changes dealing with reporting.  (See also some comments in #443.)  Closing this issue, please feel free to re-open if we haven't really fixed it.
