### ISSUE TITLE
Bind port selection logic incorrect for multi-stream tests

### ISSUE THREAD

**Issue by jfitzgibbon** [esnet/iperf#239]
If I run a TCP test, (client), with the -P [N] option, the bind ports selected for the second and subsequent connections are wrong. The selected port is 1, then 2, 3, etc., whereas they should all be using ephemeral ports selected by the O/S. Using these privileged ports by default means that I cannot run the client as anything but root. It can also cause time-wait clashes if I run tests back-to-back.

Fix is to only increment the bind_port if the original bind port is non-zero, (i.e. orig bind port == 0 means "always use next ephemeral port"):

diff --git a/src/iperf_client_api.c b/src/iperf_client_api.c
index 865faa1..1518bf5 100644
--- a/src/iperf_client_api.c
+++ b/src/iperf_client_api.c
@@ -53,7 +53,10 @@ iperf_create_streams(struct iperf_test *test)
     int orig_bind_port = test->bind_port;
     for (i = 0; i < test->num_streams; ++i) {
 
-        test->bind_port = orig_bind_port + i;
+        test->bind_port = orig_bind_port;
+        if (orig_bind_port)
+            test->bind_port += i;
+
         if ((s = test->protocol->connect(test)) < 0)
             return -1;

**Comment by bmah888** [comment]
I think this problem came about with #209.  Triggering the problem actually requires that you bind the source address with ```-B```, do *not* use the ```--cport``` option (so that the client uses an ephemeral port), and do parallel tests with ```-P```.

The patch looks correct to me.
