### ISSUE TITLE
iperf-3.0.11 : iperf3: error while loading shared libraries: libiperf.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by iamshital** [esnet/iperf#240]
This issue was resolved in Ubuntu by installing "lib32z1" package by "apt-get install lib32z1". 
But iperf3 is giving lilbiperf.so.0 file error warning for following distros :
1.Opensuse13.1
2.Suse Linux Enterprize Server 12
3.CoreOS.

**Comment by iamshital** [comment]
Same issue on Suse Linux Enterprize Server 12.

**Comment by bmah888** [comment]
This sounds like #153.  Please feel free to re-open this issue if this is a different problem.
