### ISSUE TITLE
Is there plan to support  "reverse" test ?

### ISSUE THREAD

**Issue by nyamakawa** [esnet/iperf#241]
For measuring download bandwidth of PCs behind NAT,
client-initiated "reverse" test is very useful.

In iperf2, there is a patch to support that(I usually use it).
https://github.com/tierney/iperf

Is there plan to support client-initiated "reverse" test option ?

**Comment by bmah888** [comment]
iperf3 has a ```--reverse``` command-line flag that causes the server to send test data to the client.

**Comment by joelBrun** [comment]
yes but I found that iperf3 is less relaiable on multiple streams (--parrallele) than the version iperf2.
