### ISSUE TITLE
Test intervals and summary UDP block/packet counts don't agree

### ISSUE THREAD

**Issue by nomel** [esnet/iperf#252]
Using `-u` and `-k100` for 100 datagrams,

On client:

```
Starting Test: protocol: UDP, 1 streams, 8192 byte blocks, omitting 0 seconds, 100 blocks to send
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-13.00  sec   800 KBytes   504 Kbits/sec  100
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-13.00  sec   800 KBytes   504 Kbits/sec  0.079 ms  0/99 (0%)
[  4] Sent 99 datagrams
```

Interval, and command line options, claim 100 packets. Summary and server claims 99.

On server:
```
Accepted connection from 10.10.11.130, port 35463
[  5] local 10.10.11.143 port 5201 connected to 10.10.11.130 port 44128
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-6.24   sec   792 KBytes  1.04 Mbits/sec  0.207 ms  0/99 (0%)

---

[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-6.24   sec   800 KBytes  1.05 Mbits/sec  0.207 ms  0/99 (0%)
```

EDIT:  Fix formatting for legibility.  --bmah

**Comment by bmah888** [comment]
I've seen this on the tip-of-master code.

**Comment by bmah888** [comment]
This feels something like #382, where the sender/client is sending a fixed amount of data and then ends the test via the control connection.  If the data is still in flight when the receiver/server receives that control message, that can cause a disagreement in the amount of data sent and received.  As with #382, the solution isn't obvious at this point.

**Comment by bltierney** [comment]
Confirming that this is still an issue:

./iperf3 -c nettest.lbl.gov -p 5300 -u -k 11 -l 1400
Connecting to host nettest.lbl.gov, port 5300
[  4] local 198.128.151.25 port 37339 connected to 131.243.24.11 port 5300
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-0.11   sec  15.0 KBytes  1.15 Mbits/sec  11
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-0.11   sec  15.0 KBytes  1.15 Mbits/sec  0.122 ms  0/10 (0%)
[  4] Sent 10 datagrams

I'm not sure if this is related to #382, or just an off-by-one error.

**Comment by bmah888** [comment]
I tried to reproduce this problem but I had mixed results.  This run worked as expected:
```
[bmah@antg-staging iperf]$ src/iperf3 --client antg-dev --port 5202 --udp -k 11
Connecting to host antg-dev, port 5202
[  4] local 2001:400:210:151::25 port 57963 connected to 2001:400:210:151::11 port 5202
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-0.11   sec  15.3 KBytes  1.15 Mbits/sec  11
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-0.11   sec  15.3 KBytes  1.15 Mbits/sec  0.060 ms  0/11 (0%)  sender
[  4]   0.00-0.15   sec  15.3 KBytes   846 Kbits/sec  0.060 ms  0/11 (0%)  receiver

iperf Done.
```
But this one didn't:
```
[bmah@antg-staging iperf]$ src/iperf3 --client antg-dev --port 5202 --udp -k 11
Connecting to host antg-dev, port 5202
[  4] local 2001:400:210:151::25 port 34274 connected to 2001:400:210:151::11 port 5202
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-0.11   sec  15.3 KBytes  1.15 Mbits/sec  11
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-0.11   sec  15.3 KBytes  1.15 Mbits/sec  0.386 ms  0/10 (0%)  sender
[  4]   0.00-0.14   sec  13.9 KBytes   793 Kbits/sec  0.386 ms  0/10 (0%)  receiver

iperf Done.
```
Not going to try to guess at a root cause for this yet.

**Comment by bmah888** [comment]
It seems like the client side statistics computation relies on getting the count of packets from the server side (`sp->packet_count`) and using that for computing the loss rate (`lost_percent`).  This is fine, except for the case where the last packet (or packets) doesn't make it to the receiver before the test is over.  So in the broken cases above, there are two problems:

1.  The sender should retain its own knowledge of how many sends it did and not forget that in favor of what the receiver got.  This is definitely a bug.

2.  We should try to work harder to ensure that we don't end the test before all packets arrived.  It's completely possible that the last packet would never have made it (say it was dropped), so having the sender and receiver claim different packet counts isn't automatically wrong.  Fixing this is more of an enhancement.
