### ISSUE TITLE
How to remove delays for creating multiple streams with -P option

### ISSUE THREAD

**Issue by mindolm** [esnet/iperf#254]
Hi,

I'm creating many tcp flows (e.g., -P 100) from a client to a server. I works perfectly okay except that the client has to wait some non-negligible time to start sending any meaningful traffic. 

I measured the waiting time and figured out that roughly the client waits 0.2 sec for each connection; for example, if I command to send 100 tcp flows (with -P 100), I have to wait 20 sec for the client to actually start sending the flows. 

Is it due to some misconfigurations? Any other workaround to start sending immediately? 

Thanks a lot!
Min Suk

**Comment by bmah888** [comment]
I'm not seeing this problem.  If I do -P 100 tests to localhost, the time to actually start sending traffic looks to be about a second.

What version of iperf3 are you using?

Any possibility that you might be going over a congested path of some kind?

**Comment by mindolm** [comment]
I figured out what caused the delay. The client and the server have a long-distance link (RTT = 200ms) between them. So, each tcp connection setup takes 0.2 sec and thus 100-connection setup takes 20 seconds in total. 

Based on my observation, I guess the initial connection setup for multiple connections is a serial process; once one connection is setup then the next one goes. 

Is there any way to initiate the connections concurrently with the long-distance link? Or would you recommend any workaround?

Thank you so much!
Min Suk

**Comment by bmah888** [comment]
Yes, the multiple connection setup is a serial process.  Unfortunately I don't know of a good workaround for this.  The only way I think can think of dealing with this is some kind of multi-threading or non-blocking socket setup.  Either one of these is just not something that iperf3 is designed to do, at least not at this time.

**Comment by mindolm** [comment]
I got it. Thanks a lot for your help :)

**Comment by bmah888** [comment]
This probably should have been closed when I last touched this issue a couple years ago.
