### ISSUE TITLE
How to integrate iperf into an iOS project?

### ISSUE THREAD

**Issue by yeahdongcn** [esnet/iperf#255]
Hi, I want to have the iperf integrated as a client in an iOS project, but I don't know how. Could you please provide some tutorial about that? Thank you.

**Comment by bmah888** [comment]
Running iperf3, while an interesting idea, is really outside the scope of our project.

WiFiPerf is a commercial iOS app that includes functionality from an older version of iperf3, unfortunately it was written before some of the iperf3 messages were finalized.  Thus it doesn't interoperate with any recent version of iperf3.

**Comment by JoshLoveCoder** [comment]
Hi，I want to use the lib, in my ios prj, but find it can not build, for not support the x86_64. And I get the lipo -info XXX.a, find it not support i386 arm64 armv7s x86_64. I want to know the way to build for the other ones, I git load the code, but can only get x86_64. Could you tell me the way to configure and build it.

**Comment by bmah888** [comment]
Building iperf3 under iOS is not officially supported by ESnet, and we don't really have the knowledge to help, so we can't really give any guidance on this.  Nevertheless, some people have done this successfully, see for example:

https://itunes.apple.com/us/app/he-net-network-tools/id858241710?mt=8

You could try contacting the developers of that app directly, or putting a message on the iperf-dev or iperf-users mailing lists to see if someone in the community might be able to help you.  Good luck!

**Comment by yeahdongcn** [comment]
Probably you could try https://github.com/yeahdongcn/iperf-iOS.git, I was able to use client in this sample.
