### ISSUE TITLE
Segfault in the signal handler

### ISSUE THREAD

**Issue by manojdelphix** [esnet/iperf#257]
iperf3 server runs in a loop like this (simplified):

run():
for (;;) {
  -> iperf_run_server(test)
       -> setup signal handler
       -> iperf_server_listen
            -> bind(s)
            -> test->listener = listen(s,5)
            -> print banner
       -> cleanup_server(test);
            -> close(test->listener);
  -> iperf_reset_test(test);
}

iperf3 sets up a signal handler in a loop. The routine that sets it up returns at the end of a test. Once it returns, the stack context saved by setjmp is no longer valid (per man setjmp(3)).

Until the signal handler is reestablished in the next iteration, the saved stack context is invalid. Hence a signal received during this window will result in a segfault.

I am able to demonstrate this by adding a sleep(3) in the window.

> sybase@bbdhcp:/home/sybase/iperf-3.0.11/src-> ./iperf3 -s
> -----------------------------------------------------------
> Server listening on 5201
> -----------------------------------------------------------
> Accepted connection from 10.43.11.189, port 61818
> [  6] local 10.43.13.229 port 5201 connected to 10.43.11.189 port 32916
> [ ID] Interval           Transfer     Bandwidth
> [  6]   0.00-1.00   sec  91.5 MBytes   768 Mbits/sec
> [  6]   1.00-2.00   sec  75.6 MBytes   634 Mbits/sec
> [  6]   2.00-3.00   sec  77.8 MBytes   652 Mbits/sec
> [  6]   3.00-4.00   sec  84.8 MBytes   711 Mbits/sec
> [  6]   4.00-5.00   sec  92.0 MBytes   771 Mbits/sec
> [  6]   5.00-6.00   sec  79.0 MBytes   663 Mbits/sec
> [  6]   6.00-7.00   sec  96.1 MBytes   806 Mbits/sec
> [  6]   7.00-8.00   sec  63.4 MBytes   532 Mbits/sec
> [  6]   8.00-9.00   sec  62.1 MBytes   521 Mbits/sec
> [  6]   9.00-10.00  sec  78.9 MBytes   662 Mbits/sec
> [  6]  10.00-10.00  sec   146 KBytes   705 Mbits/sec
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bandwidth
> [  6]   0.00-10.00  sec   816 MBytes   684 Mbits/sec                  sender
> [  6]   0.00-10.00  sec   801 MBytes   672 Mbits/sec                  receiver
> Sleeping between tests    <--------------------  Ctrl+C segfaults
> Segmentation fault (core dumped)
> sybase@bbdhcp:/home/sybase/iperf-3.0.11/src->

I have a fix for this bug. I can send a the patch across if someone can tell me how I send it.

**Comment by manojdelphix** [comment]
Pull request:
https://github.com/esnet/iperf/pull/258

**Comment by bmah888** [comment]
I'm going to close this issue in our issue tracker as a duplicate.  Your pull request #258 remains open (with a back-pointer to this issue)...I'm hoping to be able to look at it soon-ish.  Thanks!
