### ISSUE TITLE
Invalid bandwidth when switching from TCP to UDP

### ISSUE THREAD

**Issue by AgamAgarwal** [esnet/iperf#259]
We were doing certain network tests using `iperf` when we came across this bug.
Here is what we did:

   1. Started `iperf` server on one machine in TCP mode
   ```bash
   iperf -s -i 1
   ```

   2. Started `iperf` client on another machine
   ```bash
   iperf -c 192.168.1.30 -i 1 -t 1000
   ```

   3. Terminated the server process and started it in UDP mode instead
   ```bash
   iperf -s -i 1 -u
   ```

After the 3rd step, the client started giving weird results.
The bandwidth it should was around `147573952589675855872 bytes/sec`, which is abnormal.

We repeated the steps and it was reproducible.
The server and client were both Ubuntu 14.04 machines.

**Comment by bmah888** [comment]
This issue tracker is for iperf3, but the problems being reported looks like a bug report against iperf2.  (iperf3 does not have, not does it require, a ```-u``` flag on the server to specify a UDP test.)

Marking as invalid.
