### ISSUE TITLE
arm64: mustang: 10G: iperf3: error - unable to write to stream socket: Connection reset by peer

### ISSUE THREAD

**Issue by arun-chandran** [esnet/iperf#264]
Hi,

I am testing Iperf3 on an arm64 platform ( https://www.apm.com/products/data-center/x-gene-family/x-c1-development-kits/x-c1-development-kit-basic/)

```
Linux kernel used:
```

uname -a
Linux buildroot 4.1.0-rc3 #27 SMP PREEMPT Mon May 11 15:11:26 IST 2015 aarch64 GNU/Linux

```
Filesystem used:
```

rootfs is build from http://buildroot.uclibc.org/downloads/buildroot-2015.02.tar.gz

Iperf3(commit 7645027d0d11c8dbb57c770090adea374bdc049c) is cross compiled using http://releases.linaro.org/14.11/components/toolchain/binaries/aarch64-linux-gnu/gcc-linaro-4.9-2014.11-x86_64_aarch64-linux-gnu.tar.xz

10G port on both boards are connected via fiber cable for testing.
# Now on serverside I got

# iperf3 -s -B 192.168.1.1 -V
iperf 3-CURRENT
## Server listening on 5201

Time: Mon, 11 May 2015 16:00:11 GMT
Accepted connection from 192.168.1.2, port 54979
      Cookie: buildroot.1431359906.416514.524bc380
      TCP MSS: 1448 (default)
[  5] local 192.168.1.1 port 5201 connected to 192.168.1.2 port 59682
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 200 second test
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   218 MBytes  1.83 Gbits/sec  
[  5]   1.00-2.00   sec   233 MBytes  1.96 Gbits/sec  
[  5]   2.00-3.00   sec   221 MBytes  1.85 Gbits/sec  
[  5]   3.00-4.00   sec   224 MBytes  1.88 Gbits/sec  
[  5]   4.00-5.00   sec   226 MBytes  1.90 Gbits/sec  
[  5]   5.00-6.00   sec   226 MBytes  1.89 Gbits/sec  
[  5]   6.00-7.00   sec   226 MBytes  1.89 Gbits/sec  
[  5]   7.00-8.00   sec   228 MBytes  1.91 Gbits/sec  
[  5]   8.00-9.00   sec   226 MBytes  1.90 Gbits/sec  
[  5]   9.00-10.00  sec   246 MBytes  2.06 Gbits/sec  
iperf3: the client has unexpectedly closed the connection
# At client side

# iperf3 -c 192.168.1.1 -B 192.168.1.2 -t 200 -V -i 10
iperf 3-CURRENT
Linux buildroot 4.1.0-rc3 #27 SMP PREEMPT Mon May 11 15:11:26 IST 2015 aarch64
Time: Mon, 11 May 2015 15:58:26 GMT
Connecting to host 192.168.1.1, port 5201
      Cookie: buildroot.1431359906.416514.524bc380
      TCP MSS: 1448 (default)
[  4] local 192.168.1.2 port 59682 connected to 192.168.1.1 port 5201
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 200 second test
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-10.00  sec  2.24 GBytes  1.92 Gbits/sec   21    389 KBytes  
iperf3: error - unable to write to stream socket: Connection reset by peer

Can anyone tell me how to debug this further?

--Arun

**Comment by bmah888** [comment]
I acknowledge seeing this question but I don't have any particular insight on how to diagnose / fix it.  Hopefully someone else will be able to chime in.

**Comment by billzhuang** [comment]
i meet this problem many many times in iperf3 in one of my linux server.

**Comment by bmah888** [comment]
Are you still seeing this issue with a current version of iperf3?  Is this still a problem?

**Comment by bmah888** [comment]
Closing due to lack of additional information.  Please feel free to re-open if this is still a problem and there's some more information to help us diagnose the problem.
