### ISSUE TITLE
Set Receive Buffer Size

### ISSUE THREAD

**Issue by twoi** [esnet/iperf#267]
With iperf (v 2.0.5) you can set the receive buffer size for the iperf server via the `-l` parameter:

```
GENERAL OPTIONS
...
       -l, --len n[KM]
              set length read/write buffer to n (default 8 KB)
```

 In iperf3, that parameter turned client-side only:

```
CLIENT SPECIFIC OPTIONS
...
       -l, --length n[KM]
              length of buffer to read or write (default 128 KB for TCP, 8KB for UDP)
```

This means with iperf3 I cannot address the [extreme udp packet losses](http://serverfault.com/questions/691723/extreme-udp-packet-loss-at-300mbit-14-but-tcp-800mbit-w-o-retransmits) the way it is [possible with iperf](http://serverfault.com/a/691905/124382).

**Comment by bmah888** [comment]
In iperf3, you specify the socket buffer size on the client, but that parameter is passed to the server for it to set its socket buffer size as well.  (Unlike iperf2, iperf3 uses a control channel to exchange test parameters and results between the client and server.)  So the difference between iperf2 and iperf3, at least in this area, is not quite as big as it might seem.

There might be other factors contributing to the performance you observed (I need to read your serverfault.com postings more carefully), but at ESnet we've gotten multi-gigabit streams of UDP between hosts with little or no loss.

**Comment by twoi** [comment]
Isn't `-l` the parameter that sets the packet size for UDP packets? That's at least what I remember I saw in Wireshark, and trying a `-l64k` resulted in the following error:

```
$ iperf3 -uVc 192.168.30.160 -b300m -t3 --get-server-output -l64k
iperf 3.0.7
Linux mybox 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux
Time: Fri, 15 May 2015 23:51:59 GMT
Connecting to host 192.168.30.160, port 5201
      Cookie: mybox.1431733919.290974.027141a9
[  4] local 192.168.30.202 port 33014 connected to 192.168.30.160 port 5201
Starting Test: protocol: UDP, 1 streams, 65536 byte blocks, omitting 0 seconds, 3 second test
iperf3: error - unable to write to stream socket: Message too long
```

**Comment by twoi** [comment]
P.S. Being able to set the server side receive buffer size for every test run on the client side would be great. However, I'd suggest making that parameter separate, not tied to the sender buffer/packet/datagram size to allow for a wider range of tests.

And while I'm at it, adding "total" as the first word of the following parameter descriptions would be helpful. For `-n` in particular, it would make the difference to `-l` immediately apparent (although the comment in parentheses is helpful).

 ```
       -n, --bytes n[KM]
              number of bytes to transmit (instead of -t)

       -k, --blockcount n[KM]
              number of blocks (packets) to transmit (instead of -t or -n)
```

**Comment by bmah888** [comment]
Ah, sorry.  When you said "buffer" I immediately locked onto the socket buffer parameter.  Let me try this again.

The value of the ```-l``` parameter does get passed from the client to the server, regardless of which direction the test is going.  So both sides should be in agreement about the transfer block size.  This is separate and orthogonal to the ```-w``` parameter that sets the size of the socket buffers (and which is also passed from the client to the server).  Both sides should also be in agreement about the size of the socket buffers.

The maximum transfer size for UDP is the 65535-8-20, which is (supposed to be) the maximum size of an IP packet minus the default sizes of the IPv4 and UDP headers.  It's basically used as the size of the send call for UDP tests, which turns into the size of the UDP payload (hence subtracting off the length of the IPv4 and UDP headers to make sure we don't end up with a datagram that is larger than the maximum IPv4 packet size).

(As an aside, note that IPv6 has a different header size from IPv4.  It's possible to set ```-l``` for an IPv6 test so that the resulting IPv6 packets are too large.  I'm not sure if that leads to fragmentation or an error.)

Note the socket buffers can (and probably should) be much much bigger than the UDP packet sizes.  We saw some issues on one of the ESnet testbeds where we needed fairly big socket buffers to get satisfactory throughput.

The documentation changes you suggested are a good idea.

**Comment by twoi** [comment]
Thanks for making me aware of `-w`. Btw, it's hard for both `-l` and `-w` NOT to be in agreement, as they are client side only parameters, but that aside.

I tried `-w`, and the results were rather strange. I'll give two examples where only the `-w` parameter differs.

**iperf3 -uVc 192.168.20.59 -b300m -t5 --get-server-output -l1470 -w1M**

```
iperf 3.0.7
Linux mybox 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux
Time: Mon, 01 Jun 2015 23:14:45 GMT
Connecting to host 192.168.20.59, port 5201
      Cookie: mybox.1433200485.043625.0b06a12a
[  4] local 192.168.20.55 port 54961 connected to 192.168.20.59 port 5201
Starting Test: protocol: UDP, 1 streams, 1470 byte blocks, omitting 0 seconds, 5 second test
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec  33.3 MBytes   279 Mbits/sec  23753  
[  4]   1.00-2.00   sec  35.8 MBytes   300 Mbits/sec  25511  
[  4]   2.00-3.00   sec  35.8 MBytes   300 Mbits/sec  25510  
[  4]   3.00-4.00   sec  35.8 MBytes   300 Mbits/sec  25507  
[  4]   4.00-5.00   sec  35.8 MBytes   300 Mbits/sec  25515  
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-5.00   sec   176 MBytes   296 Mbits/sec  0.160 ms  86982/125689 (69%)  
[  4] Sent 125689 datagrams
CPU Utilization: local/sender 15.0% (1.2%u/13.8%s), remote/receiver 18.2% (7.5%u/10.7%s)

Server output:
-----------------------------------------------------------
Accepted connection from 192.168.20.55, port 59534
[  5] local 192.168.20.59 port 5201 connected to 192.168.20.55 port 54961
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  11.2 MBytes  93.9 Mbits/sec  0.382 ms  13735/21730 (63%)  
[  5]   1.00-2.00   sec  9.42 MBytes  79.2 Mbits/sec  0.074 ms  18834/25555 (74%)  
[  5]   2.00-3.00   sec  13.0 MBytes   109 Mbits/sec  0.069 ms  16272/25529 (64%)  
[  5]   3.00-4.00   sec  9.19 MBytes  77.1 Mbits/sec  0.064 ms  18858/25412 (74%)  
[  5]   4.00-5.00   sec  11.1 MBytes  92.8 Mbits/sec  0.064 ms  17711/25601 (69%)  
```

Extreme packet loss, so let's increase the buffer size to 100M.

**iperf3 -uVc 192.168.20.59 -b300m -t5 --get-server-output -l1470 -w100M**

```
iperf3 -uVc 192.168.20.59 -b300m -t5 --get-server-output -l1470 -w100M
iperf 3.0.7
Linux mybox 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux
Time: Mon, 01 Jun 2015 23:17:36 GMT
Connecting to host 192.168.20.59, port 5201
      Cookie: mybox.1433200656.459097.38cbb665
[  4] local 192.168.20.55 port 57045 connected to 192.168.20.59 port 5201
Starting Test: protocol: UDP, 1 streams, 1470 byte blocks, omitting 0 seconds, 5 second test
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec  33.3 MBytes   279 Mbits/sec  23755  
[  4]   1.00-2.00   sec  35.8 MBytes   300 Mbits/sec  25511  
[  4]   2.00-3.00   sec  35.8 MBytes   300 Mbits/sec  25507  
[  4]   3.00-4.00   sec  35.8 MBytes   300 Mbits/sec  25507  
[  4]   4.00-5.00   sec  35.8 MBytes   300 Mbits/sec  25516  
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-5.00   sec   176 MBytes   296 Mbits/sec  0.075 ms  0/37324 (0%)  
[  4] Sent 37324 datagrams
CPU Utilization: local/sender 15.3% (1.2%u/14.1%s), remote/receiver 1.6% (0.6%u/1.0%s)

Server output:
-----------------------------------------------------------
Accepted connection from 192.168.20.55, port 59574
[  5] local 192.168.20.59 port 5201 connected to 192.168.20.55 port 57045
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  6.75 MBytes  56.6 Mbits/sec  0.125 ms  0/4814 (0%)  
[  5]   1.00-2.00   sec  8.55 MBytes  71.8 Mbits/sec  0.075 ms  0/6102 (0%)  
[  5]   2.00-3.00   sec  11.1 MBytes  93.5 Mbits/sec  0.075 ms  0/7947 (0%)  
[  5]   3.00-4.00   sec  10.8 MBytes  90.3 Mbits/sec  0.065 ms  0/7678 (0%)  
[  5]   4.00-5.00   sec  11.8 MBytes  98.6 Mbits/sec  0.066 ms  0/8382 (0%)  
```

Great! No packet loss. Except the server bandwidth/total datagrams figures don't match those of the client. A bug?

**Comment by twoi** [comment]
> Both sides should also be in agreement about the size of the socket buffers.

Btw, why is the socket send buffer size required to match the socket receive buffer size? I'd like to change them separately, to match the differing needs of sender and receiver.

**Comment by bmah888** [comment]
When I meant "should" I meant that the desired behavior was that the sender and receiver's buffer sizes be the same.  There's no intrinsic reason that it needs to be this way, that's just the desired behavior of the code, as currently designed.

**Comment by nh2** [comment]
This issue I just filed seems related: https://github.com/esnet/iperf/issues/356

**Comment by bmah888** [comment]
At this point we don't have any plans for changing the sender and receiver windows independently.  This of course doesn't preclude someone from forking a copy of the code and modifying it to do this.  Closing.
