### ISSUE TITLE
Request to handle EWOULDBLOCK  on read and write

### ISSUE THREAD

**Issue by tvastri** [esnet/iperf#268]
Would it be possible to handle EWOULDBLOCK along with EAGAIN when reading (Nread) and writing (Nwrite/Nsendfile)? While the current code is fine for Linux (where EGAIN == EWOULDBLOCK), porting the code would become easier on systems where EWOULDBLOCK has a different value than EAGAIN.

I ran into the problem when porting v3.0.11 to vxWorks (where EAGAIN = 11 and EWOULDBLOCK = 70).

**Comment by bmah888** [comment]
This looks reasonable.  Need to get some bandwidth to do this.

**Comment by bmah888** [comment]
Committed to master, thanks for the suggestion.
