### ISSUE TITLE
Semicolon (;) terminating usage_longstr definition in iperf_locale.c inside conditionally compiled code

### ISSUE THREAD

**Issue by tvastri** [esnet/iperf#269]
Minor nitpick.

If someone undefs PACKAGE_BUGREPORT in config.h, iperf_locale.c will not compile because usage_longstr definition will not have a semicolon at the end.

#ifdef PACKAGE_BUGREPORT
                           "Report bugs to:     " PACKAGE_BUGREPORT "\n"; <<<<<< (move the ';' after 'endif')
#endif /* PACKAGE_BUGREPORT */

**Comment by bmah888** [comment]
Commited suggested fix on master, thanks!
