### ISSUE TITLE
Add option for delay after omitted data to test idle connections

### ISSUE THREAD

**Issue by PSUdaemon** [esnet/iperf#270]
I would like to see an option that allows me to run some amount of traffic through a TCP connection then wait for a period then send more data through. I would like to measure the flow after the delay. The point is to grow the cwnd and then test reuse of an idle connection, that might be in a connection pool, with things like `net.ipv4.tcp_slow_start_after_idle = 0`

**Comment by bmah888** [comment]
Closing.  This seems like an interesting idea, although it falls somewhat outside the usual range of use cases that we can support.
