### ISSUE TITLE
iperf3: OUT OF ORDER - Server Sends out of order

### ISSUE THREAD

**Issue by huvar** [esnet/iperf#274]
Hi,
My server seems to be sending UDP data out of order. I have done a packet capture in both ends and realized that the packages exit already out of order...
Is any bug like this known? Any maybe the cause?

```
iperf3 -v
iperf 3.0.9
Linux XXX 2.6.32-504.8.1.el6.x86_64 #1 SMP Fri Dec 19 12:09:25 EST 2014 x86_64 x86_64 x86_64 GNU/Linux

[  4]   0.00-1.00   sec   129 KBytes  1.05 Mbits/sec  0.044 ms  0/94 (0%)
[  4]   1.00-2.00   sec   129 KBytes  1.05 Mbits/sec  0.075 ms  0/94 (0%)
[  4]   2.00-3.00   sec   127 KBytes  1.04 Mbits/sec  0.078 ms  0/93 (0%)
[  4]   3.00-4.00   sec   129 KBytes  1.05 Mbits/sec  0.059 ms  0/94 (0%)
[  4]   4.00-5.00   sec   129 KBytes  1.05 Mbits/sec  0.071 ms  0/94 (0%)
[  4]   5.00-6.00   sec   127 KBytes  1.04 Mbits/sec  0.033 ms  0/93 (0%)
[  4]   6.00-7.00   sec   129 KBytes  1.05 Mbits/sec  0.070 ms  0/94 (0%)
[  4]   7.00-8.00   sec   129 KBytes  1.05 Mbits/sec  0.043 ms  0/94 (0%)
[  4]   8.00-9.00   sec   127 KBytes  1.04 Mbits/sec  0.053 ms  0/93 (0%)
iperf3: OUT OF ORDER - incoming packet = 885 and received packet = 888 AND SP = 4
[  4]   9.00-10.00  sec   129 KBytes  1.05 Mbits/sec  0.044 ms  1/94 (1.1%)
```

**Comment by bmah888** [comment]
You'll need to provide some more information.  What platform(s) are being used for the server and client?  What test parameters (you didn't say what your command-line parameters are)?  What's the network like between the client and server?  (In particular any LAGG or similar links that might reorder packets?)  Did you see this once or many times?  How often does this happen?

Note that IP doesn't guarantee in-order delivery...so getting packets out-of-order is undesirable, but not necessarily a bug in iperf3 or any other part of the end hosts.

**Comment by nhed** [comment]
If the protocol does not guarantee order, why do we expect the kernel (stack) to maintain an order?

**Comment by bmah888** [comment]
Additional information not provided in 21 months, closing issue.
