### ISSUE TITLE
iperf3 daemon not binding UDP on Amazon AMIs

### ISSUE THREAD

**Issue by TheM0ng00se** [esnet/iperf#275]
When running a UDP test I noticed that the receiving station appears to only listen on TCP not UDP. As a result, the client simply only reports what it knows about (perfect test), and I have no accurate information on the speed or loss. Running this between 2 Amazon AMIs...details below

[root@iperfserv ~]# iperf3 -s -p 80 -D
[root@iperfserv ~]# netstat -anp | grep iperf3
tcp        0      0 :::80                       :::\*                        LISTEN      2927/iperf3         

/etc/os-release
::::::::::::::
NAME="Amazon Linux AMI"
VERSION="2015.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.03"
PRETTY_NAME="Amazon Linux AMI 2015.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Comment by TheM0ng00se** [comment]
tcpdump on the receiver shows 2, 4-byte UDP packets come in after the control connection is established. The client blasts out the UDP as requested.

**Comment by bmah888** [comment]
The TCP connection you see is the control connection that the client and server use to communicate the test parameters.  The UDP sockets (for both client and server) are not created and/or bound until the test starts.  Note that this behavior is different from iperf2.

**Comment by TheM0ng00se** [comment]
It is strange that iperf3 will simply not receive crafted udp packets in this environment whereas iperf2 and nuttcp have no problems. I guess we could close out this issue, but it may be nice to know what limitations there are running iperf3 in AWS. (I have tried a number of AMIs to no avail with UDP). 

Let me know if you'd like to see captures.

**Comment by bmah888** [comment]
Ah, OK, so you are not receiving any UDP packets between the client and server?  That wasn't apparent from the initial post.

Do you know what kinds of firewalling might going on between the AMIs?  I'm not really familiar with this environment.

What happens if you run client and server on the same AMI and just test to "localhost" or to one of the IP addresses on the AMI?

**Comment by TheM0ng00se** [comment]
Correct...I will attach captures and attempt to repro locally as you suggest.

No firewalling, security groups allowing everything...as discussed iperf2 and nuttcp work without fail between these AMIs on the configured port so the SDN is not blocking them

**Comment by bmah888** [comment]
Still seeing this problem?  We don't have an easy way to replicate this issue.  Also can you try using a port other than 80, in case there's some weird special handling going on inside of AWS?

**Comment by bmah888** [comment]
We'll need some more information to troubleshoot this problem.  I'm going to close this issue for now, but it can be reopened if and when appropriate.
