### ISSUE TITLE
iperf3 doesn't send any packet when I use very small bandwidth option.

### ISSUE THREAD

**Issue by hbektas** [esnet/iperf#276]
When I specify -b with very low number, iperf3 doesn't look like it sends anything after the first second or so.

Example:
# iperf3 -v

iperf 3.0.11

iperf3 -c 198.18.151.190 -t 60 -b .01M
Connecting to host 198.18.151.190, port 5201
[  4] local 198.18.73.125 port 37824 connected to 198.18.151.190 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  66.2 KBytes   542 Kbits/sec    0   41.1 KBytes  
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    0   41.1 KBytes  
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0   41.1 KBytes  
[  4]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    0   41.1 KBytes  
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0   41.1 KBytes  
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    0   41.1 KBytes  
....

**Comment by bmah888** [comment]
This is probably a rounding error, in which iperf3 would have to be sending fewer than one packet per..."something"...and just doesn't do it.  "Something" is probably not the measurement interval, which is independent of sending the test data, but without a closer examination of the code I don't have an easy answer for this.

**Comment by edgarcosta92** [comment]
Is that issue solved ? I am having the same problem and I build iperf3 from source code today. I remember I had a similar problem with iperf 2, and I solved with this patch:

Index: compat/delay.cpp
===================================================================
--- compat/delay.cpp    (revision 81)
+++ compat/delay.cpp    (working copy)
@@ -63,8 +63,9 @@ void delay_loop(unsigned long usec)
 {
     struct timespec requested, remaining;
 
-    requested.tv_sec  = 0;
-    requested.tv_nsec = usec * 1000L;
+    /* convert to seconds; nanosleep requires 0 <= tv_nsec <= 999999999 */
+    requested.tv_sec  = usec / 1000000UL;
+    requested.tv_nsec = (usec % 1000000UL) * 1000UL;
 
Is there a solution for this problem in iperf3?

Edgar

**Comment by bmah888** [comment]
If you want to explore very low bitrate tests, you will probably need to reduce the message size with the `-l` option.  We just got through closing some issues similar to this.  There's also an entry in the recently-added FAQ on this topic.
