### ISSUE TITLE
Support QUIC

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#277]
From @bltierney:

We want to figure out whether it make sense to support Google's QUIC, and if so, do it:

https://www.chromium.org/quic

**Comment by bmah888** [comment]
QUIC is designed for Web page transfers (and similar types of client/server data transfer), not bulk data transfers.  As of when we last looked at this, there wasn't a QUIC implementation that was easily separable from Chrome.  This doesn't seem easily applicable to iperf3 or easily implementable at this time.

Closing.

**Comment by aneesh-joshi** [comment]
@bmah888 

Currently, Google has moved QUIC out of Chromium in their project called quiche 
https://quiche.googlesource.com/quiche/

I would love to work on supporting QUIC in iperf. (with some guidance)

I imagine that would involve creating a `iperf_quic.h` and `iperf_quic.c` similar to `iperf_tcp.h` and `iperf_tcp.c` which takes the `iperf_stream` struct and works with that?

Could we reopen this issue?

**Comment by njoubert** [comment]
I would also love to see QUIC as a supported protocol. I notice there are tools standing up in the spirit of iperf3. At this point I'm running two separate tools to test the same network, iperf3 for tcp qperf for quic. sure would be awesome to have it all in iperf3. https://github.com/rbruenig/qperf

**Comment by davidBar-On** [comment]
> I would also love to see QUIC as a supported protocol. I notice there are tools standing up in the spirit of iperf3. At this point I'm running two separate tools to test the same network, iperf3 for tcp qperf for quic. sure would be awesome to have it all in iperf3. https://github.com/rbruenig/qperf

@njoubert, PR #1999 adds basic QUIC support for iperf3 using [ngtcp2](https://github.com/ngtcp2/ngtcp2) library.  I don't believe it will be merged into iperf3 master version, as it is quite complicated change.  Probably QUIC support may be added to iperf3 master only if and when QUIC support will be added to Linux.  See also the discussion in issue #1017.

As far as I know, PR #1999 code was not tested yet in a real environment.  If you are willing to try it that will be great - whether it works properly, is it useful and whether QUIC essential features/options support is missing.  The PR code is currently aligned with iperf3 3.20 version but if it is useful I can rebase it to the latest iperf3 master code (currently 3.21+).
