### ISSUE TITLE
iperf Windows cannot test with iperf Linux

### ISSUE THREAD

**Issue by sujaysarma** [esnet/iperf#279]
I am testing between two systems on the same LAN and subnet (both in 192.168.1.x). One system is a Windows PC, running Server 2012 R2. The other is a Raspberry Pi 2 running Debian "Wheezy". I installed "iperf-3.0.11-win32" using the ZIP file provided on the iperf website. On the RasPi, I installed it using apt-get, and got version 2.0.5-3 (there is no "ARM" version for download on the iperf website). 

Server           Client             Works
*********          ************        ************
Windows       Debian            yes
Debian          Windows          ** NO **

In fact, when Debian (RasPi) is the server, if I hit control+C after some minutes, it gives stats like a few BYTES (14 bytes, 13 bytes etc) transferred.

Not sure why this is the case. Could you check?

**Comment by bmah888** [comment]
iperf2 and iperf3 do not interoperate, so this scenario won't work.

Note also that the iperf3 project only distributes source code, not binaries.  Any binaries or other ready-to-run artifacts are produced unofficially by third parties.
