### ISSUE TITLE
iperf 3.0.11: Random crashes on Windows 7 SP1 and Windows 2008 R2 SP1

### ISSUE THREAD

**Issue by linuxcrash** [esnet/iperf#281]
Running iPerf on different servers we saw random bluescreens on client and server Windows OS. Unfortunately I cannot provide detailed information but may I suggest to do some additional testing on these OS's since running the measurements in full production environments might have some very bad impact!

**Comment by bmah888** [comment]
iperf3 is not officially supported on Windows.  I'm not sure how it could cause BSODs, because at least in theory it wouldn't need to run with any kind of elevated privileges.
