### ISSUE TITLE
Sending UDP traffic with several network interfaces

### ISSUE THREAD

**Issue by jose205** [esnet/iperf#282]
Hi all,

I don´t know If you can help me…I have a machine with two network interfaces (1gbE), so I have 2 IPs. I´m trying to send UDP traffic in this way:
./iperf3 -i1 -u -B <IP1> -c <remote-host-1> -b900m/20 -t60 & ./iperf3 -i1 -u -B <IP2> -c <remote-host-2> -b900m/20 -t60

But I see that the maximum traffic sent is 1Gbps…why can not I send 1Gbps + 1Gbps if I have two network interfaces? or 600Mbps + 600Mbps? 
I don´t understand why I can't exceed 1Gbps If I have two interfaces...:-(

**Comment by wangyoucao577** [comment]
Step1: You have no setup the route table for your two network interfaces, makes sure that they have both correct and individual next hop to your server destination IP. 
Step2: You have to use the -B option to indicate and bind source ip address. Here's a sample for your inspection: 
./iperf3 -i 1 -c "server_ip" -B "local_ip1" -4 & ./iperf3 -i 1 -c "server_ip" -B "local_ip2" -4 

Running correct.

**Comment by wangyoucao577** [comment]
Step1: You have to setup the route table for your two network interfaces, makes sure that they have both correct and individual next hop to your server destination IP. 
Step2: You have to use the -B option to indicate and bind source ip address. Here's a sample for your inspection: 
./iperf3 -i 1 -c "server_ip" -B "local_ip1" -4 & ./iperf3 -i 1 -c "server_ip" -B "local_ip2" -4 

Running correct.

**Comment by jose205** [comment]
Hello¡¡¡¡
It works perfectly. Thanks a lot¡¡¡
