### ISSUE TITLE
[server] multi client support

### ISSUE THREAD

**Issue by kgersen** [esnet/iperf#285]
Any hope to allow more than one client at a time ? 

There are some public iperf3 servers out there (see: https://iperf.fr ) with 10G or more connectivity. They can easily handle more than one client at a time.

Also adding quotas (time and/or volume) or a global timeout would fit nicely with multi client support (to prevent a 'bad' client to DoS a server for instance).

**Comment by bmah888** [comment]
We prefer not to allow multiple tests to a server because this can lead to interference between multiple, simultaneous tests, with no way to compensate for this effect.

Within the context of perfSONAR, we coordinate between multiple tests being requested with the bwctl/bwctld set of programs.

**Comment by rooste** [comment]
I would also like to use server with multiple simultaneous clients.

I like the fact that iPerf3 has been completely re-written and it has addressed those drawbacks that previous iperf's had. 

One of these drawbacks is that as 'standard' version doesn't work for most users, everybody has a bit modified versions of it and nothing is compatible.

I would like to avoid this and I would like to contribute to this project for achieving this.

Would you be open for multi-client support if:
- max number of simultaneous clients would be configurable (default 1)
- you would not have to implement it

**Comment by shutaozhenzhen** [comment]
The biggest impact without this function is that the default port cannot be reused. This means that when I simulate multiple devices streaming to the same device, I need to use four different commands, which makes it impossible to send them all at once from my term software

**Comment by davidBar-On** [comment]
@shutaozhenzhen if you are able to build yourself the server side, see PR #1074 which adds multi-client support to the server (was rebased lately to the latest iperf3 code).
