### ISSUE TITLE
Odd behavior of iperf3 compared to iperf2

### ISSUE THREAD

**Issue by preese** [esnet/iperf#286]
We're testing a 100g switch, it has two hosts connected, each with 100g Nics.

The systems came with iperf2 and jperf installed.  When connected to the switch they were getting a bandwidth of 96+Gbps, just what was expected.

The server was started with:
iperf -s -l 4M -w 416k -p 6001

Client used:
iperf -c 10.102.xxx.xxx -w 416k -l 4M -P 16 -t 30 -i 5 -p 6001

Last line of output:
[SUM]  0.0-30.0 sec    337 GBytes  96.4 Gbits/sec

I thought, hey we should be using the current iperf3 and loaded it on both systems, 3.0.11 and 3.1.b3.

Both versions never provided a bandwidth greater than 35Gbps.  Almost like it was a cap of some sort.

Server startup:
iperf3 -s -D

Client command:
iperf3 -c 10.102.xxx.xxx -w 416k -l 1M -P 16 -t 30 -i 5

Last line of output:
[SUM]   0.00-30.00  sec   123 GBytes  35.2 Gbits/sec    0             sender
[SUM]   0.00-30.00  sec   123 GBytes  35.2 Gbits/sec                  receiver

I then tried nuttcp and also found I couldn't get more than 35Gbps out of the link.

Which one is correct?  I want it be to the 96+Gbps but the more up-to-date tools say no.

Both systems are running recently updated Centos7.1.

Thoughts?
Phil

**Comment by bmah888** [comment]
Try setting / adjusting the ```-w``` parameter to increase the socket buffer sizes.  I don't think we've done any testing at ESnet with 100Gbps NICs (40Gbps NICs are the fastest we currently have).

**Comment by bmah888** [comment]
No further activity on this issue, closing.
