### ISSUE TITLE
UDP losses ~ 27%

### ISSUE THREAD

**Issue by nnata** [esnet/iperf#287]
Hi!
I got a problem with running Iperf3 3.0.11 UDP testing on Android and Ubuntu. Average loss was 27%. Used wired connection, didn't use WiFi.
I have run the same configuration with Iperf 2.0.5 UDP testing on Android and Ubuntu and losses were ~ 4%.

To run Iperf on Android i use shell app from http://www.cs.technion.ac.il/~sakogan/DSL/2011/projects/iperf/developer.html (this app didn't change anything in iperf , just call the binary either iperf 3.0.11 or iperf 2.0.5).

For Iperf3 Android phone got command iperf -s -i1.
Iperf3 on Ubuntu got command -c 192.168.1.X -u -i1 -t300 -b151m.
For Iperf 2.0.5 Android phone got command iperf -s -i1 -u.
Iperf 2.0.5 on Ubuntu got command -c 192.168.1.X -u -i1 -t300 -b151m.

Devices: 
- Galaxy s6 Android version 5.0.2, Kernel version 3.10.61
- Ubuntu 14.04.2 LTS,
- Cisco Linksys EA 6500 router,
- CMW Rodhe&Shwarz (this devices gives IP address to the phone and managing phone's network setup. WiFi on the phone was disabled.)

Output on the phone for Iperf3:
 -s -i1
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.1.121, port 45103
[  5] local 192.168.1.19 port 5201 connected to 192.168.1.121 port 36830
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  11.8 MBytes  99.2 Mbits/sec  0.369 ms  477/1991 (24%)  
[  5]   1.00-2.00   sec  13.7 MBytes   115 Mbits/sec  0.609 ms  541/2293 (24%)  
[  5]   2.00-3.00   sec  15.2 MBytes   127 Mbits/sec  0.387 ms  371/2311 (16%)  
[  5]   3.00-4.00   sec  13.1 MBytes   110 Mbits/sec  0.366 ms  626/2304 (27%)  
[  5]   4.00-5.00   sec  12.8 MBytes   108 Mbits/sec  0.595 ms  661/2303 (29%)  
[  5]   5.00-6.00   sec  13.9 MBytes   117 Mbits/sec  0.366 ms  528/2305 (23%)  
[  5]   6.00-7.00   sec  13.2 MBytes   110 Mbits/sec  0.597 ms  600/2286 (26%)  
[  5]   7.00-8.00   sec  13.8 MBytes   116 Mbits/sec  0.384 ms  550/2317 (24%)  
[  5]   8.00-9.00   sec  11.7 MBytes  97.8 Mbits/sec  0.575 ms  816/2308 (35%)  
[  5]   9.00-10.00  sec  12.8 MBytes   107 Mbits/sec  0.304 ms  677/2310 (29%)  
[  5]  10.00-11.00  sec  14.2 MBytes   119 Mbits/sec  0.379 ms  475/2294 (21%)  
[  5]  11.00-12.00  sec  11.6 MBytes  97.3 Mbits/sec  0.582 ms  822/2308 (36%)  
....
[  5] 295.00-296.00 sec  13.7 MBytes   115 Mbits/sec  0.354 ms  554/2309 (24%)  
[  5] 296.00-297.00 sec  13.1 MBytes   110 Mbits/sec  0.404 ms  628/2304 (27%)  
[  5] 297.00-298.00 sec  14.2 MBytes   119 Mbits/sec  0.397 ms  483/2301 (21%)  
[  5] 298.00-299.00 sec  14.7 MBytes   124 Mbits/sec  0.620 ms  407/2294 (18%)  
[  5] 299.00-300.00 sec  11.8 MBytes  99.2 Mbits/sec  0.584 ms  803/2316 (35%)  
[  5] 300.00-300.05 sec   856 KBytes   145 Mbits/sec  0.374 ms  0/107 (0%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-300.05 sec  5.27 GBytes   151 Mbits/sec  0.374 ms  188169/691020 (27%)  

Output from the phone for Iperf 2.0.5:
 -s -i1 -u
------------------------------------------------------------
Server listening on UDP port 5001
Receiving 1470 byte datagrams
UDP buffer size:  224 KByte (default)
------------------------------------------------------------

[  3] local 192.168.1.19 port 5001 connected with 192.168.1.121 port 46181

[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0- 1.0 sec  18.1 MBytes   151 Mbits/sec   0.081 ms  390/13272 (2.9%)
[  3]  1.0- 2.0 sec  17.5 MBytes   147 Mbits/sec   0.082 ms  450/12913 (3.5%)
[  3]  2.0- 3.0 sec  17.5 MBytes   147 Mbits/sec   0.083 ms  600/13099 (4.6%)
[  3]  3.0- 4.0 sec  17.5 MBytes   146 Mbits/sec   0.083 ms  450/12900 (3.5%)
[  3]  4.0- 5.0 sec  17.5 MBytes   147 Mbits/sec   0.118 ms  600/13077 (4.6%)
[  3]  5.0- 6.0 sec  17.5 MBytes   147 Mbits/sec   0.083 ms  450/12936 (3.5%)
[  3]  6.0- 7.0 sec  17.5 MBytes   147 Mbits/sec   0.070 ms  450/12912 (3.5%)
[  3]  7.0- 8.0 sec  17.5 MBytes   147 Mbits/sec   0.082 ms  600/13100 (4.6%)
[  3]  8.0- 9.0 sec  17.4 MBytes   146 Mbits/sec   0.083 ms  464/12900 (3.6%)
...
[  3] 296.0-297.0 sec  17.5 MBytes   147 Mbits/sec   0.126 ms  450/12924 (3.5%)
[  3] 297.0-298.0 sec  17.5 MBytes   147 Mbits/sec   0.083 ms  600/13088 (4.6%)
[  3] 298.0-299.0 sec  17.5 MBytes   146 Mbits/sec   0.075 ms  450/12900 (3.5%)
[  3]  0.0-300.0 sec  5.12 GBytes   147 Mbits/sec   0.143 ms 154295/3896104 (4%)
[  3]  0.0-300.0 sec  1 datagrams received out-of-order

Any suggestions? Why Iperf 3 performs UDP worse than Iperf 2?
Thank you for consideration.

**Comment by bmah888** [comment]
We don't officially support Android as a platform, but maybe you can try setting and/or adjusting the ```-w``` option to set the socket buffer sizes (it's incorrectly called "TCP window size").  We've found that helpful in mitigating UDP packet loss issues in some cases.

**Comment by nnata** [comment]
Thank you! I tried with –l2050 option and losses reduced to 6%.

**Comment by bmah888** [comment]
Problem solved (it sounds like).  Closing issue.

**Comment by larryliu2018** [comment]
I had the same problem, solved it, -w 12050
