### ISSUE TITLE
Can't make Parallels UDP. (iperf 3) Help me Please!

### ISSUE THREAD

**Issue by trantuantu** [esnet/iperf#290]
I can't make Paralells UDP to server, help me!...I Only can make  Paralells TCP .

**Comment by bmah888** [comment]
It works for me.  If you want anyone to help you, you'll need to be much more specific about what you're trying to do, what you expect to have happen, and what you're actually seeing.  Saying "I can't make it work" doesn't give anyone any useful information as a starting point.

**Comment by trantuantu** [comment]
I try on local host.
Server: iperf3 -s
Client: iperf3 -c 127.0.0.1 -u -b 10m -t 2000 -P 2
It's not work. Can you help me...

**Comment by bmah888** [comment]
Posting the command-lines is good but doesn't tell me what platform you're running on, or what version(s) of iperf3 you are using.  What about the rest of the information that I (or anybody else) would need to be able to help you?  Like what kind of output did you get?

(Your command-lines worked fine for me by the way, at least out to about 100 seconds.  2000 seconds is too long for me to wait, unless your problem actually happened after a long period of time.)

**Comment by trantuantu** [comment]
I use Windows 7 32 bit. I use iperf3 3.0.11 Windows 32 bit.
It ouccurs at start time, when client start connect to server. Only One of two client thread connect to server.
Client:
![untitled](https://cloud.githubusercontent.com/assets/13659097/9116658/b6b62f42-3c8f-11e5-9c7d-313ad7135117.png)

**Comment by bmah888** [comment]
Hrm.  This is on Windows.  iperf3 isn't officially supported on Windows, and I don't have a setup for testing it.  I am not sure why Windows would work differently (is this Cygwin?).

**Comment by bmah888** [comment]
I don't think there's anything else we can do to help at this point.  Closing.
