### ISSUE TITLE
Order of command line arguments produces different results

### ISSUE THREAD

**Issue by salkiswany** [esnet/iperf#294]
Hi,

I am not sure if this is the intended behavior, but the following two commands produce two different results.
iperf -c 10.10.1.2 -u -b 100M
This command will respect the 100M bandwidth limit

while
iperf -u -b 100M -c 10.10.1.2
will ignore the bandwidth limit.

Here is a sample output
sam@node-0:~$ iperf -c 10.10.1.2 -u -b 100M
------------------------------------------------------------
Client connecting to 10.10.1.2, UDP port 5001
Sending 1470 byte datagrams
UDP buffer size: 1.95 GByte (default)
------------------------------------------------------------
[  3] local 10.10.1.1 port 48156 connected with 10.10.1.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   120 MBytes   101 Mbits/sec
[  3] Sent 85471 datagrams
[  3] Server Report:
[  3]  0.0-10.0 sec   120 MBytes   101 Mbits/sec   0.000 ms    0/85470 (0%)
[  3]  0.0-10.0 sec  1 datagrams received out-of-order

sam@node-0:~$ iperf -u -b 100M -c 10.10.1.2 
WARNING: option -b is not valid for server mode
------------------------------------------------------------
Client connecting to 10.10.1.2, UDP port 5001
Sending 1470 byte datagrams
UDP buffer size: 1.95 GByte (default)
------------------------------------------------------------
[  3] local 10.10.1.1 port 36543 connected with 10.10.1.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1.25 MBytes  1.05 Mbits/sec
[  3] Sent 893 datagrams
[  3] Server Report:
[  3]  0.0-10.0 sec  1.25 MBytes  1.05 Mbits/sec   0.000 ms    0/  893 (0%)

Thank you

**Comment by bmah888** [comment]
The output above looks like it's from iperf version 2.  This GitHub project and issue tracker are for iperf version 3.

You could try posting your bug report to the iperf-users list, which discusses both versions, at iperf-users at lists dot sourceforge dot net.
