### ISSUE TITLE
Use QProcess to control iperf3 in QT

### ISSUE THREAD

**Issue by d985201002** [esnet/iperf#299]
Hi

I use QProcess to control iperf3 of windows version in QT , my purpose is to realtime get the throughput
and to show on my UI. For example , if interval is 10 secs , i want to fetch the result every second . But i only got whole result after 10 secs ,  it seems that something triggered(no matter terminate(ctrl+c) or throughput finished) then send output to the process. Below is my code(just simple test)

void MainWindow::on_pushButton_clicked()
{
    QStringList l;

    connect(&p , SIGNAL(readyRead()) , this , SLOT(print_message()));
    l<<"-c"<<"127.0.0.1"<<"-i"<<"1";
    p.start("d:/iperf3" , l);

    while(true)
    {
        p.waitForFinished(1000);
    }
}

void MainWindow::print_message()
{
    QString tmp;
    tmp = QString(p.readAllStandardOutput());
    if(!tmp.isEmpty())
        qDebug()<<tmp;
}

Do you have any idea?It bother me a few days.
Thanks
Jack

**Comment by bmah888** [comment]
No insights off-hand, although it sounds like a problem with buffering somewhere.  Maybe something is buffering up the output from iperf3 and your Qt application isn't seeing it all until the iperf3 process exits?  This may or may not be something that the ipef3 application can control...specifically maybe you could adjust or add calls to iflush() to try to flush output to your Qt front-end.

**Comment by d985201002** [comment]
Hi

Thanks for the reply.
I've search some articles about my question.
https://forum.qt.io/topic/1316/qprocess-working-qiodevice-unbuffered-or-adjustable-buffersize-for-faster-access-to-stdout/20
I think this is most likely why i cant read the output immediately.

1. o << "Line of text here";
2. o << "Line of text here" << std::endl;

First way will not trigger qt's readyRead , but second will do this. 
I'v not trace the source , so i m not 100% sure.

But if i replace the process name with "ping.exe" i paste above , it works fine(output of each second).

**Comment by SLX-WI** [comment]
I had similar problem recently with buffered output and I used "unbuffer" from "expect" package on Ubuntu. But if you really want do it on Windows then maybe there is a similar application. The problem is that output from application is buffered by system (libc) and if you want to change this behaviour you need to modify source to flush output every line.
