### ISSUE TITLE
Confused by iperf_new_stream

### ISSUE THREAD

**Issue by teto** [esnet/iperf#302]
Hi,

In order to run iperf3 in DCE, I have to add some functionalities to DCE and step through the iperf34 code and this function puzzles me :

```
iperf_new_stream(struct iperf_test *test, int s)
{
    int i;
    struct iperf_stream *sp;
    char template[] = "/tmp/iperf3.XXXXXX";

    iprintf(test, "iperf_new_stream");

    h_errno = 0;

    sp = (struct iperf_stream *) malloc(sizeof(struct iperf_stream));
    if (!sp) {
        i_errno = IECREATESTREAM;
        return NULL;
    }

    memset(sp, 0, sizeof(struct iperf_stream));

    sp->test = test;
    sp->settings = test->settings;
    sp->result = (struct iperf_stream_result *) malloc(sizeof(struct iperf_stream_result));
    if (!sp->result) {
        free(sp);
        i_errno = IECREATESTREAM;
        return NULL;
    }

    memset(sp->result, 0, sizeof(struct iperf_stream_result));
    TAILQ_INIT(&sp->result->interval_results);

    /* Create and randomize the buffer */
    sp->buffer_fd = mkstemp(template);
    if (sp->buffer_fd == -1) {
        i_errno = IECREATESTREAM;
        free(sp->result);
        free(sp);
        return NULL;
    }
    if (unlink(template) < 0) {
        i_errno = IECREATESTREAM;
        free(sp->result);
        free(sp);
        return NULL;
    }
    if (ftruncate(sp->buffer_fd, test->settings->blksize) < 0) {
        i_errno = IECREATESTREAM;
        free(sp->result);
        free(sp);
        return NULL;
    }
    sp->buffer = (char *) mmap(NULL, test->settings->blksize, PROT_READ|PROT_WRITE, MAP_PRIVATE, sp->buffer_fd, 0);
    if (sp->buffer == MAP_FAILED) {
        i_errno = IECREATESTREAM;
        free(sp->result);
        free(sp);
        return NULL;
    }
    srandom(time(NULL));
    for (i = 0; i < test->settings->blksize; ++i)
        sp->buffer[i] = random();

    /* Set socket */
    sp->socket = s;

    sp->snd = test->protocol->send;
    sp->rcv = test->protocol->recv;

    if (test->diskfile_name != (char*) 0) {
        sp->diskfile_fd = open(test->diskfile_name, test->sender ? O_RDONLY : (O_WRONLY|O_CREAT|O_TRUNC), S_IRUSR|S_IWUSR);
        if (sp->diskfile_fd == -1) {
            i_errno = IEFILE;
            munmap(sp->buffer, sp->test->settings->blksize);
            free(sp->result);
            free(sp);
            return NULL;
        }
        sp->snd2 = sp->snd;
        sp->snd = diskfile_send;
        sp->rcv2 = sp->rcv;
        sp->rcv = diskfile_recv;
    } else
        sp->diskfile_fd = -1;

    /* Initialize stream */
    if (iperf_init_stream(sp, test) < 0) {
        iprintf(test, "iperf_init_stream failed \n");
        close(sp->buffer_fd);
        munmap(sp->buffer, sp->test->settings->blksize);
        free(sp->result);
        free(sp);
        return NULL;
    }
    iperf_add_stream(test, sp);

    return sp;
}
```

1/ why generate a random buffer if  we are sending a file `if (test->diskfile_name != (char*) 0) {` ?
2/ I don't understand why the code creates a file and removes it straightaway (mkstmp followed by unlink), shouldn't the closure be delayed ? otherwise it makes the fd available to the system again.
Instead of opening a file to get a fd, there is this http://man7.org/linux/man-pages/man3/shm_open.3.html . MAP_ANONYMOUS sounds tempting but it's not posix (yet).

**Comment by teto** [comment]
My bad the unlink is effective only when the file is closed so that's ok but a malloc should be more straightforward here. It also helped me find out that the DCE override for mkstemp was broken

**Comment by bmah888** [comment]
Sorry for the delay in answering, but does this mean you resolved your own issue and we can close this?
Thanks!

**Comment by teto** [comment]
The whole opening a file/then close it would be much simpler with a malloc IMO otherwise it can be misunderstood (as I did).

Question 1 still remains: "why generate a random buffer if we are sending a file if (test->diskfile_name != (char*) 0)" . When one tells iperf3 to use a file as an input, does it need to generate a random file ? This is no big deal but why run code when if it is useless :)

**Comment by bmah888** [comment]
I'm not sure about all aspects of iperf3's code, principally because I didn't write most of it.  You raise a couple of good points, although we're probably going to leave things as-is unless someone feels strongly enough to fix it with a pull-request.
