### ISSUE TITLE
Determine Upload Speed using iperf

### ISSUE THREAD

**Issue by simargujral** [esnet/iperf#304]
I need to determine the upload bandwidth speed using iperf. I tried using iperf -c <Ip address> -d, but this hangs in the execution and doesn't give proper output.

I also used iperf -c <Ip address> -f m -P 5, it gives the download speed. Can someone help me to determine the upload speed using iperf?

**Comment by bmah888** [comment]
Does the ``-R`` option do what you want?

**Comment by simargujral** [comment]
Hi,
-R works when we have public IP for both client and server. If the client is not having the public IP (i.e is behind NAT) then the command with -R gets hanged in between and gives error.

**Comment by bmah888** [comment]
Right, iperf3 (as well as many other similar bandwidth testers) don't always work well through NATs.

Closing.
