### ISSUE TITLE
Terminate/reset test.

### ISSUE THREAD

**Issue by applezcode** [esnet/iperf#308]
Hi,

I've integrated iperf3 into an iOS app, one major function that is missing at the moment is that I can't stop the running test (ex.: test duration = 2 hours, the test runs in background forever (app's feature), sleep is prevented. I see no way to stop test without killing the app)

Is there a way to stop running a test? 

best regards,
Oleh

**Comment by bmah888** [comment]
Not in the iperf3 API, no.  It wasn't exactly designed for this situation.  Maybe you might consider forking off a new thread and running the test in that thread?
