### ISSUE TITLE
How to properly setup a UDP stream

### ISSUE THREAD

**Issue by rpagliarix** [esnet/iperf#309]
I'd like to set up a UDP stream from one machine to another. I tried the following:

$iperf3 -s -u -p 91
$iperf3 -c ip_address -u -b 1M

There are two issues:
1. Under Windows, the -u option on the server side is not available.
2. When running both server and client under Linux with the commands above, TCP traffic is generated. I confirmed this by capturing traffic with Wireshark.

**Comment by bmah888** [comment]
On the server side, you don't specify a protocol to use (e.g. TCP or UDP).  That information is conveyed from the client side.

The TCP traffic you are seeing is a control connection used to exchange test parameters and results between the two participating processes in the test.
