### ISSUE TITLE
using --server and --udp gives parameter error 

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#31]
_From [pcrotwell](https://code.google.com/u/117941251445550941919/) on August 31, 2010 13:27:01_

What steps will reproduce the problem? 1. iperf3 -s -u 2. 3. What is the expected output? What do you see instead? crotwell$ bin/iperf3 -s -u
parameter error: Some option you are trying to set is client only What version of the product are you using? On what operating system? 3.0b4
linux Please provide any additional information below. Same problem with variations on --server and --udp

Docs seem to indicate that -u can be used with -s

_Original issue: http://code.google.com/p/iperf/issues/detail?id=31_

**Comment by ccoenen** [comment]
It is not trivial to find, especially since there are a lot of wrong/old tutorials out there that still combine `-s -u`
