### ISSUE TITLE
iPerf 3.0.11 - Arch Linux (54 Kio) does not work

### ISSUE THREAD

**Issue by wesleywang** [esnet/iperf#310]
in the download page: https://iperf.fr/iperf-download.php

following item has problem when extracted to linux root directory /:
    [ iPerf 3.0.11 - Arch Linux (54 Kio) by Timothy Redaelli ]

the reason is that libiperf.so is installed to /usr/lib, when execute iperf3, error is reported that libiperf.so could not be found. After manually copying libiperf.so.xx to /user/lib64, the problem is solved.

so should it be better that "usr/lib64" be used instead of "usr/lib" when extracting this tar ball, since this version is for x86_64.

Thanks.

**Comment by bmah888** [comment]
The official download site for iperf3 is:

http://downloads.es.net/pub/iperf/

ESnet does not distribute binaries, only source code, and is not responsible for the contents of any unofficial, third-party download sites, such as iperf.fr.

**Comment by wesleywang** [comment]
official download is ok, thanks for clarifying!
