### ISSUE TITLE
Compile Iperf3 in AIX 6.1

### ISSUE THREAD

**Issue by youf3** [esnet/iperf#312]
Hi,

I've been trying to install Iperf3 on AIX 6.1.0.0 but was not able to compile the source.

Here is the output.

-bash-4.2$ ./configure
checking for a BSD-compatible install... config/install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... config/install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... powerpc-ibm-aix6.1.0.0
checking host system type... powerpc-ibm-aix6.1.0.0
checking for gcc... no
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... no
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... -qlanglvl=extc89
checking whether cc -qlanglvl=extc89 understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of cc -qlanglvl=extc89... xlc
checking for ranlib... ranlib
checking whether ln -s works... yes
checking how to print strings... print -r
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for non-GNU ld... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 786432
checking how to convert powerpc-ibm-aix6.1.0.0 file names to powerpc-ibm-aix6.1.0.0 format... func_convert_file_noop
checking how to convert powerpc-ibm-aix6.1.0.0 file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... print -r --
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... (cached) ranlib
checking command to parse /usr/bin/nm -B output from cc -qlanglvl=extc89 object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... cc -qlanglvl=extc89 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking which variant of shared library versioning to provide... aix
checking for objdir... .libs
checking for cc -qlanglvl=extc89 option to produce PIC...  -DPIC
checking if cc -qlanglvl=extc89 PIC flag  -DPIC works... yes
checking if cc -qlanglvl=extc89 static flag -bnso -bI:/lib/syscalls.exp works... no
checking if cc -qlanglvl=extc89 supports -c -o file.o... yes
checking if cc -qlanglvl=extc89 supports -c -o file.o... (cached) yes
checking whether the cc -qlanglvl=extc89 linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... AIX lib.a(lib.so.V)
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for ANSI C header files... (cached) yes
checking for library containing nanosleep... none required
checking for library containing hstrerror... none required
checking for library containing socket... none required
checking for library containing inet_ntop... none required
checking for an ANSI C-conforming const... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for netinet/sctp.h... no
checking TCP_CONGESTION socket option... no
checking IPv6 flowlabel support... no
checking for cpuset_setaffinity... no
checking for sched_setaffinity... no
checking for sendfile... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/version.h
config.status: creating examples/Makefile
config.status: creating iperf3.spec
config.status: creating src/iperf_config.h
config.status: src/iperf_config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
-bash-4.2$ make
Making all in src
        make  all-am
        source='cjson.c' object='cjson.lo' libtool=yes  DEPDIR=.deps depmode=xlc /bin/sh ../config/depcomp  /bin/sh ../libtool  --tag=CC    --mode=compile cc -qlanglvl=extc89 -DHAVE_CONFIG_H  -I.      -g -c -o cjson.lo cjson.c
libtool: compile:  cc -qlanglvl=extc89 -DHAVE_CONFIG_H -I. -g -c cjson.c -Wp,-qmakedep=gcc,-MF.deps/cjson.TPlo  -DPIC -o .libs/cjson.o
        source='iperf_api.c' object='iperf_api.lo' libtool=yes  DEPDIR=.deps depmode=xlc /bin/sh ../config/depcomp  /bin/sh ../libtool  --tag=CC    --mode=compile cc -qlanglvl=extc89 -DHAVE_CONFIG_H  -I.      -g -c -o iperf_api.lo iperf_api.c
libtool: compile:  cc -qlanglvl=extc89 -DHAVE_CONFIG_H -I. -g -c iperf_api.c -Wp,-qmakedep=gcc,-MF.deps/iperf_api.TPlo  -DPIC -o .libs/iperf_api.o
"iperf_api.c", line 35.10: 1506-296 (S) #include file <getopt.h> not found.
"iperf.h", line 168.1: 1506-046 (S) Syntax error.
"iperf.h", line 268.1: 1506-046 (S) Syntax error.
"iperf.h", line 269.41: 1506-344 (S) Member streams has already been defined on line 268 of "iperf.h".
"iperf_api.h", line 270.29: 1506-046 (S) Syntax error.
"iperf_api.h", line 285.58: 1506-209 (S) Character constants must end before the end of a line.
"iperf_api.h", line 285.46: 1506-076 (W) Character constant 't be opened' has more than 4 characters. No more than rightmost 4 characters are used.
"iperf_api.h", line 288.51: 1506-209 (S) Character constants must end before the end of a line.
"iperf_api.h", line 288.35: 1506-076 (W) Character constant 't open log file' has more than 4 characters. No more than rightmost 4 characters are used.
make: 1254-004 The error code from the last command is 1.

Stop.
make: 1254-004 The error code from the last command is 2.

Stop.
make: 1254-004 The error code from the last command is 1.

It looks like it is looking for getopt.h which is not on AIX 6.1.0.0 by default.
Am I missing compilation flag(s)?

**Comment by youf3** [comment]
After poking for a while, I found I need to remove #include <getopt.h> from iperf_api.c for AIX.

So I did that, and also removed lines 168 and 268 which were only commented lines.
Then I ran make again and here is the output.

-bash-4.2$ make 
Making all in src 
make all-am 
source='iperf_api.c' object='iperf_api.lo' libtool=yes DEPDIR=.deps depmode=xlc /bin/sh ../config/depcomp /bin/sh ../libtool --tag=CC --mode=compile cc -qlanglvl=extc89 -DHAVE_CONFIG_H -I. -g -c -o iperf_api.lo iperf_api.c 
libtool: compile: cc -qlanglvl=extc89 -DHAVE_CONFIG_H -I. -g -c iperf_api.c -Wp,-qmakedep=gcc,-MF.deps/iperf_api.TPlo -DPIC -o .libs/iperf_api.o 
"iperf_api.h", line 270.29: 1506-046 (S) Syntax error. 
"iperf_api.h", line 285.58: 1506-209 (S) Character constants must end before the end of a line. 
"iperf_api.h", line 285.46: 1506-076 (W) Character constant 't be opened' has more than 4 characters. No more than rightmost 4 characters are used. 
"iperf_api.h", line 288.51: 1506-209 (S) Character constants must end before the end of a line. 
"iperf_api.h", line 288.35: 1506-076 (W) Character constant 't open log file' has more than 4 characters. No more than rightmost 4 characters are used. 
make: 1254-004 The error code from the last command is 1.

Stop. 
make: 1254-004 The error code from the last command is 2.

Stop. 
make: 1254-004 The error code from the last command is 1.

Stop.

Would you find what causes this please?

**Comment by bmah888** [comment]
No solid ideas...I haven't used AIX for 15 years.  :-)

Off-hand it looks like the compiler is getting confused by the C++-style (or C99-style, if you prefer) comments in iperf_api.h.  What if you try changing those from // comments to good old-fashioned /* ... */ comments instead?  (What compiler is this anyway?  GCC or some IBM compiler?)

(For the record, AIX isn't an officially supported platform.)

**Comment by ronnicek** [comment]
Hi,

I had same problem..

``iperf_api.c:35:20: error: getopt.h: No such file or directory
iperf_api.c: In function 'iperf_parse_arguments':
iperf_api.c:607: error: array type has incomplete element type
iperf_api.c:609: error: 'required_argument' undeclared (first use in this function)
iperf_api.c:609: error: (Each undeclared identifier is reported only once
iperf_api.c:609: error: for each function it appears in.)
iperf_api.c:612: error: 'no_argument' undeclared (first use in this function)
iperf_api.c:674: warning: implicit declaration of function 'getopt_long'
iperf_api.c:607: warning: unused variable 'longopts'
make: 1254-004 The error code from the last command is 1.


Stop.
make: 1254-004 The error code from the last command is 2.


Stop.
make: 1254-004 The error code from the last command is 1.``

I found, that popt should help (http://stackoverflow.com/questions/34044975/getopt-h-missing-in-aix-7-1), but it will need most probably do some code tuning to have it capable of it... :-(

**Comment by k3it** [comment]
on AIX getopt is in <unistd.h>, however there is no struct option

`iperf_api.c: In function 'iperf_parse_arguments':
iperf_api.c:620:26: error: array type has incomplete element type
     static struct option longopts[] =
                          ^
iperf_api.c:622:18: error: 'required_argument' undeclared (first use in this function)
         {"port", required_argument, NULL, 'p'},
                  ^
iperf_api.c:622:18: note: each undeclared identifier is reported only once for each function it appears in
iperf_api.c:625:20: error: 'no_argument' undeclared (first use in this function)
         {"daemon", no_argument, NULL, 'D'},
                    ^
iperf_api.c:688:5: warning: implicit declaration of function 'getopt_long' [-Wimplicit-function-declaration]
     while ((flag = getopt_long(argc, argv, "p:f:i:D1VJvsc:ub:t:n:k:l:P:Rw:B:M:N46S:L:ZO:F:A:T:C:dI:hX:", longopts, NULL)) != -1) {
     ^
iperf_api.c:620:26: warning: unused variable 'longopts' [-Wunused-variable]
     static struct option longopts[] =
                          ^
Makefile:856: recipe for target 'iperf_api.lo' failed
`

**Comment by k3it** [comment]
I changed  getopt to popt but ran into other compiler/linking errors .  the latest one with main.c daemon() call not compatible with AIX libs?  seems like there is no quick fix to get this latest release working on AIX.

**Comment by bmah888** [comment]
The problems mentioned here (no getopt_long and no daemon) appear to be addressed by two other portability issues already filed (#176 and #369).  I have proposed solutions (based on submitted patches) for both of them.

**Comment by MercyAngel** [comment]
I have compile iperf3 on android project. Its shows src/main/assets/iperf_config.h.in does not exist. Already file is available in that folder

**Comment by bmah888** [comment]
Closing based on my last comment.
