### ISSUE TITLE
iprintf type mismatch

### ISSUE THREAD

**Issue by MahdiAlikhani** [esnet/iperf#315]
Redefinition of iprintf in iperf_api.h, cause this problem to occur when compiling with cygwin:

make[1]: Entering directory '/iperf/src'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -g -O2 -Wall -MT iperf_api.lo -MD -MP -MF .deps/iperf_api.Tpo -c -o iperf_api.lo iperf_api.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -O2 -Wall -MT iperf_api.lo -MD -MP -MF .deps/iperf_api.Tpo -c iperf_api.c  -DDLL_EXPORT -DPIC -o .libs/iperf_api.o
In file included from iperf_api.c:66:0:
iperf_api.h:261:5: error: conflicting types for ‘iprintf’
 int iprintf(struct iperf_test *test, const char *format, ...) __attribute__ ((format(printf,2,3)));
     ^
In file included from /usr/include/stdio.h:29:0,
                 from iperf_api.c:32:
/usr/include/stdio.h:263:5: note: previous declaration of ‘iprintf’ was here
 int _EXFUN(iprintf, (const char *, ...)
     ^
iperf_api.c:2978:1: error: conflicting types for ‘iprintf’
 iprintf(struct iperf_test *test, const char* format, ...)
 ^
In file included from /usr/include/stdio.h:29:0,
                 from iperf_api.c:32:
/usr/include/stdio.h:263:5: note: previous declaration of ‘iprintf’ was here
 int _EXFUN(iprintf, (const char *, ...)
     ^
Makefile:856: recipe for target 'iperf_api.lo' failed
make[1]: *** [iperf_api.lo] Error 1
make[1]: Leaving directory '/iperf/src'
Makefile:381: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

this could be resolved by renaming all iprintf to another name like my_iprintf.

Regards

**Comment by tniessen** [comment]
Already discussed in #280.

**Comment by bmah888** [comment]
See #280.
