### ISSUE TITLE
iPERF CLI vs GUI

### ISSUE THREAD

**Issue by XiQshoner** [esnet/iperf#317]
Hello Community.

I have been running some tests using both iPERF CLI version 3.0 and iPERF GUI version 2.0. 
I am trying to gauge some IPSEC VPN tunnel performance however I am getting some strange results. With the CLI version I have consistent bandwidth of 15Mbps. Through the GUI version the test starts low bandwidth and increases at every interval unitl it hits around 50Mbps. It will then jump between 20 and 50 sporadically. Why such the difference? Is the GUI version using a different method of packet delivery? 

Thanks for the input.

**Comment by bmah888** [comment]
You might start by trying to locate whomever created the GUI variant.  There's no GUI in the iperf3 sources that ESnet has been developing, so someone in the community must have created it.  It'd probably be most effective to ask them about any performance or functionality differences.

(I am not sure if the "iPERF GUI version 2.0" you mentioned is based on the iperf2 or iperf3 sources, but please do note that iperf2 and iperf3 are not compatible and do not interoperate.)
