### ISSUE TITLE
iperf3 udp parallel tests does not work cross platform between windows (server) and Linux(client machine)

### ISSUE THREAD

**Issue by yunicks** [esnet/iperf#321]
Hello,
    iperf3 udp parallel test in cross platform environment failed.

Setup:
Server machine ->Windows 7 ("iperf3.exe -s")
Client machine --> RHEL6.3 ("iperf3 -c X.X.X.X -u -P 2")

This command on client failed. 
But when I try to execute without parallel tests there is no issue seen.
"iperf3 -c x.x.x.x -u" -- This runs fine.

Please check.
Regards

**Comment by oliswiss** [comment]
This seems to be a general problem in our Windows 7 only environment as well.

Setup:
Server (Windows 7 SP1 x86) -> .\iperf3.exe -s
Client (Windows 7 SP1 x86) -> .\iperf3.exe -c x.x.x.x -u -P 2
iPerf 3.1.2

This will completely stop iPerf from working (TCP and UDP) on the server machine until the next reboot. Maybe there is another way of getting it to work again but I'm no expert in the Windows network stack.

**Comment by bmah888** [comment]
Windows is not a supported platform for iperf3, and we don't have an easy way of investigating your problem.  We recommend trying iperf2 to see if that might work better for you.  Closing.
