### ISSUE TITLE
How could I use the iperf tool to test throughput between Intranet and Internet.

### ISSUE THREAD

**Issue by ErisXiang** [esnet/iperf#322]
How could I use the iperf tool to test throughput between Intranet and Internet.
troubled me , give me a hand

**Comment by ErisXiang** [comment]
I found that I couldnot get the test result when the routine line through the WAN port on the router.
whether the iperf just can work normal in the Local Area Network?

**Comment by bmah888** [comment]
If your "router" does NAT, that could present a problem.  iperf3 needs to be able to make a TCP connection from the client to the server (in addition to any data transfer), which could be difficult if the client is on the "outside" of a NAT and the server is on the "inside".  Most, if not all, measurement programs of this type have this restriction.

**Comment by sebastso** [comment]
Ref:  iperf3 needs to be able to make a TCP connection from the client to the server (in addition to any data transfer)
Is there a way to specify this TCP port as well? I've used --cport, but this only specifying the data transfer port. I'm exploring way to hole punch these ports before performing tests between hosts/clients located in different NAT.
