### ISSUE TITLE
iperf3: parameter error - number of parallel streams too large (maximum = 128)

### ISSUE THREAD

**Issue by LiliDeng** [esnet/iperf#324]
On server run
iperf3 -s -D -p 50003
On client run
/usr/bin/iperf3 -c serverip -P 256 -t 300 -p 50003 -4
iperf3: parameter error - number of parallel streams too large (maximum = 128)
How can I run connections with 256 and bigger ones?

**Comment by ErisXiang** [comment]
how about running 2 iperf3.exe on different port.

**Comment by LiliDeng** [comment]
@ErisXiang yep, have to use this way now... thanks!
