### ISSUE TITLE
add support for new SO_MAX_PACING_RATE setsockopt call

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#325]
New versions of linux (starting with 3.18, I think), include support for kernel level pacing.

I'd like the current '-b' option to call this for TCP sockets, probably instead of the current TCP pacing mechanism.

This is in debian 8, and RHEL 7.2 beta at the moment.

**Comment by bmah888** [comment]
For some reason, finding documentation on this kernel option is incredibly difficult for my meager Google search skills.  Bookmarking these:

https://lwn.net/Articles/573272/
https://lwn.net/Articles/564978/
http://man7.org/linux/man-pages/man8/tc-fq.8.html

**Comment by bmah888** [comment]
This is relevant.

http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=62748f32d501f5d3712a7c372bbb92abc7c62bc7

**Comment by bmah888** [comment]
Note for documentation:  Using this feature requires using the fq queue discipline, which can be activated per interface using something like this:
```
# tc qdisc add dev eth0 root fq
```

**Comment by bmah888** [comment]
@bltierney:  I committed some code to the issue-325 branch.  Please give this a try.  I know it doesn't make anything blow up, but I haven't had a chance to analyze the timing of packets to see if it does what we want.  The intent is that it should work for TCP and UDP in both forward and reverse direction tests.

**Comment by bltierney** [comment]
Seems to work great! See results below.

I think maybe it should either be an error to not include the "-b" flag, or
it should default to 1Gbps. Not sure what its doing now...


And a minor nit. I'd change the --help output from:

  --socket-pacing           use socket pacing

to

  --socket-pacing           use FQ-based socket pacing

or maybe even:

  --fq-maxrate               use FQ-based socket pacing




------------

iperf3 -c anl-diskpt1 --socket-pacing -b1G -t5

Connecting to host anl-diskpt1, port 5201

[  4] local 198.129.77.102 port 55511 connected to 198.124.238.170 port 5201

[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd

[  4]   0.00-1.00   sec  69.4 MBytes   583 Mbits/sec    0   11.5 MBytes


[  4]   1.00-2.00   sec   118 MBytes   988 Mbits/sec    0   11.5 MBytes


[  4]   2.00-3.00   sec   118 MBytes   987 Mbits/sec    0   11.5 MBytes


[  4]   3.00-4.00   sec   118 MBytes   988 Mbits/sec    0   11.5 MBytes


[  4]   4.00-5.00   sec   118 MBytes   988 Mbits/sec    0   11.5 MBytes


- - - - - - - - - - - - - - - - - - - - - - - - -

[ ID] Interval           Transfer     Bandwidth       Retr

[  4]   0.00-5.00   sec   540 MBytes   906 Mbits/sec    0             sender

[  4]   0.00-5.00   sec   518 MBytes   868 Mbits/sec
receiver


iperf Done.

rootblt@lbl-diskpt1.es.net(76)#iperf3 -c anl-diskpt1 --socket-pacing -b2G
-t5

Connecting to host anl-diskpt1, port 5201

[  4] local 198.129.77.102 port 55513 connected to 198.124.238.170 port 5201

[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd

[  4]   0.00-1.00   sec   112 MBytes   941 Mbits/sec    0   22.7 MBytes


[  4]   1.00-2.00   sec   234 MBytes  1.96 Gbits/sec    0   22.7 MBytes


[  4]   2.00-3.00   sec   234 MBytes  1.96 Gbits/sec    0   22.7 MBytes


[  4]   3.00-4.00   sec   234 MBytes  1.96 Gbits/sec    0   22.7 MBytes


[  4]   4.00-5.00   sec   234 MBytes  1.96 Gbits/sec    0   22.7 MBytes


- - - - - - - - - - - - - - - - - - - - - - - - -

[ ID] Interval           Transfer     Bandwidth       Retr

[  4]   0.00-5.00   sec  1.02 GBytes  1.76 Gbits/sec    0             sender

[  4]   0.00-5.00   sec  1003 MBytes  1.68 Gbits/sec
receiver


iperf Done.

rootblt@lbl-diskpt1.es.net(77)#iperf3 -c anl-diskpt1 --socket-pacing -b3G
-t5

Connecting to host anl-diskpt1, port 5201

[  4] local 198.129.77.102 port 55515 connected to 198.124.238.170 port 5201

[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd

[  4]   0.00-1.00   sec   153 MBytes  1.29 Gbits/sec    0   33.8 MBytes


[  4]   1.00-2.00   sec   351 MBytes  2.95 Gbits/sec    0   34.0 MBytes


[  4]   2.00-3.00   sec   351 MBytes  2.95 Gbits/sec    0   34.0 MBytes


[  4]   3.00-4.00   sec   352 MBytes  2.95 Gbits/sec    0   34.1 MBytes


[  4]   4.00-5.00   sec   351 MBytes  2.95 Gbits/sec    0   34.1 MBytes


- - - - - - - - - - - - - - - - - - - - - - - - -

[ ID] Interval           Transfer     Bandwidth       Retr

[  4]   0.00-5.00   sec  1.52 GBytes  2.61 Gbits/sec    0             sender

[  4]   0.00-5.00   sec  1.46 GBytes  2.50 Gbits/sec
receiver


------


this one is odd:


iperf3 -c anl-diskpt1 --socket-pacing  -t5

Connecting to host anl-diskpt1, port 5201

[  4] local 198.129.77.102 port 55527 connected to 198.124.238.170 port 5201

[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd

[  4]   0.00-1.00   sec   498 KBytes  4.08 Mbits/sec    0   8.74 KBytes


[  4]   1.00-2.00   sec  43.7 KBytes   358 Kbits/sec    0    105 KBytes


[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0    105 KBytes

[  4]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    0    105 KBytes

[  4]   4.00-5.00   sec  43.7 KBytes   358 Kbits/sec    0    105 KBytes


- - - - - - - - - - - - - - - - - - - - - - - - -

[ ID] Interval           Transfer     Bandwidth       Retr

[  4]   0.00-5.00   sec   585 KBytes   959 Kbits/sec    0             sender

[  4]   0.00-5.00   sec   157 KBytes   258 Kbits/sec
receiver



On Fri, Apr 15, 2016 at 11:57 PM, Bruce A. Mah <notifications@github.com>
wrote:

> @bltierney <https://github.com/bltierney>: I committed some code to the
> issue-325 branch. Please give this a try. I know it doesn't make anything
> blow up, but I haven't had a chance to analyze the timing of packets to see
> if it does what we want. The intent is that it should work for TCP and UDP
> in both forward and reverse direction tests.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/esnet/iperf/issues/325#issuecomment-210751484>
>



-- 
Brian Tierney, http://www.es.net/tierney
Energy Sciences Network (ESnet), Berkeley National Lab
http://fasterdata.es.net

**Comment by mfeit-internet2** [comment]
It would be better for perfSONAR if there were a way to tell iperf select the best available method so whatever invokes it doesn't have to understand what conditions cause `--socket-pacing` to be compiled in or excluded.

The ideal would be to make the command-line switch `--pacing m`, where `m` is the desired method:
  * `socket` to force `SO_MAX_PACING_RATE`
  * `soft` to force the internal software method
  * `auto` for the best available (`socket` if that can be set up, `soft` otherwise).

I didn't see anything in the kernel patch that makes `setsockopt()` fail with `EINVAL` if pacing can't be done on the socket, which might make `auto` moot.  I can't think of a better way to do it that doesn't involve divining the interface from the routing table, but even that's subject to change midstream.

**Comment by bmah888** [comment]
Call for testing...I did some selection logic changes based on a hallway discussion with @bltierney.  iperf3 will try the fair-queueing based pacing on platforms that support it, otherwise it'll use its own internal pacing.  The internal pacing can be forced by passing `--no-fq-socket-pacing`.  I've also added manpage text.

If people seem reasonably happy with this, I'll merge this to the mainline.

**Comment by bltierney** [comment]
Looks like by default its setting it to something really low (see results
below).
By default it should not set anything.

Also, can you change this:
   --no-fq-socket-pacing     disable fair-queue socket pacing (Linux only)

to this:

  --no-fq-socket-pacing     disable fair-queuing based socket pacing (Linux
only)


./iperf3 -c bnl-diskpt1

Connecting to host bnl-diskpt1, port 5201

[  4] local 198.129.77.102 port 60275 connected to 198.124.238.150 port 5201

[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd

[  4]   0.00-1.00   sec   533 KBytes  4.36 Mbits/sec    0   8.74 KBytes


[  4]   1.00-2.00   sec   122 KBytes  1.00 Mbits/sec    0    149 KBytes


[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0    149 KBytes

[  4]   3.00-4.00   sec  61.2 KBytes   501 Kbits/sec    0    149 KBytes


[  4]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0    149 KBytes

[  4]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    0    149 KBytes

[  4]   6.00-7.00   sec  61.2 KBytes   501 Kbits/sec    0    149 KBytes


[  4]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    0    149 KBytes

[  4]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec    0    149 KBytes

[  4]   9.00-10.00  sec  61.2 KBytes   501 Kbits/sec    0    149 KBytes


- - - - - - - - - - - - - - - - - - - - - - - - -

[ ID] Interval           Transfer     Bandwidth       Retr

[  4]   0.00-10.00  sec   839 KBytes   687 Kbits/sec    0             sender

[  4]   0.00-10.00  sec   245 KBytes   200 Kbits/sec
receiver




If you set it using -b, things seem OK:


tierney@lbl-diskpt1.es.net(62)>./iperf3 -c bnl-diskpt1 -b 5g

Connecting to host bnl-diskpt1, port 5201

[  4] local 198.129.77.102 port 60279 connected to 198.124.238.150 port 5201

[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd

[  4]   0.00-1.00   sec   222 MBytes  1.86 Gbits/sec    0   81.0 MBytes


[  4]   1.00-2.00   sec   584 MBytes  4.90 Gbits/sec    0   81.4 MBytes


[  4]   2.00-3.00   sec   584 MBytes  4.90 Gbits/sec    0   81.5 MBytes


[  4]   3.00-4.00   sec   582 MBytes  4.88 Gbits/sec    0   81.5 MBytes


[  4]   4.00-5.00   sec   584 MBytes  4.89 Gbits/sec    0   81.5 MBytes


[  4]   5.00-6.00   sec   583 MBytes  4.89 Gbits/sec    0   81.5 MBytes


[  4]   6.00-7.00   sec   580 MBytes  4.87 Gbits/sec    0   81.5 MBytes


[  4]   7.00-8.00   sec   582 MBytes  4.88 Gbits/sec    0   81.5 MBytes


[  4]   8.00-9.00   sec   582 MBytes  4.88 Gbits/sec    0   81.5 MBytes


[  4]   9.00-10.00  sec   583 MBytes  4.89 Gbits/sec    0   81.5 MBytes


- - - - - - - - - - - - - - - - - - - - - - - - -

[ ID] Interval           Transfer     Bandwidth       Retr

[  4]   0.00-10.00  sec  5.34 GBytes  4.58 Gbits/sec    0             sender

[  4]   0.00-10.00  sec  5.29 GBytes  4.55 Gbits/sec
receiver



On Tue, May 24, 2016 at 9:28 AM, Bruce A. Mah <notifications@github.com>
wrote:

> Call for testing...I did some selection logic changes based on a hallway
> discussion with @bltierney <https://github.com/bltierney>. iperf3 will
> try the fair-queueing based pacing on platforms that support it, otherwise
> it'll use its own internal pacing. The internal pacing can be forced by
> passing --no-fq-socket-pacing. I've also added manpage text.
>
> If people seem reasonably happy with this, I'll merge this to the mainline.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/esnet/iperf/issues/325#issuecomment-221327486>
>



-- 
Brian Tierney, http://www.es.net/tierney
Energy Sciences Network (ESnet), Berkeley National Lab
http://fasterdata.es.net

**Comment by bmah888** [comment]
Change 227992f makes it so we don't try to do SO_MAX_PACING_RATE if the rate is 0, tested this between lbl-diskpt1 and bnl-diskpt1 with expected results (7.1Gbps TCP with all default parameters).  Also changed the help text and manpage for your documentation suggestions.

@bltierney:  If that seems to work for you, I plan to merge the accumulated work to the mainline and declare this issue done.

**Comment by bmah888** [comment]
D'oh!  This issue should have been closed awhile ago, all work has been done.
