### ISSUE TITLE
What is the definition of the bandwidth?

### ISSUE THREAD

**Issue by Chekov2k** [esnet/iperf#330]
Hi all,

is the bandwidth the total bandwidth, including packet headers? Or is it just the bandwidth using the payload size?

**Comment by joemce** [comment]
The bandwidth term refers to the application level data for either TCP, UDP, or SCTP. Packet headers are not included.  The underlying packet headers do limit the maximum application level bandwidth that is possible. For example, IPv6 requires more packet header space than IPv4. VLANs consume header space, etc.

**Comment by Chekov2k** [comment]
Thanks a lot for the quick reply :-)
