### ISSUE TITLE
Making iPerf to a HTML5 app

### ISSUE THREAD

**Issue by leonheart78** [esnet/iperf#332]
I would like to check if there is any possibility to compile the iPerf source to a HTML5 app?

**Comment by bmah888** [comment]
iperf3 is written in C.  HTML5 is a markup language for Web pages.  I don't see how HTML5 could express the functionality of a generic C program (or iperf3 in particular).  So unless I've misunderstood the question (very possible!) I'd say no.

**Comment by luckxiang** [comment]
maybe you can write a HTML5 app to use iperf3.
