### ISSUE TITLE
Cannot not set window size for server -> performance issue

### ISSUE THREAD

**Issue by taismi** [esnet/iperf#333]
Server: 192.168.1.50, iperf3 -s
Client: 192.168.1.158

Whis works OK.
iperf3.exe -c 192.168.1.50 -w 1M
Connecting to host 192.168.1.50, port 5201
[  4] local 192.168.1.158 port 51598 connected to 192.168.1.50 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec   115 MBytes   949 Mbits/sec
[  4]   1.01-2.01   sec   113 MBytes   948 Mbits/sec
[  4]   2.01-3.01   sec   113 MBytes   948 Mbits/sec
[  4]   3.01-4.01   sec   112 MBytes   941 Mbits/sec
[  4]   4.01-5.01   sec   113 MBytes   948 Mbits/sec
[  4]   5.01-6.01   sec   113 MBytes   949 Mbits/sec
[  4]   6.01-7.00   sec   113 MBytes   949 Mbits/sec
[  4]   7.00-8.00   sec   113 MBytes   947 Mbits/sec
[  4]   8.00-9.00   sec   113 MBytes   948 Mbits/sec
[  4]   9.00-10.02  sec   115 MBytes   948 Mbits/sec

---

[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.02  sec  1.11 GBytes   948 Mbits/sec                  sender
[  4]   0.00-10.02  sec  1.10 GBytes   947 Mbits/sec                  receiver
iperf Done.

This doesn't work ok because server uses too small window size.
iperf3.exe -c 192.168.1.50 -w 1M -R
Connecting to host 192.168.1.50, port 5201
Reverse mode, remote host 192.168.1.50 is sending
[  4] local 192.168.1.158 port 51600 connected to 192.168.1.50 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.01   sec   384 KBytes  3.10 Mbits/sec
[  4]   1.01-2.01   sec   320 KBytes  2.63 Mbits/sec
[  4]   2.01-3.01   sec   320 KBytes  2.63 Mbits/sec
[  4]   3.01-4.01   sec   320 KBytes  2.63 Mbits/sec
[  4]   4.01-5.01   sec   256 KBytes  2.10 Mbits/sec
[  4]   5.01-6.01   sec   320 KBytes  2.63 Mbits/sec
[  4]   6.01-7.00   sec   320 KBytes  2.63 Mbits/sec
[  4]   7.00-8.00   sec   320 KBytes  2.63 Mbits/sec
[  4]   8.00-9.00   sec   320 KBytes  2.63 Mbits/sec
[  4]   9.00-10.02  sec   256 KBytes  2.07 Mbits/sec

---

[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.02  sec  3.06 MBytes  2.57 Mbits/sec                  sender
[  4]   0.00-10.02  sec  3.06 MBytes  2.57 Mbits/sec                  receiver
iperf Done.

If I run the server at 192.168.1.158 and client at 192.168.1.50 I can double check that the window size is the problem.
iperf3.exe -c 192.168.1.158
Connecting to host 192.168.1.158, port 5201
[  4] local 192.168.1.50 port 2089 connected to 192.168.1.158 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec   384 KBytes  3.15 Mbits/sec
[  4]   1.00-2.00   sec   320 KBytes  2.62 Mbits/sec
[  4]   2.00-3.00   sec   320 KBytes  2.62 Mbits/sec
[  4]   3.00-4.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   4.00-5.00   sec   320 KBytes  2.62 Mbits/sec
[  4]   5.00-6.00   sec   320 KBytes  2.62 Mbits/sec
[  4]   6.00-7.00   sec   256 KBytes  2.10 Mbits/sec
[  4]   7.00-8.00   sec   320 KBytes  2.62 Mbits/sec
[  4]   8.00-9.00   sec   320 KBytes  2.62 Mbits/sec
[  4]   9.00-10.00  sec   320 KBytes  2.62 Mbits/sec

---

[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  3.06 MBytes  2.57 Mbits/sec                  sender
[  4]   0.00-10.00  sec  3.06 MBytes  2.57 Mbits/sec                  receiver
iperf Done.

iperf3.exe -c 192.168.1.158 -w 1M
Connecting to host 192.168.1.158, port 5201
[  4] local 192.168.1.50 port 2091 connected to 192.168.1.158 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec   113 MBytes   950 Mbits/sec
[  4]   1.00-2.00   sec   111 MBytes   933 Mbits/sec
[  4]   2.00-3.00   sec   112 MBytes   935 Mbits/sec
[  4]   3.00-4.00   sec   112 MBytes   940 Mbits/sec
[  4]   4.00-5.00   sec   112 MBytes   936 Mbits/sec
[  4]   5.00-6.00   sec   112 MBytes   938 Mbits/sec
[  4]   6.00-7.00   sec   112 MBytes   937 Mbits/sec
[  4]   7.00-8.00   sec   112 MBytes   938 Mbits/sec
[  4]   8.00-9.00   sec   112 MBytes   940 Mbits/sec
[  4]   9.00-10.00  sec   112 MBytes   941 Mbits/sec

---

[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-10.00  sec  1.09 GBytes   939 Mbits/sec                  sender
[  4]   0.00-10.00  sec  1.09 GBytes   939 Mbits/sec                  receiver
iperf Done.

iperf3.exe -s -w 1M is not allowed.

**Comment by taismi** [comment]
iperf3.exe -version
iperf 3.0.11

**Comment by taismi** [comment]
The problem might be that buffer size is not set correctly. Wireshark shows that transmission window is not full.

Debug info:
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
get_parameters:
{
        "tcp":  true,
        "omit": 0,
        "time": 10,
        "parallel":     1,
        "reverse":      true,
        "window":       1048576,
        "len":  131072,
        "client_version":       "3.1"
}
SO_SNDBUF is 1048576
Accepted connection from 192.168.1.158, port 52289
[  5] local 192.168.1.50 port 5201 connected to 192.168.1.158 port 52290
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   378 KBytes  3.10 Mbits/sec
[  5]   1.00-2.00   sec   315 KBytes  2.58 Mbits/sec
[  5]   2.00-3.00   sec   315 KBytes  2.58 Mbits/sec
[  5]   3.00-4.00   sec   252 KBytes  2.06 Mbits/sec
[  5]   4.00-5.00   sec   315 KBytes  2.58 Mbits/sec
[  5]   5.00-6.00   sec   315 KBytes  2.58 Mbits/sec
[  5]   6.00-7.00   sec   315 KBytes  2.58 Mbits/sec
[  5]   7.00-8.00   sec   315 KBytes  2.58 Mbits/sec
[  5]   8.00-9.00   sec   315 KBytes  2.58 Mbits/sec
[  5]   9.00-10.00  sec   252 KBytes  2.06 Mbits/sec
[  5]  10.00-10.20  sec  63.0 KBytes  2.54 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.20  sec  3.08 MBytes  2.53 Mbits/sec                  sender
[  5]   0.00-10.20  sec  0.00 Bytes  0.00 bits/sec                  receiver
get_results
{
        "cpu_util_total":       1.61494,
        "cpu_util_user":        1.02941,
        "cpu_util_system":      0.585535,
        "sender_has_retransmits":       -1,
        "streams":      [{
                        "id":   1,
                        "bytes":        3225600,
                        "retransmits":  -1,
                        "jitter":       0,
                        "errors":       0,
                        "packets":      0
                }]
}
send_results
{
        "cpu_util_total":       0.115802,
        "cpu_util_user":        0.115802,
        "cpu_util_system":      0,
        "sender_has_retransmits":       0,
        "streams":      [{
                        "id":   1,
                        "bytes":        3225600,
                        "retransmits":  -1,
                        "jitter":       0,
                        "errors":       0,
                        "packets":      0
                }]
}

**Comment by nh2** [comment]
@taismi: You should check whether this is related to your problem: https://github.com/esnet/iperf/issues/356

**Comment by bmah888** [comment]
Is this possibly a Windows-specific issue?

**Comment by taismi** [comment]
This problem has not occured when I'm using Linux.
