### ISSUE TITLE
worst TCP performance when zerocopy used

### ISSUE THREAD

**Issue by l4mer** [esnet/iperf#334]
This is TCP TX test run on MIPS.
When -Z option is uesed (zerocopy) I would suspect better TP than without this option.
But without zerocopy I get 170Mbps, while with -Z only 140Mbps.
For case witout zerocopy kernel perf show about 14% spent in copy_from_user(). 
During tests we consume whole CPU - 0% idle left.
Any idea why zerocopy didn't increase TP?

**Comment by CAHEK7** [comment]
Had a look at the code and found out the only one significant difference: syscall `sendfile` is used instead of syscall `write` in zerocopy mode, iperf itself makes only simple wrap around these syscalls. I guess there is some problem in the system itself.

**Comment by bltierney** [comment]
closing, as likely specific to your host.
