### ISSUE TITLE
What's difference between iperf3_profile and iperf3?  

### ISSUE THREAD

**Issue by luckxiang** [esnet/iperf#335]
Dear iperf team:
When transplanting iperf3 to the embedded system, iperf3_profile fails to link in the process of build while iperf3 is ok . I want to know what's difference between iperf3_profile and iperf3.

**Comment by bmah888** [comment]
iperf3_profile has some hooks to allow a user to profile the code, that is, at runtime determine where CPU time is spent.  It's normally not needed.

**Comment by hoang-tranviet** [comment]
Hello Bruce,
Do you know if is there any available document or guide on how to use this profiling feature?
Thank you!

**Comment by hoang-tranviet** [comment]
I just found this command works and produces nice stats:
`gprof src/.libs/iperf3_profile gmon.out`
Don't know if we can have even cooler things with profiling.

**Comment by bmah888** [comment]
I've literally never used the profiled iperf3, although I believe some others in our organization have.  I would imagine that any techniques on profiling C code would work for iperf3.
