### ISSUE TITLE
strange issue: iperf not "ending", stuck after one package

### ISSUE THREAD

**Issue by Felias1701** [esnet/iperf#339]
Hi there,

on my local network i have a weird issue. Whenever i start a iperf check, it doesn't come to an end...:

    OpenELEC:~ # iperf -p 123 -c 192.168.178.21 -t 60
    ^C- - - - - - - - - - - - - - - - - - - - - - - - -
    [ ID] Interval           Transfer     Bandwidth       Retr
    iperf3: interrupt - the client has terminated

I interrupted after like 10 minutes or so. On the server side it looks like this:

    Hal2001> iperf -s -p 123
    ------------------------------------------------------------
    Server listening on TCP port 123 
    TCP window size: 85.3 KByte (default)
    ------------------------------------------------------------
    [  4] local 192.168.178.21 port 123 connected with 192.168.178.25 port 60706
    [ ID] Interval       Transfer     Bandwidth
    [  4]  0.0- 4.0 sec  14.0 Bytes  28.0 bits/sec

The weird thing is, i've tested different combination with 3 devices in my network. All showing the same behavior. I trieb it without the '-t 60' value, and with '-n' instead, but it always shows the same behaviour. Never more than 14 Bytes are transferred.

Anyone has an idea what the reason might be?

Best wishes and thanks in advance,
felias

**Comment by TheRealDJ** [comment]
Are you iperf3 on both ends?

**Comment by bmah888** [comment]
That doesn't look like iperf3 output on either the client or the server.  I'm guessing it's iperf2, try the iperf-users mailing list to get some help there.

Closing as invalid because this doesn't appear to be an iperf3 issue.
