### ISSUE TITLE
Iperf for mobile

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#341]
Is there a way to run this within iOS or android app?
perhaps a C based library which is embedded in app, can then call method to run test after specifying server address and the method returns results

**Comment by BasvanH** [comment]
Search and you will find: https://play.google.com/store/apps/details?id=com.magicandroidapps.iperf&hl=nl

**Comment by bmah888** [comment]
Searching for "iperf" in the Apple iOS app store will also yield a number of hits, some based on iperf2 and some based on iperf3.  The iperf3 project has no connection with any of these mobile versions and cannot recommend any particular app.

**Comment by pjebs** [comment]
I meant using lib in my own app as a client - Not using another app
