### ISSUE TITLE
what "Retr" field mean .

### ISSUE THREAD

**Issue by big-loser** [esnet/iperf#343]
Does the "Retr" field mean？ 

Is re-transmitted by TCP ?

Under what circumstances will appear this kind of state?

tks

**Comment by bmah888** [comment]
It's the number of TCP segments retransmitted.  This can happen if TCP segments are lost in the network due to congestion or corruption.

**Comment by penglei0** [comment]
> It's the number of TCP segments retransmitted. This can happen if TCP segments are lost in the network due to congestion or corruption.

@bmah888 
It's not the number of retransmitted segments. Actually, it's the number of attempting to retransmit segments; the retransmission attempting may fail and the segment will not be occurs on the outgoing link. 

```c
	tcp_enter_loss(sk);

	icsk->icsk_retransmits++;
	if (tcp_retransmit_skb(sk, tcp_rtx_queue_head(sk), 1) > 0) {
		/* Retransmission failed because of local congestion,
		 * Let senders fight for local resources conservatively.
		 */
		inet_csk_reset_xmit_timer(sk, ICSK_TIME_RETRANS,
					  TCP_RESOURCE_PROBE_INTERVAL,
					  TCP_RTO_MAX);
		goto out;
	}

```

**Comment by bmah888** [comment]
> > It's the number of TCP segments retransmitted. This can happen if TCP segments are lost in the network due to congestion or corruption.
> 
> @bmah888 It's not the number of retransmitted segments. Actually, it's the number of attempting to retransmit segments; the retransmission attempting may fail and the segment will not be occurs on the outgoing link.

Good point, that's a subtle but very important difference.
