### ISSUE TITLE
Support TCP_MD5SIG socketopt (Linux)

### ISSUE THREAD

**Issue by critindirecx** [esnet/iperf#347]
The TCP_MD5SIG option is based on [rfc2385](https://www.ietf.org/rfc/rfc2385.txt). This is currently not present in iperf3.

Some references on the topic:
http://criticalindirection.com/2015/05/12/tcp_md5sig/
http://sched.co/4KAn

I have the patch ready, I can send a pull request. Thanks.

**Comment by critindirecx** [comment]
Pull request: https://github.com/esnet/iperf/pull/349

**Comment by bmah888** [comment]
I'm going to close this issue and leave pull request #350 open for now, so we only have one "thing" in the issue tracker.  Thanks!
