### ISSUE TITLE
UDP streams creation is broken in lossy environments

### ISSUE THREAD

**Issue by yanavlasov** [esnet/iperf#351]
(Apologies if this is a known issue, I could not find anything like this in the existing issues).
This makes iperf3 UDP mode unusable on networks with higher frame loss (or reordering when testing on windows). It also applies to networks where iperf3 server network adapter can be in sleep mode (i.e. 802.11 on smartphones) and intervening infrastructure drops frames while it wakes up (i.e. AP under load).
UDP stream is created through the handshake where client sends 4 byte cookie and server responds backs with a different 4 byte cookie. On a network with high packet loss or reordering 3 things can happen:
1. client frame with cookie can be dropped (i.e. due to aforementioned sleep mode). which results in iperf3 client timing out and exiting
2. server frame with cookie can be dropped. which will result in timeout when more streams are to be created.
On windows the iperf3 stream establishment can fail if cookie response it reordered with the test frame. The winsock recv call in iperf_udp_connect returns "insufficient buffer" code indicating that message was truncated. This is of course unsupported configuration.

Is iperf3 UDP mode intended to be used for high loss conditions? If so are you open to discuss possible fixes?

**Comment by bmah888** [comment]
iperf3 was designed for use in high-performance R&E networks.  There's typically very little loss in those environments.  Admittedly we don't say that explicitly, but I suspect you might be trying to make iperf3 run in a different environment from where it was intended to run.
