### ISSUE TITLE
Add realtime JSON data output

### ISSUE THREAD

**Issue by TheRealDJ** [esnet/iperf#353]
I would like some way of receiving JSON data indicating that a test has started, and the test parameters. Currently, this data is all outputted once the test is complete.

I am working on wrapper scripts to coordinate testing of MANY devices back to a set of iperf3 servers. This would greatly help by allowing me to track when a test starts to assist in queueing client tests.

**Comment by bmah888** [comment]
Would something like #377 do what you have in mind?

**Comment by TheRealDJ** [comment]
That will work. Thanks!

**Comment by TheRealDJ** [comment]
Closing.

**Comment by TheRealDJ** [comment]
I just realized that [#377](https://github.com/esnet/iperf/pull/377) does not include JSON output format. If I use "-t 5 -i 1 -J --forceflush", I get all of the JSON output once the test is complete.

I was thinking something like:
-output the "start" section right away
-output each interval as they happen
-output the "end" section once the test is complete

**Comment by nyzen** [comment]
I am also very interested in a feature that lets me parse the results on time, as they come. Did you find any solution worth mentioning?

**Comment by bltierney** [comment]
design of iperf3 makes this pretty darn hard. Sorry.

**Comment by hilmiugurpolat** [comment]
> I just realized that [#377](https://github.com/esnet/iperf/pull/377) does not include JSON output format. If I use "-t 5 -i 1 -J --forceflush", I get all of the JSON output once the test is complete.
> 
> I was thinking something like: -output the "start" section right away -output each interval as they happen -output the "end" section once the test is complete

Hello,I have encountered exactly the same problem as you. Have you found a way to print json data instantly?

**Comment by hilmiugurpolat** [comment]
> I am also very interested in a feature that lets me parse the results on time, as they come. Did you find any solution worth mentioning?

Hello,I have encountered exactly the same problem as you. Have you found a way to print json data instant

**Comment by davidBar-On** [comment]
> Hello,I have encountered exactly the same problem as you. Have you found a way to print json data instantly?

@hilmiugurpolat, did you try the `--json-stream` option (added by PR #1098 relatively recently)?  If seems that it is what you are looking for.
