### ISSUE TITLE
Verify --window parameter settings

### ISSUE THREAD

**Issue by nh2** [esnet/iperf#356]
`man iperf3` says:

```
       -w, --window n[KM]
              TCP window size / socket buffer size (this gets sent to the  server
              and used on that side too)
```

But in fact, this option is (or at least my research so far has shown that it is) bounded by `/proc/sys/net/core/rmem_max`, and if the passed`-w` is bigger, it is silently ignored!

This has left me puzzled for a couple of hours, and explains why my performance is better when I pass no `-w` option at all, and always get completely horrible as soon as I pass `-w`, no matter if it's `10 K`, `1 M` or `100 M`, because of my Linux distribution's (Ubuntu) default of `net.core.rmem_max = 212992`.

From `man tcp`:

```
       The maximum sizes for  socket  buffers  declared  via  the  SO_SNDBUF  and
       SO_RCVBUF    mechanisms    are    limited    by    the   values   in   the
       /proc/sys/net/core/rmem_max and /proc/sys/net/core/wmem_max  files.   Note
       that  TCP actually allocates twice the size of the buffer requested in the
       setsockopt(2) call, and so a succeeding getsockopt(2) call will not return
       the  same size of buffer as requested in the setsockopt(2) call.
```

I believe that after `setsockopt(s, SOL_SOCKET, SO_RCVBUF, &opt, sizeof(opt)) < 0` iperf should check what the actual value of `SO_RCVBUF` is, and print a warning (or even error) if it's not the one requested by the user with `-w`.

**Comment by nh2** [comment]
For a related problem (found using iperf3, but unrelated to iperf3), see [this](stackoverflow.com/questions/31546835/tcp-receiving-window-size-higher-than-net-core-rmem-max/35438236).

**Comment by bmah888** [comment]
This is basically a suggestion to read back the socket buffer sizes after setting them to be sure they're actually the requested value.  We should do this for both the sending and receiving sides of the socket.  Testing some code to do this...it's pretty straightforward.

**Comment by nh2** [comment]
Awesome, thank you!

**Comment by bmah888** [comment]
Re-open so I remember to merge this after it's baked a bit.

**Comment by bmah888** [comment]
Merged!
