### ISSUE TITLE
Detecting if server is busy

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#357]
Right now if a server is busy with a client and another client tries to connect, the client gets a message saying the server is in use.

Is there anyway to 
A) Detect if a particular server is busy with a client by another program?
eg. A totally separate program that has no intention of being a client. i.e. Can it 'ask' the server "are you busy?"

B) Is there any way for the server to send out a signal to a separate program (that has no intention of being a client) of when it has finished running a test and is now free?

**Comment by pjebs** [comment]
C) In a worst case situation where the above is not possible, is there a way to configure the MAXIMUM time that a test could take, so after that time expires, I can safely assume that the server is guaranteed to be free?

**Comment by bltierney** [comment]
design of iperf3 makes this difficult. perfSONAR's bwctl and pscheduler tools are designed for this, so suggest using those.
