### ISSUE TITLE
Updating to iperf3.1

### ISSUE THREAD

**Issue by SrujithPoondla** [esnet/iperf#360]
How to update to iperf3.1?
I want to use the new logfile feature.
Thanks

**Comment by TheRealDJ** [comment]
Download the source code, then follow the compile and install instructions in the readme file. The steps are:

./configure
make
make install

**Comment by bmah888** [comment]
That, or if you're using some precompiled version, get a new version from whereever you got the old one.

Note that ESnet does not provide precompiled binaries.
