### ISSUE TITLE
Incorrect percentage show when using empty file for memory-disk bandwidth test

### ISSUE THREAD

**Issue by RichardCao** [esnet/iperf#361]
console 1:
    iperf3 -s
console 2:
    touch testfile
    iperfe -c localhost -i1 -F testfile
Then we can see:

   Connecting to host localhost, port 5201
   [  5] local ::1 port 36762 connected to ::1 port 5201
   [ ID] Interval           Transfer     Bandwidth
   [  5]   0.00-0.00   sec  0.00 Bytes  0.00 bits/sec                  

---

   [ ID] Interval           Transfer     Bandwidth
   [  5]   0.00-0.00   sec  0.00 Bytes  0.00 bits/sec                  sender
           Sent 0.00 Byte / 0.00 Byte (-2147483648%) of testfile
   [  5]   0.00-0.00   sec  0.00 Bytes  0.00 bits/sec                  receiver

This string "(-2147483648%) of testfile" won't effect on general testing, just a display case on the special situation. :)

**Comment by bmah888** [comment]
Reopen this bug so I know to merge it when I get a chance.

**Comment by bmah888** [comment]
Merged to 3.1.  Closing.
