### ISSUE TITLE
Shut down iperf3 server

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#363]
I am trying to run iperf3(server) on a docker container.
What code file/line would I need to change to get iperf3 to shut itself down after the first test with client finishes.

That way, I can get the docker container to automatically shutdown once the server shuts down.

**Comment by pjebs** [comment]
The problem I am trying to solve is related to https://github.com/esnet/iperf/issues/357

**Comment by bmah888** [comment]
Try ```iperf3 --server --one-off```

**Comment by pjebs** [comment]
I installed iperf3 but it says "unrecognized option '--one-off'"

**Comment by pjebs** [comment]
I installed it using this:

`apt-get install -qy iperf3`

**Comment by bmah888** [comment]
You need iperf-3.0.11 or newer for that option.
