### ISSUE TITLE
UDP Test error "malformed number" in JSON format (Perl), RFC Specification not met

### ISSUE THREAD

**Issue by Mangnoppa** [esnet/iperf#364]
Hello,

I am running iperf3 Version 3.0.11 on an Ubuntu PC. When I run an UDP-Test with the -J flag **and** there are no transmitted packets **and** no lost packets, the lost_percent string shows "-nan". 

According to the [RFC4627-Specification](https://tools.ietf.org/html/rfc4627) of JSON, "NaN" and "Infinite" is not allowed.

I am executing iperf3 with a perl script. This is the code printed with Data::Dumper:
```
"streams":	[{
	"socket":	4,
	"start":	8.00011,
	"end":	9.00102,
	"seconds":	1.00092,
	"bytes":	0,
	"bits_per_second":	0,
	"jitter_ms":	0.452296,
	"lost_packets":	0,
	"packets":	0,
	"lost_percent":	-nan,
	"omitted":	false
	}],
"sum":	{
	"start":	8.00011,
	"end":	9.00102,
	"seconds":	1.00092,
	"bytes":	0,
	"bits_per_second":	0,
	"jitter_ms":	0.452296,
	"lost_packets":	0,
	"packets":	0,
	"lost_percent":	-nan,
	"omitted":	false
}
```

I then try to parse it with the JSON module in perl, which does not work, because "-nan" is not allowed.  I would recommend the value "null" or "0" for that.

Parsing the string myself is working, but it would be great if you could fix this definition error some time.

EDIT: I think this behaviour comes from the division by zero.

**Comment by Mangnoppa** [comment]
I can reproduce this error with the following:
On the server-side
`/usr/bin/iperf3 -s -p 5111 -J`

On the client-side
`iperf3 -c SERVER_ADDR -u -p 5111 -b 0 -l 8000 -J -R`

The same output as posted above is shown, maybe in another interval.

Both PCs are connected with a 1Gbit uplink. The switch is fragmenting the packages and the client is not able to rebuild them, so they are lost (verified with wireshark).

 I looked at the source code of iperf3 and in my version I would expect a packet_lost-value of "100.0" and with the version from the master branch a value of "0.0".

**Comment by Mangnoppa** [comment]
Okay next time i should really look at the commit messages of the sources:
 	`src 	| Get rid of nan values when there were no packets in a UDP interval.  |  27 days ago`
You can close this. I look at the mentioned issue.

**Comment by bmah888** [comment]
Closed as requested.
