### ISSUE TITLE
static client listen port 

### ISSUE THREAD

**Issue by davigega** [esnet/iperf#365]
Hello!
for compatibility issues I'm still using iperf 2.0.5

as you can read in the title I was wondering whether is possible to set a client listening port.
I've been trying with -L, --listenport with no results, and -cport (but I guess this is just an iperf3 features).
If this wouldn't be possible, is there anyway to set a permanent static port that iperf might use? 
I basically having firewall issues.

**Comment by bmah888** [comment]
This issue tracker is for iperf3.  I suggest you try posting your question on the iperf-users mailing list.
