### ISSUE TITLE
getopt_long is not portable

### ISSUE THREAD

**Issue by canavan** [esnet/iperf#367]
iperf_api.c makes use of getopt_long, which isn't available everywhere. Gnulib provides an implementation, which I've used to build iperf3 on IRIX. 

I've used `gnulib/gnulib-tool --import getopt-gnu` and the folowing patch:

commit b9f66e4d9cfbb8b655a41cf1f132499a244b0bf9
Author: Rainer M. Canavan canavan@tezro.nonet
Date:   Sun Feb 28 16:51:29 2016 +0100

```
integrate gnulib getopt-gnu
```

diff --git a/Makefile.am b/Makefile.am
index f0ad1ee..de6b1fc 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -1 +1,3 @@
-SUBDIRS = src examples
+SUBDIRS = lib src examples
+ACLOCAL_AMFLAGS = -I m4 
+EXTRA_DIST = m4/gnulib-cache.m4
diff --git a/configure.ac b/configure.ac
index 3d8b825..4631e90 100644
--- a/configure.ac
+++ b/configure.ac
@@ -31,17 +31,18 @@ AC_LANG(C)
 # directory is picked so that they don't clutter up more useful directories.
 AC_CONFIG_AUX_DIR(config)
## 

 # Initialize the automake system
-AM_INIT_AUTOMAKE
+AM_INIT_AUTOMAKE(foreign)
 AM_MAINTAINER_MODE
 AM_CONFIG_HEADER(src/iperf_config.h)
+AC_CONFIG_MACRO_DIR([m4])

 AC_CANONICAL_HOST

 # Checks for tools: c compiler, ranlib (used for creating static libraries),
 # symlinks and libtool
 AC_PROG_CC
+gl_EARLY
 AC_PROG_RANLIB
 AC_PROG_LN_S
 AC_PROG_LIBTOOL
@@ -52,6 +53,8 @@ if test "x$GCC" = "xyes"; then
 fi

 # Checks for header files.
+gl_INIT
+
 AC_HEADER_STDC

 # Check for systems which need -lsocket and -lnsl
diff --git a/src/Makefile.am b/src/Makefile.am
index 23b0c72..8ef7fc1 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -1,3 +1,4 @@
+AM_CPPFLAGS             = -I$(top_builddir)/lib -I$(top_srcdir)/lib
 lib_LTLIBRARIES         = libiperf.la                                   # Build and install an iperf library
 bin_PROGRAMS            = iperf3                                        # Build and install an iperf binary
 noinst_PROGRAMS         = t_timer t_units t_uuid iperf3_profile         # Build, but don't install the test programs and a profiled version of iperf3
@@ -38,36 +39,38 @@ libiperf_la_SOURCES     = \
                         units.h \
                         version.h

+libiperf_la_LIBADD      = ../lib/libgnu.a
+
 # Specify the sources and various flags for the iperf binary
 iperf3_SOURCES          = main.c
-iperf3_CFLAGS           = -g
+iperf3_CFLAGS           = 
 iperf3_LDADD            = libiperf.la
-iperf3_LDFLAGS          = -g
+iperf3_LDFLAGS          = 

 # Specify the sources and various flags for the profiled iperf binary. This
 # binary recompiles all the source files to make sure they are all profiled.
 iperf3_profile_SOURCES  = main.c \
                          $(libiperf_la_SOURCES)

-iperf3_profile_CFLAGS   = -pg -g
-iperf3_profile_LDADD    = libiperf.la
-iperf3_profile_LDFLAGS  = -pg -g
+iperf3_profile_CFLAGS   = -pg 
+iperf3_profile_LDADD    = libiperf.la ../lib/libgnu.a
+iperf3_profile_LDFLAGS  = -pg 

 # Specify the sources and various flags for the test cases
 t_timer_SOURCES         = t_timer.c
-t_timer_CFLAGS          = -g
+t_timer_CFLAGS          = 
 t_timer_LDFLAGS         =
-t_timer_LDADD           = libiperf.la
+t_timer_LDADD           = libiperf.la ../lib/libgnu.a

 t_units_SOURCES         = t_units.c
-t_units_CFLAGS          = -g
+t_units_CFLAGS          = 
 t_units_LDFLAGS         =
-t_units_LDADD           = libiperf.la
+t_units_LDADD           = libiperf.la ../lib/libgnu.a

 t_uuid_SOURCES          = t_uuid.c
-t_uuid_CFLAGS           = -g
+t_uuid_CFLAGS           = 
 t_uuid_LDFLAGS          =
-t_uuid_LDADD            = libiperf.la
+t_uuid_LDADD            = libiperf.la ../lib/libgnu.a

diff --git a/src/iperf_api.c b/src/iperf_api.c
index 4813c20..8682293 100755
--- a/src/iperf_api.c
+++ b/src/iperf_api.c
@@ -32,7 +32,7 @@
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
-#include <getopt.h>
+#include "../lib/getopt.h"
 #include <errno.h>
 #include <signal.h>
 #include <unistd.h>
diff --git a/src/iperf_client_api.c b/src/iperf_client_api.c
index f19f6f1..d3d59e7 100644
--- a/src/iperf_client_api.c
+++ b/src/iperf_client_api.c
@@ -24,6 +24,7 @@
- This code is distributed under a BSD style license, see the LICENSE
- file for complete information.
  _/
  +#include <iperf_config.h>
  #include <errno.h>
  #include <setjmp.h>
  #include <stdio.h>
  diff --git a/src/iperf_server_api.c b/src/iperf_server_api.c
  index ac0166a..7594536 100644
  --- a/src/iperf_server_api.c
  +++ b/src/iperf_server_api.c
  @@ -27,6 +27,7 @@
  /_ iperf_server_api.c: Functions to be used by an iperf server
  */

+#include <iperf_config.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
diff --git a/src/iperf_udp.c b/src/iperf_udp.c
index 9500aa1..b8ba4e4 100644
--- a/src/iperf_udp.c
+++ b/src/iperf_udp.c
@@ -24,6 +24,7 @@
- This code is distributed under a BSD style license, see the LICENSE
- file for complete information.
  */
  +#include <iperf_config.h>
  #include <stdio.h>
  #include <stdlib.h>
  #include <string.h>
  diff --git a/src/t_timer.c b/src/t_timer.c
  index c9018e6..b3bbcea 100644
  --- a/src/t_timer.c
  +++ b/src/t_timer.c
  @@ -24,6 +24,7 @@
- This code is distributed under a BSD style license, see the LICENSE
- file for complete information.
  */
  +#include <iperf_config.h>
  #include <stdio.h>
  #include <stdlib.h>
  #include <unistd.h>

**Comment by bmah888** [comment]
As I understand things, this change (in particular the `gnulib-tool --import getopt-gnu` part) adds source files that implement the getopt_long library function, thus removing the requirement to have it present in `libc` (or whatever) on the target system.  One concern is that these source files are licensed under GPLv3.  While iperf3 is nominally BSD-licensed, and distributing a mixture of GPLv3 and BSD code is technically permitted, the sponsors of iperf3 (ESnet and Lawrence Berkeley National Laboratory) have a policy against releasing or redistributing GPL-licensed code.  So unfortunately, we can't use the solution you've provided here.  (Of course you or anyone else are certainly welcome to fork the code and maintaining your own version that uses the gnulib getopt-gnu module.)

**Comment by canavan** [comment]
There are alternative implementations that are licensed under a BSD license, e.g. https://github.com/kimgr/getopt_port
