### ISSUE TITLE
portable_endian.h does not support IRIX

### ISSUE THREAD

**Issue by canavan** [esnet/iperf#368]
The following patch adds sufficient support for IRIX to portable_endian.h to enable iperf3 to build and run on IRIX 6.5:

diff --git a/src/portable_endian.h b/src/portable_endian.h
index 05f8861..b41e17c 100644
--- a/src/portable_endian.h
+++ b/src/portable_endian.h
@@ -63,6 +63,15 @@

 #  include <sys/endian.h>

+#elif defined(__sgi)
+
+#  include <sys/endian.h>
+#  include <netinet/in.h>
+#  include <inttypes.h>
+
+#  define be64toh(x) (x)
+#  define htobe64(x) (x)
+
 #elif defined(__sun) && defined(__SVR4)

 #  include <sys/types.h>

**Comment by bmah888** [comment]
I don't have any IRIX machines available to test, but no build-time regressions noted on our supported platforms, so closing as fixed.
