### ISSUE TITLE
daemon() is not portable

### ISSUE THREAD

**Issue by canavan** [esnet/iperf#369]
daemon() is not portable; add a check to configure.ac, use own implementation if it is not available

diff --git a/configure.ac b/configure.ac
index c85b907..3d8b825 100644
--- a/configure.ac
+++ b/configure.ac
@@ -141,4 +141,11 @@ AC_CHECK_FUNCS([cpuset_setaffinity sched_setaffinity],
 # it needs and what arguments it expects.
 AC_CHECK_FUNCS([sendfile])

+# AC_DEFINE([HAVE_DAEMON], [], [Description])
+AC_CHECK_FUNC(daemon, [ac_cv_func_daemon=yes; AC_DEFINE(HAVE_DAEMON, 1, [Have daemon()])])
+
+AC_CONFIG_FILES([
+lib/Makefile
+])
+
 AC_OUTPUT([Makefile src/Makefile src/version.h examples/Makefile iperf3.spec])
diff --git a/src/main.c b/src/main.c
index 4bd5a32..150a227 100644
--- a/src/main.c
+++ b/src/main.c
@@ -125,6 +125,65 @@ sigend_handler(int sig)
     longjmp(sigend_jmp_buf, 1);
 }

+#ifndef HAVE_DAEMON
+#include <sys/stat.h>
+#include <fcntl.h>
+
+int daemon(int nochdir, int noclose)
+{
-    pid_t pid = 0;
-    pid_t sid = 0;
-   
-    pid = fork();
-    if (pid < 0)
-    {
-   return -1;
-    }
-   
-    if (pid > 0)
-    {
-   exit(0);
-    }
-   
-    umask(0);
-   
-    sid = setsid();
-    if(sid < 0)
-    {
-   return -1;
-    }
  +
-    signal(SIGHUP, SIG_IGN);
-    pid=fork();
-    if (pid == -1) {
-   iperf_errexit(NULL, "failed to fork while daemonising (errno=%d)", iperf_strerror(errno));
-    } else if (pid != 0) {
-   exit(0);
-    }
  +
-    if (nochdir == 0) {
-   chdir("/");
-    }
-   
-    if (noclose == 0) {
-   close(STDIN_FILENO);
-   close(STDOUT_FILENO);
-   close(STDERR_FILENO);
  +
-   if (open("/dev/null", O_RDONLY) == -1) {
-       return -1;
-   }
-   if (open("/dev/null", O_WRONLY) == -1) {
-       return -1;
-   }
-   if (open("/dev/null", O_RDWR) == -1) {
-       return -1;
-   }
-    }
-    return (0);
  +}
  +#endif
  +
  /**************************************************************************/
  static int
  run(struct iperf_test *test)

**Comment by bmah888** [comment]
On what platform was (is) this a problem?

(Data point:  It's deprecated, but working, on macOS.)

**Comment by bmah888** [comment]
I'm looking at this patch and it seems kind of munged.  patch(1) on my laptop says the patch is malformed, and upon manual inspection I see some parts I don't understand.  In particular, why add an `AC_CONFIG_FILES` directive to `configure.ac`, and why do some of the lines defining the daemon() function replacement remove lines (that don't seem to be there in `src/main.c`)?

If this is still applicable, any chance you can send me a pull request with this?

**Comment by bmah888** [comment]
I'm going to close this issue for now because (as reported above) I can't really use the patch as it stands.  Sorry about that!  If I can get a pull request against master, that would probably work out better.  Thanks!

**Comment by bmah888** [comment]
I changed my mind. I'm going to see if I can knock this out real quick-like.

**Comment by bmah888** [comment]
I've pushed a candidate solution to this (based on the patch above) to the issue-369 branch.  Does this work for you?

**Comment by bmah888** [comment]
Testing of the code on the issue-369, on a platform that doesn't have daemon(3), would be appreciated.  I don't have the ability to test this myself, and before merging it to master I really need someone to tell me that it's fixed the problem.

**Comment by bmah888** [comment]
Explicitly close this issue...it didn't get autoclosed with the pull request.
