### ISSUE TITLE
"nan" invalid in JSON output

### ISSUE THREAD

**Issue by mpitt** [esnet/iperf#370]
According to the JSON specification ([RFC4627](http://tools.ietf.org/html/rfc4627)), "NaN" or "nan" is not a valid numeric value. It should probably be replaced by "null" (see http://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript).

**Comment by bmah888** [comment]
Duplicate of #364 and #278.
