### ISSUE TITLE
Printing text to debug window

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#372]
I am running the example code in an iOS app.
It seems to work fine (except udp mode).

However, it seems to print a lot of text into the debug window of XCode (IDE). How can I stop this?

When I set `iperf_set_test_json_output( test, 1 );`

I can get the string via: `iperf_get_test_json_output_string(test)`

**Comment by pjebs** [comment]
But it still prints out the same content in the debug window.

**Comment by bmah888** [comment]
I don't think we have a answer for this.  XCode is a sufficiently different environment from the UNIX-style environment for which we developed iperf3 that I don't really have a good answer for this.
