### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#373]
I'm looking at the json output. (TCP mode)
I was wondering how I could calculate latency.

In the summary at the end, it has the bandwidth only.

**Comment by EnfantDup** [comment]
Looking for the same thing

**Comment by IceQubed** [comment]
I'm also looking for this. Frustratingly, iPerf outputs jitter so it definitely knows what the latency (ping) is, it just doesn't output the value. I'm looking for the JSON output include this data.

**Comment by JodieChuang** [comment]
Hi,

Is iperf3 able to calculate the latency? I agree that "iPerf outputs jitter so it definitely knows what the latency is". however, Which codes are the logic of these measurements??

Best regards,
Huan

**Comment by bmah888** [comment]
iperf3 doesn't compute / know the latency.  The algorithm for computing jitter doesn't need to know what the latency is, so it doesn't.
