### ISSUE TITLE
iperf3 performance numbers

### ISSUE THREAD

**Issue by smcifrankp** [esnet/iperf#375]
Hi,

I have received more and more inquiries from our customer regarding low performance numbers acquired from iperf3 compared to iperf. Below is a report:

---

If I send iPerf3 traffic:
From I4S to I4S = Performance is 3-400 Mbit
From I4S to B4S = Performance is 3-400 Mbit
From B4S to B4S = Performance is 3-400 Mbit
From I4S to I2S = Performance is 6-7Gbit
From B4S to I2S = Performance is 6-7Gbit
(Same numbers if I reverse the data flow)

---

In above, all these “I4S”, “B4S”, “I2S” represent various 10G SFP+ cards. 

Could you please give me some advice? I wonder what flags/parameters people usually use to test 10G/100G with iperf3? 

If using iperf, all these 10G connections can get 9+ Gbps with correct parameters set. But no matter what parameters I added, iperf3 numbers don't look good at all.

Thank you.

**Comment by bmah888** [comment]
Have you tried increasing the sending and receiving socket buffer sizes with the `-w` option?  Or looked at some of the tuning suggestions on http://fasterdata.es.net/?

**Comment by bltierney** [comment]
We've seen up to 70Gbps with single stream iperf3, so I dont think its a problem with the tool. Can you send the exact commands you are using for iperf2 vs iperf3?

Also, these pages might be helpful:

   - https://fasterdata.es.net/host-tuning/100g-tuning/
   - https://fasterdata.es.net/performance-testing/network-troubleshooting-tools/iperf-and-iperf3/iperf3-at-speeds-above-10gbps/

**Comment by dahavey** [comment]
Hi I'm Daniel from the Windows TCPIP team,
Please don't statically set the TCP buffer sizes on Windows.  This will turn the autotuning algorithm off and hurt your performance.  See our blogpost on the topic: https://blogs.technet.microsoft.com/networking/2017/05/08/windows-network-performance-suffering-from-bad-buffering/

**Comment by bmah888** [comment]
The original bug report didn't say what platform was being used, in particular they didn't say they were on Windows.  We haven't gotten any responses to our requests for other information, so closing for now.  It can be reopened if more information surfaces.

I do wonder if we should include some of the information provided by @dahavey regarding Windows network performance (in this issue and in #463) into the FAQ, although I haven't thought yet about what's the best way to do that.
