### ISSUE TITLE
timeout for TCP test

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#378]
I don't think the TCP test has a timeout. Mine keeps going without stopping and it doesn't seem to be doing anything.

**Comment by pjebs** [comment]
if there is a timeout, how can I reduce it?

**Comment by rpodgorny** [comment]
+1

**Comment by sgon00** [comment]
+1

**Comment by bmah888** [comment]
I believe this was solved by pull request #446.  Keeping this issue open to note that that code change needs to be merged.

**Comment by bmah888** [comment]
#446 merged to 3.1-STABLE.  Closing.

**Comment by JayanthRR** [comment]
Does version 3.2 have this merge? I am facing a similar problem. When the client is not connected to the internet, I closed the client and reopened it after the internet connection is available. I receive an error saying that the server was busy doing another test.

**Comment by bmah888** [comment]
Yes 3.2 has that fix.
