### ISSUE TITLE
upload and download tests

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#379]
I use iPerf to do an upload and download test (reverse direction mode).

Is it acceptable to run then both at the same time from the same client (using a different sever and client) or would that affect the results for both.

**Comment by AzerTyQsdF** [comment]
If the sum of the Upload / Download bandwidth is greater than the bandwidth your hardware can support, it will affect your results.

**Comment by mpitt** [comment]
This depends on many factors. For example, if you're testing over Wi-Fi it will affect the results for sure, because on the shared wireless medium you can only send or receive at any given time.

**Comment by bmah888** [comment]
I think this question has been reasonably answered.  Closing.
