### ISSUE TITLE
iPerf3 is using more than one vCPU while running in virtual machine

### ISSUE THREAD

**Issue by arslanekhan** [esnet/iperf#385]
I am running iPerf3 between two virtual machines. I noticed that iPerf3 is using the 2nd core as well but from design it should only utilize a single core in a virtual machine. Why the utilization by iPerf3 is exceeding one core and utilizing the 2nd core as well? 

I am using OpenStack and Centos 7 image for virtual machines.

**Comment by bmah888** [comment]
My guess (without having actually seen your test situation first-hand) is that iperf3 is using one core and perhaps the kernel's protocol processing is using (part of?) another core.  You could try playing around with the ```-A``` option to set the process CPU affinity but I'm not sure if that would mitigate the issue you're seeing.

**Comment by arslanekhan** [comment]
Actually, I have two cores in my virtual machine. When i run iperf3 then one core shows more CPU utilization but at the same time the other core is also being used upto 8 to 10% as compare to the main core which is using around 70% or sometimes 100%. 

So what could be the main reason of this multi-core CPU utilization? 
Please have a look at these two links.

![multicpu_system0](https://cloud.githubusercontent.com/assets/9864812/14055081/fb7a4eaa-f2de-11e5-90e2-0f36662d4c01.png)
![multicpu_system1](https://cloud.githubusercontent.com/assets/9864812/14055082/fb7bbfec-f2de-11e5-8d14-6c1c383cb4a2.png)

**Comment by bmah888** [comment]
The question here is more of a general question of virtual machines, not specific to iperf3.  Closing.
