### ISSUE TITLE
Send packet's with diferent size

### ISSUE THREAD

**Issue by jpgpedrosa** [esnet/iperf#387]
Would like to know what the option to send packets with different sizes (1000Kb, 1500KB, 2000Kb).
I'm undecided between the -l option (--lengthn [KM]) and -M (--set-mss n).
I'm using version 3.1.2 of iperf with Ubuntu 14.04.1.
Thanks for any help.

**Comment by bmah888** [comment]
`-l` is the size of data blocks that iperf3 tries to send at once.  The networking stack could fragment that into packets of different sizes.  If it's a TCP test, TCP could break the send up into smaller TCP segments according to the `-M` parameter.  If it's a UDP test, UDP won't do any fragmentation, but the IP layer can fragment large UDP datagrams into IP packets that can be sent on the underlying network.

Note that a 1000Kb packet (one of the sizes you mentioned) is a million bytes.  No physical packet will handle a network packet of that size (IPv4 and IPv6 networks have a limit of 64KB, or 65536 bytes, minus protocol overheads).
