### ISSUE TITLE
server crash in unit_snprintf

### ISSUE THREAD

**Issue by yanavlasov** [esnet/iperf#388]
iperf3 server may crash if it ends up with 0 duration interval at the end of the test. The 0 duration interval can occur if the server and client have small skew in intervals. The server may start new interval and then immediately receive TEST_END.
When this happens the bandwidth is NaN and the unit_snprintf crashes with invalid index in label_bit (or label_byte).
Suggested fix is to skip printing intervals with 0 duration.

**Comment by yanavlasov** [comment]
I'm testing a fix for the issue and will submit pull request shortly.

**Comment by bmah888** [comment]
Merged to 3.1-STABLE in 4a9d74f.
