### ISSUE TITLE
iperf3 does not work for a duration above 24h

### ISSUE THREAD

**Issue by Gryffoon** [esnet/iperf#392]
iperf3 does not work for a duration above 24h, and this is quite annoying

**Comment by bmah888** [comment]
In order for anyone to help yoiu, you'll need to provide more specific information than "does not work".  What happens and how does that differ from what you expected?

**Comment by Gryffoon** [comment]
When running a test UDP above 24h with -t option, it prints an error which indicate that iperf3 thoes not work above 24h

**Comment by Yakkity** [comment]
See https://github.com/esnet/iperf/issues/166   
Changing the constant to a much larger value and rebuilding should work.

**Comment by bmah888** [comment]
This is a duplicate of #166, closing.
