### ISSUE TITLE
iperf3 with ssh issue

### ISSUE THREAD

**Issue by Gryffoon** [esnet/iperf#393]
the iperf3 server opened via ssh/sshpass does not work correctly, the refreshing time is too slow, and when the test has ended it doeasn't write the result. 

However with iperf2 it works normally

**Comment by Gryffoon** [comment]
I forgot to mention that I used ssh trought gnome-terminal

**Comment by bmah888** [comment]
A lot of people have run iperf3 server processes through SSH sessions without incident.  I think for anyone to help you, they're going to require some more information, in particular what exact behavior are you experiencing and what do you expect to be seeing?

**Comment by bmah888** [comment]
Closing due to lack of response.  Could be the same as #535.
