### ISSUE TITLE
retransmission totals not in json output

### ISSUE THREAD

**Issue by mroe1234** [esnet/iperf#394]
Is it possible the retransmission totals are not being included in the json server output?  I see the totals the summary:

[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  10.8 GBytes  9.30 Gbits/sec  1245             sender
[  4]   0.00-10.00  sec  10.8 GBytes  9.30 Gbits/sec                  receiver

but I don't see any mention of 'Retr' or 'Retransmissions in the JSON.

**Comment by bltierney** [comment]
seems to work for me. Are you sure?

**Comment by bmah888** [comment]
For each measurement interval and stream there is a "retransmits" member in the JSON structure, as well as roll-ups of these across all streams in an interval and across the entire test.  As far as I know this is all working.  Verified with tip-of-master code on CentOS 7.  Closing this bug.
