### ISSUE TITLE
Poor throughput in reverse mode

### ISSUE THREAD

**Issue by luicson** [esnet/iperf#397]
Hello,

while making some tests, i found that when pushing the traffic from the server to the client (regular way), I am getting the expected throughput but when I run try to receive traffic on the client side from the server ( option -R) the throughput is really low (1 mbps vs 100 mbps). I have been running wireshark on the server side and looks like the application (iperf) is not moving data to the TCP/IP stack so it is not sent (there is  no a RWIN problem, there is lot of room ).

Does this happen to anyone else? is it a known issue? I couldnt find any topic related to this.

thanks in advance.

Regards,

Luis

**Comment by bltierney** [comment]
likely a problem with your network or host.
