### ISSUE TITLE
iperf3 default window size (-w not set)

### ISSUE THREAD

**Issue by pecigonzalo** [esnet/iperf#399]
Hi, i cant seem to find information on whats the default window size. Old iperf used to display this when starting the transfer, it would be great to do something similar, or at least put it in the documentation somewhere (if this is already the case, please link me to it, as i could not find it)

Im currently testing a scenario where im rate limiting using tc qdiscs on a pseudo router, if i set the -w parameters to small amount (eg: 5K) i get:

```
WWW (running iperf -Vs)
1 Mbit/s
|
1 Mbit/s
ROUTER (Rated at 1 Mbit/s with traffic conditioner)
1 Mbit/s
|
LAPTOP (running iperf3 -c WWW -V)
```

If i dont set it, or set it really high (-w 12313123) i get:

```
WWW (running iperf -Vs)
1 Mbit/s
|
1.5 Mbit/s
ROUTER (Rated at 1 Mbit/s with traffic conditioner)
1 Mbit/s
|
LAPTOP (running iperf3 -c WWW -V)
```

**Comment by bltierney** [comment]
you should now see this if you use the debug flag.

**Comment by bmah888** [comment]
Follow-up:  Use the ``--debug`` flag on (about) iperf-3.1.5 or newer.

**Comment by pecigonzalo** [comment]
Thanks a lot, this is great!

**Comment by pradeepspa2** [comment]
Hi, I would like to see the default window size but running "--debug" flag doesnt work for me.Any advice on this one please?

` iperf3 -c server -l1300 -b100M -V --debug
iperf 3.1.7
Linux testvm 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64
Control connection MSS 1448
send_parameters:
{
        "tcp":  true,
        "omit": 0,
        "time": 10,
        "parallel":     1,
        "len":  1300,
        "bandwidth":    100000000,
        "client_version":       "3.1.7"
}
Time: Wed, 18 Sep 2019 19:41:11 GMT
Connecting to host server, port 5201
      Cookie: testvm.1568835671.399
      TCP MSS: 1448 (default)
SNDBUF is 16384, expecting 0
RCVBUF is 87380, expecting 0
Setting application pacing to 12500000
Congestion algorithm is cubic
[  4] local client port 39676 connected to server port 5201
Starting Test: protocol: TCP, 1 streams, 1300 byte blocks, omitting 0 seconds, 10 second test
tcpi_snd_cwnd 58 tcpi_snd_mss 1448 tcpi_rtt 170
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  10.8 MBytes  90.3 Mbits/sec    1   82.0 KBytes
tcpi_snd_cwnd 67 tcpi_snd_mss 1448 tcpi_rtt 168
[  4]   1.00-2.00   sec  11.9 MBytes   100 Mbits/sec    1   94.7 KBytes
tcpi_snd_cwnd 77 tcpi_snd_mss 1448 tcpi_rtt 427
[  4]   2.00-3.00   sec  11.9 MBytes   100 Mbits/sec    0    109 KBytes
tcpi_snd_cwnd 72 tcpi_snd_mss 1448 tcpi_rtt 168
[  4]   3.00-4.00   sec  11.9 MBytes   100 Mbits/sec    1    102 KBytes
tcpi_snd_cwnd 86 tcpi_snd_mss 1448 tcpi_rtt 460
[  4]   4.00-5.00   sec  11.9 MBytes   100 Mbits/sec    0    122 KBytes
tcpi_snd_cwnd 88 tcpi_snd_mss 1448 tcpi_rtt 142
[  4]   5.00-6.00   sec  11.9 MBytes   100 Mbits/sec    0    124 KBytes
tcpi_snd_cwnd 91 tcpi_snd_mss 1448 tcpi_rtt 442
[  4]   6.00-7.00   sec  11.9 MBytes   100 Mbits/sec    0    129 KBytes
tcpi_snd_cwnd 91 tcpi_snd_mss 1448 tcpi_rtt 449
[  4]   7.00-8.00   sec  11.9 MBytes   100 Mbits/sec    0    129 KBytes
tcpi_snd_cwnd 92 tcpi_snd_mss 1448 tcpi_rtt 453
[  4]   8.00-9.00   sec  11.9 MBytes   100 Mbits/sec    0    130 KBytes
tcpi_snd_cwnd 95 tcpi_snd_mss 1448 tcpi_rtt 151
send_results
{
        "cpu_util_total":       2.976008,
        "cpu_util_user":        0.696217,
        "cpu_util_system":      2.326078,
        "sender_has_retransmits":       1,
        "congestion_used":      "cubic",
        "streams":      [{
                        "id":   1,
                        "bytes":        123784700,
                        "retransmits":  3,
                        "jitter":       0,
                        "errors":       0,
                        "packets":      0
                }]
}
get_results
{
        "cpu_util_total":       2.529133,
        "cpu_util_user":        0.178438,
        "cpu_util_system":      2.392474,
        "sender_has_retransmits":       -1,
        "congestion_used":      "cubic",
        "streams":      [{
                        "id":   1,
                        "bytes":        123784700,
                        "retransmits":  -1,
                        "jitter":       0,
                        "errors":       0,
                        "packets":      0
                }]
}
[  4]   9.00-10.00  sec  11.9 MBytes   100 Mbits/sec    0    134 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec   118 MBytes  99.0 Mbits/sec    3             sender
[  4]   0.00-10.00  sec   118 MBytes  99.0 Mbits/sec                  receiver
CPU Utilization: local/sender 3.0% (0.7%u/2.3%s), remote/receiver 2.5% (0.2%u/2.4%s)
snd_tcp_congestion cubic
rcv_tcp_congestion cubic

iperf Done.`
