### ISSUE TITLE
does iperf use DRAM on OTT when measuring?

### ISSUE THREAD

**Issue by elion83** [esnet/iperf#400]
My name is elion83, electrical engineer.
I have a question about iperf.

When measuring the maximum bandwidth of IP network using iperf with OTT(Over-the-top, like Chrome cast), does iperf use DRAM for writing or reading the data?

**Comment by bmah888** [comment]
I'm not sure how to answer this, particularly such the Chromecast isn't a supported platform (at least not by ESnet).  iperf3 does memory access for read and writing data, but that could be DRAM or cache.  It doesn't do any disk I/O unless the `-F` option is used.
