### ISSUE TITLE
How to calculate interval time between packets in iperf3? [Question]

### ISSUE THREAD

**Issue by taitan7411** [esnet/iperf#401]
Dear 
iperf3 -c <ip_addr> -u -b 5m
iperf3 will create a constant bit rate UDP stream? it will send the packets without pausing? So , How can calculate interval between packets?

I appreciate your help

**Comment by bmah888** [comment]
With those parameters, iperf3 will send at roughly 5Mbps, but the way pacing is implemented now it's fairly bursty.  If you want a "more constant" rate of packets, consider running on a relatively recent Linux that supports a fair-queueing packet queueing discipline and use the `--fq-rate` option to iperf3.
