### ISSUE TITLE
unable to receive parameters from client

### ISSUE THREAD

**Issue by FernandoMiguel** [esnet/iperf#407]
when running iperf3 -s -p 8080 on ubuntu 16.04 (packages from both repo and official site binaries)
we are getting an error stating 
iperf3: error - unable to receive parameters from client: Cannot allocate memory.

when trying other ports seems to work fine.
this machine had squid listening on port 8080 before, but the service was stop, and netstat doesnt show anything listening there.

**Comment by bmah888** [comment]
Try another port?  Is some process on another host sending to your now-ex-squid process?

It really sounds like the iperf3 server is receiving some data on its control connection that it isn't expecting.

**Comment by bmah888** [comment]
No further activity on this issue/question, closing.
