### ISSUE TITLE
Server requires reset after connection drop

### ISSUE THREAD

**Issue by serg3y** [esnet/iperf#416]
If the PC drops the wifi connection the server keeps trying to listen, while client gives up after ~10 sec. When wifi is reconnected and client is restarted, client gets an error: **"iperf3: error - the server is busy running a test. try again later"** because the server is still trying to reestablish the previous connection, and keeps trying forever.

Server: iperf3 -s
Client: iperf3 -c HOSTNAME -t 3000

Solution is to reset of the server, but when I am 500 m away on the client side trying to map out the perimeter of the WiFi range, then I have a week loooooong marathon ahead of me.

**Comment by rpodgorny** [comment]
this happens to me all time. :-( ...can we just add a timeout on the server side or something...?

**Comment by kaebmoo** [comment]
It's happen to me too. when client unexpected terminate such as power down while testing speed. the server still try to send/receive to client and infinite loop.

**Comment by bmah888** [comment]
On the server side, TCP should time the connection out if the client disappears.  Are you saying this is too long for you?  Or does this timeout never happen?

What platform are on the client and server?

**Comment by bmah888** [comment]
This is basically the same (I think) as #225, for which there's an outstanding pull request.  Going to close this as a duplicate.
