### ISSUE TITLE
Time stamps with system clock would be useful.

### ISSUE THREAD

**Issue by serg3y** [esnet/iperf#418]
It would be great if iperf could display & log computer system time with each update.

Say I want to map out quality of a wifi outdoors. I have gps and I am logging time and position. I start iperf and log results to file, BUT the time stamps are elapsed time relative to start of iperf so fussing gps and iperf logs is not possible unless mark exactly when I started iperf, and considering that it will be dropping out and need frequent restarts it a big pain.

The workaround is to make a .bat file and print the start time to the logfile, and add this time to the elapsed time afterwoods.
_echo %time% > client.log
iperf3 -c HOSTNAME -t 3000 --logfile client.log_

client.log = 
 _4:41:00.59 
...
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.01   sec   441 KBytes  3.56 Mbits/sec  
..._

But still this is crude, it would be better if iperf could display/log computer time.

**Comment by bam80** [comment]
+1. Also, something like Session ID would be useful

**Comment by bam80** [comment]
It's all seems have been implemented already - just use -V option:
```
$ iperf3 -sV
iperf 3.0.11
Linux sml-pc-066 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Time: Mon, 15 Aug 2016 18:23:24 GMT
Accepted connection from 10.65.7.161, port 55568
      Cookie: sml723x-e42771ae1654-0_0_0.147128540
      TCP MSS: 1448 (default)
[  5] local 10.65.5.80 port 5201 connected to 10.65.7.161 port 59912
Starting Test: protocol: TCP, 1 streams, 131072 byte blocks, omitting 0 seconds, 10 second test
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec  10.8 MBytes  91.0 Mbits/sec                  
[  5]   1.00-2.00   sec  11.2 MBytes  94.1 Mbits/sec
```
Note that Time: is passed from client - so it can differ from actual time on the server

**Comment by bmah888** [comment]
I never thought of using `-V` while actually running a test.  Glad that works for you!  Closing.
