### ISSUE TITLE
 UWP iperf3 3.1.1.5.0 source download

### ISSUE THREAD

**Issue by pjhoshall** [esnet/iperf#420]
UWP iperf3 3,1,1,5,0 source download  --  version.h #define IPERF_VERSION "2.0.5p27 Safety mode Natsuki-chan"

**Comment by bmah888** [comment]
I'm not sure what this is.

**Comment by pjhoshall** [comment]
I downloaded UWP iperf3 3.1.1.5.0 source download – but the version isn’t 3.1.1.5.0

It is in version.h as #define IPERF_VERSION "2.0.5p27 Safety mode Natsuki-chan"
