### ISSUE TITLE
Where can I find the MSVC 2015 project/source for iperf3 3.1.2 Win 64?

### ISSUE THREAD

**Issue by pjhoshall** [esnet/iperf#421]

**Comment by bmah888** [comment]
Windows is not an officially supported platform for iperf3; I'm not even sure if the stock sources will compile on Windows.  If you search around on the net, you might be able to find something.

**Comment by pjhoshall** [comment]
https://iperf.fr/iperf-download.php has tons of Windows iperf versions...

Wrong site?
