### ISSUE TITLE
'--cport' does not work well in udp packet case <bug>

### ISSUE THREAD

**Issue by Nimdrak** [esnet/iperf#422]
By using wireshark,
I find that udp packet generated by iperf3 do not have specified port number.

I use below command
iperf3 -s -p 12000

iperf3 -c 192.0.0.120 -p 12000 -u B 192.0.0.110 --cport 11000

If I delete command '-u'
iperf3 mode changes to TCP mode.
In this case, I find that tcp packet generated by iperf3 have specified port number by using wireshark

**Comment by acanad** [comment]
works on 3.1.4:
iperf3 -c server -t 30 -i 5  --get-server-output -u  --bind 192.168.200.65 --cport 5000 
Connecting to host n.n.n.n, port 5201
[  4] local 192.168.200.65 port 50000 connected to n.n.n.n port 5201

**Comment by Nimdrak** [comment]
Thank you so much!
