### ISSUE TITLE
IPERF sending LDAP requests when starting the client

### ISSUE THREAD

**Issue by IbTornoe** [esnet/iperf#426]
When starting the client on a Windows machine it looks like that it everytime it starts up it connects to a Domain Controller to figure out what controles etc the AD supports. Why is this happening and can it be disabled?

**Comment by bmah888** [comment]
No idea.  You might ask whomever provided the Windows executable for...this project only distributes source code (and doesn't explicitly support Windows as a platform).  Perhaps contacting the AD controller is a basic part of process startup on Windows?

**Comment by bmah888** [comment]
I'm going to close this, it's not really an iperf3 problem.
