### ISSUE TITLE
Add a systemd unit

### ISSUE THREAD

**Issue by wooptoo** [esnet/iperf#430]
A systemd unit for iperf would be very useful for those cases when you want a long-running iperf instance.
I'm running the following unit on my NAS:

```
[Unit]
Description=iperf3 server
After=syslog.target network.target auditd.service

[Service]
User=iperf
ExecStart=/usr/bin/iperf3 -s --logfile /var/log/iperf.log

[Install]
WantedBy=multi-user.target
```

**Comment by rpodgorny** [comment]
https://github.com/esnet/iperf/pull/340

**Comment by bmah888** [comment]
@rpodgorny:  Thanks for linking up #340 and #430.

Not being much of an expert on systemd myself, would it possible for the authors of the two versions of the systemd unit file to reconcile the two into something that I could merge?  The one piece of feedback I have is that I like the `--logfile` parameter in #430.

**Comment by wooptoo** [comment]
I think `After=network.target` should suffice in the `[Unit]` section.
iperf doesn't need the whole network up (with routing) as per issue #340, it just needs to bind to 0.0.0.0

So the final unit file could be:

    [Unit]
    Description=iperf3 server
    After=network.target

    [Service]
    User=iperf
    ExecStart=/usr/bin/iperf3 -s --logfile /var/log/iperf.log

    [Install]
    WantedBy=multi-user.target

**Comment by bmah888** [comment]
OK, it sounds like we're getting somewhere.

One thing I just noticed:  Here in #430 there's a `User=` definition.  I guess this presumes that there's an `iperf` user on the system?

Conversely, #340 doesn't define `User=` in the `[Service]` section.  What happens there, does it run as `root`?

Giving a poke to @sspreitzer, author of #340.  (In case he didn't see any of the discussion in this issue.)

**Comment by rpodgorny** [comment]
well, according to the systemd's best practices, one should use the journal for logging (so no explicit log file which is then subject to rotation etc...). also, there should be a Restart=on-failure according to https://www.freedesktop.org/software/systemd/man/systemd.service.html

...if there's no update in few days, i'll create a pull request with the mentioned changes.

**Comment by rpodgorny** [comment]
oh, i missed the questions: yup, if user is not specified, systemd defaults to root. usually, that's a default for most distros but individual maintainers are free to change that according to their policies...

**Comment by wooptoo** [comment]
Yes, the `User=` directive does exactly that. I run iperf under its own user since it's a common practice for internet facing services.

As for the log option, IMHO we should *not* log into the system log, since iperf is quite verbose.

**Comment by bmah888** [comment]
Any suggestions what to do on this?  I'm still hoping that those of you-all who are knowledgeable about systemd will be able to converge on something that I can commit.

**Comment by helmo** [comment]
There is a pretty good howto written specifically for iperf ... https://scottlinux.com/2014/12/08/how-to-create-a-systemd-service-in-linux-centos-7/

The only extra property that example adds is 'Type=simple' ... which is the default.

The only personal suggestion I would like to add it to use the '--server' option instead of '-s' ... more obvious and self documenting.

**Comment by rpodgorny** [comment]
not that good, i'm afraid... :-(

1) type=simple is the default - no need to specify it
2) user=iperf - this is what individual distros should decide
3) restart=on-abort is not a recommended practice (see my past post)
...i agree with being verbose for the command arguments, thou.

so, http://pastebin.com/YymALuZM is what i recommend.

**Comment by bmah888** [comment]
I'm going to merge pull request #340 and then put the contents of the pastebin on top of that.

**Comment by bmah888** [comment]
All done.
