### ISSUE TITLE
Server sends [RST,ACK] but client continues to send data

### ISSUE THREAD

**Issue by morphyno** [esnet/iperf#431]
I'm noticing this even on a simplest cases of 1 to 1 iperf TCP tests. 

I'm running iperf3 cloned from github roughly a year ago. Here, two clients are running a short session of iperf, their connection is tapped to another port and captured to pcap. 

I notice there's always [RST] and [RST,ACK] from the server during an iperf. After the [RST,ACK], the client continues to send more data until the connections are torn down. That can be observed in pcap below:

![image](https://cloud.githubusercontent.com/assets/3343500/15756992/79ce5774-28b8-11e6-8027-8adf76f363d8.png)

I was under an impression that after [RST,ACK], the client should either stop sending data or initiate a new connection. I'm curious the reason behind this behavior.

**Comment by morphyno** [comment]
Github doesn't allow me to upload the pcap, even in the zip format.

**Comment by paweltopczewski** [comment]
Hi,

Just wanted to ask of You received any clarification if this situation with [RST,ACK] flags is OK(as designed) or NOT OK(bug).

PT

**Comment by bmah888** [comment]
In a "normal" TCP test there are two TCP connections; one is a control channel connection that's used to coordinate the starting and stopping of the test and the other is the actual connection over which the test is run.  The lifetime of these two connections is independent.

That having been said, the control connection isn't supposed to be closed until after the data transfer is done.  It's not clear to me which of the two connection is being reset.

What OSs are running on the client and server?

**Comment by bmah888** [comment]
Closing due to lack of response.  Note also that there are two separate TCP connections in play here.
