### ISSUE TITLE
Bottleneck and latest download

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#432]
@bmah888 

**Q1** In order to make a multi-client iperf3 server, I am using Docker to run an individual iperf3 server in a individual container.
What is going to be the bottleneck in terms of how many clients I can serve simultaneously and give accurate reading to **all** clients?
Is it CPU-bound, memory bound, number of ports available bound, number of connections available bound?

**Q2** I can see that a lot of work and improvements keep going into github repo all the time. How often does https://iperf.fr/iperf-download.php#ubuntu get update to _**latest**_ version?

**Comment by pjebs** [comment]
@bmah888 any ideas? I assumed you would be best person to know answers.

**Comment by pjebs** [comment]
@bmah888

**Comment by pjebs** [comment]
@bmah888 any ideas? I assumed you would be best person to know answers.

**Comment by bmah888** [comment]
A1:  I don't think you'll be limited by the number of ports or number of connections.  As for CPU or memory, that depends quite a lot on the workload (e.g. how much throughput will an individual client's connections be generating or consuming?  how many clients do you expect to serve?).  Note that iperf3 was designed for measuring throughput in high-performance R&E environments, where the throughput of a single flow on a path is important.

A2:  ESnet doesn't provide binaries, only source code.  I think you'd have to ask whomever is responsible for making Ubuntu packages to know the answer to that.
