### ISSUE TITLE
--cport does not work

### ISSUE THREAD

**Issue by ItayBenL** [esnet/iperf#437]
Hi,

I'm using iPerf version 3.1.3.
Wireshark approves that the --cport feature does not work. it seems that the code "ignores" the input argument followed by "--cport" and a source port is selected randomly.
To emphasize my claim, after running this deliberately erroneous command: **iperf3 -c 192.168.1.3 -p 12000  --bind 192.168.1.4 --cport fdfdf**, no error message was printed and the client sent a TCP packet with a random source port.

Is there any plan to fix this bug? the feature is very important to some users.

Thanks,
Itay.

**Comment by h3ct0r** [comment]
Hi, @ItayBenL did you resolve this issue?

**Comment by anuradhapriyankara** [comment]
I have the same issue. What was the solution?
