### ISSUE TITLE
failing to redirect iperf3 command output to a file.

### ISSUE THREAD

**Issue by sdandge** [esnet/iperf#438]
version: '3.0.1' 
server command: 
iperf3 -s 192.168.70.1 -p 5001 -i 2 >  server_file.txt &
client command:
iperf3 -c 192.168.70.1 -B 192.168.70.13 -p 5001 -i 2 -t 300 > client_file.txt &

Description:
- Not able to get output of these iperf3 commands to mentioned files.
- I tried various options[such as 2>&1, tee -a etc] for redirecting output but still not working.
  Note:
- same commands were working few days back with same iperf package.
- with iperf2 commands i am able to redirect output with above fashion.

**Comment by bmah888** [comment]
Try using the `--logfile` option.  This option might require iperf 3.1 or later.
