### ISSUE TITLE
iperf3 dies with "Too Many Errors" due to non-iperf connections

### ISSUE THREAD

**Issue by cpuwhiz22** [esnet/iperf#445]
Hello Team,

I am not sure if this should be classified as a bug or not but I figured I would start here.  We are trying to use iperf3 for public bandwidth testing.  The issue I am seeing presently is that we are monitoring the service availability via a simple TCP check to the port it runs on, and I see the following in the output:

...

Server listening on 6001
-----------------------------------------------------------
iperf3: error - unable to receive parameters from client:

-----------------------------------------------------------
Server listening on 6001
-----------------------------------------------------------
iperf3: error - unable to receive parameters from client:

-----------------------------------------------------------
Server listening on 6001
-----------------------------------------------------------
iperf3: error - unable to receive parameters from client:

too many errors, exiting

It appears that it doesn't handle non-iperf connections very gracefully.  This is a problem because we need to monitor it to ensure it's available with a TCP check, and additionally, this will be running publically on TCP port 443 so there is a good chance that web crawlers will hit this with HTTP requests.

With this said, what can be done to either turn off the "too many error, exiting" behavior so the application does not shut down as a result of non-iperf connections, or allow it to handle these scenarios more gracefully?

**Comment by bmah888** [comment]
If you're running iperf 3.1.3 or newer, it should this condition more gracefully, in particular not exiting when it gets hit with a bunch of non-iperf3 connections on its control socket.  The set of conditions on which an iperf3 server process will actually exit is greatly restricted compared to earlier versions.

**Comment by cpuwhiz22** [comment]
Sounds good.  I'll check which release I'm running and report back if I
have issues.

**Comment by cpuwhiz22** [comment]
I have installed 3.1.3 and so far things are looking better.  Thanks!

**Comment by bmah888** [comment]
Glad it's working...thanks for the follow-up!
