### ISSUE TITLE
--bind option doesn't accept interface name

### ISSUE THREAD

**Issue by bam80** [esnet/iperf#450]
It's more like a feature request, because now I have to write tricky scripts to get IP address of the interface, instead of just passing it by name in the -B option

**Comment by bmah888** [comment]
We note this is a little tricky because an interface can have multiple IPv4/IPv6 addresses and picking the right one might be hard.

**Comment by hoang-tranviet** [comment]
This at least requires getting protocol family from specified server (-c). Maybe I did it already in my local branch...

**Comment by bam80** [comment]
Can this feature be implemented at least for the case when an interface has only one IP address? It is far more convenient and straightforward to specify interface by name

**Comment by bmah888** [comment]
This is not likely to happen for reasons I cited above, but #1089 and #1097 are somewhat related to this.
