### ISSUE TITLE
Stuck at "connected to" (High Load UDP Traffic)

### ISSUE THREAD

**Issue by jrmfreitas88** [esnet/iperf#452]
Hello,

I have noticed that sometimes when generating more downstream UDP traffic (e.g.: 1 Gbps) than the receiving link can handle (e.g.: 100 Mbps) iperf3 gets stuck at "connected to" as depicted on the picture bellow.

![01 - stuck_connected](https://cloud.githubusercontent.com/assets/15096532/17895307/9d81f03c-6944-11e6-8039-f251930adc73.png)

Sometimes it stays there forever, and the work-around consists on stopping and restarting the test. Other times it unstucks itself after about 10-20 seconds reporting the expected value but, with a different packet loss at the first seconds when comparing to the following time intervals:
- Case 1 - Faulty Scenario (Stuck at connected to for a couple of seconds)

![02 - stuck_finish](https://cloud.githubusercontent.com/assets/15096532/17895311/9fbe2320-6944-11e6-8d72-c890dfa9232c.png)
- Case 2 - Working Scenario (Test started right away)

![03 - ok](https://cloud.githubusercontent.com/assets/15096532/17895461/11476e98-6945-11e6-82c3-7e29cf65ffb7.png)
- Network Topology:

![scenario](https://cloud.githubusercontent.com/assets/15096532/17895278/7e83cb42-6944-11e6-8b6c-6b3eef706b44.png)

In aid of understanding the root cause of this issue I have inspected the network traffic (at the client side) and found out that iPerf3 Client only moves from the "connect to" state to start presenting the time intervals after it receives a TCP Packet from the server containing the following payload "0102" as depicted on the picture bellow (which in this case took 15 seconds):

![delayed_packet](https://cloud.githubusercontent.com/assets/15096532/17895915/8adde45c-6946-11e6-982d-ef9540a98f00.png)

I have also collected a network trace at the server side and found out that because the server starts generating the UDP Traffic before it sends the TCP Packet. As a result because there is less available bandwidth at the client side the packet gets discarded along the way and iperf3 Client only unstucks itself if it is lucky enough to receive a TCP Retransmission which, due to the "TCP Exponential Back-off Algorithm" may take forever.
- TCP Retransmissions

![tcp_retry - copy](https://cloud.githubusercontent.com/assets/15096532/17898928/74c9c234-6951-11e6-8f6b-77c648efac87.png)

Please also note that packet 11 (highlighted in red) was the last packet before UDP traffic and the "TCP Packet" (highlighted in green) only shows up at frame 15958, which means that a total of 15946 UDP packets were sent before the "start" signalisation.

Is anyone else struggling with the same issue? Have you considered only generating the traffic after this packet is sent?

Kind regards,

João

**Comment by bltierney** [comment]
have you tried iperf2.0.8? It has better windows support.

**Comment by bmah888** [comment]
Closing this...iperf2 is likely to be able to handle this scenario better.
