### ISSUE TITLE
stdout not flushed after each reporting interval

### ISSUE THREAD

**Issue by khutchings85** [esnet/iperf#458]
I am consuming the standard output using C# in order to create a graphical front end with reported results during the test (similar to speedtest).  The standard output is being buffered such that the results are not available until the process has finished and the standard output is flushed.

This is not an issue in iPerf2, fflush( stdout ) is called after each printed line.

Possible fixes include calling fflush at the end of print_interval_results, or enabling forceflush as an optional parameter to allow the code to call iflush at the end of print_interval_results.

**Comment by khutchings85** [comment]
I'd be happy to implement the fix myself and contribute it.

**Comment by bmah888** [comment]
If you're up for it, you could send a pull request and cross-reference this issue.

**Comment by khutchings85** [comment]
It looks like this was addressed in fix #377, but is not yet available in version 3.1.3.  Will this be released with 3.1.4?

**Comment by bmah888** [comment]
It wasn't in 3.1.4.  That fix only exists on the mainline (which is why it has a "3.2" milestone).  That having been said I might need to do a 3.1.5 soon-ish to fix a problem introduced in 3.1.3.

Do you have the ability to compile and run the tip of the mainline code, to see if that code change indeed works for your application?

**Comment by khutchings85** [comment]
Yes actually, after compiling with the latest code I can verify that stdout is indeed being flushed after each line. It works perfectly for my application.

**Comment by bmah888** [comment]
OK, thanks for checking.  Let me mark #377 for 3.1.x so I remember (hopefully) to merge it before I do another build.

**Comment by bmah888** [comment]
Merged in 72ab703.  Closing this issue.
