### ISSUE TITLE
Memory overflow on long runtimes

### ISSUE THREAD

**Issue by WolleTD** [esnet/iperf#462]
I am using iperf3 to test switches in my company. To do this, iperf3 needs to run for days and weeks on several embedded devices running ucLinux Kernel 2.6.28. So I compiled iperf 3.1 against the blackfin toolchain.

At first, everything seemed to work well and basically, it does what I want it to do. When the test stopped the second time after several days, I realized that both client and server processes on the ucLinux devices fill up the memory to the point where the Out of Memory killer terminates either or both.
This is reproducable and seems to always happen after the same runtime on all twelve devices.

I'll try to be able to monitor the setup during the weekend, as it should run into trouble again before monday, from what I've experienced. I'll try to get more accurate runtimes and also I'll keep iperf3 running on the RPi (even if it's Kernel 4.4.14) in the system to look for similar issues.

Command lines are:
iperf3 -u -c $ADDR -i 1 -t 0
iperf3 -s -B $LISTEN_ADDR

Also, [here](https://gist.github.com/WolleTD/fb4f591a68248691442b01ae77cdeb73) the dmesg log of two OOM kills. I'm unable to reconstruct this exactly as the ucLinux dmesg has no timestamps. From how the OOM killer works, I would assume these are two different times where one of the iperf3 processes got killed. But concluding from the preceding dmesg information, these are logs from only one test run and therefore it shows both the client and the server being killed.

**Comment by bmah888** [comment]
iperf3 wasn't really designed to handle this use case.  It keeps a linked list of test intervals, and steadily accumulates data until the end of the test, when it writes everything out.  So an iperf3 process will (slowly?) grow in size until the test is over.  If you're running a really long test on memory-poor hardware, this can cause some issues.

To check this, you could try monitoring the iperf3 process sizes with top or ps while they're running.

To mitigate this problem you could try increasing the measurement / statistics reporting interval with the `-i` option.

**Comment by WolleTD** [comment]
I didn't know the `-i` option affects the behaviour that much. Now trying with a ten second interval. Obviously not a bug, just a bunch of data.

Besides that memory issue, iperf3 makes quite a good job handling this use case.

**Comment by bmah888** [comment]
Closing this issue for now.  It can be reopened later if need be.
