### ISSUE TITLE
iperf3 --logging doesn't provide bandwidth results for udp 

### ISSUE THREAD

**Issue by 6hopsaway** [esnet/iperf#464]
When configuring the iperf3 to run as a server in logging mode and with Verbose mode enabled I am unable to see UDP bandwidth statistics when testing.  When running in Verbose mode only the statistics are displayed.  I am looking for others to confirm this problem.  When testing locally on loopback 127.0.0.1 where client and server are running in two separate terminal windows it seems to log correctly.   server sample below, client sample read 840 mb/s  and a typical output.  This was reproducible on several occasions.

Test 1 UDP “No Phone” - Average 923
Time: Thu, 22 Sep 2016 18:31:31 GMT
Accepted connection from 10.103.97.246, port 64858
      Cookie: CDE0166323.1474569091.421853.09946fe
[  6] local 10.103.141.96 port 5201 connected to 10.103.97.246 port 49746
Starting Test: protocol: UDP, 1 streams, 8192 byte blocks, omitting 0 seconds, 10 second test
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  6]   0.00-1.00   sec  8.00 KBytes  65.5 Kbits/sec  0.322 ms  0/1 (0%)  
[  6]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  
[  6]  10.00-10.19  sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/0 (0%)  

---

Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  6]   0.00-10.19  sec  0.00 Bytes  0.00 bits/sec  0.322 ms  0/1 (0%)  
CPU Utilization: local/receiver 0.0% (0.0%u/0.0%s), remote/sender 0.0% (0.0%u/0.0%s)

**Comment by bltierney** [comment]
does adding the  --forceflush flag fix this for you?

**Comment by bltierney** [comment]
no reply, so closing.

**Comment by bmah888** [comment]
This didn't really get closed as per the last comment so I'm really closing it.

Also it looks like data isn't really getting from the client to the server, which would indicate a network problem not an iperf3 problems.
