### ISSUE TITLE
iperf3.1.3 incorrect out of order packets reported in json

### ISSUE THREAD

**Issue by singn** [esnet/iperf#469]
Running iperf 3.1.3 on Ubuntu 14.04 to test udp bandwidth with defined packet size. The out of order packets can be seen on the server side as non-zero. When json output on client side is observed it always shows zero '0' in section end->streams->out_of_order. This seems not reporting the correct out of order packets on the client side.

**Comment by bltierney** [comment]
can you see if this is fixed in 3.1.6 or later?

**Comment by bltierney** [comment]
closing do to lack of response.
