### ISSUE TITLE
iperf rate change

### ISSUE THREAD

**Issue by akosenkov** [esnet/iperf#471]
Hello guys,

I'm trying to reproduce a trace of bandwidth with iperf.
I do that by switching iperf_reporter_callback - there I call iperf_reset_stats and setting t->settings->rate to whatever the current point in time rate should be.

But the actual bandwidth is way off for some reason...

Thank you,
Alex

**Comment by akosenkov** [comment]
Ok, solved by resetting metrics after changing the rate:

            struct timeval now;
            gettimeofday(&now, NULL);
            SLIST_FOREACH(sp, &t->streams, streams) {
                sp->result->start_time_fixed = sp->result->start_time = now;
                sp->result->bytes_sent = 0;
                sp->result->bytes_sent_omit = 0;
            }

Cheers

**Comment by bmah888** [comment]
Thanks for following up with your solution!
