### ISSUE TITLE
iperf 2.0.5 UDP (MAC Air) 

### ISSUE THREAD

**Issue by BharatNT2IE** [esnet/iperf#473]
Have a Apple OS-X Yosemite.  When i run TCP test on this device over Gig Ethernet Link , the throughput values are as expected 944mbps . However UDP tests on them on not very encouraging, i am only able to attain 644mbps  ? So i increased the number of "streams" to -P4 and the throughput supposedly improved, please correct me if i am wrong -P4 is not locked for TCP stream , it can also be used for UDP streams right ???

**Comment by bmah888** [comment]
This issue tracker is for problems associated with iperf3.  You're running iperf2.  I suggest that you post your question to the iperf-users@lists.sourceforge.net mailing list, where discussion for both iperf2 and iperf3 takes place.
