### ISSUE TITLE
Why do I use iperf3 to test performance data much lower than iperf 

### ISSUE THREAD

**Issue by zjk2752** [esnet/iperf#474]
Need your help ,tks.

In the same test environment for Intel 82599 network card on centos, 
with iperf test network card bandwidth can reach **9.4Gbits / sec**, but 
test bandwidth with **iperf3 card only 5.5Gbits / sec**. Can you tell me 
which parameters of iperf3 tools make network bandwidth achieve the 
highest rate? And what's the differnece had lead the big huge.

versions:
iperf version 2.0.5
iperf3 version version 3.1.3

These are the iperf commands, as follows:
for iperf tools:
server:
iperf -s -B 192.168.90.10
iperf -s -B 192.168.100.10

client:
iperf -c 192.168.90.10 -i 3 -t 3600 -P 3
iperf -c 192.168.100.10 -i 3 -t 3600 -P 3

for iperf3 tools
server:
iperf3 -s -B 192.168.90.10
iperf3 -s -B 192.168.100.10

client:
iperf3 -c 192.168.90.10 -i 3 -t 3600 -P 3
iperf3 -c 192.168.100.10 -i 3 -t 3600 -P 3

Thanks in advance

**Comment by dezenxi** [comment]
Could you show your running log?
I've tried with both iperf and iperf3 as your case.
Bandwidth in iperf is a (little) higher than iperf3.
See my log for details.

Thanks
Duong
[running_log.txt](https://github.com/esnet/iperf/files/574657/running_log.txt)

**Comment by zjk2752** [comment]
@dezenxi 

Really thanks for your replay.

I can show the log,but maybe later, i need rebuild the environment. 
And what's the bandwidth in define of your test card?  I used the intel 82599 card with a 10Gbps bandwidth.

because this problem, i have gave up the iperf3 and installed iperf again to have my Nic card's performance test. It is so sad.

And finally , do you know who i can report or  ask for help about this problem.

**Comment by bmah888** [comment]
Consider experimenting with a larger `--window` size.  Depending on the bandwidth-delay product of the path you are measuring, the TCP window and buffer sizes might be limiting your performance.

**Comment by purumishra** [comment]
iperf3 uses single thread so by just giving multiple stream with -P option it will not help.
To get good throughput using iperf3 run multiple server on different port and in client side run same number of client  and connect to those server ports.
Like if you have started three servers on different port in a single machine then at the client side run one client per port.

**Comment by bltierney** [comment]
added info on this to the iperf3 FAQ, so closing.

See: http://software.es.net/iperf/faq.html
