### ISSUE TITLE
iperf3 3.1.4: server report summary always shows 0.00 Kbits/sec 

### ISSUE THREAD

**Issue by acanad** [esnet/iperf#476]
server output summary shows 0.00Kbits/sec:

iperf3 -c testserver -t 60 -i 10  --get-server-output
.....
[  4]  50.00-60.00  sec  4.61 MBytes  3.87 Mbits/sec   78   15.8 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-60.00  sec  27.1 MBytes  3.79 Mbits/sec  467             sender
[  4]   0.00-60.00  sec  27.0 MBytes  3.77 Mbits/sec                  receiver
.....
Server output:
iperf 3.1.4
.....
[  5]  60.00-60.03  sec  22.4 KBytes  5762 Kbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth
**[  5]   0.00-60.03  sec  0.00 Bytes  0.00 Kbits/sec                  sender**
[  5]   0.00-60.03  sec  27.0 MBytes  3768 Kbits/sec                  receiver
CPU Utilization: local/receiver 0.0% (0.0%u/0.0%s), remote/sender 0.9% (0.3%u/0.7%s)
rcv_tcp_congestion cubic

iperf3 -c testserver -t 60 -i 10  --get-server-output -R
....
Server output:
...
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  5]   0.00-60.04  sec  51.8 MBytes  7244 Kbits/sec  134             sender
**[  5]   0.00-60.04  sec  0.00 Bytes  0.00 Kbits/sec                  receiver**
CPU Utilization: local/sender 0.1% (0.0%u/0.1%s), remote/receiver 0.1% (0.1%u/0.1%s)
snd_tcp_congestion cubic
rcv_tcp_congestion cubic

iperf3 -c testserver -t 30 -i 5  --get-server-output -u 
.....
Server output:
....
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
**[  5]   0.00-30.05  sec  0.00 Bytes  0.00 Kbits/sec  18.948 ms  6/479 (1.3%)**  
CPU Utilization: local/receiver 0.1% (0.0%u/0.1%s), remote/sender 2.4% (1.1%u/1.3%s)

iperf3 -c testserver -t 30 -i 5  --get-server-output -u -R
....
Server output:
....

Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-30.06  sec  3.76 MBytes  1049 Kbits/sec  0.000 ms  0/481 (0%)  
CPU Utilization: local/sender 0.3% (0.0%u/0.2%s), remote/receiver 0.4% (0.2%u/0.2%s)

**Comment by bmah888** [comment]
This is a real bug (I consider it a minor one), in that the server-side output is sent along with all of the server-side statistics, but the client-side output isn't complete at that point.  I managed to convince myself earlier that solving this would require some non-trivial changes to the workflow and messages between the client and server.  (I know this bug has been reported before but I can't find it.)

**Comment by bmah888** [comment]
Found it during an issue triage.  This is basically issue #293.
