### ISSUE TITLE
is it possible to simulate video on demand and streaming on iperf?

### ISSUE THREAD

**Issue by delinage** [esnet/iperf#477]
is it possible to simulate video on demand traffic and streaming video traffic on iperf?

what options should I select to make this?

I would really appreciate your help because I don't know where I should go asking this and I really need it.
Thanks in advance.

**Comment by bmah888** [comment]
iperf3 is designed to do bulk data transfers.  Someone with knowledge of streaming video traffic would have to say whether or not a bulk data transfer would be a sufficient approximation to that workload.

**Comment by bmah888** [comment]
Closing this issue, as I've answered the question as best I can with the information I've been given.

(My intuition says that no, this type of multimedia data isn't well-simulated by a bulk-transfer tool.  But I could be completely wrong on this...)
