### ISSUE TITLE
Stream id's skip 2

### ISSUE THREAD

**Issue by utahwithak** [esnet/iperf#478]
In the case of multiple streams the id's of the streams skip number 2 and continue incrementing from there.

So the id's are 1,3,4,5...
The problem occurs here:
```
void iperf_add_stream(struct iperf_test *test, struct iperf_stream *sp)
{
        ...
    } else {
        // for (n = test->streams, i = 2; n->next; n = n->next, ++i);
        i = 2; // SET IT TO 2; SHOULD BE 1
        SLIST_FOREACH(n, &test->streams, streams) {
            prev = n;
            ++i; // INCREMENT IT TO 3 SINCE 1's ALREADY IN LIST
        }
        SLIST_INSERT_AFTER(prev, sp, streams);
        sp->id = i; // SET THE ID TO 3. SKIPPING 2.
    }
}

**Comment by bmah888** [comment]
I agree with your analysis.  The fix seems obvious, as you pointed out.  Do you know what the impact is of this bug?  I'm not sure what, if any, difference it makes.

**Comment by utahwithak** [comment]
I only noticed it when working on a piece of software integrating with the results. It had 10 streams so I set up a for loop for 0 to 10 and couldn't find 2! Otherwise it doesn't make much difference.

When using it both client and server have the same bug between id's and it won't show when doing results.

The fix would break cross version tests, but make integrating more sensible.

**Comment by bmah888** [comment]
Ok got it, thanks for the explanation.  I think we should leave it as is for now, because cross-version compatibility is important for our primary use cases.  (Also as far as I know, iperf3 has always had this bug.)

**Comment by bmah888** [comment]
I'm going to declare that we're not going to fix this, even though I totally agree it's a real (non-user-visible) bug.  We can't break tests across versions (again).
