### ISSUE TITLE
Javascript/browser client

### ISSUE THREAD

**Issue by s193956** [esnet/iperf#482]
Do you see any way to implement a javascript client? I. e running iperf3 on a router, and then from a browser on the local network communicate with the router to measure bandwidth?

**Comment by bmah888** [comment]
This is way outside the scope of the iperf3 project, but basically to implement it you'd have to make some kind of wrapper around iperf3 that your Javascript could connect to and request a test.  Something like bwctl or pScheduler (both from the perfSONAR) project might be something you could leverage.
