### ISSUE TITLE
cross compile issue

### ISSUE THREAD

**Issue by Khadmi** [esnet/iperf#483]
Hi,
I cross compile  iperf-3.0.9 for mips-linux but i got following error.

compilation steps
configure  path 
CC=/home/mashkur/Desktop/ROUTER/rsdk-1.5.6-5281-EB-2.6.30-0.9.30.3-110915/bin/mips-linux-gcc ./configure --host=mips-linux 
make 

but i got the following error can any one help me out

iperf3_profile-main.o: In function `main':
/home/mashkur/Downloads/iperf-3/src/main.c:56: undefined reference to `_mcount'
/home/mashkur/Downloads/iperf-3/src/main.c:111: undefined reference to `_ecount'
iperf3_profile-cjson.o: In function `cJSON_GetErrorPtr':
/home/mashkur/Downloads/iperf-3/src/cjson.c:48: undefined reference to `_mcount'
/home/mashkur/Downloads/iperf-3/src/cjson.c:50: undefined reference to `_ecount'
iperf3_profile-cjson.o: In function `cJSON_InitHooks':
Makefile:768: recipe for target 'iperf3_profile' failed
make[2]: *** [iperf3_profile] Error 1
make[2]: Leaving directory '/home/mashkur/Downloads/iperf-3/src'
Makefile:615: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/mashkur/Downloads/iperf-3/src'
Makefile:369: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by bmah888** [comment]
At the point the build failed it was trying to link a profiled version of iperf3.  If it succeeded in producing a normal (non-profiling) version before this point, is that sufficient for your needs?

**Comment by bmah888** [comment]
Didn't get an answer to my last question...closing.  Please re-open if you're still seeing this or if my workaround isn't good enough.

**Comment by andy-js** [comment]
I'm also running into problems trying to cross compile iperf3.  Is there any chance an option could be added to turn it of?
