### ISSUE TITLE
iperf 3.1.3 -len option interfere bandwidth limitation

### ISSUE THREAD

**Issue by shahar3000** [esnet/iperf#485]
Hello,
I'm using iperf with bandwidth limitation on both TCP and UDP
I try to limit the bandwidth to 1.3536M

in **UDP** protocol without -len flag it works as expected but when I add -l 28.2K the bandwidth is 2.31 Mbits/sec (if I give a bigger len it rises) for example:
iperf3 -c 192.168.0.2 -i 1 -u -b 1.3536M -P 1 -p 5002 -t 5 -f m -l 28.2K
Connecting to host 192.168.0.2, port 5002
[  4] local 192.168.0.3 port 54763 connected to 192.168.0.2 port 5002
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec   310 KBytes  2.54 Mbits/sec  11
[  4]   1.00-2.00   sec   282 KBytes  2.31 Mbits/sec  10
[  4]   2.00-3.00   sec   282 KBytes  2.31 Mbits/sec  10
[  4]   3.00-4.00   sec   282 KBytes  2.31 Mbits/sec  10
[  4]   4.00-5.00   sec   282 KBytes  2.31 Mbits/sec  10
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-5.00   sec  1.40 MBytes  2.36 Mbits/sec  1.928 ms  1/50 (2%)

in **TCP** protocol without the flag it give 10.5 Mbits/sec (probably because of the default len value):
iperf3 -c 192.168.0.2 -i 1 -b 1.3536M -P 1 -p 5002 -t 5 -f m
Connecting to host 192.168.0.2, port 5002
[  4] local 192.168.0.3 port 34403 connected to 192.168.0.2 port 5002
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  1.30 MBytes  10.9 Mbits/sec    0   62.2 KBytes
[  4]   1.00-2.00   sec  1.21 MBytes  10.2 Mbits/sec   36   62.2 KBytes
[  4]   2.00-3.00   sec  1.25 MBytes  10.5 Mbits/sec    0   74.9 KBytes
[  4]   3.00-4.00   sec  1.25 MBytes  10.5 Mbits/sec    0   79.2 KBytes
[  4]   4.00-5.00   sec  1.25 MBytes  10.5 Mbits/sec    0   79.2 KBytes
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-5.00   sec  6.26 MBytes  10.5 Mbits/sec   36             sender
[  4]   0.00-5.00   sec  6.21 MBytes  10.4 Mbits/sec                  receiver
and when I add the flag with 28.2K it gives the same bandwidth like the UDP case

I tested it with iperf2 and it worked as expected and without this weird behavior.
any ideas on how to solve this issue?

**Comment by bltierney** [comment]
There are some known issues at very low bandwidth, but I'll try to do more testing too.

**Comment by bltierney** [comment]
This is expected. With low bandwidth, you need smaller packets (e.g.: -l 100).

See the new FAQ for details.
