### ISSUE TITLE
Always 100ms burst

### ISSUE THREAD

**Issue by zhongwen25** [esnet/iperf#486]
I do a UDP test, the traffic alway has 90~100ms burst.
I think this is cause by this code:
sp->send_timer = tmr_create((struct timeval*) 0, send_timer_proc, cd, 100000L, 1);

I think the parameter "100000L" shoud be a argument. such as:
iperf3 -c 127.0.0.1 -u -b 20m -l 1400 **--burst-interval 100ms**

**Comment by bmah888** [comment]
This is basically #386.  We've been thinking about this, although we need to do some measurements to see what the CPU load would be under a different burst interval.  Making it tunable as you suggest might be a good compromise.
