### ISSUE TITLE
iPerf3 sending 1000 packets/sec

### ISSUE THREAD

**Issue by krisa85** [esnet/iperf#487]
Hi All,

I'm trying to perform some network convergence/failure tests and therefore trying to send a constant flow of a 1000 packets per second (to calculate msec loss). 

I have tried various options to try and setup a constant flow but with no success. I've managed to send a single burst of a 1000 packets but I can't seem to keep it going. 

Does anybody have any ideas? 

Thanks 
Kris

**Comment by bmah888** [comment]
The best way I can think of doing this is to do a UDP test and set the bitrate and message size appropriate to what you want for your test.  To smooth it out, considering running on a Linux system that supports per-socket fair-queue-based pacing and use the `--fq-rate` option.
