### ISSUE TITLE
Support of UDP parallel streams on Windows 

### ISSUE THREAD

**Issue by annadhpi** [esnet/iperf#489]
Is iperf2 officially being supported on windows OS?
I have read UDP bugs and found that parallel stream for UDP is not working on Windows and no progress on that because iperf 3 is not officially supported on Windows OS... 

The UDP multi-stream is also not working on iperf2 on Windows 10.  The client(-c) sends multi-streams, but server(-s) receives only one. 
multi-stream not work on below versions. 

iperf version 2.0.5 (08 Jul 2010) **pthreads**,  - downloaded from GitHub.
iperf version 2.0.8 (12 Jan 2015) pthreads
iperf version 2.0.9 (1 June 2016) pthreads

I got a different version from a colleague that multi-stream works, but could not find where he got and if it is reliable. It is, 

iperf version 2.0.5 (08 Jul 2010) **win32 threads**

Does anyone know about win32 threads build? Does others also see the same behavior on Windows?

**Comment by asafshakedverint** [comment]
I'm working with version 3.1.3 on Windows Server 2012...

Parallel client streams combined with UDP doesn't work (no error... just nothing happens)

Any chance this can be fixed ?

**Comment by bmah888** [comment]
@annadhpi:  This is an issue tracker for iperf3.  iperf2 issues should probably be posted via email to iperf-users@lists.sourceforge.net.

@asafshakedverint:  I'm not sure why it wouldn't work on Windows, we actually don't officially support that platform.  I can tell you it works fine on macOS.  I'm not sure off-hand what might be causing your problem.
