### ISSUE TITLE
iperf3 logfile 

### ISSUE THREAD

**Issue by Dongxintian** [esnet/iperf#492]
I tested my PC with the last iperf3 for **24H**. Please kindly help tell me what’s the meaning of xFF%x94xD2.  Logfiles as attached.  Thanks.
[ ID] Interval           Transfer     Bandwidth
[Desktop.zip](https://github.com/esnet/iperf/files/660096/Desktop.zip)

[  5]   0.00-86400.01 sec  0.00 xFF%x94xD2As   887 Mbits/sec                  sender
[  5]   0.00-86400.01 sec  0.00 xFF%x94xD2As   887 Mbits/sec                  receiver

iperf Done.
OS: windows 7 pro Chinese

**Comment by bmah888** [comment]
On my macOS system the place where you see "xFF%x94xD2As" is the unit for the number of bytes transferred during the tests (e.g. "Bytes", "MBytes, "GBytes", etc.).  I am not sure how that turned into what you see.

Note that Windows is not an officially supported platform for iperf3, and it's not clear to me what changes someone might have made to produce an executable for that platform.  That could be a factor as well.

**Comment by bmah888** [comment]
Closing this issue...I've answered the question as best I can with the information I was given.
