### ISSUE TITLE
iperf3 to handle EMFILE (Too many open files) / ulimit -n (NOFILE)

### ISSUE THREAD

**Issue by andrey01** [esnet/iperf#493]
Hello,

would it be possible to make iperf3 to handle EMFILE (Too many open files), when NOFILE (number of open files) is exhausted?

By ``handle``, I mean, it would be nice if it could explicitly tell that NOFILE got exhausted, otherwise it only throws "connection closed" (or reset by peer, I can't exactly remember now). So the only way to figure this out was to strace the iperf3 on the receiving side as follows:

```
# strace -f -e accept -p $(pidof -s iperf3)
...
accept(3, 0x7ffdc5a2d440, [128])        = -1 EMFILE (Too many open files)
accept(3, {sa_family=AF_INET, sin_port=htons(56876), sin_addr=inet_addr("172.28.16.15")}, [16]) = 4
accept(3, 0x7ffdc5a2d440, [128])        = -1 EMFILE (Too many open files)
accept(3, {sa_family=AF_INET, sin_port=htons(56880), sin_addr=inet_addr("172.28.16.15")}, [16]) = 4
```

The solution for me was to increase NOFILE (max number of open files) via ``ulimit -n``

Thanks.

**Comment by bmah888** [comment]
It looks like iperf3 is already doing what you had in mind (this is running on CentOS 6):
```
[bmah@antg-staging iperf]$ limit descriptors 16
[bmah@antg-staging iperf]$ src/iperf3 --client antg-dev -4 --port 5202 --time 5 --parallel 16
Connecting to host antg-dev, port 5202
[  4] local 198.128.151.25 port 37916 connected to 198.128.151.17 port 5202
[  6] local 198.128.151.25 port 37918 connected to 198.128.151.17 port 5202
[  8] local 198.128.151.25 port 37920 connected to 198.128.151.17 port 5202
[ 10] local 198.128.151.25 port 37922 connected to 198.128.151.17 port 5202
[ 12] local 198.128.151.25 port 37924 connected to 198.128.151.17 port 5202
[ 14] local 198.128.151.25 port 37926 connected to 198.128.151.17 port 5202
iperf3: error - unable to connect stream: Too many open files
```
Is it doing something different for you?

**Comment by bmah888** [comment]
We believe that iperf3 is reporting this error condition as requested.  (I don't remember any recent code change in this area.)  Closing for now, please feel free to re-open if this isn't what you had in mind.
