### ISSUE TITLE
Better default socket buffer size for UDP tests

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#495]
Filing this issue mostly to document what's been learned.  As of this writing there is no plan to address the problem.

If no socket buffer size is explicitly specified with the `-w` flag, iperf uses the OS default socket buffer sizes.  For TCP, this generally means allowing the OS to auto-tune the socket buffer sizes (this is true for Linux, macOS, and FreeBSD).  For UDP tests, the default static buffer sizes are too small for good performance (a common symptom is packet loss at high data rates).  On macOS and FreeBSD the default UDP send buffer size of 9216 bytes; even on Linux as of CentOS 7.3 the limit is only 212992 bytes.  Note that ESnet recommends a socket buffer size around 4MB (see http://fasterdata.es.net/network-tuning/udp-tuning/ for more information).

Note that it may not be possible to actually set that socket buffer size without some other OS tuning (for example, a sysctl to raise the maximum socket buffer size).  The exact mechanism and parameters necessary are OS-dependent.  This sort of tuning is beyond the scope of what iperf3 has been designed to do; it requires some intervention from the tool user and system administrator.

With proper host tuning and sufficiently capable hardware, iperf3 can push multi-Gbps of UDP.

**Comment by bltierney** [comment]
decided its probably better to stick with system defaults, and document that one should use -w1m, or something similar. closing.
