### ISSUE TITLE
iPerf 2.0 - adding -t option to bidirectional test (10 seconds default)

### ISSUE THREAD

**Issue by csagar** [esnet/iperf#497]
I am trying to run the following test, and the server refuses to connect if '-t' option is enabled. By default without -t option the test runs for 10 seconds (default). Can the support to add -t option be enabled for this case of running bidirectional tests?

`iperf.exe -c 192.168.1.10 -B 192.168.1.100 -P 10 -t 60 -r`

**Comment by bmah888** [comment]
This issue tracker is for iperf3.  You should probably post your question to the iperf-users mailing list.
