### ISSUE TITLE
"Connection reset by peer" while testing iperf over a NAT

### ISSUE THREAD

**Issue by pm3213** [esnet/iperf#499]
With iperf3 version 3.1.3, and the connection as follows -

iperf client                                                     
192.168.0.102                                     

Device with NAT
192.168.0.1/10.207.0.66

iperf server
10.207.102.38

the following errors are seen 10 % of the time at the end of the test (at the 14th second when the test duration is 15 s) -

Client -
iperf3: error - unable to receive control message: Connection reset by peer

Server -
iperf3: error - unable to write to stream socket: Connection reset by peer

From the logs -
1. The client sends IPERF_DONE to the server.
2. The server closes the control socket and sends a TCP FIN.
3. The client has not yet initiated the TCP FIN (after step 1), and sends a TCP RST.

In the good case -
1. The client sends IPERF_DONE to the server.
2. The client sends a TCP FIN.
3. The server closes the control socket and sends a TCP FIN.

It appears to be a race condition where the the server immediately responds to the IPERF_DONE with a TCP FIN, but the client TCP has not yet sent the FIN.

As a solution, would it be a good idea to add a sleep in the server(iperf_run_server() function) after it exits the main loop when test_state is set to IPERF_DONE, and before the cleanup_server() is called?

	if (result == 0 ||
	    (timeout != NULL && timeout->tv_sec == 0 && timeout->tv_usec == 0)) {
	    /* Run the timers. */
	    (void) gettimeofday(&now, NULL);
	    tmr_run(&now);
	}
    }

    sleep(2);
    cleanup_server(test);

**Comment by pm3213** [comment]
The client command includes a -R option for reverse mode, and the client is executed on a Windows laptop. The server runs on Ubuntu.

**Comment by jonfcervantes** [comment]
I am seeing the same thing but it is intermittent. We are running using client (linux vm) and server (ubuntu vm)
`unable to receive control message: Connection reset by peer`

**Comment by bmah888** [comment]
@jonfcervantes :  Is this the same problem you reported in a comment on issue #447?

@pm3213:  Are you still seeing this problem?  If so, could you please post the command lines for both server and client?  Also could you say whether the client or the server is on the "inside" of the NAT?  What sort of device is implementing the NAT?  iperf3 wasn't really designed with NAT traversal in mind, so this might be a problem we just can't solve (easily).

**Comment by danielmajhor** [comment]
![image](https://user-images.githubusercontent.com/40669119/42045750-f1ffdd8c-7ac1-11e8-91ee-b905ed11cd39.png)
Here is my screenshot of client side iperf3,  showing command line. The server side command line is just "iperf3 -s" . The environment is that I am doing a test with a wireless gateway and an extender,  with a PC attached to each. THe test is to see how well it performs when I am doing iperf test and playing a video  on client PC  that is located on server side PC,  simultaneously.  I am trying to understand how to avoid the socket error message as that condition interrupts my test.

**Comment by pm3213** [comment]
There was TCP RST on the data stream, so the socket is closed. The control socket however is hung and hence another connection cannot be established. Currently the server does not detect this. I have a change where the server waits for test duration + 10s and then closes the connection. The code is attached (over version 3.1.3). We did not choose to use this, however. We just restarted iperf server.


[iperf_server_busy.zip](https://github.com/esnet/iperf/files/2146218/iperf_server_busy.zip)

**Comment by danielmajhor** [comment]
Thanks for your response.  What would cause the TCP RST? I am looking to confirm any latency issues or things like that which impact performance.

**Comment by pm3213** [comment]
TCP Reset can be due to several reasons, and implementation dependent. In your case there is no data for several seconds, so it could be that the server sent a TCP RST due to failed retransmissions.

**Comment by bmah888** [comment]
Some middleboxes (such as NATs) can drop connection state under some conditions, which can end up causing a TCP RST.  Although it's not really obvious what about the iperf3 test might cause this to happen, so this might not be the cause.  I agree that testing with the client and server connected with a switch (or some similar stateless device) is a good next step.

**Comment by bmah888** [comment]
Closing, no response after 2+ months.

**Comment by kodati9** [comment]
I face the same issue as my client and server are both behind a NAT.

**Comment by HOVR-17** [comment]
I am also facing this issue.  The setup I have is laptop ---> router ---> wireless AP ---> WiFi dongle ---> laptop.  The laptop wired to the router is the iPerf server, but I am doing the test in reverse (with "-R" in the iPerf command at the client laptop).  The laptops are both Windows machines running iPerf v3.1.3.  Any further insights into this?

[iPerf issue.pdf](https://github.com/esnet/iperf/files/4548236/iPerf.issue.pdf)
