### ISSUE TITLE
UDP tests can "appear" broken if FreeBSD server has multiple IP addresses

### ISSUE THREAD

**Issue by seanbruno** [esnet/iperf#505]
Pretty minor documentation issue, I think.  If you have a host (FreeBSD) with multiple interfaces that are active and have IP addresses assigned, the UDP tests will assume that you want to listen on whatever the first interface retrieved is (primary?).

It won't listen on all addresses and your UDP tests can appear to be broken.  A simple explicit entry in documentation to add the server listen address to the server invocation would probably keep most folks from banging their heads against this in the future.  With the server set to listen/bind to a specific address, the tests run well!

e.g. server with two interfaces configured, iperf3 -s will default to 'em0' in this example:

> # ifconfig
> 
> ix0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500        options=e53fbb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
>         ether 00:25:90:05:7b:ac
>         inet 192.168.100.101 netmask 0xffffff00 broadcast 192.168.100.255 
>         inet6 fe80::225:90ff:fe05:7bac%ix0 prefixlen 64 scopeid 0x1 
>         nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
>         media: Ethernet autoselect (10Gbase-SR <full-duplex,rxpause,txpause>)
>         status: active
> 
> em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500       options=5259b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,LRO,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO>
>         ether 00:30:48:da:d7:26
>         inet 10.14.229.18 netmask 0xffffff00 broadcast 10.14.229.255 
>         inet6 fe80::230:48ff:feda:d726%em0 prefixlen 64 scopeid 0x3 
>         nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
>         media: Ethernet autoselect (1000baseT <full-duplex>)
>         status: active
> 

If you want to listen on ix0, in this example, just adding the bind address fixes the issue for me.  `iperf3 -s -B 192.168.100.101`

So, this isn't really a bug, but how the thing works IMO.  Feel free to just close this out, but I thought I'd leave it here in case you wanted to be explicit in the man page or in the documentation regarding UDP tests.

**Comment by bmah888** [comment]
That's really interesting behavior.  It's not what I thought iperf3 should be doing in this circumstance, so this actually feels like a bug to me.  In the failure case, do you get any output on either the client or server sides?

Is it only on FreeBSD or have you observed it on other platforms?  I need to hack on my testing setup to try to reproduce this problem.

**Comment by seanbruno** [comment]
I've only seen this on FreeBSD and have not tried on Linux.

In the failure case, the TCP control connection is made, the test times out and I have to restart the server.

**Comment by bltierney** [comment]
man page updated to clarify the default behavior in this commit:

https://github.com/esnet/iperf/commit/0c4d5992fd0af58d1b846a9d2e67a1e81f58474c#diff-e08dae5c53ccf95030621450eb8e044c

Bruce: please review, and then close.

**Comment by bmah888** [comment]
Text looks good.  I'd like to understand this behavior a little better, but there's no reason to keep the issue open.  Closing...
