### ISSUE TITLE
iperf3.1.3 and iperf3.1.4 both having inconsistent UDP throughput measurement and huge packet loss

### ISSUE THREAD

**Issue by purumishra** [esnet/iperf#509]
I have tested UDP throughput between ubuntu vm having 4 vcpu and 8gb RAM using both iperf-3.1.3 and iperf3.1.4.
In both the cases getting almost 50% packet loss. 
Same instances are showing 0.5% packet loss if I am using iperf2 .
I think its a bug in iperf3 if so, is it going to be fixed in iperf new release.

Any help would be appreciated. 

Thanks
Puru

**Comment by purumishra** [comment]
Hi ALL,
     I verified one more thing with tcpdump . This time I have used iperf2 and iperf3.
    The data reported by iperf2 is almost matching with tcpdump packet received filter. 
   But in case of iperf3 tcpdump is showing 0.2 % packet loss but iperf3 is showing 30% packet loss.
  iperf command used for iperf:
   iperf -c $server_ip  -l 1000 -ub 300m -t 10 -i 1
   iperf3 -c $server_ip  -l 1000 -ub 300m -t 10 -i 1.
  
  I also tried using other parameter like -w , -A, -Z but no improvement.

Thanks
Puru

**Comment by purumishra** [comment]
I have one more observation. I was running udp test between same setup as I explained above but this time bandwidth was 1G. I have used recent iperf3-current and did tcpdump on ovs port of vm (qbr and tap port) .Below are the results of packet drop shown by tcpdump and qbr port of vm.
iperf report: on client side:
Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-30.00  sec  3.49 GBytes  1000 Mbits/sec  0.013 ms  633188/
 as I explained above but this time bandwidth was 1G. I have used recent iperf3-current and did tcpdump on ovs port of vm (qbr and tap port) .Below are the results of packet drop shown by tcpdump and qbr port of vm.
iperf report: on client side:
Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-30.00  sec  3.49 GBytes  1000 Mbits/sec  0.013 ms  633188/3124652 (20%)
[  4] Sent 3124652 datagrams

And tcpdump report on receiving side vm on qbr port:
3104370 packets received by filter.
We can see the difference: 3124652-3104370 = approx 20K. But iperf reports : 633188 loss.

Is this a expected behaviour. Same issue I am facing in iperf3.1.3 also.

**Comment by bltierney** [comment]
I'm trying to replicate this, and having trouble consistently seeing this ( I do see it sometimes).

Just to confirm: Can you try adding "-w 4M" to both iperf2 and iperf3, and see if iperf3 still drops more? Also, which version of iperf2 are you using? I'm seeing even higher loss with 2.0.5 than iperf3, but no loss with 2.0.9.

**Comment by bltierney** [comment]
after more testing, I do see this issue constantly in 3.1.3, but in iperf3 version 3.1.6 gives the same results as iperf3 2.0.9 if I use "-w 1m" with both tools. 

Please let us know if 3.1.6 is working for you now.

**Comment by bltierney** [comment]
no reply, so closing.

**Comment by ChowdaryDinesh** [comment]
Hi , 
The iperf3(3.1.3) and iperf(2.0.10) data varies significantly. Iperf has no/les packetloss which maps with tcpdump/tshark data while iperf3 data is no match and describes there is a huge packet loss mainly when we test the bidirectional data speed.

Additional info:
We see the packet loss is huge in case of data coming from server(in bidirectional speed test).
This should be addressed in the up coming versions of iperf3.
