### ISSUE TITLE
Add updated changelog in place of RELEASE_NOTES

### ISSUE THREAD

**Issue by scottlinux** [esnet/iperf#511]
Hi, 

First of all thank you for this awesome app. 

Would it be possible to add a changelog file to the repo so to document each release's changes?

The existing RELEASE_NOTES file appears to be abandoned and a changelog file seems to be more mainstream and what users would look to find in a repo.

**Comment by bmah888** [comment]
The `RELEASE_NOTES` file is updated independently on each release branch.  So to see the changes on the 3.1.x codeline, change to the 3.1-RELEASE branch and examine the `RELEASE_NOTES` file there.
