### ISSUE TITLE
How to update time-stamp every second to stdout of iPerf command?

### ISSUE THREAD

**Issue by mamun072009** [esnet/iperf#512]
[http://stackoverflow.com/questions/42136662/how-to-update-time-stamp-every-second-to-stdout-of-iperf-command](url)

**Comment by bmah888** [comment]
I don't know of a way of doing this, off-hand.  It looks like you used `--title` to prepend a string onto each line which, as you see, just adds a static string.  iperf3 itself doesn't have a mechanism for doing what you asked.

**Comment by mamun072009** [comment]
Is there any other way to put time-stamp while running iperf3 like in iperf2 we can use a command **-y C** at the client side which gives us time-stamp for each output line.

**Comment by bmah888** [comment]
Closing...question answered.
