### ISSUE TITLE
Rename bandwidth to data rate/throughput

### ISSUE THREAD

**Issue by sedrubal** [esnet/iperf#516]
The amount of data you can send per time is actually called data rate but colloquially called bandwidth (which is actually the amount of frequencies you use, measured in Hz).

If you don't want to rename it, you can just close this issue :wink:

**Comment by bmah888** [comment]
I agree completely with you about the terminology, bandwidth is a capacity.  I personally would have used the word "throughput" to describe the actual amount of data sent/received per unit time (the terminology in use predates my involvement with iperf3).  I don't have a strong opinion at this point whether we should actually make this change.

**Comment by bltierney** [comment]
Also agree, but this would break backwards compatibility, so closing.
