### ISSUE TITLE
iperf3.1stable udp protocol,client as the sender, server as the reciver, server summary transfer and bandwidth shows 0

### ISSUE THREAD

**Issue by Marisa-coding** [esnet/iperf#519]
client output:
ygl@ubuntu:~$ iperf3 -c 106.15.40.45 -u 
Connecting to host 106.15.40.45, port 5201
[  4] local 192.168.184.135 port 51593 connected to 106.15.40.45 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec   115 KBytes   944 Kbits/sec  81  
[  4]   1.00-2.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  4]   2.00-3.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  4]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  4]   4.00-5.00   sec   127 KBytes  1.04 Mbits/sec  89  
[  4]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  4]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  4]   7.00-8.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  4]   8.00-9.00   sec   128 KBytes  1.05 Mbits/sec  90  
[  4]   9.00-10.00  sec   127 KBytes  1.04 Mbits/sec  89  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec  1.24 MBytes  1.04 Mbits/sec  0.228 ms  166/889 (19%)  
[  4] Sent 889 datagrams

iperf Done.

server output:

root@iZuf6gj7uz1bywfdz7373yZ:~# iperf3 -s
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 218.80.1.114, port 5573
[  5] local 106.15.40.45 port 5201 connected to 218.80.1.114 port 22367
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  81.3 KBytes   666 Kbits/sec  0.201 ms  4/61 (6.6%)
[  5]   1.00-2.00   sec   106 KBytes   864 Kbits/sec  0.148 ms  15/89 (17%)
[  5]   2.00-3.00   sec   110 KBytes   899 Kbits/sec  0.365 ms  17/94 (18%)
[  5]   3.00-4.00   sec   106 KBytes   864 Kbits/sec  0.205 ms  15/89 (17%)
[  5]   4.00-5.00   sec   104 KBytes   853 Kbits/sec  0.195 ms  17/90 (19%)
[  5]   5.00-6.00   sec   108 KBytes   888 Kbits/sec  0.151 ms  10/86 (12%)
[  5]   6.00-7.00   sec   101 KBytes   829 Kbits/sec  0.132 ms  19/90 (21%)
[  5]   7.00-8.00   sec  92.7 KBytes   759 Kbits/sec  0.365 ms  25/90 (28%)
[  5]   8.00-9.00   sec   104 KBytes   853 Kbits/sec  0.234 ms  20/93 (22%)
[  5]   9.00-10.00  sec  98.4 KBytes   806 Kbits/sec  0.258 ms  20/89 (22%)
[  5]  10.00-10.20  sec  20.0 KBytes   817 Kbits/sec  0.228 ms  4/18 (22%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-10.20  sec  0.00 Bytes  0.00 bits/sec  0.228 ms  166/889 (19%)
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------

@bmah888

**Comment by bmah888** [comment]
This is basically bug #293.
