### ISSUE TITLE
iperf 3.1.3 error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by fl4w** [esnet/iperf#521]
I'm trying to integrate iperf with a GUI based on Qt, but when I run the iper_run_client() through the method invoked by the clicked button event _"Resource temporarily unavailable"_ error is thrown just after summary data.

```
---------------------------------------------------
Server listening on 1234
---------------------------------------------------

Accepted connection from 127.0.0.1, port 55132
[  5] local 127.0.0.1 port 1234 connected to 127.0.0.1 port 55134
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec  2.16 GBytes  18.6 Gbits/sec                  (omitted)
[  5]   1.00-2.00   sec  2.23 GBytes  19.2 Gbits/sec                  (omitted)
[  5]   2.00-3.00   sec  2.37 GBytes  20.4 Gbits/sec                  (omitted)
[  5]   0.00-1.00   sec  2.25 GBytes  19.4 Gbits/sec                  
[  5]   1.00-2.00   sec  2.23 GBytes  19.1 Gbits/sec                  
[  5]   2.00-3.00   sec  2.24 GBytes  19.3 Gbits/sec                  
[  5]   3.00-4.00   sec  2.33 GBytes  20.0 Gbits/sec                  
[  5]   4.00-5.00   sec  2.28 GBytes  19.6 Gbits/sec                  
[  5]   5.00-5.04   sec  99.4 MBytes  20.5 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-5.04   sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-5.04   sec  11.4 GBytes  19.5 Gbits/sec                  receiver
iperf3: error - unable to receive results: Resource temporarily unavailable
```

what are the possible causes of this problem? Could it be generate by something related to Qt's signal/slots mechanism?

Thank you in advance for the reply.

**Comment by bmah888** [comment]
I have absolutely no idea.  But leaving this issue open in case someone in the community has an idea.

**Comment by fl4w** [comment]
Thank you for your reply.
I've tried to workaround by putting the same code in a "pure" C++ project and it worked with no problem, so I think this is definitly a Qt related issue.
Anyway I'll leave this issue open in case someone had the same problem as mine.

**Comment by bmah888** [comment]
OK, I'm going to close this issue because there isn't much else for us to do about it.  It should still show up in case people search for it.  The issue tracker isn't an archive of questions and answers, it's really more a list of things that we should be thinking about to improve iperf3.

**Comment by JBGS** [comment]
I got this problem, I my case was the diffs between iperf versions.

**Comment by TalLandes** [comment]
Hi, 
I am still seeing this issue and made sure both sides of are running the same version. It happens when I try to bind to an interface to be able and set a source port: 
iperf3 -c <server IP> 10.39.29.15 -i 1 -P 2 -u -b 1M -R -V -t 10 -p <server port> -B <interface> --cport <source port> 

iperf 3.1.3
ubuntu18.4 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64
iperf3: error - unable to connect to server: 

This works: 
iperf3 -c <server IP> 10.39.29.15 -i 1 -P 2 -u -b 1M -R -V -t 10 -p <server port>

Thanks,

**Comment by kunal14kapoor** [comment]
Can we re-open this issue, I am also facing this issue and binding a port looks to be the issue. I am using ueransim and trying to benchmark the bandwidth using iperf3. I am continuously getting below error : 
{
        "start":        {
                "connected":    [],
                "version":      "iperf 3.7",
                "system_info":  "Linux 29a1e56b8b73 5.15.0-1051-aws #56~20.04.1-Ubuntu SMP Tue Nov 28 15:43:31 UTC 2023 x86_64"
        },
        "intervals":    [],
        "end":  {
        },
        "error":        "error - unable to connect to server: Resource temporarily unavailable"
}
