### ISSUE TITLE
Build fails on Solaris 11.3 SPARC

### ISSUE THREAD

**Issue by pa-jberanek** [esnet/iperf#522]
Just attempting to build iperf 3.1.6 on a Solaris 11.3 SPARC server, and the build fails at the link phase.

>admin@test-vmsparc-00:~/iperf-3.1.6$ pkg info entire
             Name: entire
          Summary: entire incorporation including Support Repository Update (Oracle Solaris 11.3.17.5.0).
      Description: This package constrains system package versions to the same
                   build.  WARNING: Proper system update and correct package
                   selection depend on the presence of this incorporation.
                   Removing this package will result in an unsupported system.
                   For more information see:
                   https://support.oracle.com/rs?type=doc&id=2045311.1
         Category: Meta Packages/Incorporations
            State: Installed
        Publisher: solaris
          Version: 0.5.11 (Oracle Solaris 11.3.17.5.0)
    Build Release: 5.11
           Branch: 0.175.3.17.0.5.0
   Packaging Date: February 17, 2017 02:04:57 AM
             Size: 5.46 kB
             FMRI: pkg://solaris/entire@0.5.11,5.11-0.175.3.17.0.5.0:20170217T020457Z

The link failure:

>/bin/sh ../libtool --tag=CC    --mode=link gcc  -g -O2 -Wall    -o libiperf.la -rpath /usr/local/pkg/iperf-3.1.6/lib cjson.lo iperf_api.lo iperf_error.lo  iperf_client_api.lo iperf_locale.lo iperf_server_api.lo  iperf_tcp.lo iperf_udp.lo iperf_sctp.lo iperf_util.lo net.lo  tcp_info.lo tcp_window_size.lo timer.lo units.lo  -lsctp -lnsl -lsocket -lresolv -lm
libtool: link: gcc -shared  -fPIC -DPIC -Wl,-z -Wl,text -Wl,-h -Wl,libiperf.so.0 -o .libs/libiperf.so.0.0.0  .libs/cjson.o .libs/iperf_api.o .libs/iperf_error.o .libs/iperf_client_api.o .libs/iperf_locale.o .libs/iperf_server_api.o .libs/iperf_tcp.o .libs/iperf_udp.o .libs/iperf_sctp.o .libs/iperf_util.o .libs/net.o .libs/tcp_info.o .libs/tcp_window_size.o .libs/timer.o .libs/units.o   -lsctp -lnsl -lsocket -lresolv -lm  -O2
libtool: link: (cd ".libs" && rm -f "libiperf.so.0" && ln -s "libiperf.so.0.0.0" "libiperf.so.0")
libtool: link: (cd ".libs" && rm -f "libiperf.so" && ln -s "libiperf.so.0.0.0" "libiperf.so")
libtool: link: ar cru .libs/libiperf.a  cjson.o iperf_api.o iperf_error.o iperf_client_api.o iperf_locale.o iperf_server_api.o iperf_tcp.o iperf_udp.o iperf_sctp.o iperf_util.o net.o tcp_info.o tcp_window_size.o timer.o units.o
libtool: link: ranlib .libs/libiperf.a
libtool: link: ( cd ".libs" && rm -f "libiperf.la" && ln -s "../libiperf.la" "libiperf.la" )
gcc -DHAVE_CONFIG_H -I.    -g -g -O2 -Wall -MT iperf3-main.o -MD -MP -MF .deps/iperf3-main.Tpo -c -o iperf3-main.o `test -f 'main.c' || echo './'`main.c
mv -f .deps/iperf3-main.Tpo .deps/iperf3-main.Po
/bin/sh ../libtool --tag=CC    --mode=link gcc -g -g -O2 -Wall  -g  -o iperf3 iperf3-main.o libiperf.la -lsctp -lnsl -lsocket -lresolv -lm
libtool: link: gcc -g -g -O2 -Wall -g -o .libs/iperf3 iperf3-main.o  ./.libs/libiperf.so -lsctp -lnsl -lsocket -lresolv -lm -R/usr/local/pkg/iperf-3.1.6/lib
Undefined                       first referenced
 symbol                             in file
fpclassify                          ./.libs/libiperf.so
isnormal                            ./.libs/libiperf.so
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
*** Error code 1
make: Fatal error: Command failed for target `iperf3'

Happy to provide any other information required to help diagnose the issue. I tried running bootstrap.sh, but it didn't change the link issue.

>$ gcc --version
gcc (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by WaterByWind** [comment]
I haven't dug in deep yet to see whether this is an issue with iperf3 or gcc, but this is easily worked around by by defining `CFLAGS="-std=c11"` when running `configure`.

**Comment by bmah888** [comment]
Closing, as there's a workaround for this issue.
