### ISSUE TITLE
I have a question about iperf3's TCP bandwidth setting

### ISSUE THREAD

**Issue by Nimdrak** [esnet/iperf#526]
Hello.
I'm a graduate student majoring in networking.

I know the fact that iperf3.1x can set a TCP flow's rates.
But I cannot imagine why it is possible.
Because, TCP flow is increasing its rate until it reaches to link's bandwidth, before congestion, basically.
I want to find why it is possible in iperf3.1x's source code but I fail.

Could you explain how to limit TCP flow's rate?
is it working like Linux TC?(Linux TC can set queue for each flows for rate limiting, I know)
Please let me know how to limit TCP flow's rate and how it is designed in iperf3.1x source code.

I guess there are two mechanism from iper3 manual.
First is using fair queue of TC. So, each flow have their own queue. So by using this, we limit flow's rate
Second is using iperf3's own rate control algorithm. I don't know this. and I don't know this algorithm in source code.

Could you help me a little?

Help me!
Thanks

**Comment by bmah888** [comment]
Hi @Nimdrak!

iperf3 is able to pace itself.  It might take a bit of study but if you see where the `--bandwidth` parameter gets used, it uses that to limit the rate at which it sends data at the application layer.  See the functions `iperf_send()` and `iperf_check_throttle()` in the file `src/iperf_api.c`.  Of course if TCP determines that the bottleneck bandwidth on the path is less than that, then TCP would control the sending rate.

In addition, as you point out, on newer Linux systems, iperf3 can configure fair-queueing as another rate-limiting mechanism.  This takes place in the packet queues below the TCP/IP stack, so this mechanism can be used to artificially limit the rate at which TCP will allow data to be sent.  This gets configured in various places (search for `SO_MAX_PACING_RATE` in the sources, which is the name of the socket option to use for this).

Hope this helps...

**Comment by Nimdrak** [comment]
Thank you so much :) It really help sto me
