### ISSUE TITLE
UDP server creates TCP connection

### ISSUE THREAD

**Issue by scottgrobinson** [esnet/iperf#531]
Ubuntu 14.04

```
iperf 3.1.7
Linux ORT001 3.13.0-57-lowlatency #95-Ubuntu SMP PREEMPT Fri Jun 19 09:45:24 UTC 2015 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing
```

When running the following client command: sudo iperf3 -c 10.34.152.87 -u -b 10m -p 1235

I get nothing but UDP packets. I see no mention of requiring a TCP connection anywhere, but I'm assuming this might not be the case?

```
tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size 65535 bytes
18:25:56.585054 IP (tos 0x0, ttl 64, id 64352, offset 0, flags [DF], proto TCP (6), length 60)
    10.34.219.143.52579 > 10.34.152.87.1235: Flags [S], cksum 0x8859 (incorrect -> 0x0f6b), seq 867276233, win 26883, options [mss 8961,sackOK,TS val 336820820 ecr 0,nop,wscale 8], length 0

18:26:00.597078 IP (tos 0x0, ttl 64, id 64353, offset 0, flags [DF], proto TCP (6), length 60)
    10.34.219.143.52579 > 10.34.152.87.1235: Flags [S], cksum 0x8859 (incorrect -> 0xffbe), seq 867276233, win 26883, options [mss 8961,sackOK,TS val 336824832 ecr 0,nop,wscale 8], length 0
```

**Comment by bmah888** [comment]
The TCP connection (used for all tests) is a control channel used to communicate the test parameters and results between the client and server.

**Comment by scottgrobinson** [comment]
I feared that would be the case... Time to wait for the darn firewall request to go through! Appreciate the quick response.

(NB - Maybe worth adding that to the 'help' section when running with the UDP command so others know? Or maybe it's just me not thinking it through enough... Who knows)
