### ISSUE TITLE
unclear which algorithms can be passed to -C

### ISSUE THREAD

**Issue by ingenthr** [esnet/iperf#533]
The man page indicates `-C <algo>`, but doesn't define where to get that so now I'm diving through old patches and random websites.  Would be good to update the man page to indicate what that reference is.

**Comment by bmah888** [comment]
We have some information on tuning Linux and FreeBSD TCP (which includes setting the congestion control algorithm) at the following Web pages:

http://fasterdata.es.net/host-tuning/linux/
http://fasterdata.es.net/host-tuning/freebsd/

Pondering whether it's useful to put links to those either in the manpage or the documentation Web site.

**Comment by ingenthr** [comment]
In my particular case, the problem is sort of actually with the hypervisor OS, so I was looking for a workaround.  I was trying to build on an LX brand on SmartOS.  The autoconf detects it as linux, which makes sense, but also detects that it has support for changing congestion control, which it does not.  

I'd hoped to plug in something in the `-C <algo>` to indicate not to specify anything, but that doesn't appear to be an option nor does using other params.  I can hack around it for now, but just FYI, that's how I'd ended up in this situation.

**Comment by ingenthr** [comment]
Was anything done, or just closing because one should just "know"?

**Comment by bltierney** [comment]
I guess I dont quite understand what you are asking for. You can get the list of supported CC algs in Linux by doing:  /sbin/sysctl net.ipv4.tcp_available_congestion_control

By default iperf3 will use this one: /sbin/sysctl net.ipv4.tcp_congestion_control
