### ISSUE TITLE
iperf3 client runs longer than it should if ssh connection hangs

### ISSUE THREAD

**Issue by oakey-b1** [esnet/iperf#535]
It seams only to happen if

1. the time period is higher (e.g. `-t 120`s)
2. the client is receiving (`-R`)
3. multiple streams are used (e.g. `-P 128`)

client command: `iperf3 -c 192.168.100.66 -P 128 -t 120 -R`
```
[SUM]   0.00-209.26 sec  12.0 GBytes   491 Mbits/sec  17425             sender
[SUM]   0.00-209.26 sec  0.00 Bytes  0.00 bits/sec                  receiver
```
```
[SUM]   0.00-210.33 sec  11.5 GBytes   470 Mbits/sec  12479             sender
[SUM]   0.00-210.33 sec  11.4 GBytes   465 Mbits/sec                  receiver
```

after the server shows that it it finished it still takes a while until the ssh connection catches it self again and then shows the results from above.

iperf version (CentOS 7 / from epel repo)
```
Name        : iperf3
Arch        : x86_64
Version     : 3.1.6
Release     : 1.el7
```

**Comment by bmah888** [comment]
Which SSH connection are you talking about?  From what machine to what machine?

**Comment by oakey-b1** [comment]
The ssh connection to the server which is running the iperf3 client

**Comment by bmah888** [comment]
`-P 128` is a lot.  Does it still do this if you're running with fewer parallel streams (like 1 even!).

If that's an important part of your use case, iperf2 might be a better fit for you.

**Comment by bmah888** [comment]
Feedback timeout...closing.  Please re-open if this is still a problem or if my suggestion doesn't work for you.
