### ISSUE TITLE
--get-server-output does NOT obey the -f format specifier

### ISSUE THREAD

**Issue by kburbach** [esnet/iperf#536]
I am running a client with the flag "-fm" to force results to be in "Mbps", but the server results that come back with "--get-server-output" do not always obey this flag. 

Specifically, if the up bandwidth (from client to server) is less that ~1Mbps the client reports in Mbps while the server output is all in Kbps.

I believe all outputs should obey the format specified.

**EDIT**: I am running from the command line

**Comment by bmah888** [comment]
With `--get-server-output`, the clients gets a copy of the output that was generated on the server, but it's the server side that gets to determine how its output is formatted.  If you want to control the formatting of the server-side output you need to pass `-fm` (or whatever variant you have in mind) when invoking the server.  This functionality is actually working as designed.
