### ISSUE TITLE
iperf server and Windows socket client

### ISSUE THREAD

**Issue by JodieChuang** [esnet/iperf#537]
Hi all, 

I want to use iperf to measure the latency of my communication layer. The system is as follows.

iperf_server ----(socket)---> socket_client -----(com-layer)---> socket_server ----(socket)---> iperf_client
         ^---------(socket)----- socket_server <---(com-layer)---- socket_client <----(socket)--------<-|

In this way, I want to measure the bandwidth of the bi-directional communication.
Here, the socket_client and socket_server are customized. socket_client ueses Winsock API.

My question is, iperf_server is not able to send data to socket_client, but socke_client connects with iperf_server. Why doesn't iperf_server send data to socket_client?

Please help. I am very new to iperf. 
Any tips and suggestions are greatly appreciated. Thanks in advance.

Best regards,
Huan

**Comment by JodieChuang** [comment]
I am not sure if here is the right place to ask. If not, please show me a right place. Thanks.

**Comment by bmah888** [comment]
You didn't say which version of iperf you were using, but note that you've posted to the iperf3 issue tracker.  It's not clear to me what the "socket_client" and "socket_server" are supposed to be; iperf3 (and similar tools like it) are designed to communicate directly over an IP network.  They're only supported on UNIX-like platforms although some people have made Windows executables available.

Also note that the iperf3 client and server use a TCP-based control connection to exchange test data and results.  If your Windows client doesn't speak the protocol used over the control connection (which we have never documented aside from comments in the code) it's probably not going to do what you want.  

It almost feels to me that iperf3 is not the tool you want to use, but to be honest it's a little difficult for me to understand what you're trying to measure.

**Comment by JodieChuang** [comment]
Hi, I am using iperf3 in Windows.

My first step is to make iperf3 server talk to Winsock client. Winsock
programming centers around TCP/IP. (
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740673(v=vs.85).aspx)

I am using this sample code (
https://msdn.microsoft.com/en-us/library/windows/desktop/ms737591(v=vs.85).aspx)
as the client. The result is that
(1) the connection is done;
(2) client sends the message to iperf3 server, however I am not sure if
iperf3 receives it properly since I don't know how to do debuging at the
iperf3 server side, but the sending function at wincosk client is finished
without error;
(3) client receiving hangs due to some unknown reason.

So I wonder if I can use iperf3 with such a customized TCP-based client.
Any suggestions?

2017年3月30日 18:25，"Bruce A. Mah" <notifications@github.com>写道：

You didn't say which version of iperf you were using, but note that you've
posted to the iperf3 issue tracker. It's not clear to me what the
"socket_client" and "socket_server" are supposed to be; iperf3 (and similar
tools like it) are designed to communicate directly over an IP network.
They're only supported on UNIX-like platforms although some people have
made Windows executables available.

Also note that the iperf3 client and server use a TCP-based control
connection to exchange test data and results. If your Windows client
doesn't speak the protocol used over the control connection (which we have
never documented aside from comments in the code) it's probably not going
to do what you want.

It almost feels to me that iperf3 is not the tool you want to use, but to
be honest it's a little difficult for me to understand what you're trying
to measure.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/esnet/iperf/issues/537#issuecomment-290464862>, or mute
the thread

**Comment by JodieChuang** [comment]
Oh, I sorry that I mix up thing. I am using iperf-3.1.3-win64, not iperf3.

**Comment by JodieChuang** [comment]
I am using iperf-3.1.3-win64,

**Comment by bmah888** [comment]
It sounds like you are basically trying to recreate what iperf3 does, using your own code?  Still trying to understand what you want to do, and, not knowing much if anything about Windows networking.

If you're trying to do a measurement of a path, then you shouldn't need to do anything with your own code just to use iperf3.  If you're trying to write your own measurement code, then there are probably easier ways to do this than to try to communicate with iperf3.

**Comment by JodieChuang** [comment]
Hi,
I have a system composed of a host application and a guest application. The guest application runs in a virtual platform emulated by QEMU. I made the communciation of the host app and guest app via a Windows named pipe. Now I want to measure the performance of this communication layer. The guest OS is linux and the host OS is Windows. Since the linux API does not provide a time precision of mircosecond, I am thinking to use iperf3 for the measurements. Of course, I need to rewrite something in iperf3 sourse since it uses TCP-based socket. 

How to perform the measurements really makes me a headache. Do you think it possible to do something rewriting to make iperf applicable for Windows named pipe interface? 
The thoughts from iperf3 mainainters are very helpful to me indeed.

Best,
Huan

**Comment by bmah888** [comment]
Not being familiar with Windows named pipes, I don't know of an easy way to do this.  You might see if iperf2, or some other measurement tool that explicitly supports the Windows platform, provides the functionality you need.
