### ISSUE TITLE
simultaneous bidirectional test in Iperf3

### ISSUE THREAD

**Issue by MrStonedOne** [esnet/iperf#541]
@bltierney
>iperf3 design makes this pretty impossible.

Explain why, in details.

You are talking to developers, don't bullshit us.

Spawn a new thread, call the client function with the connected client as the server argument, and bam, issue solved.

If you are abusing globals, and can't call a client function with a server arg, well, that's your bed, you made it, now you lie in it. Don't abuse globals.

**Comment by bmah888** [comment]
Duplicate of #201.  Submitting a series of duplicate bug reports that are essentially demands is highly antisocial.
