### ISSUE TITLE
cross-compile Iperf for ARM

### ISSUE THREAD

**Issue by JodieChuang** [esnet/iperf#543]
Hi, 

I followed the steps in readme, configured and made "iperf3", but get this error when running it:

iperf-master$ export CROSS_COMPILE=~/Downloads/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabi/bin/arm-linux-gnueabi-

iperf-master$ ./configure --build=arm-linux-gnueabi --host=arm-none-linux-gnueabi

iperf-master$ make CFLAGS=-static CXXFLAGS=-static

iperf-master/src$ file iperf3

iperf3: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 2.6.16, BuildID[sha1]=14e8f0fadbba0bb786975ddf28e3d3b6d8ca79b5, not stripped

iperf-master/src$ ./iperf3 -s
/lib/ld-linux.so.3: No such file or directory

iperf-master/src$ ls ~/Downloads/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabi/libc/lib/ld-linux*
/Downloads/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabi/libc/lib/ld-linux.so.3

Why does it complain the missing of an existing library?

Best,
Huan

**Comment by JodieChuang** [comment]
Solved. Some lib is missing in my system.
do "sudo apt install glibc-*" to install the lids. Now it is working. Please close the thread.

**Comment by JodieChuang** [comment]
Solved! 
the problem is that the iperf3 is [Requesting program interpreter: /lib/ld-linux.so.3]
Linking the requested library in the cross compiling tool-chain to the requested location solved it.

**Comment by JodieChuang** [comment]
Bad luck! after reconfiguration and recompilation, now the PROBLEM is 

iperf-master/src$ file iperf3
iperf3: POSIX shell script, ASCII text executable, with very long lines
iperf-master/src$ ./iperf3 -s
/iperf-master/src/.libs/lt-iperf3: error while loading shared libraries: libm.so.6: cannot open shared object file: No such file or directory

Any clue??

**Comment by TheRealDJ** [comment]
Normal compilation creates iperf3 "binary" as a script the references the shared libraries. Try adding "--enable-static --disable-shared" to your configure params. So ...

./configure --build=arm-linux-gnueabi --host=arm-none-linux-gnueabi --enable-static --disable-shared

**Comment by bmah888** [comment]
I've never needed to do the cross-compiling thing, but I think that's the right answer (the script is a part of GNU libtool).  Thanks for answering, @TheRealDJ!

**Comment by krisarmstrong** [comment]
What steps did you take.  No matter what I do it shows dynamic

**Comment by tom-shen-asus** [comment]
How build Windows Arm64 iperf?
