### ISSUE TITLE
iperf 3.0.3 crashes Windows 7 guest on ESXi 6.0 - repeatable

### ISSUE THREAD

**Issue by tqmbill** [esnet/iperf#546]
Running iperf 3.0.3 server on a Win2012 R2 guest on ESXi 6 host.
Initiated test from Win 7 client VM on the same host machine with this command:
   iperf3 -c 172.16.10.xxx -p 45678 -t 10  
Response from server is:
-----------------------------------------------------------
Accepted connection from 172.16.10.xxx, port 56813
[  5] local ### 172.16.10.xxx port 45678 connected to 172.16.10.xxx port 56814
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec   514 MBytes  4.31 Gbits/sec
[  5]   1.00-2.00   sec   685 MBytes  5.75 Gbits/sec
[  5]   2.00-3.00   sec   679 MBytes  5.70 Gbits/sec
[  5]   3.00-4.00   sec   209 MBytes  1.76 Gbits/sec
[  5]   4.00-5.00   sec   259 MBytes  2.17 Gbits/sec
[  5]   5.00-6.00   sec   170 MBytes  1.42 Gbits/sec
[  5]   6.00-7.00   sec   759 MBytes  6.37 Gbits/sec
[  5]   7.00-8.00   sec   719 MBytes  6.03 Gbits/sec
[  5]   8.00-9.00   sec   706 MBytes  5.92 Gbits/sec
[  5]   9.00-10.00  sec   788 MBytes  6.61 Gbits/sec
[  5]  10.00-**10.37**  sec   278 MBytes  6.27 Gbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.37  sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-10.37  sec  5.63 GBytes  4.66 Gbits/sec                  receiver
-----------------------------------------------------------
Server listening on 45678
-----------------------------------------------------------

Note that the speed is both erratic and low for GB network.  And moreover, the normal 0.00 seconds on the 10th test was 0.37 sec... I presume this is because it crashes, every time, after the 9th test.  
Upon powering off/on the VM, i get this bugcheck report:

   The computer has rebooted from a bugcheck.  
      0x00000027 (0x00000000baad0073, 0xfffff88006c77188, 0xfffff88006c769e0, 0xfffff80002ad7f8e). 

BTW, testing from a client Win2012R2 VM to the same server was successful.

**Comment by bmah888** [comment]
It's not clear what the underlying issue is...noting that Windows is not an officially supported platform.  You might be better off trying your tests with iperf2.

**Comment by bmah888** [comment]
No feedback on this issue, and I added a FAQ to a possibly-related issue (#590).  Closing for now.
