### ISSUE TITLE
Graceful failure of --congestion on server

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#549]
iperf3 allows setting of the TCP congestion control algorithm with the `--congestion` flag on Linux and FreeBSD.  Currently iperf3 tries to set the same algorithm on both client and server (because either can play the role of sender or receiver).  However the client and server might not have the same set of congestion control algorithms available (for example, if an algorithm is loaded via a kernel module on one machine, but not another).

The requested enhancement (per suggestion from @bltierney) is to emit a warning if setting the congestion control algorithm on the server fails, but to otherwise continue.  This seems reasonable, noting that server processes running on platforms with no pluggable congestion control modules will work fine with no warning at all.

**Comment by bltierney** [comment]
FWIW, I don't think its particularly important that this error gets propagated back to the client. Sure, it would be nice, but its not critical. More important is the ability to do bbr testing if you have a bbr client (or whatever new CC alg. you want to test).

**Comment by bmah888** [comment]
I wonder if it makes sense (and if it's possible) to warn on the server side at least.  It feels weird to just let this fail silently, especially if someone's going to try a `--reverse` test.  According to what I wrote, iperf3's behavior with a non-pluggable-congestion-control-aware server can be interpreted as broken too.

**Comment by bltierney** [comment]
Yeah, it would be good to print a warning on the server side, at least in non-daemon mode.

**Comment by bmah888** [comment]
Tested this with two VMs with different sets of congestion control algorithm modules loaded.  Merged to 3.1-STABLE.  Closing.
