### ISSUE TITLE
Surface 3 Pro parallel streams

### ISSUE THREAD

**Issue by gthb96** [esnet/iperf#552]
Hello
I came to a strange issue while testing Wifi performance.
When doing "iperf3 -c IP -P 4" I get around 450mbps to a wired server.

When doing anything more than 4 parallel connections it gets weird.
It starts with 450mbps then drops down to about 100mbps and after a few seconds it goes up to 450mbps again.

So from 1-4 parallel connections I get stable 450mbps all the time but with >4 connections it starts with 450, goes down to 100 and then stays at 450 again. CPU usage is not a problem.

This is just happening with Windows.
I tested it with Ubuntu 17.04 on the Surface and there I get 450mbps all the time.

What could be the cause that this happens just with Windows 10 and just on the Surface 3 Pro for me?
Is Windows doing something weird with parallel TCP streams or whats going on?

Edit:
I just left cmd.exe open for about 20 minutes and did the test again with 6 parallel streams a couple of times.
I got continuous 450mbps for a few minutes.
As soon as I opened a second cmd.exe window the issue came back.
Is Windows messing with something?

Edit2:
Just tested a USB wifi dongle on the Surface and the problem with more than 4 streams persists although the dongle works for more than 4 streams on another computer.
Also when doing a UDP test with more than 4 streams on Surface over the wifi dongle the throughput goes down to 0!

What makes the Surface to be problematic with iperf?

**Comment by gthb96** [comment]
Maybe some screenshots help :)
First one is with 4 connections and second one is with 5.
<img width="150" alt="4tcp streams" src="https://cloud.githubusercontent.com/assets/26583737/25145875/815a487a-2472-11e7-9c94-30261b7a858e.PNG">
<img width="146" alt="5tcp streams" src="https://cloud.githubusercontent.com/assets/26583737/25145878/83b37d4e-2472-11e7-8447-8235932f6ac0.PNG">

**Comment by bltierney** [comment]
windows is not supported by iperf3. Have you tried iperf2.0.8, which has does support windows.?

For more info, see: http://software.es.net/iperf/faq.html

**Comment by bmah888** [comment]
OP, are you still seeing this problem?

Also it might be useful to look at some of the comments attached to issues #463 or #375 regarding old versions of Cygwin libraries and network performance.

**Comment by bltierney** [comment]
no reply, so closing.
