### ISSUE TITLE
cport issue

### ISSUE THREAD

**Issue by navigationhi** [esnet/iperf#555]
Iperf3 Version : iperf 3.1.3

The cport function is working well in two PC connect directly. show my test command as below : 
iperf3 -s -p 20000
iperf3 -c 172.16.1.1 -u -B 172.16.1.2 --cport 20000 -p 20000 -t 10 -b 10m -l 1000 -i 1

But the cport funtion doesn't work in routing mode or NAT mode, the client port still random. show my test command as below : 
iperf3 -s -p 20000
iperf3 -c 10.1.1.1 -u -B 172.16.1.2 --cport 20000 -p 20000 -t 10 -b 10m -l 1000 -i 1

**Comment by bltierney** [comment]
This seems like a system / NAT issue, not an iperf3 issues per se. I dont think this will work.

**Comment by wangqianyv123** [comment]
I have same problem. How to do?
