### ISSUE TITLE
argument parsing error in 'master' branch: default block size not getting set?

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#559]
./src/iperf3 -u -c nettest.lbl.gov
iperf3: parameter error - block size invalid (minimum = 16 bytes, maximum = 65507 bytes)

This works fine in 3.1.7, so its something introduced recently.
(setting '-l' flag fixes it.)

**Comment by bmah888** [comment]
Yeah I probably botched that in 03224c9f56cd59f7375db10c59cb09233f36f392.  Will look, fortunately this code change (for #390) didn't make it into any build yet.
