### ISSUE TITLE
UDP receiver reports 0 for bytes and bits/sec

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#560]
iperf3 version: 'master' branch

client: /iperf3 -c nettest.lbl.gov -p 5300 -u -b 5m -l 1000 -t 5

server: 
[  5]   0.00-1.00   sec  96.7 KBytes   792 Kbits/sec  7.973 ms  0/99 (0%)
[  5]   1.00-2.00   sec   102 KBytes   832 Kbits/sec  8.045 ms  0/104 (0%)
[  5]   2.00-3.00   sec  99.6 KBytes   816 Kbits/sec  9.123 ms  532/634 (84%)
[  5]   3.00-4.00   sec  99.6 KBytes   816 Kbits/sec  10.882 ms  592/694 (85%)
[  5]   4.00-5.00   sec   102 KBytes   832 Kbits/sec  14.478 ms  589/693 (85%)
[  5]   5.00-6.00   sec   101 KBytes   824 Kbits/sec  23.900 ms  591/694 (85%)
[  5]   6.00-6.91   sec  93.8 KBytes   841 Kbits/sec  7.998 ms  0/96 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-6.91   sec  **0.00 Bytes  0.00 bits/sec**  7.998 ms  2304/3014 (76%)

**Comment by bmah888** [comment]
The 3.1-STABLE branch has this problem too BTW.

The problem is (at least partly) in the function `iperf_print_results()`, which prints the summary statistics at the end of the test.  For TCP and SCTP it prints two lines, one for the sender and one for the receiver.  For UDP it prints only one line, and the data on that line seems to be a mixture between sender data and receiver data.

Note that any solution to this problem needs to preserve the structure of the emitted JSON.

**Comment by bmah888** [comment]
With test code on the issue-560 branch...client:
```
Bruce-Mahs-MBP:iperf% src/iperf3 --client localhost --bandwidth 1g -t 5 --udp
Connecting to host localhost, port 5201
warning: Block size 16312 > sending socket buffer size 9216
Increasing socket buffer size to 17336
[  6] local ::1 port 60482 connected to ::1 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  6]   0.00-1.00   sec   119 MBytes   999 Mbits/sec  7659
[  6]   1.00-2.00   sec   119 MBytes  1000 Mbits/sec  7663
[  6]   2.00-3.00   sec   119 MBytes  1000 Mbits/sec  7662
[  6]   3.00-4.00   sec   119 MBytes  1000 Mbits/sec  7663
[  6]   4.00-5.00   sec   119 MBytes  1.00 Gbits/sec  7665
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  6]   0.00-5.00   sec   596 MBytes  1000 Mbits/sec  0.045 ms  0/38312 (0%)  sender
[  6]   0.00-5.00   sec   187 MBytes   313 Mbits/sec  0.045 ms  26313/38312 (69%)  receiver

iperf Done.
```

Server (default parameters):

```
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from ::1, port 56762
warning: Block size 16312 > sending socket buffer size 9216
Increasing socket buffer size to 17336
[  5] local ::1 port 5201 connected to ::1 port 60482
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  35.7 MBytes   299 Mbits/sec  0.050 ms  5367/7659 (70%)
[  5]   1.00-2.00   sec  35.1 MBytes   294 Mbits/sec  0.039 ms  5407/7662 (71%)
[  5]   2.00-3.00   sec  38.7 MBytes   325 Mbits/sec  0.031 ms  5172/7662 (68%)
[  5]   3.00-4.00   sec  43.2 MBytes   362 Mbits/sec  0.028 ms  4887/7663 (64%)
[  5]   4.00-5.00   sec  34.0 MBytes   285 Mbits/sec  0.045 ms  5480/7666 (71%)
[  5]   5.00-5.00   sec  0.00 Bytes  0.00 bits/sec  0.045 ms  0/0 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-5.00   sec   187 MBytes   313 Mbits/sec  0.045 ms  26313/38312 (69%)  receiver
```

Note that although this bug was originally filed against UDP, the fix alters the output of TCP and SCTP tests as well on the server side.

**Comment by bmah888** [comment]
@bltierney:  Want to play around with the code on the issue-560 branch and tell me if that's what you had in mind?  It's close to what you saw when you dropped by my desk.  I'll file another bug (or reopen a prior one if it exists) for the "very short last measurement interval" problem.

**Comment by bltierney** [comment]
Its a lot better, but the value reported at the server does not match what is reported on the client.

For example, running this command: ./iperf3 -c nettest.lbl.gov -p 5300 -u -b 9M -t 5

I see this summary on the server:
[  5]   0.00-5.05   sec  5.36 MBytes  8.92 Mbits/sec  0.038 ms  0/4018 (0%)  receiver

And this on the sender:

[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-5.00   sec  5.36 MBytes  9.00 Mbits/sec  0.038 ms  0/4018 (0%)  sender
[  4]   0.00-5.00   sec  5.36 MBytes  9.00 Mbits/sec  0.038 ms  0/4018 (0%)  receiver

I'd expect the second line above to match the line on the server side.

**Comment by bmah888** [comment]
Yep, that's a problem.  Here's what I think is happening.  The server has its own idea of how long the test took (5.05 seconds in your example).  The client statistics computation needs to use that value in the appropriate place (receiver for a normal test, sender for a reverse tests), but it's instead using its own timing for both sides.

I think (but I'm not sure yet) that the fix is that the server needs to pass its own "end time" back to the client (it doesn't seem to do that now), and the client needs to use that value where needed.

**Comment by bltierney** [comment]
yeah, that sounds like the right way to do it to me too.

**Comment by bmah888** [comment]
@bltierney:  Does this work better?  I wasn't able to come up with a good test case for this (like is there a pair of ESnet machines that can exhibit this behavior reliably?  machines that are far apart?).

**Comment by bltierney** [comment]
That looks good!  I can reliable replicate the use case between antg-staging.es.net and nettest.lbl.gov.

I did noticed a compiler warning you might want to address:

iperf_api.c:2702:19: warning: ‘lost_percent’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       iperf_printf(test, report_bw_udp_format, sp->socket, start_time, receiver_time, ubuf, nbuf, sp->jitter * 1000.0, (sp->cnt_error - sp->omitted_cnt_error), (sp->packet_count - sp->omitted_packet_count), lost_percent, report_receiver);
                   ^
iperf_api.c:2529:58: note: ‘lost_percent’ was declared here
     double start_time, end_time = 0.0, avg_jitter = 0.0, lost_percent;

**Comment by bmah888** [comment]
3f6325cff0f80dd6a4436ff61dcb3b6304604236 fixed the compiler warning but I forgot to cross-reference this bug in the commit message.

**Comment by bmah888** [comment]
Here's the current state of output for a UDP test, this is with the code on the issue-560 branch.  Note that on the client side we're now printing the summary for both sides of the test, with each side called out explicitly.  On the sender side we only print out the parts of the summary where we actually have data.  Also the client and sender side are printing consistent summaries.

```
[bmah@antg-staging iperf]$ src/iperf3 -4 --client antg-dev.es.net --port 5202 --time 5 --udp --bandwidth 500m
Connecting to host antg-dev.es.net, port 5202
[  4] local 198.128.151.25 port 41555 connected to 198.128.151.17 port 5202
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec  57.8 MBytes   485 Mbits/sec  41840
[  4]   1.00-2.00   sec  61.4 MBytes   515 Mbits/sec  44477
[  4]   2.00-3.00   sec  59.6 MBytes   500 Mbits/sec  43142
[  4]   3.00-4.00   sec  59.6 MBytes   500 Mbits/sec  43168
[  4]   4.00-5.00   sec  59.6 MBytes   500 Mbits/sec  43156
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-5.00   sec   298 MBytes   500 Mbits/sec  0.015 ms  0/215783 (0%)  sender
[  4]   0.00-5.04   sec   288 MBytes   479 Mbits/sec  0.015 ms  7388/215783 (3.4%)  receiver

iperf Done.
```

```
-----------------------------------------------------------
Server listening on 5202
-----------------------------------------------------------
Accepted connection from 198.128.151.25, port 50904
[  5] local 198.128.151.17 port 5202 connected to 198.128.151.25 port 41555
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  53.3 MBytes   447 Mbits/sec  0.061 ms  2367/40950 (5.8%)
[  5]   1.00-2.00   sec  56.7 MBytes   476 Mbits/sec  0.282 ms  2448/43507 (5.6%)
[  5]   2.00-3.00   sec  58.3 MBytes   489 Mbits/sec  0.026 ms  1129/43344 (2.6%)
[  5]   3.00-4.00   sec  58.9 MBytes   494 Mbits/sec  0.015 ms  479/43138 (1.1%)
[  5]   4.00-5.00   sec  58.3 MBytes   489 Mbits/sec  0.018 ms  965/43166 (2.2%)
[  5]   5.00-5.04   sec  2.32 MBytes   497 Mbits/sec  0.015 ms  0/1678 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-5.04   sec   288 MBytes   479 Mbits/sec  0.015 ms  7388/215783 (3.4%)  receiver
```

**Comment by gourabm1981** [comment]
I am using Iperf3.4 and I do still see some mismatch in the server and client outputs .
So i ran a Downstream UDP test (-R option) and the results are as below -

Client side 

iperf -c 3800:0:0:271c::f -R -u -b 0 -P 8
 Connecting to host 3800:0:0:271c::f, port 5201
Reverse mode, remote host 3800:0:0:271c::f is sending
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  1]   0.00-1.10   sec  7.31 MBytes  55.7 Mbits/sec  0.474 ms  1158/6480 (18%)  
[  3]   0.00-1.10   sec  7.71 MBytes  58.8 Mbits/sec  0.451 ms  866/6480 (13%)  
[  4]   0.00-1.10   sec  7.87 MBytes  60.0 Mbits/sec  0.486 ms  751/6479 (12%)  
[  5]   0.00-1.10   sec  8.09 MBytes  61.7 Mbits/sec  0.491 ms  585/6479 (9.03%)  
[  6]   0.00-1.10   sec  7.73 MBytes  59.0 Mbits/sec  0.573 ms  848/6479 (13%)  
[  7]   0.00-1.10   sec  7.21 MBytes  55.0 Mbits/sec  0.522 ms  1230/6479 (19%)  
[  8]   0.00-1.10   sec  7.14 MBytes  54.5 Mbits/sec  0.497 ms  1277/6479 (20%)  
[  9]   0.00-1.10   sec  7.14 MBytes  54.5 Mbits/sec  0.514 ms  1267/6469 (20%)  
[SUM]   0.00-1.10   sec  60.2 MBytes   459 Mbits/sec  0.501 ms  7982/51824 (15%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[SUM]   0.00-10.23  sec  3.33 GBytes  2.79 Gbits/sec  0.000 ms  0/2481270 (0%)  sender
[SUM]   0.00-12.51  sec   566 MBytes   380 Mbits/sec  0.635 ms  1506183/1918521 (61%)  receiver


server side 

-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 3800::26a1:0:0:ffff:ffec, port 55625
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-10.23  sec   425 MBytes   349 Mbits/sec  0.000 ms  0/309610 (0%)  sender
[  6]   0.00-10.23  sec   429 MBytes   352 Mbits/sec  0.000 ms  0/312600 (0%)  sender
[  9]   0.00-10.23  sec   429 MBytes   352 Mbits/sec  0.000 ms  0/312190 (0%)  sender
[ 11]   0.00-10.23  sec   423 MBytes   347 Mbits/sec  0.000 ms  0/308360 (0%)  sender
[ 13]   0.00-10.23  sec   428 MBytes   351 Mbits/sec  0.000 ms  0/311620 (0%)  sender
[ 15]   0.00-10.23  sec   423 MBytes   347 Mbits/sec  0.000 ms  0/307990 (0%)  sender
[ 17]   0.00-10.23  sec   423 MBytes   347 Mbits/sec  0.000 ms  0/307690 (0%)  sender
[ 19]   0.00-10.23  sec   427 MBytes   350 Mbits/sec  0.000 ms  0/311210 (0%)  sender

[SUM]   0.00-10.23  sec  3.33 GBytes  2.79 Gbits/sec  0.000 ms  0/2481270 (0%)  sender

As you can see the total bytes datagrams are different on the server and client side . 
Same issue seen with Upstream test (without -R option) . Is this a bug ?

**Comment by wu0407** [comment]
test on the udp,  version 3.6, same output 

###on the client
```
[SUM]   0.00-60.00  sec   288 MBytes  40.2 Mbits/sec  0.000 ms  0/18863480 (0%)  sender
[SUM]   0.00-60.00  sec   244 MBytes  34.1 Mbits/sec  0.013 ms  979399/16947617 (5.2%)  receiver
```

### on the server
```
[SUM]   0.00-60.00  sec   244 MBytes  34.1 Mbits/sec  0.013 ms  979399/16947617 (5.8%)  receiver
```
packets  different on the server and client side,  server not receive 18863480 -  16947617 =  1915863 packets.  the server report lost packets is 979399.
 how to count lost packets on server, and server know the packet lost? 
can  explain the result?
