### ISSUE TITLE
Make Check fails with FAIL: t_units

### ISSUE THREAD

**Issue by coderxx** [esnet/iperf#561]
# Make Check error while building from source on Raspberry Pi

* Version of iperf3: source build master branch

* Hardware: Raspberry Pi B+ 

* Operating system (and distribution, if any): 
    Distributor ID: Raspbian
    Description:    Raspbian GNU/Linux 8.0 (jessie)
    Release:        8.0
    Codename:       jessie

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

Compiling with gcc version 4.9.2
[test-suite.txt](https://github.com/esnet/iperf/files/970022/test-suite.txt)

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate._

# Bug Report

While building iperf3 from master branch, make check fails with the above error. If i continue and make, make install, running the iperf3 binary results in an ILLEGAL ACTION error

* Expected Behavior
Compile and run iperf3 tests.

* Actual Behavior
Produces error "ILLEGAL ACTION"

* Steps to Reproduce
sudo ./configure; 
sudo make;
sudo make install
iperf3 -s 

* Possible Solution

_Please submit patches or code changes as a pull request._

# Enhancement Request

* Current behavior

* Desired behavior

* Implementation notes

_If submitting a proposed implementation of an enhancement request,
please use the pull request mechanism._

**Comment by bmah888** [comment]
This seems to be Raspberry Pi specific, or at least somewhat platform-specific.  We don't see this problem on (for example) macOS or CentOS 7.

It might be specific to e9e2d6d19c713f9a849609eb32a6cc06d7cc211a (for #402).  Upon a quick read of that file, I notice that I did some not-so-great code where I tried to assign a floating point value to a long.  Perhaps `TERA_UNIT` and `TERA_RATE_UNIT`, et al. should be `const double` instead (including the ones that existed in the file originally).

**Comment by bmah888** [comment]
@coderxx:  Can you try the tip of master again with a fix I just pushed?  (This is one of those "I'm not sure how it ever worked" bugs.)  Thanks.

**Comment by coderxx** [comment]
@bmah888 - Seemed to fix the issue perfectly!.  The new master branch compiled perfectly and runs well as far as I can see. I've done a few tests. Thank you 👍

**Comment by bmah888** [comment]
Thanks for the testing!  Merged to the 3.1-STABLE branch so it's fixed everywhere.
