### ISSUE TITLE
Additional TCP_INFO items to be saved in the JSON output

### ISSUE THREAD

**Issue by bltierney** [esnet/iperf#569]
Currently we are capturing the following:

        tcp_info.tcpi_retrans,
        tcp_info.tcpi_snd_cwnd,
        tcp_info.tcpi_rtt,

I think we should go ahead and capture several more of the TCP_INFO fields, as they might be useful for various types of analysis. In particular, I'd like to have (for Linux):

        tcp_info.tcpi_snd_ssthresh,
        tcp_info.tcpi_rcv_ssthresh,
        tcp_info.tcpi_rttvar,
        tcp_info.tcpi_sacked,
        tcp_info.tcpi_lost,
        tcp_info.tcpi_fackets
        tcp_info.tcpi_snd_wscale
       tcp_info.tcpi_rcv_wscale
       tcp_info.tcpi_rto
       tcp_info.tcpi_ato
       tcp_info.tcpi_snd_mss
       tcp_info.tcpi_rcv_mss
       tcp_info.tcpi_pmtu
       tcp_info.tcpi_advmss
       tcp_info.tcpi_reordering
       tcpi_rcv_rtt;
       tcpi_rcv_space;
       tcpi_total_retrans;

Highest on my wish list are tcpi_rttvar, tcpi_pmtu, and tcpi_rcv_space.

I have no idea what the difference between tcpi_total_retrans and tcpi_retrans is. 
Need to look into that.

Note that this is a replacement for issue #99

**Comment by bmah888** [comment]
Just a note that `tcpi_rttvar` was added by #525 / #534.

**Comment by bmah888** [comment]
FreeBSD and NetBSD don't have `tcpi_pmtu`, so this is Linux-only at least for now.

**Comment by bmah888** [comment]
Here's an example of PMTU, which we're recording per-stream, per-interval. That's probably more often than is really needed:
```
			"streams":	[{
					"socket":	4,
					"start":	0,
					"end":	1.0021219253540039,
					"seconds":	1.0021219253540039,
					"bytes":	77112,
					"bits_per_second":	615589.76447110344,
					"retransmits":	8,
					"snd_cwnd":	2856,
					"rtt":	329,
					"rttvar":	318,
					"pmtu":	1500,
					"omitted":	false
				}],
```
@bltierney is this what you had in mind?

**Comment by bmah888** [comment]
Regarding an off-line discussion on the `tcpi_retrans` vs. `tcpi_total_retrans`.  The latter `tcpi_total_retrans` is the cumulative number of TCP retransmissions on the connection.  That value is being saved now.

`tcpi_retrans` is more of a state variable.  It comes from the `retrans_out` field in the TCP PCB, like this line in `tcp.c` in the Linux kernel:
```
info->tcpi_retrans = tp->retrans_out;
```
That in turn basically counts the number of packets in the retransmit queue for whom a retransmission is currently in flight.

```
 * We have three tag bits: SACKED(S), RETRANS(R) and LOST(L).
 * Packets in queue with these bits set are counted in variables
 * sacked_out, retrans_out and lost_out, correspondingly.
```
Not sure how useful this would be but anyway, 7b4f1a4cf9bd00d7bb8006ca9970703f96594574 on the issue-569 branch grabs this value and puts it into the JSON output, per-stream, in a member named `tcpi_retrans`.

**Comment by bltierney** [comment]
Good to know. I agree that tcpi_retrans is not particularly useful for iperf3.

**Comment by bmah888** [comment]
Pulling this issue back to 3.2.x.  There are other `tcp_info` structure members that are interesting, but none of these should block the 3.2 release.  We should consider which ones to do next.  To recap those in the original enhancement request:  `tcpi_rttvar` was already in the code, `tcpi_pmtu` has been added, and after some investigation `tcpi_rcv_space` and `tcp_retrans` don't quite do what we want.

**Comment by bmah888** [comment]
Closing. The scope of this item is too broad to be meaningful. If there are specific items that we want to add, we should open up issues for those.
