### ISSUE TITLE
Client hangs when testing with duration of 300 seconds

### ISSUE THREAD

**Issue by elad** [esnet/iperf#572]
# Context

* Version of iperf3: 3.0.11

* Hardware: VM

* Operating system (and distribution, if any): Ubuntu Linux 16.04.02 LTS

# Bug Report

Try to run a test between two hosts for 300 seconds. The`client.run()` function doesn't return.

* Expected Behavior

The function should return.

* Actual Behavior

The function does not return.

* Steps to Reproduce

On host A:

```
$ iperf3 -s
```

On host B:

```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import iperf3
>>> client = iperf3.Client()
>>> client.server_hostname = 'A'
>>> client.port = 5201
>>> client.duration = 300
>>> result = client.run()
[this will hang forever]
```

**Comment by bmah888** [comment]
It looks like you're using the iperf3 Python package.  That package is maintained separately from iperf3 itself, by a completely separate set of developers.  If you're having an issue with this Python integration, you should probably invoke whatever support mechanism there is for this package.  I'd start here:

https://pypi.python.org/pypi/iperf3

One troubleshooting tip for you:  See if iperf3 (the regular executable) works as a client on host B.

**Comment by elad** [comment]
You're absolutely right. Sorry for the noise. FWIW, I "fixed" it by using iperf3's `--json` switch and parsing the output myself (no module).

**Comment by bmah888** [comment]
No worries, glad you got things working and thanks for the follow-up.
