### ISSUE TITLE
Unnecessary machine identification in cookie

### ISSUE THREAD

**Issue by Safari77** [esnet/iperf#576]
# Context

* Version of iperf3:
git

* Hardware:
x86_64 SandyBridge

* Operating system (and distribution, if any):
Fedora 25

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate._

# Bug Report

* Expected Behavior
No identifying information about the system is needed when doing a bandwidth test.

* Actual Behavior
Spy cookie is sent on each test, which includes hostname and system's time in microsecond precision.

* Steps to Reproduce
Just run it.

* Possible Solution
Cookie can be ascii-string  with entropy from `/dev/urandom` or `getrandom(2)` and equivalent system calls.

In addition to the cookie, also `sp->buffer` is initialized with random data. On slow systems reading from `/dev/urandom` might be, well, slow. I implemented the random stuff by reading first a seed, then filling the buffers with `arc4random_buf` (libressl-portable).  If you disagree, nice, code would be a lot less simpler.

I haven't published the code as of yet, but it's working.

**Comment by bmah888** [comment]
I think the term "spy cookie" is a bit of an exaggeration.  But I'm doing a little research to try to figure out why we put this information in the cookie, instead of using, say, a random UUID.

How big of a problem is the initialization of `sp->buffer`?  We only do this once per stream at the start of the test.  I don't object in principle to initializing in a different way, but I'd like to not introduce any new dependencies into iperf3.

**Comment by Safari77** [comment]
`MAX_BLOCKSIZE` is 1048576. Some systems have read speeds below 10 MiB/s from `/dev/urandom`... For example, my Android device OnePlus 3 has 12 MiB/s. So if it needs on some slow system for example 0.25s to init the buffer, I don't think that's very nice.

Using `srandom(time(NULL))` and `random` to fill the buffer also leaks info about the system time.
You wouldn't need to add a new dependency, if you include the needed module directly into iperf repo...

**Comment by bmah888** [comment]
@Safari77 : OK after a bit of discussion, I learned that there's no particular reason, historically, for the hostname or timestamp to be in the cookie.  In fact the cookie appears to have been UUID-based originally (which I think we agree would make sense, among different alternatives) but it was removed for the sake of "portability".  I'm not sure what to make of that decision, which happened about five years ago.  An entropy-generated ASCII string, as you suggested, would be fine with me too.

About the buffer initialization, I'm honestly not too worried about a quarter second operation that happens once at the start of a test.  I don't object to doing it a different way, as long as it doesn't break our supported platforms (and ideally wouldn't break any platform)...it's not at the top of my personal priority list to work on, so if you have something working maybe we can discuss that a bit.

Sound fair?

**Comment by Safari77** [comment]
OK then. If you just make a function which reads from /dev/urandom using `fread` (and keeps file open)... `size_t readentropy(void *out, size_t len)` , it could be used for both reading entropy for the cookie, and for filling the`sp->buffer`. Or would you like a pull request?

**Comment by bmah888** [comment]
I can't guarantee that I'd merge a pull request, but if it's not too much trouble, yes we'd like see a pull request with the change you have in mind.  Thanks!

**Comment by bmah888** [comment]
Merged pull request #582, which implements this enhancement request.  Closing.

**Comment by TheRealDJ** [comment]
Any chance the old Cookie value could be re-enabled with a client flag? We use this value to track results back to a device.

Thanks. 
DJ

**Comment by bmah888** [comment]
I think I like your latest proposed implementation for #600.  Let's continue talking about it in that issue thread.
