### ISSUE TITLE
dual test and reverse mode is not working from client side

### ISSUE THREAD

**Issue by pradeep75** [esnet/iperf#598]
Hi,

We have successfully cross-compiled iperf 2.0.5 source for speed test and bandwidth measurement in Android. Upload test is working properly, but -d and -r option is not working from client side. 
The iperf server receives packets and again server sends data back to client in reverse and dual test mode. But the data are not received by client. The client only shows the sent data and generates report at end.
We have tried many of the patches sources of iperf for resolving NAT and firewall issue. But none of them working. Even if, the binary source from this repository also doesn't work.

Please help us to resolve this issue that will be really appreciated.

Thanks,
Pradeep Sahoo

**Comment by bmah888** [comment]
This issue tracker is for reporting bugs and enhancement requests for iperf3.  You have a question about the use of iperf2.  This is not the correct place for your question.  Please use the iperf-users mailing list for iperf2 questions.  Thanks!
