### ISSUE TITLE
JSON Output (Client and Server side) doesn't include client's target bandwidth option (-b X)

### ISSUE THREAD

**Issue by TheRealDJ** [esnet/iperf#599]
# Context

* Version of iperf3: 3.1.7

* Hardware: HP DL 360 / Mac Book Pro

* Operating system: CentOS 6.8 Linux / OSX 10.10.2

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.): N/A

# Bug Report

* Expected Behavior
JSON output on client and server side should include client's target bandwidth option (-b X)
* Actual Behavior
JSON output on both client and server does NOT include target bandwidth
* Steps to Reproduce
Run an iperf3 test with '-b 1M' on the client side and '-J' on both sides.
* Possible Solution
Add a 'target_bandwidth' parameter under the 'start' section of the JSON for both client and server mode if the '-b X' option is used on the client side.

**Comment by bmah888** [comment]
In general I think this is a good idea.

**Comment by bmah888** [comment]
@TheRealDJ : Does PR #776 fulfill the requirement?
