### ISSUE TITLE
Add client/server ethernet interface ID and MAC to JSON output

### ISSUE THREAD

**Issue by TheRealDJ** [esnet/iperf#600]
# Enhancement Request

* Current behavior: JSON output does not include ethernet interface ID or MAC address
* Desired behavior: Include ethernet interface ID and MAC addresses for both client and server to JSON output

**Comment by TheRealDJ** [comment]
Related: https://github.com/esnet/iperf/issues/569

**Comment by TheRealDJ** [comment]
Maybe an additional client flag to add string data (I'm thinking a JSON string for my purposes) ... Basically an additional option like -T (title) to pass an arbitrary string. I could write platform specific code on the client to gather the MAC address (and/or any other needed data), JSON format it, and send it with this new flag ... Maybe --extra-client-data '{JSON}'.

I guess I could use the title flag to send JSON, but I would have to re-vamp some code. I am already using the title field to associate results back together. I generate a UUID for the test (consists of upstream iperf, ping, downstream iperf, ping) and pass the same UUID for the 4 results.

**Comment by bmah888** [comment]
I like the idea of using something similar to `-T` to associate arbitrary text/data with the results.  I'm trying to figure out why we need another one...like I'm open to the possibility of adding another flag / field like this if there's really something different about the semantics of this data compared to the title.  (As opposed to being just a second title field.)  Thinking about this some more...

**Comment by TheRealDJ** [comment]
What about something like --extra-data-<key> <value> (where <key> could be anything) ... Then in the test params JSON, add "key":"value".

For my purposes, I would use "--extra-data-mac 00:11:22:33:44:55" which would add "mac":"00:11:22:33:44:55" to the JSON output test params.

**Comment by TheRealDJ** [comment]
Any thoughts? I am stuck on 3.1.7 until we can get something going here.

Open to alternative suggestions as well.

**Comment by bmah888** [comment]
Bah.  I forgot that I wanted to work on this.  So the agreed upon functionality is to have a client-side option `--extra-data` that takes a string argument and puts that in the output on both the client and server side?  For `--json` we'd just put it as one of the fields in the JSON output similar to how `--title` is handled and for non-JSON output we just print it somewhere?

**Comment by bmah888** [comment]
@TheRealDJ : What do you think of #729?  Will that do what you want?

**Comment by bmah888** [comment]
Merged #729...going to declare victory on this.
