### ISSUE TITLE
Can you help me？

### ISSUE THREAD

**Issue by JonkMing** [esnet/iperf#601]
Hi All,
I'm looking for someone to compile iperf 2.0.9 for the iOS (iphone) platform. Has anybody any experience with this?
Thanks,
MingmingHuang

**Comment by wangyoucao577** [comment]
Where do you get the iperf 2.0.9? And why not use the newest version directly? This repo is only iperf3, but not iperf2. It's not very difficult to compile it for iOS. If you meet some issue, ask your real issue clearly, but not ask an open question like this.

**Comment by JonkMing** [comment]
hi. I build iperf2 to android devices.But when I was writing iOS, I found only the source code for iperf3。
I'm confused

**Comment by JonkMing** [comment]
Speak Chinese？
当初编译Android的时候用的是iperf2 .想用iOS iperf2 调试一下。好像么有找到

**Comment by wangyoucao577** [comment]
You can find source code of iperf2 on sourceforge.net. (https://sourceforge.net/projects/iperf/)

**Comment by bmah888** [comment]
I'm going to close this issue, as it seems to be a question regarding iperf2.  This issue tracker is for bug reports, enhancement requests, and pull requests for iperf3.
