### ISSUE TITLE
getline() not available on OSX pre-10.7

### ISSUE THREAD

**Issue by aque** [esnet/iperf#607]
# Context

* Version of iperf3:
4f3a7a5403b61f49ab277d0756e87c651a45bdfe

* Hardware:
Mac

* Operating system (and distribution, if any):
Snow Leopard (10.6) and prior

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
built with MacPorts (gcc 4.2)

# Bug Report

* Expected Behavior
successful build

* Actual Behavior
```
Undefined symbols:
  "_getline", referenced from:
      _iperf_getpass in iperf3_profile-iperf_auth.o
ld: symbol(s) not found
```

* Steps to Reproduce
N/A

* Possible Solution
Replace the missing getline() function in [src/iperf_auth.c](https://github.com/esnet/iperf/blob/master/src/iperf_auth.c) for OSX <= 10.6. This was [proposed to libgss](http://lists.gnu.org/archive/html/help-gss/2017-04/msg00001.html) and that patch can be used here as well.

**Comment by bmah888** [comment]
Thanks for the report and pointer towards a solution.  I think the code in the patch should go into `src/iperf_util.c`.

Are you able to create and test a pull request with this patch?  I'm trying to release iperf-3.2 today (June 26 2017)...I'd rather not hold it for an issue that affects very old macOS versions (2011?) especially ones that I don't have available to me.  No objections to doing a bugfix release (3.2.1?) later once we get this sorted out.

**Comment by aque** [comment]
I have no objection to waiting until 3.2.1 to implement this fix. We can stay on 3.1.7 and anyone wanting the new features can always install -devel. That way, it won't hold up your release.

**Comment by aque** [comment]
@bmah888, I'm afraid I'm out of my league there. I submitted a PR to test building this patch and it still failed. Below is the relevant portion from the output (10.6 x86_64) and it looks like `iperf_auth.c` (first line) is built before `iperf_util.c` (last line) got to define the `getline()` function. Here is [the full log](https://build.macports.org/builders/ports-10.6_x86_64_legacy-builder/builds/34864/steps/install-port/logs/stdio) if you need it. Is that correct?

```
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_auth.lo -MD -MP -MF .deps/iperf_auth.Tpo -c iperf_auth.c  -fno-common -DPIC -o .libs/iperf_auth.o
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_client_api.lo -MD -MP -MF .deps/iperf_client_api.Tpo -c iperf_client_api.c  -fno-common -DPIC -o .libs/iperf_client_api.o
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_locale.lo -MD -MP -MF .deps/iperf_locale.Tpo -c iperf_locale.c -o iperf_locale.o >/dev/null 2>&1
mv -f .deps/iperf_locale.Tpo .deps/iperf_locale.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I.   -I/usr/include -I/opt/local/include  -pipe -Os -arch x86_64 -Wall -MT iperf_udp.lo -MD -MP -MF .deps/iperf_udp.Tpo -c -o iperf_udp.lo iperf_udp.c
iperf_api.c: In function ‘iperf_print_intermediate’:
iperf_api.c:2482: warning: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘iperf_size_t’
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_error.lo -MD -MP -MF .deps/iperf_error.Tpo -c iperf_error.c -o iperf_error.o >/dev/null 2>&1
iperf_auth.c: In function ‘Base64Encode’:
iperf_auth.c:112: warning: value computed is not used
iperf_auth.c:114: warning: value computed is not used
iperf_auth.c: In function ‘iperf_getpass’:
iperf_auth.c:294: warning: implicit declaration of function ‘getline’
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_tcp.lo -MD -MP -MF .deps/iperf_tcp.Tpo -c iperf_tcp.c -o iperf_tcp.o >/dev/null 2>&1
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_client_api.lo -MD -MP -MF .deps/iperf_client_api.Tpo -c iperf_client_api.c -o iperf_client_api.o >/dev/null 2>&1
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_udp.lo -MD -MP -MF .deps/iperf_udp.Tpo -c iperf_udp.c  -fno-common -DPIC -o .libs/iperf_udp.o
mv -f .deps/iperf_error.Tpo .deps/iperf_error.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I.   -I/usr/include -I/opt/local/include  -pipe -Os -arch x86_64 -Wall -MT iperf_sctp.lo -MD -MP -MF .deps/iperf_sctp.Tpo -c -o iperf_sctp.lo iperf_sctp.c
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_server_api.lo -MD -MP -MF .deps/iperf_server_api.Tpo -c iperf_server_api.c -o iperf_server_api.o >/dev/null 2>&1
libtool: compile:  /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I. -I/usr/include -I/opt/local/include -pipe -Os -arch x86_64 -Wall -MT iperf_auth.lo -MD -MP -MF .deps/iperf_auth.Tpo -c iperf_auth.c -o iperf_auth.o >/dev/null 2>&1
mv -f .deps/iperf_tcp.Tpo .deps/iperf_tcp.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile /usr/bin/gcc-4.2 -DHAVE_CONFIG_H -I.   -I/usr/include -I/opt/local/include  -pipe -Os -arch x86_64 -Wall -MT iperf_util.lo -MD -MP -MF .deps/iperf_util.Tpo -c -o iperf_util.lo iperf_util.c
```

**Comment by bmah888** [comment]
@aque:

Maybe it needs a declaration of the getdelim and getline functions in `src/iperf_util.h`, conditional on the checks for the macOS version.  Sorry, I should have thought of that.  The new code to go into `src/iperf_util.h` would look something like this:
```
#ifdef __APPLE__
#include <Availability.h>
#if __MAC_OS_X_VERSION_MIN_REQUIRED <= 1060

static ssize_t
getdelim (char **lineptr, size_t *n, int delim, FILE *stream);

static ssize_t
getline (char **lineptr, size_t *n, FILE *stream);

#endif
#endif
```
Also, take out the declarations of getdelim and getline (but not the definitions) in `src/iperf_util.c`.

I think I understand the problem well enough to try this if necessary (modulo testing), but I am just going to be time-crunched for the next few weeks so might not get to do anything with it until then.

BTW I like your avatar.

**Comment by aque** [comment]
@bmah888, the last time I programmed in C was for a PIC16 in my embedded systems class. I hope you are patient with me as I do not have much experience. Looking at `src/iperf_auth.c` though, `#include  "iperf_util.h"` is not listed. So `getline()` is undefined until that is added, correct? Would it be better to create a new file instead (e.g. `iperf_macos.h`) and include it when OSX <= 10.6? 

If you prefer, we can wait until you have some cycles for this. I am in no hurry.

And thanks for the comment on my avatar. I am a long-time Snoopy fan.

**Comment by bmah888** [comment]
@aque:  I'm happy to work on it later...if somebody else wants to do a pull request on this I'm fine with that too (though I won't get to doing anything with it for a few weeks).  I just wasn't sure how much you wanted to try to solve this problem on your own vs. get it solved somehow-it-doesn't-matter-how.

My wife and kid are big Snoopy fans, and the World War I Flying Ace is my favorite Snoopy persona.

**Comment by bmah888** [comment]
@aque:  Do you have the ability to checkout the tip of the master branch of iperf3 and test this on a macOS <= 10.6 machine?  I don't have anything like this, and I'm not 100% sure if it'll build right.  If there's a problem, please re-open this bug and paste in the error output.  Thanks!

**Comment by bmah888** [comment]
Reopening this so I remember to fix this...`src/iperf_util.h` probably needs a conditionally-included function declaration for the getline(3) function.  Trivial to add but I'm working on something else, so making sure I don't forget to do this.

**Comment by aque** [comment]
@bmah888: I built 95d408962a9fcbd57f0fc69d915463f09ed9bdba under macOS 10.6.8 with no errors.  Also, Testsuite passed 3/3. Let me know if you would like me to run a specific test. Thanks!
