### ISSUE TITLE
UDP block test issue

### ISSUE THREAD

**Issue by DennisEdlund** [esnet/iperf#614]
Hi,
I'm seeing some issues when receiveing UDP on a Windows PC with iperf3.1.3 (I seen no difference in the test on a Linux machine).
What I'm trying to do here is to receive 10000 packets of 100bytes in size and limiting them to a speed of 10Mbit/s.
iperf3 -c ping.online.net -V -l100 -w10000 -R -p5204 -k10000 --get-server-output -u -b10M -i.1
The deault speed is 1Mbit/s without this -b10M setting.
How come that I'm seeing 20103 packets sent?
Is there a calculation error?
Complete received packets are around 10000 when you just read the test summary.
Even if there could be fragmentation, that wouldn't add 10103 more packets as I see it.
For that test Wireshark sees 14590 of 100bytes sizes packets received on that port, which is even more strange.

When I do a SEND test everything is working 100%.

When I'm receiving packetsize of 1000bytes then I don't see this issues.
iperf3 -c ping.online.net -V -l1000 -w10000 -R -p5203 -k1000 --get-server-output -u -b10M -i.1

My internet bandwidth is 100/100 Mbit/s.
There could be issues with traffic-shapning from my fiber optical supplier, I can't ruled that out.
Though TCP bandwidth work without issues, even when MTU is set to 200bytes.
I will make a LAN test on this setting to see what it says.

REVERSE MODE
```
D:\iperf3>iperf3 -c ping.online.net -V -l100 -w10000 -R -p5204 -k10000 --get-server-output -u -b10M -i.1
> iperf 3.1.3
> CYGWIN_NT-10.0 xxx 2016-04-21 22:14 x86_64
> Time: Thu, 20 Jul 2017 11:12:12 GMT
> Connecting to host ping.online.net, port 5204
> Reverse mode, remote host ping.online.net is sending
>       Cookie: ---
> [  4] local 192.168.1.210 port 65402 connected to 62.210.18.40 port 5204
> Starting Test: protocol: UDP, 1 streams, 100 byte blocks, omitting 0 seconds, 10000 blocks to send
> [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
> [  4]   0.00-0.10   sec  40.2 KBytes  3.25 Mbits/sec  0.040 ms  271/683 (40%)
> [  4]   0.10-0.20   sec  66.1 KBytes  5.42 Mbits/sec  0.044 ms  738/1415 (52%)
> [  4]   0.20-0.30   sec  56.2 KBytes  4.61 Mbits/sec  0.041 ms  630/1206 (52%)
> [  4]   0.30-0.40   sec  86.5 KBytes  7.09 Mbits/sec  0.026 ms  580/1466 (40%)
> [  4]   0.40-0.50   sec  59.8 KBytes  4.90 Mbits/sec  0.040 ms  460/1072 (43%)
> [  4]   0.50-0.60   sec  57.0 KBytes  4.67 Mbits/sec  0.041 ms  618/1202 (51%)
> [  4]   0.60-0.70   sec  56.8 KBytes  4.66 Mbits/sec  0.034 ms  655/1237 (53%)
> [  4]   0.70-0.80   sec  85.3 KBytes  6.97 Mbits/sec  0.035 ms  669/1542 (43%)
> iperf3: OUT OF ORDER - incoming packet = 10134 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10135 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10136 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10137 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10138 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10139 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10140 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10141 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10142 and received packet = 10144 AND SP = 4
> iperf3: OUT OF ORDER - incoming packet = 10143 and received packet = 10144 AND SP = 4
> [  4]   0.80-0.90   sec  43.1 KBytes  3.54 Mbits/sec  0.027 ms  753/1184 (64%)
> [  4]   0.90-1.00   sec  54.1 KBytes  4.43 Mbits/sec  0.041 ms  564/1118 (50%)
> [  4]   1.00-1.10   sec  52.2 KBytes  4.28 Mbits/sec  0.057 ms  617/1152 (54%)
> [  4]   1.10-1.20   sec  53.8 KBytes  4.41 Mbits/sec  0.051 ms  730/1281 (57%)
> [  4]   1.20-1.30   sec  54.1 KBytes  4.43 Mbits/sec  0.041 ms  704/1258 (56%)
> [  4]   1.30-1.40   sec  84.8 KBytes  6.94 Mbits/sec  0.029 ms  634/1502 (42%)
> [  4]   1.40-1.50   sec  66.3 KBytes  5.43 Mbits/sec  0.046 ms  332/1011 (33%)
> [  4]   1.50-1.60   sec  51.6 KBytes  4.22 Mbits/sec  0.041 ms  710/1238 (57%)
> [  4]   1.60-1.61   sec  8.59 KBytes  12.0 Mbits/sec  0.039 ms  123/211 (58%)
> - - - - - - - - - - - - - - - - - - - - - - - - -
> Test Complete. Summary Results:
> [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
> [  4]   0.00-1.61   sec  1.92 MBytes  10.0 Mbits/sec  0.040 ms  10042/20103 (50%)
> [  4] Sent 20103 datagrams
> [SUM]  0.0- 1.6 sec  10 datagrams received out-of-order
> CPU Utilization: local/receiver 17.9% (11.1%u/6.8%s), remote/sender 0.1% (0.0%u/0.1%s)
> 
> iperf Done.
> 
```

SEND MODE
```
D:\iperf3>iperf3 -c ping.online.net -V -l100 -w10000 -p5204 -k10000 --get-server-output -u -b10M -i.1
iperf 3.1.3

> CYGWIN_NT-10.0 --- 2016-04-21 22:14 x86_64
> Time: Thu, 20 Jul 2017 11:23:42 GMT
> Connecting to host ping.online.net, port 5204
>       Cookie: ---
> [  4] local 192.168.1.210 port 60767 connected to 62.210.18.40 port 5204
> Starting Test: protocol: UDP, 1 streams, 100 byte blocks, omitting 0 seconds, 10000 blocks to send
> [ ID] Interval           Transfer     Bandwidth       Total Datagrams
> [  4]   0.00-0.10   sec  29.8 KBytes  2.39 Mbits/sec  305
> [  4]   0.10-0.20   sec   205 KBytes  16.8 Mbits/sec  2096
> [  4]   0.20-0.30   sec  24.6 KBytes  2.01 Mbits/sec  252
> [  4]   0.30-0.40   sec   156 KBytes  12.8 Mbits/sec  1602
> [  4]   0.40-0.50   sec   144 KBytes  11.8 Mbits/sec  1471
> [  4]   0.50-0.60   sec   155 KBytes  12.7 Mbits/sec  1585
> [  4]   0.60-0.70   sec  44.6 KBytes  3.66 Mbits/sec  457
> [  4]   0.70-0.80   sec   199 KBytes  16.3 Mbits/sec  2042
> [  4]   0.80-0.82   sec  18.6 KBytes  8.85 Mbits/sec  190
> - - - - - - - - - - - - - - - - - - - - - - - - -
> Test Complete. Summary Results:
> [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
> [  4]   0.00-0.82   sec   977 KBytes  9.77 Mbits/sec  0.008 ms  0/10000 (0%)
> [  4] Sent 10000 datagrams
> CPU Utilization: local/sender 40.4% (12.0%u/28.4%s), remote/receiver 0.0% (0.0%u/0.0%s)
> 
> Server output
> iperf 3.1.3
> Linux ping 3.8.0-35-generic #52~precise1-Ubuntu SMP Thu Jan 30 17:24:40 UTC 2014 x86_64
> -----------------------------------------------------------
> Server listening on 5204
> -----------------------------------------------------------
> Time: Thu, 20 Jul 2017 11:23:42 GMT
> Accepted connection from ---, port 64885
>       Cookie: ---
> [  6] local 62.210.18.40 port 5204 connected to --- port 60767
> Starting Test: protocol: UDP, 1 streams, 100 byte blocks, omitting 0 seconds, 10000 blocks to send
> [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
> [  6]   0.00-0.88   sec   977 KBytes  9.08 Mbits/sec  0.008 ms  0/10000 (0%)
> - - - - - - - - - - - - - - - - - - - - - - - - -
> Test Complete. Summary Results:
> [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
> [  6]   0.00-0.88   sec  0.00 Bytes  0.00 bits/sec  0.008 ms  0/10000 (0%)
> CPU Utilization: local/receiver 0.0% (0.0%u/0.0%s), remote/sender 17.9% (11.1%u/6.8%s)
> 
> 
> iperf Done.
> 
```

REVERSE MODE
```
D:\iperf3>iperf3 -c ping.online.net -V -l1000 -w10000 -R -p5203 -k1000 --get-server-output -u -b10M -i.1
iperf 3.1.3

> CYGWIN_NT-10.0 --- 2016-04-21 22:14 x86_64
> Time: Thu, 20 Jul 2017 11:29:09 GMT
> Connecting to host ping.online.net, port 5203
> Reverse mode, remote host ping.online.net is sending
>       Cookie: ---
> [  4] local 192.168.1.210 port 62175 connected to 62.210.18.40 port 5203
> Starting Test: protocol: UDP, 1 streams, 1000 byte blocks, omitting 0 seconds, 1000 blocks to send
> [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
> [  4]   0.00-0.10   sec   122 KBytes  9.82 Mbits/sec  0.083 ms  1/126 (0.79%)
> [  4]   0.10-0.20   sec   122 KBytes  9.95 Mbits/sec  0.081 ms  3/128 (2.3%)
> [  4]   0.20-0.30   sec   121 KBytes  9.93 Mbits/sec  0.084 ms  0/124 (0%)
> [  4]   0.30-0.40   sec   123 KBytes  10.1 Mbits/sec  0.078 ms  0/126 (0%)
> [  4]   0.40-0.50   sec   122 KBytes  10.0 Mbits/sec  0.079 ms  0/125 (0%)
> [  4]   0.50-0.60   sec   122 KBytes  9.99 Mbits/sec  0.079 ms  0/125 (0%)
> [  4]   0.60-0.70   sec   122 KBytes  9.97 Mbits/sec  0.083 ms  0/125 (0%)
> [  4]   0.70-0.80   sec   121 KBytes  9.91 Mbits/sec  0.079 ms  0/124 (0%)
> [  4]   0.80-0.88   sec  1000 Bytes   106 Kbits/sec  0.679 ms  0/1 (0%)
> - - - - - - - - - - - - - - - - - - - - - - - - -
> Test Complete. Summary Results:
> [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
> [  4]   0.00-0.88   sec  1.08 MBytes  10.3 Mbits/sec  0.077 ms  4/1129 (0.35%)
> [  4] Sent 1129 datagrams
> CPU Utilization: local/receiver 8.4% (1.4%u/7.1%s), remote/sender 0.2% (0.0%u/0.2%s)
```

EDIT:  Reformatted for legibility.  --bmah.

**Comment by DennisEdlund** [comment]
This is a LAN test with that setting.
Better but still getting issues.
Connected on the same 1Gbit LAN switch.

D:\iperf3>iperf3 -c 192.168.1.208 -l100 -w10000 -p5201 -k10000 --get-server-output -u -b10M -i.1
Connecting to host 192.168.1.208, port 5201
[  4] local 192.168.1.210 port 53370 connected to 192.168.1.208 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-0.10   sec   300 Bytes  24.0 Kbits/sec  3
[  4]   0.10-0.20   sec   186 KBytes  15.3 Mbits/sec  1905
[  4]   0.20-0.30   sec   113 KBytes  9.22 Mbits/sec  1154
[  4]   0.30-0.40   sec   141 KBytes  11.5 Mbits/sec  1445
[  4]   0.40-0.50   sec   103 KBytes  8.47 Mbits/sec  1058
[  4]   0.50-0.60   sec   182 KBytes  14.9 Mbits/sec  1859
[  4]   0.60-0.70   sec  15.3 KBytes  1.26 Mbits/sec  157
[  4]   0.70-0.80   sec   177 KBytes  14.5 Mbits/sec  1815
[  4]   0.80-0.82   sec  59.0 KBytes  20.6 Mbits/sec  604
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-0.82   sec   977 KBytes  9.71 Mbits/sec  0.036 ms  77/10000 (0.77%)
[  4] Sent 10000 datagrams

Server output:
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.1.210, port 60716
[  5] local 192.168.1.208 port 5201 connected to 192.168.1.210 port 53370
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-0.87   sec   969 KBytes  9.11 Mbits/sec  0.036 ms  77/10000 (0.77%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-0.87   sec  0.00 Bytes  0.00 bits/sec  0.036 ms  77/10000 (0.77%)


iperf Done.

D:\iperf3>iperf3 -c 192.168.1.208 -l100 -w10000 -p5201 -k10000 --get-server-output -u -b10M -i.1 -R
Connecting to host 192.168.1.208, port 5201
Reverse mode, remote host 192.168.1.208 is sending
[  4] local 192.168.1.210 port 53371 connected to 192.168.1.208 port 5201
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-0.10   sec  99.6 KBytes  8.16 Mbits/sec  0.029 ms  55/1075 (5.1%)
[  4]   0.10-0.20   sec   148 KBytes  12.1 Mbits/sec  0.015 ms  0/1516 (0%)
[  4]   0.20-0.30   sec   104 KBytes  8.57 Mbits/sec  0.029 ms  181/1249 (14%)
[  4]   0.30-0.40   sec   131 KBytes  10.5 Mbits/sec  0.019 ms  0/1338 (0%)
[  4]   0.40-0.50   sec  81.2 KBytes  6.74 Mbits/sec  0.022 ms  224/1055 (21%)
[  4]   0.50-0.60   sec   132 KBytes  10.7 Mbits/sec  0.026 ms  92/1447 (6.4%)
[  4]   0.60-0.70   sec   104 KBytes  8.66 Mbits/sec  0.021 ms  169/1239 (14%)
[  4]   0.70-0.80   sec   133 KBytes  10.9 Mbits/sec  0.016 ms  0/1357 (0%)
[  4]   0.80-0.90   sec  27.8 KBytes  2.28 Mbits/sec  0.026 ms  0/285 (0%)
[  4]   0.90-0.91   sec  15.6 KBytes  9.39 Mbits/sec  0.044 ms  0/160 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-0.91   sec  1.03 MBytes  9.41 Mbits/sec  0.024 ms  721/10752 (6.7%)
[  4] Sent 10752 datagrams

Server output:
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.1.210, port 60717
[  5] local 192.168.1.208 port 5201 connected to 192.168.1.210 port 53371
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  5]   0.00-0.96   sec  1.03 MBytes  8.95 Mbits/sec  10752
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-0.96   sec  1.03 MBytes  8.95 Mbits/sec  0.000 ms  0/10752 (0%)


iperf Done.

**Comment by bmah888** [comment]
The iperf issue tracker is really for reporting bugs and requesting enhancements/features, not for general support.  It'd probably be better to try this as a discussion on the iperf-users or iperf-dev mailing lists.

Nevertheless...you said on Windows you were using iperf 3.1.3.  If you can try a newer version of iperf3 (preferably 3.2, and I'm well aware that as I'm typing this there aren't any publically available Windows executables of 3.2) there are some improvements that directly affect UDP performance.

Is the server machine to which you're connecting running Windows, Linux, BSD, or some other UNIX?  What version of iperf3?

What's the network like between the two endpoints in your initial report?  (You mentioned traffic-shaping, so I'm wondering what's on the path besides just routers.  Any NATs, firewalls, or other kinds of middleboxes?)

I don't rule out some weird problem with `-k` getting the packet counts wrong, although I have no evidence one way or the other (that particular mode of operation hasn't been tested much).

I agree there's some odd behavior here.

**Comment by DennisEdlund** [comment]
It's a public iperf3 10Gbit/s server, ping.online.net.
> Server output
> iperf 3.1.3
> Linux ping 3.8.0-35-generic #52~precise1-Ubuntu SMP Thu Jan 30 17:24:40 UTC 2014 x86_64

Set to side that there could be an issue with the traffic-shapning it's the odd counting of packets lost which I'm addressing here.
As there should only be 10000 packets sent and not more as I presume, then it's a possible counting ERROR?
And isn't the don't fragment bit set in the packets?
I think I saw that in the packets in wireshark the last time I checked.

**Comment by bmah888** [comment]
As you indicated in the original comment, this problem might be Windows specific.  I played around with this on my macOS laptop and couldn't make the problem happen.  Windows is not a platform that we support officially, so the best thing I can think of is just to put this out on the iperf-users or iperf-dev list and see if someone else can help you troubleshoot or give some ideas..

**Comment by DennisEdlund** [comment]
I'll do the same tests again with Linux machines and reply back.

**Comment by bmah888** [comment]
No feedback for 2.5 months, closing for now.  I can reopen this issue if necessary.
