### ISSUE TITLE
iperf/iperf3 error with multicast IPV6

### ISSUE THREAD

**Issue by rakeshbasavaraju** [esnet/iperf#617]
# Context
I am trying to use the iperf3 for trying the multicast traffic with IPV6.

* Version of iperf3:
iperf 3.0.7
* Hardware:

* Operating system (and distribution, if any):

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate._

# Bug Report

* Expected Behavior

* Actual Behavior
running "iperf3 -s -B ff02::1" gives the following error

$ iperf3 -s -B ff02::1 
iperf3: error - unable to start listener for connections: Invalid argument

iperf3: error - unable to start listener for connections: Invalid argument

iperf3: error - unable to start listener for connections: Invalid argument

iperf3: error - unable to start listener for connections: Invalid argument

iperf3: error - unable to start listener for connections: Invalid argument

too many errors, exiting

* Steps to Reproduce
iperf3 -s -B ff02::1 

* Possible Solution

_Please submit patches or code changes as a pull request._

# Enhancement Request

* Current behavior

* Desired behavior

* Implementation notes

_If submitting a proposed implementation of an enhancement request,
please use the pull request mechanism._

**Comment by bmah888** [comment]
iperf3 doesn't support IP multicast (either on IPv4 or IPv6).  There's an open enhancement for it (#27), but it's not in our immediately roadmap to implement it.

In the meantime you could try iperf2, which does support IP multicast and (I think) IPv6.
