### ISSUE TITLE
Build IPerf3: ProcessBuilder Run blocking

### ISSUE THREAD

**Issue by JonkMing** [esnet/iperf#621]
I compiled IPerf3 into a Android Library.
Then use ProcessBuilder to run it. But it causes thread congestion. It takes a round of running before you have a result. I need to set parameter settings?

Code：
  List<String> commandList = new ArrayList<String>(Arrays.asList(commands));
                //If the first parameter is "iperf", it is removed
                if (commandList.get(0).equals((String) "iperf3")) {
                    commandList.remove(0);
                }
                //The execution command is added first in the list for the shell interface.
                commandList.add(0,libPath);
                //The process is now being run with the verified parameters.
                process = new ProcessBuilder().command(commandList).redirectErrorStream(true).start();
                //A buffered output of the stdout is being initialized so the iperf output could be displayed on the screen.
                reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                int read;
                //The output text is accumulated into a string buffer and published to the GUI
                char[] buffer = new char[4096];
                StringBuffer output = new StringBuffer();
                while ((read = reader.read(buffer)) > 0) {
                    if(isCancelled())
                        break;
                    output.append(buffer, 0, read);
                    //This is used to pass the output to the thread running the GUI, since this is separate thread.
                    publishProgress(output.toString());
                    output.delete(0, output.length());
                }

**Comment by bmah888** [comment]
Asking fro help with this sort of integration on Android (or any other unsupported platform) is, well, unsupported.  Please direct these to the iperf-dev or iperf-users mailing lists.  The `--forceflush` flag might help you.
