### ISSUE TITLE
pidfile incorrectly deleted on start fail

### ISSUE THREAD

**Issue by cfsmp3** [esnet/iperf#623]
```
/usr/bin/iperf3 -p 8282 -s -D --version4 -I /var/run/iperf3/iperf3-1.pid
cat /var/run/iperf3/iperf3-1.pid
4283
```

Works OK, generates the pidfile as expected and the value is correct.

Rerun the same command (without killing the previous instance)
```
/usr/bin/iperf3 -p 8282 -s -D --version4 -I /var/run/iperf3/iperf3-1.pid
cat /var/run/iperf3/iperf3-1.pid
cat: /var/run/iperf3/iperf3-1.pid: No such file or directory
```
So when iperf3 it doesn't check if it's running already. Then when it cannot start  (can't bind, for example) it terminates and deletes the pre-existing PID file.

IMHO correct behavior:
- Check if PID file exists
- If yes, check if the process is still running
- If yes, terminate with an error, leave PID file alone
- Otherwise delete or overwrite the PID file and continue

**Comment by bmah888** [comment]
Confirming that it does behave as described your initial report.  This does seem like a bug, although I haven't yet decided for myself what I think the correct behavior is for this situation.

**Comment by bmah888** [comment]
It turns out the problem doesn't really require a startup failure, the real problem is overwriting the PID file corresponding to an earlier invocation.

**Comment by cfsmp3** [comment]
The failure is a way to quickly demo the problem :-)

**Comment by bmah888** [comment]
@cfsmp3:  Would you care to take a look at pull request #654, which should fix this problem?
