### ISSUE TITLE
iperf3 - Cannot assign requested address - Error after forcing traffic with 2 NICs to go over the wire

### ISSUE THREAD

**Issue by rpandav** [esnet/iperf#625]
* Version of iperf3: iperf 3.1.3

* Operating system (and distribution, if any): Linux Centos7.2 3.10.0-327.el7.x86_64 

# Bug Report

I am trying to build a traffic tool on a single machine with two NIC cards. The ideal scenario for this is that I generate traffic (the source) from NIC1 and it traverses over the wire to NIC2 (the destination). I was initially having problems with forcing the traffic to go over the wire since the linux kernel routes the packets internally (as its aware of both NIC IPs). That problem was solved [here](https://stackoverflow.com/questions/45410824/force-ip-packets-to-route-through-2-nic-cards-on-same-machine-over-external-ne#comment77819579_45428229).

The problem I am facing now is that after following the suggestions mentioned in the above post, iperf3 is not able to bind to the mentioned IP address.

```
iperf3 -s -B 192.168.121.75 -p 9999
iperf3: error - unable to start listener for connections: Cannot assign requested address
iperf3: exiting 
```

Does anyone know why this could be happening? I am able to ping successfully if I run the command

```
ping 192.168.121.75 -I eno1
PING 192.168.121.75 (192.168.121.75) from 192.168.252.85 eno1: 56(84) bytes of data.
64 bytes from 192.168.121.75: icmp_seq=1 ttl=64 time=0.048 ms
64 bytes from 192.168.121.75: icmp_seq=2 ttl=64 time=0.031 ms
64 bytes from 192.168.121.75: icmp_seq=3 ttl=64 time=0.034 ms
64 bytes from 192.168.121.75: icmp_seq=4 ttl=64 time=0.030 ms
```

**Comment by bmah888** [comment]
As I weakly suggested at the end of issue #618, it'd be much better if you could please post support questions like this to the iperf-users or iperf-dev list, not as issues in iperf3's issue tracker.  Thanks!
