### ISSUE TITLE
Iperf Jump in Bandwidth Issue

### ISSUE THREAD

**Issue by saimsalman36** [esnet/iperf#628]
Setting the bandwidth in Iperf3 to 500 and using Iperf I'm getting this wierd trend: (Attaching the server report below)

[  5]  30.00-31.00  sec  59.5 MBytes   499 Mbits/sec                  
[  5]  31.00-32.00  sec  59.6 MBytes   500 Mbits/sec                  
[  5]  32.00-33.00  sec  59.6 MBytes   500 Mbits/sec                  
[  5]  33.00-34.00  sec  59.6 MBytes   500 Mbits/sec                  
[  5]  34.00-35.00  sec  59.6 MBytes   500 Mbits/sec                  
[  5]  35.00-36.00  sec  59.6 MBytes   500 Mbits/sec                  
[  5]  36.00-37.00  sec  59.6 MBytes   500 Mbits/sec                  
[  5]  37.00-38.00  sec  59.5 MBytes   499 Mbits/sec                  
[  5]  38.00-39.00  sec  59.6 MBytes   500 Mbits/sec                  
[  5]  39.00-40.00  sec  53.6 MBytes   450 Mbits/sec                  
[  5]  40.00-41.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  41.00-42.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  42.00-43.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  43.00-44.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  44.00-45.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  45.00-46.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  46.00-47.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  47.00-48.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  48.00-49.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  49.00-50.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  50.00-51.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  51.00-52.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  52.00-53.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  53.00-54.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  54.00-55.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  55.00-56.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  56.00-57.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  57.00-58.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  58.00-59.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  59.00-60.01  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  60.01-61.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  61.00-62.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  62.00-63.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  63.00-64.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  64.00-65.00  sec  0.00 Bytes  0.00 bits/sec                  
[  5]  65.00-66.00  sec   146 MBytes  1.23 Gbits/sec                  
[  5]  66.00-67.00  sec  1.43 GBytes  12.3 Gbits/sec                  
[  5]  67.00-68.00  sec  59.6 MBytes   500 Mbits/sec    

I'm running an iperf3 connection between VM1 and VM2 when they are on the same computer and then migrating VM2 to another machine hence the 10 seconds where it's 0.00 bits/sec.

But why does iperf hit 1.23 Gbits / sec when the bandwidth limit is set to 500 Mbits/sec.

**Comment by bmah888** [comment]
You migrated the server while it had some amount of data "in flight".  It probably took that data some time to arrive at the migrated server, at which point it was delivered as a burst.  Remember that these periodic statistics measure what iperf3 sent or received at the application layer; network effects are all at layers underneath this.

In the future please post questions like this to the iperf-users list.  Issues are for reporting bugs or feature enhancements.  Thanks.
