### ISSUE TITLE
iPerf 3 missing from EPEL

### ISSUE THREAD

**Issue by Deadringers** [esnet/iperf#634]
As the title suggests, there is no iPerf 3 package in the current EPEL release:

http://mirror.cogentco.com/pub/linux/epel/7/x86_64/i/

I can see and install iPerf2, but 3 is not there.

It was there within the last 6 months or so, beyond that I couldn't tell you when it went. 

No info online as to why this is missing.

**Comment by bmah888** [comment]
Hmmm.  I did a little looking around and couldn't find anything either, although yes I do remember i being there.  ESnet doesn't control what goes into EPEL, we only distribute source code.  I do know that as of about five months ago, I had a conversation with someone at RedHat, who was informing me that iperf3 was going to go into RHEL 7 (some version of it anyway).  Perhaps it'll show up as a part of the normal RHEL / CentOS 7 soon.

In the meantime, it's not hard to compile from source.
