### ISSUE TITLE
Connection refused when binding to specific interface

### ISSUE THREAD

**Issue by rob-scheepens** [esnet/iperf#636]
# Context
Running iperf3 on two Windows Server 2016 hosts.

* Version of iperf3:
iperf 3.1.3
CYGWIN_NT-10.0 rob-254-2 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64
Optional features available: None

* Hardware:
CPU: E2580v3
NIC: Intel 82599, PCI\VEN_8086&DEV_10FB&SUBSYS_061115D9&REV_01\0CC47AFFFFBC59F600

* Operating system (and distribution, if any):
Windows Server 2016. I know it says this is not supported, but I did not see such message on iperf.fr, so I'll take my chances.

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
n/a

# Bug Report

* Expected Behavior
Get connected to the specific interface to which iperf3 server is bound to.

* Actual Behavior
Connection refused to client.

* Steps to Reproduce
```
C:\>iperf3 -d -s -B 10.60.7.222
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------

C:\>iperf3 -d -c 10.60.7.223 -p 5201
iperf3: error - unable to connect to server: Connection refused
```

I can see server listening correctly:
```TCP    10.60.7.222:5201       0.0.0.0:0              LISTENING       7292```

I ensured Windows Firewall is off, and even explicitly allowed iperf3.exe in there. When not using -b option, iperf3 works fine.

**Comment by bmah888** [comment]
The `-B` option on the server and the `-c` option on the client need to match for this to work.  In your examples you had above, you had the server listening on 10.60.7.222 and the client trying to connect to 10.60.7.223.  Is that really what you meant to do?

(FYI, iperf.fr isn't affiliated with ESnet, and we at ESnet can't take any responsiblity for the Windows or other executables they post.  We've actually been trying to get in touch with them, for friendly reasons, but have not been successful.)

**Comment by rob-scheepens** [comment]
@bmah888 : looks like I indeed mixed up IPs. Thanks for the correction!
