### ISSUE TITLE
iperf3: error - select failed: Bad file descriptor

### ISSUE THREAD

**Issue by zx2c4** [esnet/iperf#653]
iperf-3.1.7 does not contain this bug. iperf-3.2 has this bug.

Below I've interleaved the client and server console outputs.  Doing a low latency (veth, localhost) iperf on the same system results in the following error. The error always happens after exactly 15 seconds, even if the bitrate is much lower. It occurs in TCP mode and in UDP mode, over v4 and over v6.

This error occurs when `-n 10000G` is set. However if `-t 1000` is set, things continue much beyond 15 seconds.

A brief poke at the source indicates:

```c
tmr_add(test->duration + test->omit + 5)
```

It would seem that the default value of `-t 10` then is still being used, albeit improperly, when `-n` is in use.

The error:

```
Connecting to host 192.168.241.2, port 5201
Accepted connection from 192.168.241.1, port 33744
[  6] local 192.168.241.1 port 33746 connected to 192.168.241.2 port 5201
[  6] local 192.168.241.2 port 5201 connected to 192.168.241.1 port 33746
[ ID] Interval           Transfer     Bitrate
[  6]   0.00-1.00   sec   629 MBytes  5.27 Gbits/sec                  
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  6]   0.00-1.00   sec   653 MBytes  5.48 Gbits/sec    0   1.49 MBytes       
[  6]   1.00-2.00   sec   623 MBytes  5.22 Gbits/sec                  
[  6]   1.00-2.00   sec   626 MBytes  5.25 Gbits/sec  151   1.24 MBytes       
[  6]   2.00-3.00   sec   587 MBytes  4.92 Gbits/sec                  
[  6]   2.00-3.00   sec   585 MBytes  4.91 Gbits/sec    0   1.35 MBytes       
[  6]   3.00-4.00   sec   551 MBytes  4.62 Gbits/sec                  
[  6]   3.00-4.00   sec   548 MBytes  4.59 Gbits/sec   25   1.02 MBytes       
[  6]   4.00-5.00   sec   481 MBytes  4.04 Gbits/sec                  
[  6]   4.00-5.00   sec   481 MBytes  4.04 Gbits/sec    0   1.07 MBytes       
[  6]   5.00-6.00   sec   499 MBytes  4.19 Gbits/sec                  
[  6]   5.00-6.00   sec   501 MBytes  4.21 Gbits/sec    0   1.11 MBytes       
[  6]   6.00-7.00   sec   632 MBytes  5.30 Gbits/sec                  
[  6]   6.00-7.00   sec   636 MBytes  5.34 Gbits/sec    0   1.14 MBytes       
[  6]   7.00-8.00   sec   653 MBytes  5.48 Gbits/sec                  
[  6]   7.00-8.00   sec   652 MBytes  5.47 Gbits/sec    0   1.16 MBytes       
[  6]   8.00-9.00   sec   556 MBytes  4.67 Gbits/sec                  
[  6]   8.00-9.00   sec   555 MBytes  4.66 Gbits/sec    0   1.17 MBytes       
[  6]   9.00-10.00  sec   672 MBytes  5.63 Gbits/sec                  
[  6]   9.00-10.00  sec   666 MBytes  5.59 Gbits/sec    0   1.17 MBytes       
[  6]  10.00-11.00  sec   537 MBytes  4.51 Gbits/sec                  
[  6]  10.00-11.00  sec   539 MBytes  4.52 Gbits/sec    0   1.17 MBytes       
[  6]  11.00-12.00  sec   544 MBytes  4.56 Gbits/sec                  
[  6]  11.00-12.00  sec   544 MBytes  4.56 Gbits/sec    0   1.17 MBytes       
[  6]  12.00-13.00  sec   543 MBytes  4.55 Gbits/sec                  
[  6]  12.00-13.00  sec   542 MBytes  4.55 Gbits/sec    0   1.17 MBytes       
[  6]  13.00-14.00  sec   516 MBytes  4.33 Gbits/sec                  
[  6]  13.00-14.00  sec   518 MBytes  4.34 Gbits/sec    0   1.18 MBytes       
iperf3: error - select failed: Bad file descriptor
iperf3: error - control socket has closed unexpectedly
```

**Comment by bmah888** [comment]
Thanks for the bug report!  This was previously reported in #645 and fixed in #648.  The next (I think) iperf3 release will contain the fix for this problem.

**Comment by xueruini** [comment]
> Thanks for the bug report! This was previously reported in #645 and fixed in #648. The next (I think) iperf3 release will contain the fix for this problem.

which version is it included?

**Comment by xEngeLx** [comment]
Also happens in 3.6 without using the -n switch.
Test case - two UDP streams that request more than available bandwidth.
This results in "**iperf3: error - select failed: Bad file descriptor**" message.

**Comment by ckleu** [comment]
Replicated (built from source):
```
# iperf3 -v
iperf 3.6+ (cJSON 1.5.2)
Linux 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64
```

I am using the python wrapper (`pip install iperf3`), happens when I start my second iteration - first iteration completes each time

```
Traceback (most recent call last):
  File "test-iperf3.py", line 20, in <module>
    r = get_result(c)
  File "test-iperf3.py", line 15, in get_result
    return c.run()
  File "/usr/local/lib/python2.7/dist-packages/iperf3/iperf3.py", line 598, in run
    output_to_pipe(self._pipe_in)  # Disable stdout
  File "/usr/local/lib/python2.7/dist-packages/iperf3/iperf3.py", line 70, in output_to_pipe
    os.dup2(pipe_in, 1)  # stdout
OSError: [Errno 9] Bad file descriptor
Exception OSError: (9, 'Bad file descriptor') in <bound method Client.__del__ of <iperf3.iperf3.Client object at 0x7fecf6012f10>> ignored
```

Also tried putting in a static delay of 5 seconds before starting the second iteration

**Comment by ckleu** [comment]
When keeping the same `iperf3.Client()` object between tests

```
Test iteration: 2
r: {"error": "unable to send cookie to server: Bad file descriptor"}
```
r = client.run()

**Comment by AllanLeanderRostockHansen** [comment]
I'm also having this issue, but it seens like it's not enough the instantiate a new Client-object. The old client object should be deleted before a new one is created... I'm not eaactly sure about this, but it _seems_ to fix the problem.

**Comment by lyylee18** [comment]
@AllanLeanderRostockHansen Hi, Do you know how to deleted the old client?

**Comment by AllanLeanderRostockHansen** [comment]
I think that I just did a `del client`, where `client = iperf3.Client()`.
The `Client` class handles the teardown associated with the delete operation (evident in [the source code](https://github.com/thiezn/iperf3-python/blob/master/iperf3/iperf3.py#L211)).
