### ISSUE TITLE
Question about iperf2.0.5?

### ISSUE THREAD

**Issue by exiulan** [esnet/iperf#666]
1.In the source code of iperf2.0.5,there are some code as follows:
if(delay>0)
{delay_loop(delay);}
Could you tell me what’s the affect of the delay?
2.Why the send rate is about the receive rate rather than the same as the number of (-b) when I send udp date?
Thanks very much.

**Comment by bmah888** [comment]
This issue tracker is for bug reports and feature requests for iperf3.  For iperf2 questions, please post your support question to iperf-users@sourceforge.net.  Thanks.

**Comment by exiulan** [comment]
But I have no access/control of the (source forge) iperf2 website.

**Comment by bmah888** [comment]
You have to join the mailing list before you can post to it.

Go to this URL and fill out the Web form to join.

https://sourceforge.net/projects/iperf/lists/iperf-users
