### ISSUE TITLE
Authentication time check issue

### ISSUE THREAD

**Issue by FuzzyStatic** [esnet/iperf#673]
# Context

* Version of iperf3:

3.2

* Hardware:

x86_64

* Operating system (and distribution, if any):

Linux

# Bug Report

* Expected Behavior

I expect authentication to fail if the time difference between the server and client is more than a set range.

* Actual Behavior

I've run into issues where the time difference between the server and client is around 1 second and authentication fails.

* Steps to Reproduce

I dug into the code and found this in the iperf_auth.c file:

```
    time_t t = time(NULL);
    time_t utc_seconds = mktime(localtime(&t));
    if ( (utc_seconds - ts) < 10 && (utc_seconds - ts) > 0 ){
        return 1;
    }
```

The code logic seems to imply that any time difference between the client and server that is between 0 and 10 seconds should fail, while every other scenario should pass. If a time difference is more than 10 seconds (100 seconds, 1 day) it succeeds. If a time difference is less than 0 seconds it succeeds. I tested this and it seems to be the case. It does not make sense to me to fail authentication only within a small timeframe.

* Possible Solution

Change the code to an OR statement and have authentication only pass if it is within a certain time range. In the code below it would be +/- 10 seconds.

```
    time_t t = time(NULL);
    time_t utc_seconds = mktime(localtime(&t));
    if ( (utc_seconds - ts) > 10 || (utc_seconds - ts) < -10){
        return 1;
    }
```

I tested this code and it seems to work as intended. The authentication timing could be a command line argument to allow people to set the range for themselves.

**Comment by bmah888** [comment]
Hmmm.  I only looked at this code very quickly but it does seem to have the problem you described and your fix looks to be correct.  @ralcini, what do you think of this?

**Comment by ralcini** [comment]
@bmah888 ..yes, it's a bug! the proposed patch is correct. Thank you @FuzzyStatic !

**Comment by FuzzyStatic** [comment]
Can we get the range to be a configurable command line argument? I feel it should be up to the end user to determine what time range is acceptable for their own security measures. I already have a setup to test this if needed.

**Comment by ralcini** [comment]
@FuzzyStatic why do you need to be more permissive on time token validation? Do you have time syncronization problem with NTP?

**Comment by FuzzyStatic** [comment]
@ralcini I would hope to not have NTP issues but sometimes things happen that I cannot control. Having a default authentication time difference of +/-10 seconds is fine, but for testing and debugging purposes it would be convenient to be able to adjust that value, just in case NTP synchronization is lost.

**Comment by bmah888** [comment]
See PR #674 for the bug fix, which is on the issues-673 branch for testing.  Are we all good with that?  (It's basically what's in the first comment on this issue, plus a tiny whitespace fix.)

To me, the enhancement for having the time skew limit as a parameter is a different issue.  I don't object to doing it, but I just wanted to fix the bug first.

Thanks @FuzzyStatic and @ralcini!
