### ISSUE TITLE
Server doesn't detect abrupt client disconnection with -t 0

### ISSUE THREAD

**Issue by isurakka** [esnet/iperf#675]
# Context

* Version of iperf3:
3.3

* Hardware:
Ubuntu server:  1 core CPU, 2GB RAM
Ubuntu client: 2 core CPU, 2GB RAM

(I can also reproduce this on Windows and ARM Linux clients)

* Operating system (and distribution, if any):
Server and client: Ubuntu 16.04

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.): 
Compiled the 3.3 git tag

# Bug Report

* Expected Behavior
The server should close the connection once it detects the client isn't present anymore.

* Actual Behavior
The server never detects the connection is dead. This causes the server to never be available again unless you manually restart the server.

* Steps to Reproduce
1. Start the server with `iperf3 -s` command
2. Start the client with `iperf3 -c <serverip> -b 10M -R -t 0` command
3. Power off the client without leaving a chance to close the connection
4. The server now never detects the connection is dead and sends or ties to receive data indefinitely

* Possible Solution
The server should should detect the connection is dead and stop the session and start waiting for more connections.

If you run the client without -t 0 or with a non-zero value the server does detect the disconnection once the time has passed but I need -t 0 for my use case.

**Comment by bmah888** [comment]
So you started the client with `-t 0` indicating an unlimited-time test.  It's not clear what the server should do in this case...it doesn't have any basis for just closing the test on its own.  Maybe if the server doesn't receive any data for N measurement intervals or something like that, or we can enable keepalives on the control connection.  Just thoughts at this point.

**Comment by swlars** [comment]
No comments in a long time, closing
