### ISSUE TITLE
Is it possible to suppress the TCP/IP handshake in iPerf3?

### ISSUE THREAD

**Issue by vnikitin72** [esnet/iperf#676]
I'm using IPerf (3) to investigate some packet loss issues on my network.

Even in UDP mode the IPerf client actually makes a TCP/IP connection to connect to the server. This is troublesome for me, because in my specific test I want to test with my firewall blocking TCP/IP and only allowing UDP.

Is there a way to tell IPerf to send the UDP even if there isn't a server connected?

**Comment by bmah888** [comment]
The short answer to this is "no".  That TCP control channel is a part of iperf3's design.

If this doesn't fit your use case, you might want to consider using iperf2, which (I think) will do what you want.
