### ISSUE TITLE
file binary path can be different than /usr/bin/file

### ISSUE THREAD

**Issue by teto** [esnet/iperf#679]
# Context

* Version of iperf3: 3.3
* Operating system (and distribution, if any): linux/nixos

# Bug Report
In the generated ./configure, /usr/bin/file is assumed, caa't we use the file in PATH or configure it ? for instance the file binary on my system lives in "/run/current-system/sw/bin/file" (but on nixos paths change a lot so you have either to set it or assume it is in path).
```
case `/usr/bin/file conftest.o` in
      *32-bit*)
	case $host in
	  x86_64-*kfreebsd*-gnu)
	    LD="${LD-ld} -m elf_i386_fbsd"
	    ;;
	  x86_64-*linux*)
	    case `/usr/bin/file conftest.o` in
```

An other request would be to not link with ` -pg` by default or allow to disable it from configure since it generates linking errors with DCE (Direct Code Execution) and doesn't seem to be. This problem hit me in another problem that involves compiling iperf3 against a rumpkernel http://wiki.rumpkernel.org/Info:-FAQ .

**Comment by bmah888** [comment]
`configure` is generated by GNU autoconf.  How do other autoconf-using programs handle this situation?  (I'm asking because in 30 years of using UNIX I have never seen a system where `/usr/bin/file` didn't exist.)

**Comment by bmah888** [comment]
In reference to a secondary comment in the initial bug report, it's now possible to specify `--disable-profiling` at configure time to disable profiled builds.

The main problem remains unsolved.

**Comment by bmah888** [comment]
There's not an obvious way to handle this, given that the code in question is generated by GNU autoconf.

**Comment by teto** [comment]
ok thanks. seems like it's a common warning in autoconf packages but not impactful in the end.
