### ISSUE TITLE
iperf3 will block during wifi throughput test

### ISSUE THREAD

**Issue by smartnfc** [esnet/iperf#681]
# Context

* Version of iperf3: 3.0.11

* Hardware: Mips/Embedded

* Operating system (and distribution, if any): Linux

# Bug Report

* Expected Behavior
iperf3 will not block during test process
* Actual Behavior
iperf3 will block during test
* Steps to Reproduce
iperf -c 192.168.1.22 -w 256k -P 8 -t 15
* Possible Solution
iperf3 can't ensure the control message will receive by peer, but if the control message
was lost during the bad network environment, the iperf3 will block at certain step.
So, can we add more fault-tolerant mechanism to optimize the iperf ?

for example:
iperf3 client fail to receive TEST_END ACK, and client try to retransmission, client will not stop sending data
iperf3 server fail to receive EXCHANGE_RESULT ACK, and server try to retransmission, and server will not
receive test result

**Comment by bmah888** [comment]
I'd note you should probably be using a newer version of iperf3...3.0.11 is very old (3 years?), although if I understand the problem you are reporting, that probably won't change much in current code.

Are you saying that a lossy network can cause something in the exchange of control messages to block?  Note that iperf3 uses TCP for its control connection, which attempts to retransmit data in case of loss.  Also, iperf3 does work on lossy networks, although its performance isn't the best.

Have you actually observed these problems?  If so can you give some more details, such as (but not limited to) command-line arguments, wireless environment?

**Comment by bmah888** [comment]
Timeout for additional information.  Closing for now, can be reopened later if needed.
