### ISSUE TITLE
LIBTOOL error trying to build on BBB running Debian-7.11

### ISSUE THREAD

**Issue by ionreflex** [esnet/iperf#684]
* Version of iperf3: latest Git pull
* Hardware: BeagleBoneBlack (armv7l)
* Operating system (and distribution, if any): Debian-7.11

# Bug Report

* Expected Behavior

./bootstrap to complete normally...

* Actual Behavior

zerounit@nullunit:~/gitstuff/iperf$ ./bootstrap.sh
+ libtoolize --copy --force --automake
+ aclocal -I config
+ autoheader
+ automake --foreign --add-missing --copy
src/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:1:   its definition is in aclocal's search path.
+ autoconf
configure.ac:48: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
+ rm -rf config.cache

* Additional details

This has appeared over the last 2 or 3 Git push; it was fine before, then it stopped compiling; I'm not dev savvy, so bear with me! I've tried to fix it by :

- adding LT_INIT to "configure.ac", it gives the error above (only src/Makefile.am error before);
- purge + reinstall "libtool" = IDEM;

* Possible Solution

Not sure at this point...

**Comment by bmah888** [comment]
Two questions:

1.  Is there a reason you need to run `bootstrap.sh` in the first place?  If you get the tarball you should be able to just do `./configure && make` and have it just built.

2.  One of the "fun" things about using libtool, automake, autoconf, etc. is that different versions behave differently, and different OS distributions include different versions.  Would you be able to get the output of the following commands?
```libtool --version
aclocal --version
autoheader --version
automake --version
autoconf --version
```
I'll note that when I need to re-run `bootstrap.sh` to update these files in the iperf3 repository, I usually need to do this on either FreeBSD or macOS...the Linux distribution I run (CentOS 7) uses old versions of these tools and doesn't work right.  The resulting configure and build scripts (which gets committed to GitHub) builds and runs fine on CentOS 7 and most other platforms where we've tried.

**Comment by ionreflex** [comment]
2 responses:

1. I did a "git checkout ." to try without bootstrapping, and it appears to be working as expected; why I ran it before? Always did, cannot recall why!

2. Not sure if relevant then, but here you go :

```
nullunit@offline:~$ aclocal --version
aclocal (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
nullunit@offline:~$ autoheader --version
autoheader (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Roland McGrath and Akim Demaille.
nullunit@offline:~$ automake --version
automake (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
nullunit@offline:~$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```
Since it appears to be working properly, I'm closing this.

TY
