### ISSUE TITLE
iperf 3 multiple clients

### ISSUE THREAD

**Issue by pjebs** [esnet/iperf#685]
iperf3 server in the past only allowed 1 client to connect.

@bmah888  Has this been changed to allow multiple clients to connect to the one server?
When did this change occur?

**Comment by bmah888** [comment]
There hasn't been any change in this area.  iperf3 deliberately only runs one test at a time.

In the high-performance networking environment for which iperf3 was designed, multiple tests on the same endpoint (whether the client or server) would interfere with each other, so it was a conscious choice to not do this.  The perfSONAR tools, such as pScheduler (preferred) or bwctl (deprecated) are used to coordinate iperf3 tests where there's a possibility that multiple clients might be trying tests at the same time.

**Comment by pjebs** [comment]
Is there a queue for multiple clients? I recently read people writing about multiple clients.

**Comment by bmah888** [comment]
No, there's no queue.  Anybody trying to support multiple clients needs to deal with this outside iperf3.
