### ISSUE TITLE
Verbose mode used with Parallel streams causes iperf3 to stop

### ISSUE THREAD

**Issue by ExpandingScope** [esnet/iperf#686]
# Context
* Version of iperf3: iperf 3.3 (cJSON 1.5.2)
* Operating system (and distribution, if any): Centos7 (Both ends)
Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64

# Bug Report

* Actual Behavior
When using Verbose mode on the server and Parallel streams on the client. The iperf on the server will stop and the client will not display all results.

* Steps to Reproduce
A server in verbose mode "iperf3 -s -V" and running the client with multiple threads "iperf3 -P2 -c x.x.x.x".
The client reports "iperf3: error - control socket has closed unexpectedly" and stops before displaying the last second and summary results. The server end will show results but will stop functioning and have to be restarted due to "Segmentation fault (core dumped)"

Server: iperf3 -s -V
Client: iperf3 -P2 -c x.x.x.x

* Possible Solution
Unknown

**Comment by bmah888** [comment]
First, thanks for a well-researched and well-written bug report.  I'm able to reproduce the problem you reported on iperf-3.3 and master (single CentOS 7 host acting as both client and server).  No idea what the problem is at this point but appears to be a Real Bug (tm).
