### ISSUE TITLE
IPv6 Flow Labels not working correctly

### ISSUE THREAD

**Issue by cygnus2048** [esnet/iperf#689]
1) Setting IPv6 flow labels fails consistently when specifying >1 stream
2) Trying to re-run with less than ~10 seconds from prior run, fails to set flow label

* Version of iperf3:
3.2

* Operating system (and distribution, if any):
Ubuntu 16.04

# Bug Report
* Expected Behavior
Should *not* display error message.

* Actual Behavior
Both case 1) and case 2) displays the following error message:
     iperf3: error - unable to set IPv6 flow label

* Steps to Reproduce
case 1)
  1a. run the following command or similar:
          iperf3 -c 2001:db8:bad:a55::2 -t10 -i5 -P2 -6 -L0x12345
case 2)
  2a. run the following command or similar:
          iperf3 -c 2001:db8:bad:a55::2 -t10 -i5 -P1 -6 -L0x12345
  2b. once finished, run the same command right away. 

* Possible Solution

**Comment by cygnus2048** [comment]
Was able to fix both of my issues with the following patch:
```
--- src/iperf_tcp.c.orig	2018-01-16 15:05:42.764551767 -0500
+++ src/iperf_tcp.c	2018-01-24 19:10:54.351167756 -0500
@@ -511,7 +511,7 @@
             freq->flr_label = htonl(test->settings->flowlabel & IPV6_FLOWINFO_FLOWLABEL);
             freq->flr_action = IPV6_FL_A_GET;
             freq->flr_flags = IPV6_FL_F_CREATE;
-            freq->flr_share = IPV6_FL_F_CREATE | IPV6_FL_S_EXCL;
+            freq->flr_share = IPV6_FL_S_ANY;
             memcpy(&freq->flr_dst, &sa6P->sin6_addr, 16);
 
             if (setsockopt(s, IPPROTO_IPV6, IPV6_FLOWLABEL_MGR, freq, freq_len) < 0) {
```

**Comment by bmah888** [comment]
I'm able to reproduce the problem (both versions of it) on one of my CentOS 7 VMs.
