### ISSUE TITLE
Lost/Total Datagrams strange results

### ISSUE THREAD

**Issue by ric79** [esnet/iperf#698]
```
# iperf3 --version
iperf 3.1.7

#iperf3 --client x.x.79.106 --port 5201  -u -k 10
Connecting to host x.x.79.106, port 5201
[  4] local x.x.230.164 port 53812 connected to x.x.79.106 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-0.10   sec  14.1 KBytes  1.16 Mbits/sec  10
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-0.10   sec  14.1 KBytes  1.16 Mbits/sec  28487.952 ms  0/1 (0%)
[  4] Sent 1 datagrams
```
I do not understand why Total Datagram is sent 10, received 1 and Lost 0...

Riccardo

**Comment by bmah888** [comment]
First if you're doing UDP tests, I recommend using a version of iperf3 that's at least 3.2.  There were some pretty big fixes that improved the UDP performance (or rather removed some artifacts that showed up with UDP).

iperf3 count losses by looking at the gaps in the sequence numbers (not, as you might think, by looking at the absolute number of packets sent, although that's a natural expectation).  All `-k` does is to set the number of packets transmitted by the sender, it doesn't communicate any expectation to the receiver (server in your case).

It's also possible that the server is told by the client to terminate the test before all of the UDP packets have been received.  That can cause the receiving iperf3 process to stop receiving packets before they've all arrived.

The combination of these can generate the somewhat odd result of 1 datagram being received and no losses, starting from a total of ten packets sent.  Perhaps we need to revisit that logic.  Also our use case doesn't usually involve such short tests.

**Comment by ric79** [comment]
Thanks. Could you tell me how to install 3.2? For centos 7.4 there is not a valid repo.

**Comment by bmah888** [comment]
I think you'd need to take this up with whomever builds RPMs for CentOS.  Or you could try compiling iperf3 from source code, which is how we distribute it from ESnet.  Going to close this for now as there isn't really an iperf3 code issue that we know of.
