### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alexmarder** [esnet/iperf#699]
I'm not sure if this is right place for this but I've run into this problem on installation from source. The instructions are `./configure && make && make install`. These instruction do not appear to properly install the binaries on Linux (at least Ubuntu 16.04). A final step is required, which is running `sudo ldconfig`, otherwise I get the error `iperf3: error while loading shared libraries: libiperf.so.0: cannot open shared object file: No such file or directory`.

I posted this here to make it easier for people to find through a search.

**Comment by FuzzyStatic** [comment]
Known issue: https://github.com/esnet/iperf/issues/153

**Comment by bmah888** [comment]
Closing as a duplicate of #153.
