### ISSUE TITLE
10G throughput is very low and even low in subsequent run

### ISSUE THREAD

**Issue by surc123** [esnet/iperf#703]
My network is L2 switch connected with network side with a Ubuntu PC and on the PON client side Ubuntu  PC.   Both the server PC is configured with static IP and able to ping each direction. 

Now, running the throughput test it result is very low and even seen 0.00 bytes at times. See below. 

I switched server/client in both sides always seeing one direction very less throughput. I tried similar test with STC and could see bi-directional traffic more than 8g

**Any suggestions ?**

ceteam@ceteam-HP-EliteDesk-800-G3-TWR:~$ iperf3 -c 192.168.1.2 -t 10
Connecting to host 192.168.1.2, port 5201
[  4] local 192.168.1.1 port 60920 connected to 192.168.1.2 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  84.8 KBytes   694 Kbits/sec    2   1.41 KBytes       
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec    1   1.41 KBytes       
[  4]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
[  4]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec    0   1.41 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  84.8 KBytes  69.5 Kbits/sec    5             sender
[  4]   0.00-10.00  sec  0.00 Bytes  0.00 bits/sec                  receiver

iperf Done.
ceteam@ceteam-HP-EliteDesk-800-G3-TWR:~$ iperf3 -c 192.168.1.2 -t 10 -R
Connecting to host 192.168.1.2, port 5201
Reverse mode, remote host 192.168.1.2 is sending
[  4] local 192.168.1.1 port 60924 connected to 192.168.1.2 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec   971 MBytes  8.15 Gbits/sec                  
[  4]   1.00-2.00   sec   972 MBytes  8.16 Gbits/sec                  
[  4]   2.00-3.00   sec   972 MBytes  8.16 Gbits/sec                  
[  4]   3.00-4.00   sec   972 MBytes  8.16 Gbits/sec                  
[  4]   4.00-5.00   sec   972 MBytes  8.16 Gbits/sec                  
[  4]   5.00-6.00   sec   972 MBytes  8.16 Gbits/sec                  
[  4]   6.00-7.00   sec   972 MBytes  8.16 Gbits/sec                  
[  4]   7.00-8.00   sec   972 MBytes  8.16 Gbits/sec                  
[  4]   8.00-9.00   sec   972 MBytes  8.16 Gbits/sec                  
[  4]   9.00-10.00  sec   972 MBytes  8.16 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  9.50 GBytes  8.16 Gbits/sec  159             sender
[  4]   0.00-10.00  sec  9.49 GBytes  8.16 Gbits/sec                  receiver

iperf Done.

**Comment by K9A2** [comment]
I also encounter this problem in my evaluations, and I decide to fix it by myself.
But after navigating the source code, I am confused in which functions does it calculating the thoughput, rtt, retransmission and cwnd which I need to test a newly designed TCP congestion control algorithm for high speed netwrok.

**Comment by bmah888** [comment]
@surc123: Sorry for the delay in responding.  You realize that since your throughput in one direction is reasonable, it's probably not a software problem in iperf3.  iperf3 in fact doesn't do much, each test is merely opening a socket and shoving bytes into it at some rate (that rate could be "as fast as possible").  Possible explanations we've seen in the past are hardware issues, host-based firewalls, or middleboxes between the two.

@K9A2: In your case, iperf3 just calculates throughput based on the number of bytes sent (or received) during a given time interval, divided by the duration of that time interval.  The other quantities (rtt, retransmissions, and cwnd) are merely obtained from values in the TCP_INFO structure.

I'm going to close this issue because it doesn't appear to be a software flaw in iperf3 (in this respect anyway).
