### ISSUE TITLE
Iperf Resource Temporarily Unavailable error -- /Win7/Iperf3/Server/ <-> /Win7/VirtualBox/Ubuntu/Iperf/Client/

### ISSUE THREAD

**Issue by Aeneas32** [esnet/iperf#710]
Running Iperf 3.1.3 under Windows 7 64 as the Server
on one laptop, and
Iperf 2.0.5 under /Windows 7 64/VirtualBox/Ubuntu 16.04/
as the client, on another laptop.
Having navigated around the TCP port incompatibility
using "-c <192.168.x.y> -p 5201",
I still am receiving an error:
iperf3: error - unable to receive parameters from client: Resource temporarily unavailable".
What is causing this error ?

**Comment by bmah888** [comment]
iperf2 and iperf3 do not inter-operate (they have completely different paradigms for managing tests).  You need to either do iperf2 on both ends or iperf3 on both ends.
