### ISSUE TITLE
UDP issues with too many packets reported (out-of-order as well)

### ISSUE THREAD

**Issue by smalenfant** [esnet/iperf#716]
# Context

* Version of iperf3: iperf-3.2

* Hardware: VM/Docker Client. VM->Server

* Operating system (and distribution, if any): Centos 7 for server, alpine in Docker

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.): Using from apk/rpm from major distribution

# Bug Report

I'm using iPerf to send small 100Kbps UDP stream (10 seconds) to a remote server. 

* Expected Behavior

Packet less then 3000, no out-of-order frames

* Actual Behavior

10% of the time, results report lost_packets=364,936 and out-of-order=2,103 (number changes a little bit). I don't think it's possible to stream more packets than bytes.

```
   "end": {
      "sum": {
        "end": 10.000157117843628,
        "seconds": 10.000157117843628,
        "bits_per_second": 101038.41250625034,
        "bytes": 126300,
        "packets": 367040,
        "out_of_order": 2103,
        "start": 0,
        "jitter_ms": 0.027921016023479076,
        "lost_packets": 364936,
        "lost_percent": 99.42676547515258
      },
```

* Steps to Reproduce

```
['iperf3', '--json', '-interval', '0', '--client', 'x.x.x.x', '--port', '5201', '--bandwidth', '100k', '--udp', '--length', '60']
```

Docker container: smalenfant/iperf-elastic:0.3
Source: https://github.com/smalenfant/iperf-elastic

* Possible Solution

No solution at this time

**Comment by bmah888** [comment]
Something definitely seems odd here, although I'm not sure what.  Do you experience this problem outside of this Docker-based environment?  (Like what happens if you run iperf3 by just giving those parameters on the command-line?)

**Comment by smalenfant** [comment]
I'll try to run outside of docker next week. The server is not running in Docker.

**Comment by smalenfant** [comment]
@tb-bingel Sorry I haven't. Not pursuing this project I was working on.

**Comment by bmah888** [comment]
Is there still an issue for us to look at here?  If not, I would like to close this issue.
