### ISSUE TITLE
DSCP Client Option Not Reflected in Results

### ISSUE THREAD

**Issue by TheRealDJ** [esnet/iperf#727]
# Context

* Version of iperf3: iperf3.5

* Hardware: VirtualBox Running on OSX

* Operating system (and distribution, if any): CentOS release 6.4

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.): NA

# Bug Report

* Expected Behavior: Client's DSCP Mark should show in JSON results

* Actual Behavior: No mention of DSCP mark in either Client or Server JSON

* Steps to Reproduce (corrected client command)
  * Server: iperf3 -s --json -1 > iperf_35_server_json.txt
  * Client: iperf3 -c localhost --json --dscp 10 > iperf_35_client_json.txt

* Possible Solution: Add DSCP value to JSON start section

**Comment by bmah888** [comment]
You get the TOS byte as the `tos` member of the `test_start` structure in the JSON.  It's basically the same as the DSCP codepoint (and in the iperf3 implementation the `--dscp` option basically maps onto the `--tos` option)...does that work for you?

**Comment by TheRealDJ** [comment]
The server side output does not reflect this data (correctly) ... 
cat iperf_35_client_json.txt | grep tos
			"tos":	10
cat iperf_35_server_json.txt | grep tos
			"tos":	140320876527626

**Comment by bmah888** [comment]
Ah OK, I understand the bug you're reporting.  I haven't been able to reproduce it yet despite your explicit instructions...I'll play with it a bit more.

**Comment by bmah888** [comment]
I think I got this one...forgot to cast something correctly before JSON rendering.  Not sure why we don't see this on other platforms.
