### ISSUE TITLE
Port iperf to vxworks6.x

### ISSUE THREAD

**Issue by Ysan521** [esnet/iperf#730]
Hello , how can i port iperf to vxworks6.x?

**Comment by ruier** [comment]
please see https://github.com/Wind-River/vxworks7-layer-for-iperf for information, this project shows how to use iperf in vxwork7.  For vxworks6.x, I think the most difficult step is add the  Unix Compatibility layer. You may have a try with Wind-River's help

**Comment by bmah888** [comment]
I'm going to close this, seeing that a similar issue was submitted to the Wind-River/vxworks7-layer-for-iperf repository.  That organization / project is better suited to handle this question.
