### ISSUE TITLE
How to install iperf on vsrx (junOS) juniper

### ISSUE THREAD

**Issue by tahirahmad1985** [esnet/iperf#732]
Hi,

I have installed vsrx on Ubuntu 16.04. And now for throughput testing I need to install iperf on vsrx!

Could you please tell me how I can install iperf on vsrx??

Regards:
Tahir

**Comment by bmah888** [comment]
iperf3 compiles and runs fine on Ubuntu Linux, but you might need to give some more details for someone to be able to help you (in particular how the presence of vsrx impacts the installation of arbitrary executable files).  User questions like this should probably go to the iperf-users mailing list, or perhaps if there's a mailing list or forum for vsrx someone there might be better suited to help you.
