### ISSUE TITLE
iperf3: abrupt interval display

### ISSUE THREAD

**Issue by nikitarulz** [esnet/iperf#734]
While checking network performance using iperf3, I'm facing interval issue at client end. Below are the logs:

[  5]   0.00-1.05   sec  11.2 MBytes  88.7 Mbits/sec    0   42.4 KBytes      
[  5]   1.05-2.01   sec  10.0 MBytes  88.2 Mbits/sec    0   42.4 KBytes      
[  5]   2.01-3.07   sec  11.2 MBytes  88.4 Mbits/sec    0   42.4 KBytes      
[  5]   3.07-4.05   sec  10.3 MBytes  88.5 Mbits/sec    0   42.4 KBytes      
[  5]   4.05-5.11   sec  11.2 MBytes  88.6 Mbits/sec    0   42.4 KBytes      
[  5]   5.11-6.06   sec  10.0 MBytes  88.7 Mbits/sec    0   42.4 KBytes      
[  5]   6.06-7.07   sec  10.7 MBytes  89.0 Mbits/sec    0   42.4 KBytes      
[  5]   7.07-8.02   sec  10.0 MBytes  88.6 Mbits/sec    0   66.5 KBytes      
[  5]   8.02-9.09   sec  11.1 MBytes  86.8 Mbits/sec    0    112 KBytes      
[  5]   9.09-10.06  sec  10.0 MBytes  85.7 Mbits/sec    0    112 KBytes      
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.06  sec   106 MBytes  88.1 Mbits/sec    0             sender
[  5]   0.00-10.12  sec   106 MBytes  87.6 Mbits/sec                  receiver

I checked github bug #125 which was addressing this specific issue. But no help.
I have tried iperf3.0.5, iperf3.1, iperf3.3, iperf3.5. In all versions, I'm getting the same issue.

P.S. Server(with same iperf3 version) provides result as expected with 1 sec time interval, but client provides data at different time intervals in every iteration.

Kindly look into the issue and do let me know if m missing something.

**Comment by bmah888** [comment]
I see where you posted this question to the iperf-users mailing list as well, which was actually the more correct place to ask.  I'm going to close the issue here and reply on the mailing list.
