### ISSUE TITLE
Segfault when killing server

### ISSUE THREAD

**Issue by adrienminet** [esnet/iperf#739]
* Version of iperf3: 3.5
* Hardware: KVM
* Operating system: CentOS 7.4

Hi,
We are using iperf3 in our company to generate concurrent connections in our virtual test lab.
We are currently working on automated testing and we are currently facing a small issue regarding iperf3. Basically, when a client is starting iperf3 with 10 concurrent connections, everything works perfectly. However, when we kill the iperf3 process on the server, it generates the report for each connection but not globally. Instead, we get a segmentation fault. This is the error I have:

`` iperf3[1365]: segfault at 10 ip 00007f312f1e8a89 sp 00007ffff446f670 error 4 in libiperf.so.0.0.0[7f312f1d7000+23000] ``

Note that the same behavior with only 1 connection doesn't raise this segfault.

**Comment by bmah888** [comment]
Tried one more time to recreate this on iperf-3.6, not successful.  Closing due to lack of follow-up after 5 months.
