### ISSUE TITLE
IPERF 3.1.3 reports different results using different IP addressess

### ISSUE THREAD

**Issue by msaadat2018** [esnet/iperf#740]
I use IPERF 3.1.3 to run a UDP test between server (172.20.X.X) and client (172.16.X.X) over MPLS. When I use the mentioned IP scheme, I get 22% packet loss:

C:\Users\Tetra>iperf -c 172.20.128.101 -u -b512k -w128k -l1500
Connecting to host 172.20.128.101, port 5201
[  4] local 172.16.3.80 port 49345 connected to 172.20.128.101 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.01   sec   170 KBytes  1.37 Mbits/sec  116
[  4]   1.01-2.01   sec  14.6 KBytes   120 Kbits/sec  10
[  4]   2.01-3.01   sec  16.1 KBytes   132 Kbits/sec  11
[  4]   3.01-4.01   sec  45.4 KBytes   373 Kbits/sec  31
[  4]   4.01-5.01   sec  63.0 KBytes   517 Kbits/sec  43
[  4]   5.01-6.01   sec  63.0 KBytes   517 Kbits/sec  43
[  4]   6.01-7.00   sec  61.5 KBytes   505 Kbits/sec  42
[  4]   7.00-8.00   sec  63.0 KBytes   517 Kbits/sec  43
[  4]   8.00-9.00   sec  63.0 KBytes   517 Kbits/sec  43
[  4]   9.00-10.02  sec  67.4 KBytes   544 Kbits/sec  46
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datag
rams
[  4]   0.00-10.02  sec   627 KBytes   513 Kbits/sec  31.325 ms  96/428 (22%)
[  4] Sent 428 datagrams

iperf Done.

But when I assign 172.20.X.X IP to the client instead of 172.16.X.X, then I get no packet loss:

C:\Users\Tetra>iperf -c 172.20.128.101 -u -b512k -w128k -l1500
Connecting to host 172.20.128.101, port 5201
[  4] local 172.20.80.80 port 49353 connected to 172.20.128.101 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.01   sec   183 KBytes  1.48 Mbits/sec  125
[  4]   1.01-2.01   sec  14.6 KBytes   120 Kbits/sec  10
[  4]   2.01-3.03   sec  1.46 KBytes  11.8 Kbits/sec  1
[  4]   3.03-4.01   sec  46.9 KBytes   391 Kbits/sec  32
[  4]   4.01-5.01   sec  63.0 KBytes   517 Kbits/sec  43
[  4]   5.01-6.01   sec  63.0 KBytes   517 Kbits/sec  43
[  4]   6.01-7.00   sec  61.5 KBytes   505 Kbits/sec  42
[  4]   7.00-8.00   sec  63.0 KBytes   517 Kbits/sec  43
[  4]   8.00-9.00   sec  63.0 KBytes   517 Kbits/sec  43
[  4]   9.00-10.02  sec  67.4 KBytes   544 Kbits/sec  46
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datag
rams
[  4]   0.00-10.02  sec   627 KBytes   513 Kbits/sec  33.564 ms  0/428 (0%)
[  4] Sent 428 datagrams

iperf Done.

Please advise.

**Comment by AStotal** [comment]
Are the server and client connected over MPSL router, or connected directry?
Have you checked counters on rx/tx interfaces?

**Comment by msaadat2018** [comment]
Yes they are connected through MPLS router. Could you please let me know how can I check the counters on RX/TX interfaces? and why do I need to do that?

Thanks

**Comment by TheRealDJ** [comment]
Sounds like an MPLS issue. Do you get packet loss with other protocols? What happens with iperf in TCP mode? Have you tried a more recent version of iperf? Latest release is 3.5

**Comment by bmah888** [comment]
No response to feedback...closing.
