### ISSUE TITLE
Error in Mobile Phone

### ISSUE THREAD

**Issue by McCrewfree** [esnet/iperf#745]
I use iperf at mobile phone.
My goal is using iperf to get the whole bandwidth trace in every second.

In AT&T LTE
use mobile phone as client. 

iperf -c XXX.XXX.XXX.XXX -t 200

No response, then time out.

But in WIFI
everything is good.

What's wrong with that?

**Comment by TheRealDJ** [comment]
Are you using a public IP or a private IP?

**Comment by bmah888** [comment]
Is this even an iperf3 issue?  I'm asking because the name of the iperf3 executable is `iperf3`, not `iperf`.

**Comment by McCrewfree** [comment]
@bmah888 
Thank you for the reply! 
I got the Android version at https://iperf.fr/iperf-download.php
I thought the fault is the public IP and private IP.

**Comment by McCrewfree** [comment]
@TheRealDJ 
Thank you for the reply! It's my first time to use Git, sorry for response you so late.
Actually, I thought that is the fault.

A is a campus server, with a IP 128.238.X.X (use ifconfig to find out)
B is a mobile phone(AT&T)  
C is my laptop under campus Wifi  
D is my laptop under home Wifi (Verizon)

A: -s 
B: -c 128.238.X.X        time out
C: -c 128.238.X.X        Good
D: -c 128.238.X.X        time out

In D, when I use ipconfig I can only get my private IP, I find my public IP at website(https://whatismyipaddress.com/ip-lookup) 100.2.45.X
 
I checked some files, it looks like I need to set up tunnel or so. Is that right?
Do you know how to do that? 

Thank you so much!

**Comment by TheRealDJ** [comment]
Ideally, you would need port forwarding from the Public IP (100.2.45.X) to the A server IP. You could setup a tunnel, but you would need another server accessible from the Internet to tunnel to ... and a tunnel and additional server would/could decrease performance. I would not recommend running iperf over a tunnel unless you are trying to measure the bandwidth of the tunnel.
