### ISSUE TITLE
v3.5 error - control socket has closed unexpectedly

### ISSUE THREAD

**Issue by bcronje** [esnet/iperf#751]
# Context
I use iperf3 as part of an automated test environment using ansible. We run various tests over different network conditions.

* Version of iperf3: iperf 3.5 (cJSON 1.5.2)

* Hardware: lxd containers

* Operating system (and distribution, if any): Ubuntu 16.04.3

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

# Bug Report
**Randomly** I get the following error in the json report:
`"error":	"error - control socket has closed unexpectedly"`
When it happens, it seems to always occur after the second last interval, e.g. using `-t 60` the json report will contain the interval report for interval 58 - 59, and then ends with the error. So the 60th interval is never reported on.

The server is run with `iperf3 -s -D`
The client is run with `iperf3 -c 1.1.1.1 -t 60 -P 8 -J`

Unfortunately I do not have access to the output of the server.

Note - I never experienced this when I was still using iper3 version that ships with Ubuntu, think it was v3.1.x ?? This might only be coincidence or a regression.

* Expected Behavior
Expects to complete the test without any errors.

* Actual Behavior
Test ends with `"error":	"error - control socket has closed unexpectedly"`

* Steps to Reproduce
It occurs randomly, so not easy to reproduce.

**Comment by bmah888** [comment]
Increased the timeout on the control channel as per the first commit in PR #859, which hopefully will solve this issue.

A further enhancement could be to allow setting this as a command-line parameter, although note that the timer that is affected by this has no effect for the `--bytes` or ``--blockcount` cases.

Closing.
