### ISSUE TITLE
iperf3.5 : bandwidth limitation in UDP reverse mode is not working

### ISSUE THREAD

**Issue by geertn444** [esnet/iperf#761]
# Context

* Version of iperf3:
iperf 3.5 (cJSON 1.5.2)
CYGWIN_NT-6.1 workstation 2.10.0(0.325/5/3) 2018-02-02 15:16 x86_64
Optional features available: CPU affinity setting, authentication

* Hardware:
 HP portables

* Operating system (and distribution, if any):
Windows

# Bug Report

sending UDP streams at 1M:

>iperf3 -l 100 -k 20000000 -u -c WORKSTATION **-b 1M**

warning: Ignoring nonsense TCP MSS -13312
Connecting to host WORKSTATION, port 5201
[  5] local 10.104.16.135 port 49152 connected to 10.104.80.77 port 5201
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-1.00   sec   122 KBytes   999 Kbits/sec  1249
[  5]   1.00-2.00   sec   122 KBytes  **1.00 Mbits/sec**  1250
[  5]   2.00-3.00   sec   122 KBytes  1.00 Mbits/sec  1250
[  5]   3.00-3.31   sec  37.7 KBytes   999 Kbits/sec  386

This works ok
However, when i try to reverse the flow with -R option:

>iperf3 -R -l 100 -k 20000000 -u -c WORKSTATION **-b 1M**
warning: Ignoring nonsense TCP MSS -13312
Connecting to host WORKSTATION, port 5201
Reverse mode, remote host WORKSTATION is sending
[  5] local 10.104.16.135 port 58935 connected to 10.104.80.77 port 5201
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datag
rams
[  5]   0.00-1.00   sec   546 KBytes  4.47 Mbits/sec  0.165 ms  606993/612585 (9
9%)
[  5]   1.00-2.00   sec  1.57 MBytes  **13.2 Mbits/sec**  0.077 ms  -16472/0 (0%)

then the "server" is actually sending at maximum speeds (not the limited 1M)
(note: remote workstation is across a WAN link, hence the 13 Mbps)

* Expected Behavior

communicate all parameters to remote side and comply with these parameters

**Comment by bmah888** [comment]
I agree this behavior is unexpected.  Please note that Windows is not an officially supported platform for iperf3.

That having been said I'm doing a little testing to see if we can reproduce the problem on one of the supported platforms.  (So far I haven't been able to but I'll keep looking.)

I wonder if the fact that the client wasn't able to determine a TCP MSS (which we use as kind of a proxy for the path MTU) might be a factor.

**Comment by bmah888** [comment]
Closing for now.  This bug can be re-opened if more information is discovered.
