### ISSUE TITLE
Multiple stream bandwidth limitation

### ISSUE THREAD

**Issue by rsafer** [esnet/iperf#771]
Dear Iperf team,

I am using iperf3 to test our connection and would like to use multiple streams with bandwidth specified for each stream separately.
From documentation and "-P" and "-b" parameter description I understand that this should be possible for both UDP and TCP using ipert3.

Commands that I tried are following variants:
```
 iperf3 -c 192.168.0.22 -i 10 -f k -t 30 -P 2 -b 100K 2000K
 iperf3 -c 192.168.0.22 -i 10 -f k -t 30 -P 2 -b /100K /2000K
 iperf3 -c 192.168.0.22 -i 10 -f k -t 30 -P 2 -b 100K /2000K
```

But I always get same throughput on both streams.

Is there a way to make something like this work without using multiple iperf3 calls on different ports? Am I doing something wrong with function call?

# Context

* Version of iperf3: 3.1.5

* Hardware: Zynq board

* Operating system (and distribution, if any): Linux

# Bug Report

* Expected Behavior
Throughput in each stream is limited according to the stream bandwidth limitation

* Actual Behavior
 Different bandwidth limit is not applied for each stream

* Steps to Reproduce
Setup server side:
`ipert3 -s`
Start client side:
`iperf3 -c 192.168.0.22 -i 10 -f k -t 30 -P 2 -b 100K 2000K`

**Comment by bmah888** [comment]
That's not what `-b` does.  The idea is that if you give two arguments to `-b`, the first is a bitrate and the second is a write count to allow sending in bursts.  They two arguments need to be separated by a slash and no spaces.

But that's not what you wanted.  There is not currently a way to apply different bandwidth limits to multiple, parallel streams.  You need to use separate iperf3 client and server instances to do that.
