### ISSUE TITLE
UDP warning when using a length larger than 1448 bytes

### ISSUE THREAD

**Issue by sangorrin** [esnet/iperf#785]
# Context
* Version of iperf3:
iperf 3.6+ (cJSON 1.5.2)
* Hardware:
x86_64
* Operating system (and distribution, if any):
Ubuntu 16.04

# Bug Report

When testing with UDP (iperf3 -u -c 192.168.20.99 -p 5100 -b 10G -l 1449) if we specify the length -l to be greater than 1448 the following warning appears:
warning: UDP block size 1449 exceeds TCP MSS 1448, may result in fragmentation / drops

I believe that fragmentation starts for lengths larger than 1472 in case of MTU 1500 (8972 for jumbo frames with mtu 9000, that is MTU-28), and UDP has nothing to do with TCP MSS.

Thanks,
Daniel

**Comment by zimash** [comment]
@sangorrin https://github.com/esnet/iperf/issues/604#issuecomment-310161190

**Comment by sangorrin** [comment]
Thanks!
