### ISSUE TITLE
--forceflush not working for an iperf3 server message

### ISSUE THREAD

**Issue by thatguy7** [esnet/iperf#790]
* Version of iperf3: 3.6

* Operating system (and distribution, if any): Ubuntu 16 LTS

# Bug Report

* Expected Behavior
When calling iperf3 -s --forceflush from phyton (Popen), output should be flushed to stdout immediately. And it helps with the actual measurements - with the flag they are flushed in the same manner they are displayed in the terminal, and so should the other output of iperf3.

* Actual Behavior
But the "Server started listening on ..." is not flushed until a client connects to the server, even with the flag.

* Steps to Reproduce
The following python code will not generate any output, until a client actually connects.
```Python
import subprocess
process = subprocess.Popen("iperf3 -s --forceflush".split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)

for line in iter(process.stdout.readline, ""):
    print(line)
```

**Comment by bmah888** [comment]
So there's a bug here, although it's not that `--forceflush` is totally broken, just that it doesn't work in this specific case.

Need to add a check and flush output in `src/iperf_server_api.c`, also take care of some stupid-looking code that I left behind when I did 246c1bcacdbddfb9e6ac177de834bc5108483786.
