### ISSUE TITLE
Iperf 3 UDP stop working 

### ISSUE THREAD

**Issue by soeyehtet1993** [esnet/iperf#792]
I test Iperf 3 UDP testing between two controller (one is server and another is client). Then the command line to test the UDP bandwidth has been executed in server site and client side. But after running 1 hours, the UDP from client side is stopped working. After it is stopped, the server side capture MDNS protocol from the client side. The experiment has been repeated again and again and the experiment is always stopped after 1 hour.

**Comment by bmah888** [comment]
You'd need to provide more details, such as the hardware and operating system, version numbers and command-line arguments for both client and server.  It would also be good to know something about the networking environment.  Off-hand I'm wondering if there is a middlebox or host-based firewall on the path that is limiting the length of a UDP session to one hour.  iperf3 has no intrinsic limits on how long a test can run.

**Comment by bmah888** [comment]
No response, closing.  Thanks @danger89 for trying to get more information.
