### ISSUE TITLE
truncates file transfers

### ISSUE THREAD

**Issue by rdp** [esnet/iperf#798]
# Context

Transfer of large files.

* Version of iperf3:

af34c411dfbb2a452543311f1989f445edb3b3c1

* Hardware:

some type of xeon server

* Operating system (and distribution, if any):

CentOS release 6.7 (also Ubuntu 18.04)

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

gcc version 4.4.7

# Bug Report

* Expected Behavior

Using the "-F" flag on both sides, it should copy files in their entirety.

* Actual Behavior

It creates a truncated file

* Steps to Reproduce

server:
 ./iperf3 -s -F 5G.hprof

client:
$ ls -l 5G.hprof 
-rw-rw-r-- 1 packrd packrd 5000000000 Sep 24 17:27 5G.hprof

./iperf3 -c server_ip -F 5G.hprof 

server:

$ ls -l /dev/shm/5G.hprof 
-rw-rw-r-- 1 packrd packrd 4997809144 Sep 24 18:26 5G.hprof

Perhaps it's not flushing?

**Comment by bmah888** [comment]
Although iperf3 is capable of reading test data from a file and writing the results to a file, it was never designed to transfer files.  If you want a real file transfer tool, there's a multitude of utilities that are designed for that task.  FTP is the classic example of this, but netcat can be made to work too (it's probably the closest to iperf3 in terms of how you run it).

**Comment by rdp** [comment]
I found iperf3 to be more performant cpu-wise than any existing raw file transferers, FWIW: https://unix.stackexchange.com/a/471951/8337 .  Might be nice to add a bonus "file transfer option" sometime to it, cheers!
