### ISSUE TITLE
iPerf 3, no 'lost_packets' reported' in UDP streams when -R is used

### ISSUE THREAD

**Issue by Buli1212** [esnet/iperf#802]
**Context**
Version of iperf3: "iperf 3.1.6"

**Hardware / OS** : Linux localhost 3.18.14-12365438 #1 SMP PREEMPT Wed Feb 14 14:42:58 KST 2018 aarch64

**Bug Report**
When using `-c xx.xx.xx.xxx -p 5200 -J -t 20 -u -R -b 1000000` the JSON output streams do not contain a lost_packets value. This value is shown when I run `-c xx.xx.xx.xxx -p 5200 -J -t 20 -u -b 1000000` without `-R`

**Expected Behavior**

```
"streams":	[{
					"socket":	4,
					"start":	0,
					"end":	1.000294,
					"seconds":	1.000294,
					"bytes":	125976,
					"bits_per_second":	1007511.821641,
					"jitter_ms":	0.304162,
					"no":	0,
					"packets":	87,
					"lost_percent":	0,
					"omitted":	false
				}],
			"sum":	{
				"start":	0,
				"end":	1.000294,
				"seconds":	1.000294,
				"bytes":	125976,
				"bits_per_second":	1007511.821641,
				"jitter_ms":	0.304162,
				"lost_packets":	0,
				"packets":	87,
				"lost_percent":	0,
				"omitted":	false
			}
```

**Actual Behaviuor**:

```
"streams":  [{
                "socket":   4,
                "start":    0,
                "end":  1.000469,
                "seconds":  1.000469,
                "bytes":    112944,
                "bits_per_second":  903128.245216,
                "packets":  78,
                "omitted":  false
            }],
        "sum":  {
            "start":    0,
            "end":  1.000469,
            "seconds":  1.000469,
            "bytes":    112944,
            "bits_per_second":  903128.245216,
            "packets":  78,
            "omitted":  false
        }
```

**Steps to Reproduce**
Running UDP test with the `-R` parameter.

**Comment by bmah888** [comment]
Please try a newer version of iperf3.  In particular, version 3.2 and newer have better handling of UDP statistics.  I did a quick test on 3.6 and it provides the `lost_packets` and `lost_percent` in the JSON for `-R` (reverse direction) tests.
