### ISSUE TITLE
iperf3 throughput vs /proc/net/dev throughput measurements

### ISSUE THREAD

**Issue by ckleu** [esnet/iperf#809]
# Context

* Version of iperf3:
iperf 3.6+ (cJSON 1.5.2)
Linux 4.19.0-041900-generic #201810221809 SMP Mon Oct 22 22:11:45 UTC 2018 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing

* Hardware:
Two machines connect back-to-back
Testing revolves putting the IP directly on the physical port

* Operating system (and distribution, if any):
Ubuntu 18.04.1 + v4.19.0 kernel

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
Execution string: "iperf3 --client {ip} --omit {omit} --time {time} " \
      "--affinity {affinity} --zerocopy --parallel {parallel} --json " \
      "--no-delay --set-mss {mss} --port {port}"

# Bug Report

* Actual Behavior
iperf3 results do not match up with bwm-ng and other tools polling /proc/net/dev or /sys/class/net/ statistics

* Expected Behavior
Not seeing a delta between what external OS tools measure for throughput, or being able able to cater for the deviation in some way.
Perhaps a goodput vs throughput scenario?

* Steps to Reproduce
Run iperf3 test (single parallel thread to make it easier to debug)
Simultaneously run: "bwm-ng -I {netdev} --unit bits"

Seems to be applicable in small packets (--no-delay --set-mss 216) or large packets (--no-delay --set-mss 1460)
216 (256B): 5Gbps vs 3.8Gbps
1460 (1500B): 24.6Gbps vs 23.5Gbps

* Possible Solution
Further investigation required

**Comment by ckleu** [comment]
Using `--set-mss 216` (256-40)

Packet capture (when TSO is disabled and Neagle algorithm is disabled)
MAC: 14B | IP: 20B | TCP: 32B | data: 204B -> 270B

```
-M, --set-mss n
              set TCP/SCTP maximum segment size (MTU - 40 bytes)

```
270-40-14 = 216

perhaps iperf3 only reports on good-put BW? [excluding any headers]
5*204/270 = 3.77  (where 5Gbps is the on-the-wire throughput, 204B is the DATA portion of the pcap and 270B is the on-the-wire size)

**Comment by FuzzyStatic** [comment]
iperf3 reports the TCP payload. It does not report on-the-wire speeds.

**Comment by bmah888** [comment]
Thanks @FuzzyStatic, this is correct.  iperf3 only computes throughput, etc. based on the amount of TCP/UDP/SCTP payload data successfully transferred.  Protocol overheads are generally not counted.
