### ISSUE TITLE
Feature request: more control of src-port-base and src-port-stride to improve repeatability on small packet sizes

### ISSUE THREAD

**Issue by ckleu** [esnet/iperf#810]
# Context

* Version of iperf3:
iperf 3.6+ (cJSON 1.5.2)

* Hardware:
Two machines connect back-to-back
Testing revolves putting the IP directly on the physical port

* Operating system (and distribution, if any):
Ubuntu 18.04.1 + v4.19.0 kernel

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
Execution string: "iperf3 --client {ip} --omit {omit} --time {time} " 
"--affinity {affinity} --zerocopy --parallel {parallel} --json " 
"--no-delay --set-mss {mss} --port {port}"
Scale from 88B to 1460B

Validation is in the repeatability of tests:
tests are executed 10 or 20 times and verification is done to check results are within 3%

# Enhancement Request

* Current behavior
Scenario: NIC with 8 queues configured, IRQs pinned to dedicated cores
NIC has RSS algorithms: toeplitz, xor, crc32

When running the exact same test, the RSS algorithms have different queuing outputs (and results in different iperf3 performance) because the src-port-base cannot be specified (static input variables: L2-src, L2-dst, L3-src,L4-dst,L4-dst) - performance reduces by ability for kernel to handle interrupts

Increasing the `--parallel` higher than 8 (16/24/32) reduces the performance - single-threaded iperf3 userspace application becoming the bottleneck

**Workaround:** 
start up multiple iperf3 daemons listening on different ports and assign CPU affinity to each instance
use 8 streams for each instance
use python multiprocessing library to aggregate results
execute tests 5, 10 or 20 times and use the MEDIAN value to graph results (goal is to reduce these multiple iterations to about 3 for sanity checks)

* Desired behaviour
Have a bit more control on the L4-SRC-base and L4-SRC-stride values to ensure consistency and reproducibility of test results

**Comment by bmah888** [comment]
I believe that the `--cport` option will give you (approximately) the L4-SRC-base you want.  As for your L4-SRC-stride, it's probably just easiest for you to go into your local copy of the source code and make the necessary changes.
