### ISSUE TITLE
How to run iperf in android

### ISSUE THREAD

**Issue by victors0991** [esnet/iperf#816]
Hello,
I download iperf3 and I opened with android studio but when I ran app, it show me a blank page with hello word, I read main activity and it is empty so how do I run iperf?

**Comment by bmah888** [comment]
Building and running iperf3 on Android isn't officially supported, although there have been some reports of success.  It sounds like your development environment isn't set up correctly, or at least it isn't finding the iperf3 sources.

**Comment by victors0991** [comment]
But if you read main activity, there is only show a text.
