### ISSUE TITLE
Cannot use Ptcp or Pudp from iperf_api.h

### ISSUE THREAD

**Issue by reschl** [esnet/iperf#821]
# Context

* Version of iperf3: libiperf-dev 3.6-2 (Debian testing) as well as github master latest

* Hardware: any

* Operating system (and distribution, if any): Running on Debian testing, but probably also others

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):  g++ (Debian 8.2.0-9) 8.2.0

# Bug Report

* Expected Behavior
Constants from the iperf_api.h to be usable as is

* Actual Behavior
Compiler error
```
error: ‘SOCK_DGRAM’ was not declared in this scope
         set_protocol(iperf_test_, Pudp);
```

* Steps to Reproduce
Include only `iperf_api.h` and try to use `Pudp` or `Ptcp` constants defined in the header.

* Possible Solution
Add `#include <sys/socket.h>` to the header. Which is reasonable in my opinion, as you include the header in other files already.
Define `Ptcp` und `Pudp` in a way that allow a user to use those constants without requiring to include additional files in the right order. Probably harder to preserve portability this way.

**Comment by bmah888** [comment]
If we do decide to fix this (which I _think_ is a good idea), I'd favor the approach of adding `#include <sys/socket.h>`.
