### ISSUE TITLE
Json Parsing Error

### ISSUE THREAD

**Issue by lukaseller** [esnet/iperf#826]
It seems that there is an issue in iPerf regarding json output.
 
In the case of packet loss iPerf does not generate valid json files. 
Instead of a valid `null` or a `"nan"` string the output is as follows:

`"lost_percent":	nan,`

When replacing `nan` with null using `sed` the jsons are valid. 

We are using version 3.1b3 on Ubuntu.

**Comment by bmah888** [comment]
3.1b3 is pretty old.  Most notably we've updated the included JSON library at least once since then.  Can you try with something newer?  (3.6 is current as of this writing.)

**Comment by bmah888** [comment]
Closing due to lack of feedback.  It feels to me like we also did a code change to prevent "nan" from showing up.
