### ISSUE TITLE
iperf_time.c:43:error: ‘CLOCK_MONOTONIC_RAW ’ undeclared

### ISSUE THREAD

**Issue by xiao4214** [esnet/iperf#829]
********    in ubuntu 10.04 : make error    *********************************************

1:  ./configure        (OK)

2:  make                 (error)
     iperf_time.c:43:error:'CLOCK_MONOTONIC_RAW' undeclared

     Detection cause:    /usr/include/linux/time.h    (presence)  OK
     test code:
            #include <stdio.h>
            //#include <time.h>  // Compile failed
           #include <linux/time.h>  // Compile success

            int main (void)
            {
                    printf ("%d\n", CLOCK_MONOTONIC_RAW);
                    return 0;
             }

3:  make install       (error, wait 2 success)
*******************************************************************************************

********    in ubuntu 14.04 : make OK,  run OK ***********
1:  ./configure        (OK)

2:  make                 (OK)

3:  make install       (OK, need root)
****************************************************************

1. Why can't ubuntu 10.04 compile?

2. How to compile on windows?

**Comment by bmah888** [comment]
For the Ubuntu 10.04 case, does it help if you change `CLOCK_MONOTONIC_RAW` to `CLOCK_MONOTONIC`?  I'm seeing a compile failure on FreeBSD which is fixed with that change...I think `CLOCK_MONOTONIC_RAW` is a Linux-ism.

This code change came in with #738.
