### ISSUE TITLE
Cygwin Configure Error: Cannot Guess Build type; you must specify one

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#83]
_From [BabaGanoush45](https://code.google.com/u/101372295868330011028/) on August 05, 2013 07:42:44_

What steps will reproduce the problem? 1.Installed Cygwin with proper Make Packages
2.Decompressed packages and navigated to iperf-3.0b5 folder
3.Run ./configure What is the expected output? What do you see instead? After running the ./configure, I try to run make, and get:

make: **\* No targets specified and no makefile found. Stop. What version of the product are you using? On what operating system? Iperf-3.0b5.tar.gz
Windows 7 Enterprise SP1 x64 with Cygwin64 Terminal Please provide any additional information below.

_Original issue: http://code.google.com/p/iperf/issues/detail?id=83_

**Comment by ralcini** [comment]
I think that this ticket can be considered obsolete. The version on branch master has not this problem.

**Comment by bmah888** [comment]
Closing due to previous comment.
