### ISSUE TITLE
Iperf3 server with listening port 0 does not print its listening port

### ISSUE THREAD

**Issue by jamofer** [esnet/iperf#831]
# Context

* Version of iperf3: iperf 3.1.3

* Hardware: X86_64

* Operating system (and distribution, if any): Kubuntu 18.04

# Bug Report

* Expected Behavior
```
iperf3 -B 127.0.0.1 -s -p 0
-----------------------------------------------------------
Server listening on 39653
-----------------------------------------------------------
```
* Actual Behavior
```
-----------------------------------------------------------
Server listening on 0
-----------------------------------------------------------
```
* Steps to Reproduce
iperf3 -B 127.0.0.1 -s -p 0

* Possible Solution
#832

**Comment by bmah888** [comment]
The fact that `--port 0` (or `-p 0`) is accepted is actually a bug.  There's no reason to allow the iperf3 server to bind itself to a random port. I'm going to file an issue for that.

**Comment by MrMino** [comment]
@bmah888 Port 0 is a standard way of saying "kernel, please give me an unused port". It is expected by users as it's something standard to Linux.

First use-case that comes to mind would be automation of iperf on remote hosts. I need to use port 0 for that, as I'm never sure what port would be open for me.

This would also make it possible to make simple scripts that run performance tests without the need of specifying a port.

Port 0 is expected and solves a valid use-case. Why reject it? Why _defend_ against it?

**Comment by jamofer** [comment]
In fact that was my use case. It's really strange to put a new feature limiting the application usage in my opinion.
