### ISSUE TITLE
iperf 3.6 UDP lost datagrams 100G

### ISSUE THREAD

**Issue by exc1te** [esnet/iperf#841]
# Context
Hi!
I am testing a 100G Mellanox network: 2 servers connected through switch SN2700.
When i testing using TCP all seems to be fine, but when i testing using UDP i have a lot of lost datagrams, also same thing when i test UDP in one process:
```
[ ID] Interval           Transfer     Bitrate         Total Datagrams
[  5]   0.00-60.00  sec  38.5 GBytes  5.51 Gbits/sec  28310420
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.00  sec  38.5 GBytes  5.51 Gbits/sec  0.000 ms  0/28310420 (0%)  sender
[  5]   0.00-60.04  sec  24.3 GBytes  3.48 Gbits/sec  0.001 ms  10427939/28304262 (37%)  receiver
```

* Version of iperf3:
iperf 3.6 (cJSON 1.5.2)
Optional features available: CPU affinity setting, IPv6 flow label, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing

* Hardware:
Mellanox Technologies MT27800 Family [ConnectX-5] with MLNX_OFED_LINUX-4.5-1.0.1.0-rhel7.6-x86_64 drivers

* Operating system (and distribution, if any):
CentOS Linux release 7.6.1810 (Core)
3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
net.core.rmem_max = 2147483647
net.core.wmem_max = 2147483647
net.ipv4.tcp_rmem = 4096 87380 2147483647
net.ipv4.tcp_wmem = 4096 65536 2147483647
net.ipv4.udp_mem = 8388608 12582912 16777216
net.ipv4.udp_rmem_min = 131072
net.ipv4.udp_wmem_min = 131072

# Bug Report

* Expected Behavior
No lost UDP datagrams.

* Actual Behavior
There are a lot of lost datagrams:
```
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.00  sec  24.1 GBytes  3.45 Gbits/sec  0.001 ms  4552161/22287505 (20%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.00  sec  24.5 GBytes  3.51 Gbits/sec  0.003 ms  3844464/21872131 (18%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.00  sec  25.1 GBytes  3.59 Gbits/sec  0.002 ms  7342850/25796013 (28%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.00  sec  24.9 GBytes  3.57 Gbits/sec  0.001 ms  2467206/20803944 (12%)
[  5]   0.00-60.00  sec  18.8 GBytes  2.69 Gbits/sec  0.006 ms  948898/14756964 (6.4%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.00  sec  23.4 GBytes  3.35 Gbits/sec  0.001 ms  8836691/26032893 (34%)
[  5]   0.00-60.00  sec  13.7 GBytes  1.97 Gbits/sec  0.019 ms  7346799/17457784 (42%)
[  5]   0.00-60.00  sec  21.4 GBytes  3.07 Gbits/sec  0.001 ms  4870851/20636920 (24%)
[  5]  60.00-60.04  sec  14.3 MBytes  3.10 Gbits/sec  0.001 ms  6626/16866 (39%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.04  sec  25.1 GBytes  3.59 Gbits/sec  0.001 ms  7349476/25812879 (28%)  receiver
[  5]  60.00-60.04  sec  9.07 MBytes  1.97 Gbits/sec  0.013 ms  2592/9105 (28%)
[  5]  60.00-60.04  sec  17.4 MBytes  3.78 Gbits/sec  0.001 ms  1769/14263 (12%)
[  5]  60.00-60.04  sec  15.6 MBytes  3.39 Gbits/sec  0.001 ms  2099/13303 (16%)
[  5]  60.00-60.04  sec  15.8 MBytes  3.43 Gbits/sec  0.001 ms  2921/14254 (20%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.04  sec  24.1 GBytes  3.45 Gbits/sec  0.001 ms  4553930/22301768 (20%)  receiver
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.04  sec  18.8 GBytes  2.69 Gbits/sec  0.013 ms  951490/14766069 (6.4%)  receiver
[  5]   0.00-60.04  sec  24.9 GBytes  3.57 Gbits/sec  0.001 ms  2469305/20817247 (12%)  receiver
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.04  sec  24.5 GBytes  3.51 Gbits/sec  0.001 ms  3847385/21886385 (18%)  receiver
[  5]  60.00-60.04  sec  14.8 MBytes  3.16 Gbits/sec  0.002 ms  6602/17257 (38%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.04  sec  23.4 GBytes  3.35 Gbits/sec  0.002 ms  8843293/26050150 (34%)  receiver
[  5]  60.00-60.04  sec  13.9 MBytes  2.97 Gbits/sec  0.001 ms  2963/12954 (23%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.04  sec  21.5 GBytes  3.07 Gbits/sec  0.001 ms  4873814/20649874 (24%)  receiver
[  5]  60.00-60.04  sec  5.26 MBytes  1.12 Gbits/sec  0.008 ms  7393/11168 (66%)
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-60.04  sec  13.8 GBytes  1.97 Gbits/sec  0.008 ms  7354192/17468952 (42%)  receiver
```

* Steps to Reproduce
Server:
$IPERF_3 -s -B 10.128.102.2 -p 5201 -i 10 &
$IPERF_3 -s -B 10.128.102.2 -p 5202 -i 10 &
$IPERF_3 -s -B 10.128.102.2 -p 5203 -i 10 &
$IPERF_3 -s -B 10.128.102.2 -p 5204 -i 10 &
$IPERF_3 -s -B 10.128.102.2 -p 5205 -i 10 &
$IPERF_3 -s -B 10.128.102.2 -p 5206 -i 10 &
$IPERF_3 -s -B 10.128.102.2 -p 5207 -i 10 &
$IPERF_3 -s -B 10.128.102.2 -p 5208 -i 10 &

Client:
$IPERF_3 -B 10.128.102.1 -c 10.128.102.2 -p 5201 -t 60 -b 0 -u -i 10 --udp-counters-64bit -w4m &
$IPERF_3 -B 10.128.102.1 -c 10.128.102.2 -p 5202 -t 60 -b 0 -u -i 10 --udp-counters-64bit -w4m &
$IPERF_3 -B 10.128.102.1 -c 10.128.102.2 -p 5203 -t 60 -b 0 -u -i 10 --udp-counters-64bit -w4m &
$IPERF_3 -B 10.128.102.1 -c 10.128.102.2 -p 5204 -t 60 -b 0 -u -i 10 --udp-counters-64bit -w4m &
$IPERF_3 -B 10.128.102.1 -c 10.128.102.2 -p 5205 -t 60 -b 0 -u -i 10 --udp-counters-64bit -w4m &
$IPERF_3 -B 10.128.102.1 -c 10.128.102.2 -p 5206 -t 60 -b 0 -u -i 10 --udp-counters-64bit -w4m &
$IPERF_3 -B 10.128.102.1 -c 10.128.102.2 -p 5207 -t 60 -b 0 -u -i 10 --udp-counters-64bit -w4m &
$IPERF_3 -B 10.128.102.1 -c 10.128.102.2 -p 5208 -t 60 -b 0 -u -i 10 --udp-counters-64bit -w4m &

**Comment by bmah888** [comment]
`-b 0` means that iperf3 will be sending packets in a (kinda) tight loop as fast as it can.  You are likely overrunning the socket buffers on the client side faster than your 100G link can drain them.  Remember that UDP has no flow control or congestion control.  Now if your goal is to saturate the link, this test is probably a good way to do it, even though a bunch of packets are getting dropped.  You'd need to add up the throughput received by all of the server processes to get the aggregate throughput.  If your goal is error-free tests, you probably should be doing TCP anyway because UDP doesn't guarantee delivery of data.

**Comment by bmah888** [comment]
There doesn't appear to be an iperf3 bug here, closing.
