### ISSUE TITLE
Invalid bandwidth

### ISSUE THREAD

**Issue by ipetrushin** [esnet/iperf#843]
* Hardware:

* Operating system (and distribution, if any):
Linux srv1c 2.6.32-504.23.4.el6.centos.plus.x86_64 #1 SMP Wed Jun 10 13:09:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
CentOS 6

iperf version 2.0.5 (08 Jul 2010) pthreads

iperf -c iperf.mts-nn.ru -t 60 -i 1 -p 5201 
gives abnormal speed:
> Client connecting to iperf.mts-nn.ru, TCP port 5201
> TCP window size: 19.3 KByte (default)
> ------------------------------------------------------------
> [  3] local 192.168.0.10 port 58702 connected with 213.177.97.66 port 5201
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0- 1.0 sec  18014398509481962 KBytes  18014398509481962 KBytes/sec
> [  3]  1.0- 2.0 sec  18014398509481918 KBytes  18014398509481918 KBytes/sec
> [  3]  2.0- 3.0 sec  18014398509481916 KBytes  18014398509481916 KBytes/sec
> [  3]  3.0- 4.0 sec  18014398509481916 KBytes  18014398509481916 KBytes/sec
> [  3]  4.0- 5.0 sec  18014398509481918 KBytes  18014398509481918 KBytes/sec
> [  3]  5.0- 6.0 sec  18014398509481916 KBytes  18014398509481916 KBytes/sec
> [  3]  6.0- 7.0 sec  18014398509481916 KBytes  18014398509481916 KBytes/sec

This occurs only with given server, but from differetn machine everything goes OK:
Ubuntu 16.04, Linux teacher-MS-7A74 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

iperf version 2.0.10 (11 Aug 2017) pthreads
iperf -c iperf.mts-nn.ru -t 60 -i 1 -p 5201

> Client connecting to iperf.mts-nn.ru, TCP port 5201
> TCP window size: 85.0 KByte (default)
> ------------------------------------------------------------
> [  3] local 194.176.114.13 port 52156 connected with 213.177.97.66 port 5201
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0- 1.0 sec  1.25 MBytes  10.5 Mbits/sec
> [  3]  1.0- 2.0 sec  1.38 MBytes  11.5 Mbits/sec
> [  3]  2.0- 3.0 sec  1.62 MBytes  13.6 Mbits/sec
> [  3]  3.0- 4.0 sec  1.88 MBytes  15.7 Mbits/sec
> [  3]  4.0- 5.0 sec  1.88 MBytes  15.7 Mbits/sec
> [  3]  5.0- 6.0 sec  2.00 MBytes  16.8 Mbits/sec
> [  3]  6.0- 7.0 sec  1.12 MBytes  9.44 Mbits/sec
> [  3]  7.0- 8.0 sec  1.25 MBytes  10.5 Mbits/sec
>

**Comment by FuzzyStatic** [comment]
@ipetrushin this repo supports iperf3, it looks like you are using iperf2. Typically the binary name for iperf2 is `iperf` where the binary name for iperf3 (https://github.com/esnet/iperf) is `iperf3`.

Can you try installing iperf3 and running your tests again?
