### ISSUE TITLE
TCP fragmentation at server

### ISSUE THREAD

**Issue by jeter1112** [esnet/iperf#844]
Iperf3 support setting maximum fragmentation size at TCP sender. So my question is that how could I set fragmentation size at TCP Server. For example, TCP packets are wrapped with UDP packets when server sends packets to client in my project. The MTU of UDP is 1500B. Can I  set MSS at TCP Server with 1400 ?

**Comment by bmah888** [comment]
Use the `-M` option to iperf3, which allows you to set the MSS of the TCP connection.
