### ISSUE TITLE
iperf -c <server ip> -J --get-server-output does not format server output properly

### ISSUE THREAD

**Issue by iAn-Pinto** [esnet/iperf#845]
output above server_output_text is properly JSON object, but server_output_text is formatted for commandline display with /n (new line) character which require further parsing. Can this server_output_text be further formatted to proper JSON object format.
...
    server_output_text:
     'Accepted connection from 49.32.255.90, port 22753\n[  5] local 117.102.109.186 port 5203 connected to 49.32.255.90 port 26609\n[ ID] Interval           Transfer     Bandwidth\n[  5]   0.00-1.00   sec   154 KBytes  1.26 Mbits/sec                  \n[  5]   1.00-2.00   sec   464 KBytes  3.80 Mbits/sec                  \n[  5]   2.00-3.00   sec  18.3 KBytes   150 Kbits/sec                  \n[  5]   3.00-4.00   sec   646 KBytes  5.29 Mbits/sec                  \n[  5]   4.00-5.00   sec   345 KBytes  2.83 Mbits/sec                  \n[  5]   5.00-6.00   sec   527 KBytes  4.32 Mbits/sec                  \n[  5]   6.00-7.00   sec   523 KBytes  4.28 Mbits/sec                  \n[  5]   7.00-8.00   sec   559 KBytes  4.58 Mbits/sec                  \n[  5]   8.00-9.00   sec   523 KBytes  4.29 Mbits/sec                  \n[  5]   9.00-10.00  sec   376 KBytes  3.08 Mbits/sec                  \n' } ]

**Comment by bmah888** [comment]
Give the `-J` flag to the server when you start it up.
