### ISSUE TITLE
Different UDP behaviour when on Ethernet 100 vs Ethernet 1000

### ISSUE THREAD

**Issue by Dermiste** [esnet/iperf#847]
# Context
I want to test the maximum UDP throughput between two computers on different cat 5e & cat 6 cables and see how much is achievable. 
* Version of iperf3:
iperf 3.1.3
CYGWIN_NT-10.0 PCCR0016 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64

* Hardware:
Two PC dirrectly connected with a single Cat 6 Ethernet cable

* Operating system (and distribution, if any):
Windows 7 on server
Windows 10 on client

# Bug Report
Cable used is brand new Cat 6.
I force the ethernet connection speed at 100 MBits/s between the computers. I run the client in UDP mode using the following command:
`iperf3.exe -c 192.168.1.1 -f M -u -b 100m` 

I then set the speed at 1GBits/s and run the same command.

* Expected Behavior
Packet drop is the same

* Actual Behavior
Packet drop is different, I have none for the 100 MBits/s speed, and about 10% for the 1 GBits/s.

**Comment by bmah888** [comment]
Perhaps your end systems can't handle, for one reason or another, 1Gbps?  Note that we don't officially support iperf3 on Windows, but you could try increasing the socket buffer sizes with the `-w` parameter.  That's been shown to reduce UDP packet drops when running iperf3 on UNIX operating systems.

If you are trying to test the performance of different CAT5/CAT6 cables you need a cable tester not a software-based bandwidth tester.
