### ISSUE TITLE
iperf3 packet size (-l) is being changed 

### ISSUE THREAD

**Issue by inbalz1** [esnet/iperf#848]
# Context
i run " iperf3  -c 172.16.8.137 -p 8080  -i 1 -t 1 -f M -l 100 --no-delay  -V  --get-server-output"
and when checking in TCP dump im getting packets which arent in 100 B size.
what can be the problem?

![image](https://user-images.githubusercontent.com/46919925/53492563-d2a9cd80-3aa1-11e9-8dc3-747f7392ea77.png)

* Version of iperf3: iperf 3.1.3

* Operating system (and distribution, if any): Ubuntu 18.10 

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):
im checking iperf3 between 2 docker containers.

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate._

# Bug Report
 why not all the packets are 100B size?

_

**Comment by FuzzyStatic** [comment]
Those are acknowledgement packets, what are the size of the data packets?

**Comment by Safari77** [comment]
```write(x, y, 100)``` system call does not mean kernel sends out one TCP packet with size of 100 bytes.
Kernel has its own buffers, too, and also things like ```ethtool -k``` options affect what you see with packet capture programs.

**Comment by bmah888** [comment]
@FuzzyStatic makes a good point about the acknowledgement packets.  Is it possible that the data packets you are referrring to are the ones in the bottom half of your screenshot?

As @Safari77 has pointed out, the networking stack (including TCP) sets the size of packets that go out on the wire, which are not necessarily the same as the size of sends from the application (the latte is what you control with iperf3's `-l` parameter).  You might get more expected results by using the `-M` parameter to set the TCP MSS (maximum segment size) but that's not a guarantee either. TCP is a bytestream protocol, and doesn't preserve the size of send operations from the application.  This differs from UDP, which is a datagram protocol.

**Comment by bmah888** [comment]
There doesn't appear to be an iperf3 bug here.  Closing this bug...it can be reopened if necessary.
