### ISSUE TITLE
Iperf benchmark testing with CentOS7 

### ISSUE THREAD

**Issue by rashidbaloch** [esnet/iperf#849]
Hello Everyone, 
I am having difficulties in making the GRAPH for the Benchmark testing results.
I have achieved my desired results, But I want to present the results in GRAPH so that I can compare it with other tests which I have performed in other systems.
Please guide me on this matter. As it lacks documentation to achieve such tasks.

Thank You.

**Comment by bmah888** [comment]
This isn't an iperf3 support issue...you need to figure out how to parse the output of iperf3 (which you can do either with the user-readable output or the JSON output) and import that data into whatever graphing tool you are using.
