### ISSUE TITLE
How to define the UDP packet size?

### ISSUE THREAD

**Issue by TomHsiung** [esnet/iperf#861]
Hello,

It seems that the iperf3 UDP packets size by default is 8,000 bytes or more, with a testing bandwidth of 10Mbps. I know there is option like --set-mss to limit the packet size, but it is only applicable to TCP packets.

So is there any way to define the UDP packet size? I don't want the fragmentation issue interfere with the interpretation of the iperf3 outputs. Thank you.

Tom

**Comment by bmah888** [comment]
Use `--length` to explicitly set the size of UDP packets.  8000 bytes as a default send size was way too large because it results in IP fragmentation (one notable exception is that of network paths that support Ethernet jumbo frames from end-to-end).  The default was changed in iperf-3.1.5 to behave thusly:
```
  * iperf3 now chooses a more sane default UDP send size (#496, #498).
    The former default (8KB) caused IP packet fragmentation on paths
    having smaller MTUs (including any Ethernet network not configured
    for jumbo frames).  This could have effects ranging from increased
    burstiness, to packet loss, to complete failure of the test.
    iperf3 now attempts to use the MSS of the control connection to
    determine a default UDP send size if no sending length was
    explicitly specified with --length.
```

**Comment by TomHsiung** [comment]
Thanks, the --length option works. I like the iperf3 tool. Really useful to access network quality.

Tom

**Comment by socketpair** [comment]
A couple of words: In order to send IPv4 packet of length 1500 you probably want `--length 1472`.

**Comment by MuhammadMunir12** [comment]
@bmah888  @socketpair What length is to set for packet sizes of length 9000 Bytes in case of UDP? `--length 1472` is defult for UDP. For different packet sizes do we need to update --length parameter every time we change the packet size?
