### ISSUE TITLE
Make one-shot mode only count authenticated requests

### ISSUE THREAD

**Issue by mfeit-internet2** [esnet/iperf#864]
# Enhancement Request

* Current behavior - Server with the `-1` switch in effect exits after one connection even if authentication is being used and the request was never successfully authenticated.

* Desired behavior - Server with the `-1` switch in effect exits after it has run a test for an authenticated requester.  Unauthenticated requests send the server back to listen for the next one.

* Implementation notes - I'd have no problem if this were done with a separate switch to preserve the current behavior.

The use case for this is a future enhancement to the pScheduler iperf3 plugin that will use authentication to prevent third parties from hijacking a server which has been started to service a specific client.  See https://github.com/perfsonar/pscheduler/issues/836.

**Comment by bmah888** [comment]
This sounds like a reasonable thing to do.  Thinking out loud:

At the moment I'm not sure which is the best way to implement...the part that implements the one-shot logic is in `run()` in `main.c.` but the results of failed authentication are first seen in `test_is_authorized`, which is called from `iperf_exchange_parameters()`, which is called from `iperf_run_server()`. Right now the internal APIs don't have the granularity needed to express an authentication error (or other kind of failure for which we should restart a one-shot test) versus some other kind of problem, so we need to have some kind of conduit (that is preferably not a global variable of some kind) for passing this information.

Love this interaction between features.
