### ISSUE TITLE
Bind to interface with client

### ISSUE THREAD

**Issue by shawnl** [esnet/iperf#865]
# Context

* Version of iperf3:
iperf 3.6 (cJSON 1.5.2)

* Hardware:
model		: IBM pSeries (emulated by qemu)

* Operating system (and distribution, if any):
Linux test-wireguard 4.19.0-5-powerpc64le #1 SMP Debian 4.19.37-1 (2019-05-05) ppc64le

# Enhancement Request

* Current behavior

can bind for server, but not client.

* Desired behavior
Force traffic to go out a certain interface with client

* Implementation notes
I am trying to benchmark wireguard through localhost, but I cannot with iperf3 because i cannot specify the client interface so that the traffic goes through wireguard,

**Comment by jonesmz** [comment]
I'm also experiencing this issue on OpenWRT 18.06.0

I tell iperf3 to use the specific ipaddress that I want it to use (my wifi connection, in this case), and it claims to be using it, but is obviously not since it's getting speeds far higher than wifi should be able to use.

If I unplug the ethernet cable, and run the command again, I get significantly lower speeds.

What debugging information can I provide?

**Comment by shawnl** [comment]
@jonesmz You can work around this with network namespaces, but it isn't ideal. (and it works better for my use case than yours, as an interface can only be in one network namespace at a time)

**Comment by shawnl** [comment]
@jonesmz There is no debug information to provide. The feature just doesn't exist. While it will require reading up on the APIs and knowing some C, this feature is small enough that it could be implemented by someone without much programming experience. If you do decide to work on it, ping me when you submit a pull request and I will review it.

**Comment by jonesmz** [comment]
The feature may not exist, but iperf3 --help clearly says that it does, for both client, and also server :(

**Comment by shawnl** [comment]
@jonesmz that is a differn't feature. That is the address passed to `bind()` for the server, not binding to an interface for outbound. The latter is a feature rarely useful outside of networking stuff.

You can also work around this problem with very complicated networking rules which I don't understand.

**Comment by shawnl** [comment]
@jonesmz What we want is `SO_BINDTODEVICE`

**Comment by jonesmz** [comment]
Well, I think we may be talking past each other here.

Here's the output from iperf3 --help.

```
Server or Client:
  -p, --port      #         server port to listen on/connect to
  -f, --format   [kmgtKMGT] format to report: Kbits, Mbits, Gbits, Tbits
  -i, --interval  #         seconds between periodic throughput reports
  -F, --file name           xmit/recv the specified file
  -A, --affinity n/n,m      set CPU affinity
  -B, --bind      <host>    bind to the interface associated with the address <host>
```

If -B is not supported in the client, then it should be moved to the server specific section of the --help output.

If it's supposed to be used with the client mode, why doesn't it work?

You say it doesn't work because the feature doesn't exist in the iperf3 codebase. If that's the case, then the output from --help should be fixed to properly reflect the supported features.

**Comment by bmah888** [comment]
Out of curiosity, if you use `-B` on the client, do you actually see the control and test traffic going over the correct interfaces? (Say with tcpdump?)  `-B` is supposed to work on the client side.  I haven't put together a proper test environment for this but in some extremely limited testing on my laptop I haven't found any obvious failures yet.

**Comment by bmah888** [comment]
`-B` works for both the client and server side on perfSONAR, which was the original consumer of iperf3.  I'm going to close this issue for now.

**Comment by geerlingguy** [comment]
Just wanted to mention that it seems like if I have two interfaces configured on my Raspberry Pi, then `--bind` doesn't seem to allow me to specify an interface. The first interface (e.g. `eth0` even if I bind to the IP of `eth1`) is always chosen.

**Comment by bmah888** [comment]
> Just wanted to mention that it seems like if I have two interfaces configured on my Raspberry Pi, then `--bind` doesn't seem to allow me to specify an interface. The first interface (e.g. `eth0` even if I bind to the IP of `eth1`) is always chosen.
> 
> Tested with both iperf3 3.6 from the Pi OS repo and a source install.

@geerlingguy Try `--bind` and `--bind-dev` on a relatively recent tip-of-master build (for example `--bind 192.168.2.1 --bind-dev eth1`). #1089 and #1097 have more information.

**Comment by geerlingguy** [comment]
@bmah888 - Oh, thanks! I will try that out in my next round of testing!

**Comment by nyrahul** [comment]
> > Just wanted to mention that it seems like if I have two interfaces configured on my Raspberry Pi, then `--bind` doesn't seem to allow me to specify an interface. The first interface (e.g. `eth0` even if I bind to the IP of `eth1`) is always chosen.
> > Tested with both iperf3 3.6 from the Pi OS repo and a source install.
> 
> @geerlingguy Try `--bind` and `--bind-dev` on a relatively recent tip-of-master build (for example `--bind 192.168.2.1 --bind-dev eth1`). #1089 and #1097 have more information.

This works.
