### ISSUE TITLE
NULL settings inside iperf_check_throttle

### ISSUE THREAD

**Issue by Karry** [esnet/iperf#876]
Hi folks. 

# Context

I was investigating "Bad file descriptor" issue with recent iperf3 (build from master few days ago), I had iperf3 server opened in the gdb without touching process memory, I just put breakpoints to multiple places, run iperf client from different computer and after the test, server crashed... 

* Version of iperf3:
3.6+ build from master few days ago, commit 61b82c0b25052364bae99f83a583ab7c7f5f2d2d

* Hardware:
x86_64, virtual computer

* Operating system (and distribution, if any):
Linux, CentOS 7 (3.10.0-514.el7.x86_64)

# Few details from gdb:
```
(gdb) run  -s -p 666 --interval 60 
Starting program: /opt/iperf-upstream/bin/iperf3 -s -p 666 --interval 60

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bc2677 in iperf_check_throttle (sp=0x604210, nowP=<optimized out>) at iperf_api.c:1352
1352        if (bits_per_second < sp->test->settings->rate) {


(gdb) bt full
#0  0x00007ffff7bc2677 in iperf_check_throttle (sp=0x604210, nowP=<optimized out>) at iperf_api.c:1352
        temp_time = {secs = 905, usecs = 5}
        seconds = <optimized out>
        bits_per_second = <optimized out>
        nowP = <optimized out>
        sp = 0x604210
#1  0x00007ffff7bcfbac in tmr_run (nowP=nowP@entry=0x7fffffffe000) at timer.c:191
        now = {secs = 4765240, usecs = 437456}
        t = 0x6043d0
        next = 0x0
#2  0x00007ffff7bcb90c in iperf_run_server (test=test@entry=0x603010) at iperf_server_api.c:650
        result = <optimized out>
        s = <optimized out>
        send_streams_accepted = 1
        rec_streams_accepted = 1
        streams_to_send = 1
        streams_to_rec = 1
        saved_errno = <optimized out>
        read_set = {__fds_bits = {0 <repeats 16 times>}}
        write_set = {__fds_bits = {0 <repeats 16 times>}}
        sp = <optimized out>
        now = {secs = 4765240, usecs = 437456}
        timeout = <optimized out>
        flag = -1
#3  0x0000000000400f23 in run (test=test@entry=0x603010) at main.c:152
        rc = <optimized out>
#4  0x0000000000400ce7 in main (argc=6, argv=0x7fffffffe288) at main.c:107
        test = 0x603010

(gdb) frame 0
#0  0x00007ffff7bc2677 in iperf_check_throttle (sp=0x604210, nowP=<optimized out>) at iperf_api.c:1352
1352        if (bits_per_second < sp->test->settings->rate) {
(gdb) print sp
$1 = (struct iperf_stream *) 0x604210
(gdb) print sp->test
$2 = (struct iperf_test *) 0x603810
(gdb) print sp->test->settings
$3 = (struct iperf_settings *) 0x0
```

I saved coredump, so I can provide more information if it will be useful...

Lukas

**Comment by bmah888** [comment]
Thanks for the report.  This is the first I've heard of a problem like this...specifically I tried for a few minutes to recreate the problem and could not (also we have not seen anything like this on perfSONAR nodes, many of which run iperf-3.6).  It looks like you're running the server side under GDB to get this information.  Can you say what were the client side parameters?

**Comment by Karry** [comment]
I believe that client parameters was: `iperf3 -c sky-iperf-test-001.prg5.ff.avast.com  -t 900 -p 5201 -l60 -b 0.5M --interval 60 --version4 --bidir`

Yes, I was running server in gdb. I am not able to reproduce this crash again :-/ But I can send you coredump and binaries if you think that it would be useful. Question is how many energy you want to spend  with it...

**Comment by bmah888** [comment]
Thanks for the parameters.  I was hoping you had some weirdo flag that would trigger something, but your client command-line is pretty close to what I was trying yesterday.  I'm going to keep this issue open for now, but it doesn't feel like I have a lot to go on at the moment.

**Comment by bmah888** [comment]
I'm going to close this issue for now.  If it shows up in force again, we can re-open it.
