### ISSUE TITLE
v3.6: arbitrary connection to the iperf's port can block access

### ISSUE THREAD

**Issue by asy972** [esnet/iperf#878]
iperf 3.6 (cJSON 1.5.2)
ALT Linux p8

# Bug Report

* Expected Behavior
Terminate a poor connection as soon as possible

* Actual Behavior
A poor connection blocks server's operation for a long time

* Steps to Reproduce
1. Establish the connection. For example: telnet <server's ip> 5201
2. Try to run the test (from another host or console): iperf3 -c <server's ip>

**Comment by bmah888** [comment]
This is the same as issue #788.
