### ISSUE TITLE
Parallel UDP Streams

### ISSUE THREAD

**Issue by asafshakedverint** [esnet/iperf#894]
Hi,

Does parallel client streams supposed to work on UDP, using latest v3.1.3 on Windows Server 2016 ?

_iperf3 -s
iperf3 -u -c 127.0.0.1 -b 100M -l 1400 -t 60 -P 2_

Unlike TCP that works fine, when adding _-P n_ param to UDP, client execution won’t start

BTW, please notice _iperf-dev@google-groups.com_ doesn't work

Thanks,

Asaf

**Comment by bmah888** [comment]
Please note that Windows is not an officially supported platform, although some users have been able to compile it under Cygwin.  If you find binaries for Windows on the Internet, they didn't come from ESnet, and we can't provide support for it.

(As a side note, 3.1.3 is quite old.)

**Comment by bmah888** [comment]
PS.  Thanks for pointing out the error in the domain name.  Amazing that nobody noticed this for a couple years.

**Comment by asafshakedverint** [comment]
NP... It says to email there for questions before posting issues :)

About my issue, I'm still wondering whether it's expected to work, let's say if it were on Linux ?
