### ISSUE TITLE
Unable to test Network Performance using Iperf3 on AWS EC2

### ISSUE THREAD

**Issue by khalilmebarkia** [esnet/iperf#896]
I aim to test my Network Performance using **Iperf3** on *AWS EC2* where I have 2 Amazon Linux 2 AMI CentOS I**D_LIKE="centos rhel fedora"** in 2 different VPCs according to this topology in which there are 4 *CSR 1000v Routers* deployed and **Segment Routing** enabled in which the **Segment Routing Headend** is *R1* and the destination is *R3*.

I aim to send iperf traffic from Endpoint1(Client) to Endpoint2 (Server) with the following SR path = {R1, R2, R3, R4, R3, R2, R1, R2, and R3}.

[![enter image description here][1]][1]

I have a static route between the Endpoints and the router which is attached to. Therefore, I am being able to ping the other endpoint.

    sudo route add -net 172.2.1.0 netmask 255.255.255.240 gw 172.0.1.8
    sudo route add -net 172.0.1.0 netmask 255.255.255.240 gw 172.2.1.4

The problem I'm having when I try to test the Network Performance using **Iperf3** is that the traffic is not being sent to other point at all according to the server report.

**On Endpoint2:** 

    [ec2-user@ip-172-2-1-10 ~]$ iperf3 -s -p 50001  

**On Endpoint1:** 

    [ec2-user@ip-172-0-1-8 ~]$ sudo iperf3 -c 172.2.1.10 -p 50001 -u 

and here's the server's report:

    Server listening on 50001
    -----------------------------------------------------------
    Accepted connection from 172.0.1.8, port 52040
    [  5] local 172.2.1.11 port 50001 connected to 172.0.1.4 port 40882
    [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
    [  5]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    [  5]  10.00-10.05  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  
    - - - - - - - - - - - - - - - - - - - - - - - - -
    [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
    [  5]   0.00-10.05  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  

As well as the client:

    Connecting to host 172.2.1.10, port 50001
    [  4] local 172.0.1.4 port 40882 connected to 172.2.1.10 port 50001
    [ ID] Interval           Transfer     Bandwidth       Total Datagrams
    [  4]   0.00-1.00   sec   122 KBytes  1.00 Mbits/sec  14  
    [  4]   1.00-2.00   sec   122 KBytes  1.00 Mbits/sec  14  
    [  4]   2.00-3.00   sec   131 KBytes  1.07 Mbits/sec  15  
    [  4]   3.00-4.00   sec   131 KBytes  1.07 Mbits/sec  15  
    [  4]   4.00-5.00   sec   122 KBytes  1.00 Mbits/sec  14  
    [  4]   5.00-6.00   sec   131 KBytes  1.07 Mbits/sec  15  
    [  4]   6.00-7.00   sec   131 KBytes  1.07 Mbits/sec  15  
    [  4]   7.00-8.00   sec   122 KBytes  1.00 Mbits/sec  14  
    [  4]   8.00-9.00   sec   131 KBytes  1.07 Mbits/sec  15  
    [  4]   9.00-10.00  sec   131 KBytes  1.07 Mbits/sec  15  
    - - - - - - - - - - - - - - - - - - - - - - - - -
    [ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
    [  4]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.000 ms  0/0 (0%)  
    [  4] Sent 0 datagrams
         

The traffic is not being sent at all. What would be the reason?

P.S. I provided here a UDP test, on the other hand, it did not work with TCP as well.

  [1]: https://i.stack.imgur.com/1G9w9.png

**Comment by gkalwani** [comment]
Hi,

Were you able to fix the issue?
Please advise.

Thanks!!
Gaurav Kalwani

**Comment by bmah888** [comment]
This really looks like a firewall (possibly host-based-firewall) issue within AWS EC2.  Closing this issue, please re-open if there's some evidence to the contrary.
