### ISSUE TITLE
iperf in android

### ISSUE THREAD

**Issue by xudongMk** [esnet/iperf#900]
I got an IOException Cannot run program “xxx/iperf3” : error=13, Permission denied in android program.
but i already run the chmod 744 command for iperf3 file.

**Comment by bmah888** [comment]
We don't officially support iperf3 on Android.  However, just based on the information you gave, you probably want to set file mode 755 instead...the command you gave didn't set all the execute bits.

**Comment by nilin2008** [comment]
I needed to call iperf3 (3.7) from java (apk) via ProcessBuilder.
In android 8 (and probably in 7) $TMPDIR = /data/local/tmp. This code did not work for me. I just commented too much for the test iperf_api.c:

 char template[1024];
    //if (test->tmp_template) {
    //    snprintf(template, sizeof(template) / sizeof(char), "%s", test->tmp_template);
    //} else {
    //    //find the system temporary dir *unix, windows, cygwin support
    //char* tempdir = getenv("TMPDIR");
    //    if (tempdir == 0){
    //        tempdir = getenv("TEMP");
    //    }
    //    if (tempdir == 0){
    //        tempdir = getenv("TMP");
    //    }
    //    if (tempdir == 0){
    char* tempdir = "/data/data/iperf.proj/cache";
    //    }
    snprintf(template, sizeof(template) / sizeof(char), "%s/iperf3.XXXXXX", tempdir);
    //}

where "iperf.proj" - name of my app.
I suspect that you can also specify the application directory "/data/data/iperf.proj", not "cache" folder

**Comment by hardikbhalodi** [comment]
I build IPerf3 shared library for Android and its working but when i do this command
"iperf3 -c ping-90ms.online.net" It's Blocking until complete output does not fetch and printing all lines at once but In Ubuntu i installed IPerf3 and its working asynchronously.

Also with this command "iperf3 -s" nothing printed! it should print something
"Server listening on 5201" like it does in Ubuntu

any help on this?

**Comment by hugoinfante83** [comment]
> I needed to call iperf3 (3.7) from java (apk) via ProcessBuilder.
> In android 8 (and probably in 7) $TMPDIR = /data/local/tmp. This code did not work for me. I just commented too much for the test iperf_api.c:
> 
> char template[1024];
> //if (test->tmp_template) {
> // snprintf(template, sizeof(template) / sizeof(char), "%s", test->tmp_template);
> //} else {
> // //find the system temporary dir _unix, windows, cygwin support //char_ tempdir = getenv("TMPDIR");
> // if (tempdir == 0){
> // tempdir = getenv("TEMP");
> // }
> // if (tempdir == 0){
> // tempdir = getenv("TMP");
> // }
> // if (tempdir == 0){
> char* tempdir = "/data/data/iperf.proj/cache";
> // }
> snprintf(template, sizeof(template) / sizeof(char), "%s/iperf3.XXXXXX", tempdir);
> //}
> 
> where "iperf.proj" - name of my app.
> I suspect that you can also specify the application directory "/data/data/iperf.proj", not "cache" folder



> I needed to call iperf3 (3.7) from java (apk) via ProcessBuilder.
> In android 8 (and probably in 7) $TMPDIR = /data/local/tmp. This code did not work for me. I just commented too much for the test iperf_api.c:
> 
> char template[1024];
> //if (test->tmp_template) {
> // snprintf(template, sizeof(template) / sizeof(char), "%s", test->tmp_template);
> //} else {
> // //find the system temporary dir _unix, windows, cygwin support //char_ tempdir = getenv("TMPDIR");
> // if (tempdir == 0){
> // tempdir = getenv("TEMP");
> // }
> // if (tempdir == 0){
> // tempdir = getenv("TMP");
> // }
> // if (tempdir == 0){
> char* tempdir = "/data/data/iperf.proj/cache";
> // }
> snprintf(template, sizeof(template) / sizeof(char), "%s/iperf3.XXXXXX", tempdir);
> //}
> 
> where "iperf.proj" - name of my app.
> I suspect that you can also specify the application directory "/data/data/iperf.proj", not "cache" folder


Any luck with the cache path for android (apk)?
