### ISSUE TITLE
iperf3(SCTP):error - unable to connect stream :connection refused

### ISSUE THREAD

**Issue by Edmondxu** [esnet/iperf#902]
server----------------------
iperf3 -s -p 12345 -i 1

client------------------------
iperf3 -c 192.168.1.10 -p 12345 --sctp -V

Operating on the same host, iperf can be connected normally

The two hosts are connected through the network. Similar instructions can be tested under the TCP protocol and UDP protocol. The following problems arise under the SCTP protocol:

iperf3:error - unable to connect stream :connection refused

**Comment by bmah888** [comment]
What version of iperf?  What operating system?  Do you know if SCTP functionality requires a kernel module to be enabled, and if so, did you do that?  Any host-based firewall that might need to be adjusted?

I just tested this successfully on a CentOS 7 (x86_64) VM, with tip-of-master sources.
```
bmah-centos7:iperf% src/iperf3 --sctp --client localhost -p 12345
Connecting to host localhost, port 12345
[  5] local ::1 port 33774 connected to ::1 port 12345
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   576 KBytes  4.71 Mbits/sec
[  5]   1.00-2.00   sec   384 KBytes  3.15 Mbits/sec
[  5]   2.00-3.00   sec   576 KBytes  4.72 Mbits/sec
[  5]   3.00-4.00   sec   384 KBytes  3.15 Mbits/sec
[  5]   4.00-5.00   sec   576 KBytes  4.71 Mbits/sec
[  5]   5.00-6.00   sec   384 KBytes  3.14 Mbits/sec
[  5]   6.00-7.00   sec   576 KBytes  4.73 Mbits/sec
[  5]   7.00-8.00   sec   384 KBytes  3.15 Mbits/sec
[  5]   8.00-9.00   sec   512 KBytes  4.19 Mbits/sec
[  5]   9.00-10.00  sec   256 KBytes  2.10 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  4.50 MBytes  3.77 Mbits/sec                  sender
[  5]   0.00-10.04  sec  4.44 MBytes  3.71 Mbits/sec                  receiver

iperf Done.
```

**Comment by bmah888** [comment]
Closing for lack of information.

**Comment by jackie-lee** [comment]
@bmah888 
I run into the same error on ubuntu 16.04(x86_64). SCTP kernel was enabled. When capture sctp segment, the client send a [INIT], the server answer with [ABOIRT].

AND, i notice that the captured segment show the the client connect port NOT the same as the server show.

mec@mec1:~/git/iperf$ iperf3 --sctp -c 192.168.110.1
Connecting to host 192.168.110.1, port 5201
iperf3: error - unable to connect stream: Connection refused

mec@mec2:~$ iperf3 -s
-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.110.110, port **39238**
iperf3: the client has unexpectedly closed the connection
-----------------------------------------------------------
Server listening on 5201

16:00:15.889139 IP 192.168.110.110.**37617** > 192.168.110.1.5201: sctp (1) [INIT] [init tag: 2956799752] [rwnd: 106496] [OS: 10] [MIS: 65535] [init TSN: 232454744] 
16:00:15.889205 IP 192.168.110.1.5201 > 192.168.110.110.**37617**: sctp (1) [ABORT]

mec@mec2:~$ lsmod |grep sctp
sctp                  258048  2
libcrc32c              16384  2 sctp,raid456

mec@mec1:~/git/iperf$ lsmod |grep sctp
sctp                  258048  2
libcrc32c              16384  2 sctp,raid456
