### ISSUE TITLE
I have a question about bandwidth setting implement.

### ISSUE THREAD

**Issue by sunnlo** [esnet/iperf#904]
Hi,

I have a little confused about the implement of bandwidth setting. After checking the code, I found Iperf use SO_MAX_PACING_RATE socket option to set bandwidth, and this socket option needs FQ scheduler enabled. But my experiment shows that bandwidth setting on Iperf can work well when I using pfifo_fast rather than FQ. Why this happened?

Thanks,
Qian

**Comment by bmah888** [comment]
There are two mechanisms for setting bandwidth...iperf3 can use per-socket fair queueing on systems that support it, or it can internally pace itself.  You use the `--fq-rate` for the per-socket fair queueing, and `--bitrate` for internal pacing.
