### ISSUE TITLE
iperf3.1.3 and iperf(2.0.10) both having inconsistent UDP throughput measurement and huge packet loss #5

### ISSUE THREAD

**Issue by ChowdaryDinesh** [esnet/iperf#906]
Hi ,
The iperf3(3.1.3) and iperf(2.0.10) data varies significantly. Iperf has no/less packetloss which maps with tcpdump/tshark data while iperf3 data is no match and describes there is a huge packet loss mainly when we test the bidirectional data speed.

Additional info:
We see the packet loss is huge in case of data coming from server(in bidirectional speed test).
This should be addressed in the up coming versions of iperf3.

**Comment by bmah888** [comment]
iperf-3.1.3 is quite old now (mid 2016).  Newer versions have made a number of improvements that improve the transmission of UDP test data, pacing in general, and statistics reporting.  Please try with a more recent version of iperf3 (3.7 is current as of this writing) and see if that fixes the problems you are seeing.  If not, please follow the directions that you should have seen when submitting this issue, regarding information that is necessary to help troubleshoot your problem.

**Comment by bmah888** [comment]
Closing for lack of information.
