### ISSUE TITLE
Default window size - iperf vs iperf3 (3.17)

### ISSUE THREAD

**Issue by pradeepspa2** [esnet/iperf#912]
Hello,
I am trying to find the default window size of iperf3 comparing iperf which i need to troubleshoot my udp packet loss. I tried running iperf3 with "--debug" flag but that doesnt give me any window size. Can someone help me guiding a right place to look?

`[root@pradeeptestvm ~]# iperf3 -c server -u -l1300 -b100M  --debug
send_parameters:
{
        "udp":  true,
        "omit": 0,
        "time": 10,
        "parallel":     1,
        "len":  1300,
        "bandwidth":    100000000,
        "client_version":       "3.1.7"
}
Connecting to host server, port 5201
SNDBUF is 212992, expecting 0
RCVBUF is 212992, expecting 0
Setting application pacing to 12500000
[  4] local client port 47039 connected to server port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec  10.8 MBytes  90.6 Mbits/sec  8709
[  4]   1.00-2.00   sec  11.9 MBytes  99.8 Mbits/sec  9598
[  4]   2.00-3.00   sec  11.9 MBytes   100 Mbits/sec  9615
[  4]   3.00-4.00   sec  11.9 MBytes   100 Mbits/sec  9619
[  4]   4.00-5.00   sec  11.9 MBytes   100 Mbits/sec  9615
[  4]   5.00-6.00   sec  11.9 MBytes   100 Mbits/sec  9611
[  4]   6.00-7.00   sec  11.9 MBytes   100 Mbits/sec  9616
[  4]   7.00-8.00   sec  11.9 MBytes   100 Mbits/sec  9616
[  4]   8.00-9.00   sec  11.9 MBytes   100 Mbits/sec  9615
send_results
{
        "cpu_util_total":       4.265689,
        "cpu_util_user":        0.733966,
        "cpu_util_system":      3.581423,
        "sender_has_retransmits":       0,
        "streams":      [{
                        "id":   1,
                        "bytes":        123797700,
                        "retransmits":  -1,
                        "jitter":       0,
                        "errors":       0,
                        "packets":      95229
                }]
}
get_results
{
        "cpu_util_total":       0.445476,
        "cpu_util_user":        0.040279,
        "cpu_util_system":      0.400782,
        "sender_has_retransmits":       -1,
        "streams":      [{
                        "id":   1,
                        "bytes":        55919500,
                        "retransmits":  -1,
                        "jitter":       0.000009,
                        "errors":       52211,
                        "packets":      95226
                }]
}
[  4]   9.00-10.00  sec  11.9 MBytes   100 Mbits/sec  9615
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec   118 MBytes  99.0 Mbits/sec  0.009 ms  52211/95226 (55%)
[  4] Sent 95226 datagrams

iperf Done.
`

**Comment by bmah888** [comment]
The term "window" is a little difficult to apply to UDP tests, so I'm going to take a couple guesses at what you're looking for.

If you want to know the UDP payload size, it's the "len" parameter in the send parameters (1300 in your example).

If you want to know the socket buffer sizes, those are SNDBUF and RCVBUF, which are 212992 in your example.
