### ISSUE TITLE
UDP issue iperf3

### ISSUE THREAD

**Issue by embeddedRSA** [esnet/iperf#916]
# Context

* Version of iperf3: 3.1.3

* setup
pc running ubuntu (client)
rpi model 3 b running rasbian.

I'm running over a thread network (open thread), verified to work with ping and iperf3 -tcp test
# Bug Report

UDP notworking, data seems to be received, but received bytes are listed as 0. No jitter is visible either. 

* Expected Behavior
Server should output a BW and Jitter attribute !=0 

* Actual Behavior
It seems as if the messages in fact are received, since the results are listed syncronous wHEN the client is transferring data.
**I get the following client output:**

` root@f292c2ddd84e:/app/borderrouter# iperf3 -c
fd11:22::e9:c314:9668:b4d7 -u --get-server-output
Connecting to host fd11:22::e9:c314:9668:b4d7, port 5201
[  4] local fd11:22::b441:551f:17d1:bdad port 59867 connected to
fd11:22::e9:c314:9668:b4d7 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   1.00-2.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   2.00-3.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   3.00-4.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   4.00-5.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   5.00-6.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   6.00-7.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   7.00-8.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   8.00-9.00   sec   128 KBytes  1.05 Mbits/sec  16
[  4]   9.00-10.00  sec   128 KBytes  1.05 Mbits/sec  16
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter Lost/Total
Datagrams
[  4]   0.00-10.00  sec  1.25 MBytes  1.05 Mbits/sec  0.000 ms 0/0 (0%)
[  4] Sent 0 datagrams

Server output:
Accepted connection from fd11:22::b441:551f:17d1:bdad, port 51606
[  5] local fd11:22::e9:c314:9668:b4d7 port 5201 connected to
fd11:22::b441:551f:17d1:bdad port 59867
[ ID] Interval           Transfer     Bandwidth       Jitter Lost/Total
Datagrams
[  5]   0.00-1.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]  10.00-11.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]  11.00-12.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]  12.00-13.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]  13.00-14.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]  14.00-15.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]  15.00-16.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]  16.00-17.00  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
[  5]  17.00-17.50  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter Lost/Total
Datagrams
[  5]   0.00-17.50  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%) `

* Steps to Reproduce

run the following line:
**client:**

`iperf3 - c [IPv6-addr] -u --get-server-output 
`
**server**
`perf3 -s`

* Possible Solution
no idea
_Please submit patches or code changes as a pull request._

**Comment by bmah888** [comment]
Are you sure that UDP packets can get between the two hosts?  It looks like the control connection gets set up (which goes over TCP), but the actual test packets (UDP because you specified `-u` as a command-line flag) didn't arrive at the server.

Perhaps you should try using tcpdump(8) to see if the packets actually show up on the server side?

I'm really not sure how Open Thread relates to iperf3.

**Comment by embeddedRSA** [comment]
i used tcpdump as suggested and identified a few packets arriving sever-side. Lowering the bandwidth to 100k and message length to 1k seems to have fixed the issue at hand.

Thanks for the support, i appreciate it.
