### ISSUE TITLE
Why default packet size is less in udp than tcp in iperf3?

### ISSUE THREAD

**Issue by sarashakeri** [esnet/iperf#918]
As I see the tcp defualt packet size is 128KB whereas the UDP default is just 8KB, and when I measure the maximum badnwidth of tcp and udp, the udp bandwidth is much lower than tcp in iperf3. I believe the reason lays in the limitation in the maximum packet size of UDP. So, why the udp packet size is much smaller than tcp, here?

* Version of iperf3: iperf 3.1.3

* Operating system (and distribution, if any): Ubuntu 18

**Comment by bmah888** [comment]
There are a few points here:

You're running a very old version of iperf3.  At some between then and the current version 3.7, we made some changes that improved UDP performance.

The default send size for TCP is indeed 128K but that doesn't translate to an IP packet size (the maximum size of an IP packet is 64K, and is almost always much less due to the limits imposed by the physical layer, for example 1500 for typical Ethernet networks or 9100+ for Ethernet with jumbo frames).  The send size for UDP does really determine the size of the underlying IP packet.  If you increase the send size for UDP tests to be larger than MTU of the path, the IP packets will get fragmented, which is also likely to make performance worse.

You might want to try increasing the socket buffer size, as that might improve the performance of UDP tests.

To help any further, I think I'd need to see the client and server command lines, as well as the output from both client and server.

**Comment by sarashakeri** [comment]
That is true for the fragmentation, however, I believe the lower packet size will increase the number of userspace-kernel space transitions. Below is the result of running iperf3:

```
sara@ovr-2:~$ iperf3 -c  " server address"  -u -b 0  --get-server-output
Connecting to host 145.100.132.197, port 5201
[  4] local 145.100.132.34 port 49987 connected to 145.100.132.197 port 5201
[ ID] Interval           Transfer     Bandwidth       Total Datagrams
[  4]   0.00-1.00   sec   415 MBytes  3.48 Gbits/sec  53060  
[  4]   1.00-2.00   sec   383 MBytes  3.21 Gbits/sec  49010  
[  4]   2.00-3.00   sec   387 MBytes  3.25 Gbits/sec  49520  
[  4]   3.00-4.00   sec   410 MBytes  3.44 Gbits/sec  52460  
[  4]   4.00-5.00   sec   387 MBytes  3.25 Gbits/sec  49560  
[  4]   5.00-6.00   sec   413 MBytes  3.46 Gbits/sec  52870  
[  4]   6.00-7.00   sec   398 MBytes  3.33 Gbits/sec  50880  
[  4]   7.00-8.00   sec   404 MBytes  3.39 Gbits/sec  51710  
[  4]   8.00-9.00   sec   329 MBytes  2.75 Gbits/sec  42150  
[  4]   9.00-10.00  sec   354 MBytes  2.98 Gbits/sec  45350  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec  3.79 GBytes  3.25 Gbits/sec  0.033 ms  254818/496565 (51%)  
[  4] Sent 496565 datagrams

Server output:
Accepted connection from 145.100.132.34, port 49438
[  5] local 145.100.132.197 port 5201 connected to 145.100.132.34 port 49987
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  13.6 MBytes   114 Mbits/sec  0.134 ms  110/1812 (6.1%)  
[  5]   1.00-2.00   sec   169 MBytes  1.42 Gbits/sec  0.023 ms  65615/87196 (75%)  
[  5]   2.00-3.00   sec   108 MBytes   906 Mbits/sec  0.135 ms  46534/60368 (77%)  
[  5]   3.00-4.00   sec   324 MBytes  2.72 Gbits/sec  0.037 ms  9790/51319 (19%)  
[  5]   4.00-5.00   sec   292 MBytes  2.45 Gbits/sec  0.052 ms  12134/49568 (24%)  
[  5]   5.00-6.00   sec   131 MBytes  1.10 Gbits/sec  0.013 ms  30557/47376 (64%)  
[  5]   6.00-7.00   sec   136 MBytes  1.14 Gbits/sec  0.034 ms  11229/28701 (39%)  
[  5]   7.00-8.00   sec   195 MBytes  1.64 Gbits/sec  0.022 ms  54601/79549 (69%)  
[  5]   8.00-9.00   sec   335 MBytes  2.81 Gbits/sec  0.018 ms  1507/44371 (3.4%)  
[  5]   9.00-10.00  sec   173 MBytes  1.45 Gbits/sec  0.018 ms  22672/44761 (51%)  
[  5]  10.00-10.04  sec  11.5 MBytes  2.37 Gbits/sec  0.033 ms  69/1544 (4.5%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec  0.033 ms  254818/496565 (51%)  
[SUM]  0.0-10.0 sec  34 datagrams received out-of-order
```

**Comment by bmah888** [comment]
Ah.  You're sending UDP at an unlimited rate, but UDP is a lossy protocol.  There is no guarantee of reliable delivery as there is with TCP.  So basically what you're testing is how fast packets can get dropped on the floor.  The actual usable bitrate looks like it's somewhere around 2Gbps, given your current command-lines (I'm looking at the bandwidths over the intervals on the server/receiver side).  It might help a bit to increase the socket buffers with the `-w` command-line flag.  But generally you don't want to do UDP with `-b 0`, the results aren't likely to be useful.

**Comment by tabeshforoughi** [comment]
Please explain why packet sizes 1152 and 1408 have lower UDP throughput than packets 640 and 896, please

**Comment by davidBar-On** [comment]
> Please explain why packet sizes 1152 and 1408 have lower UDP throughput than packets 640 and 896, please

More information is required to answer this: the command lines, the throughput and %lost packets in any case, network MTU, etc.

For example, if the MTU is 1,024, then packets with size 1152 or 1408 requires fragmentation (practically two packets are sent over the network), which may lead to lower throughput.

**Comment by tabeshforoughi** [comment]
Hi,
Thank you for your time,
Would you kindly send me a UDP code so I can use it for my command prompt for using different packet sizes, please
my TCP results are about 8.2 Gbp/s, so UDP should be a fraction more but it is only 4.1 Gbp/s.
Thank you for your time.
Tabesh

**Comment by davidBar-On** [comment]
Hi, to find the MTU between the client and server, use the **tracepath** command (assuming you are using Linux).  Then use the `-l` option run the UDP test with packet length that is not more then the MTU.  Also, you must limit the UDP sending rate using the `-b` option, since otherwise the client sending rate will be limited only by the machine resources (mainly CPU) and not by the network throughput.

E.g. if the MTU is 1024 bytes, then set he UDP packet length to 1000 by`-l 1000`.  If you want to test sending UDP with sending rate of 8Gbps, use `-b 8G`.  The full command will be `iperf3 -c <server ip> -l 1000 -b 8G`.

Note that trial and error is required for finding the UDP maximum rate, since as explained by @bmah888 in [this comment](https://github.com/esnet/iperf/issues/918#issuecomment-548975420) and as I explained above, UDP sending limit is not limited by the network performance.  In addition to the TCP rate, UDP **%lost** can be used to understand whether the rate is close to the maximum.  Around the maximum the lost rate is usually higher then zero but less then 10%.

**Comment by tabeshforoughi** [comment]
Hi Dave,
Happy New Year
Thank you for your instructions.
I will try it in the lab today.
Many thanks, regards
Tabesh

**Comment by tabeshforoughi** [comment]
Hi Dave
My server is server 22 and my client is windows 11.
Switch= 10G
NIC=10G
Media= copper
Does the same scenario apply?
Regards
Tabesh

**Comment by davidBar-On** [comment]
Hi Tabesh and happy new year. 
Yes, the same scenario applies.  What is important to determine is the PMTU (Path MTU).  Along the way from the client to the server, packets are fragmented according to the MTU.  E.g if PMTU is 1KB and you send 2KB packets, they will be split into 2 1K packets, which reduces the throughput.

From what I find, on Windows **Ping** command can be used to find the MTU.  See for example [https://www.pcwdld.com/ping-mtu](https://www.pcwdld.com/ping-mtu).

**Comment by tabeshforoughi** [comment]
Hi Mr. Dave
Thank you for the information.
So what do you think I must command for the evaluation of 10Gbp/s UDP throughput?
My TCP measurements are satisfactory.
is?
iperf3 -c <server ip> -l 1000 -b 8G. ok? or i must change it to 10G Please?
 
As an example
How do you set the MTU packet size for size 1408?
Knowing the maximum MTU for Ethernet Connection is 1500.
 
I'm so sorry for holding you up so much, but i need your help.
Best regards
Tabesh

**Comment by davidBar-On** [comment]
> `iperf3 -c <server ip> -l 1000 -b 8G`. ok? or i must change it to 10G Please?

This is o.k. as a start, but as I wrote above it is a trial and error to find the maximum UDP throughput for a specific packet size (`-l`).  I.e. you should run several tests each with different `-b` (e.g. 4G, 5G, 6G, 7G, 8G, 9G, 10G).  If you don't know the MTU, to find the best length you can also run tests with different `-l` (e.g. 512 600, 700, ... 1300, 1400, 1500).

Note that you should pay attention to the %lost as I explained above.

> How do you set the MTU packet size for size 1408?

You don't set MTU.  This is a network limitation.  You should find what it is for the path between the client and server.

> Knowing the maximum MTU for Ethernet Connection is 1500.

This is for Ethernet, but what is important is the IP MTU - the minimum allowed is 512.  It depends on the MTU used by the different switches, routers, etc. in the network path.

**Comment by tabeshforoughi** [comment]
Thanks for your explanations, sir.

**Comment by tabeshforoughi** [comment]
Dear Dave,
Would you guide me please.
Going to measure latency on port 8999 (Server)
My Client only starts the process and ends the process without printing any, as the results.
Would you please help me with the commands.
Regards
Tab

**Comment by davidBar-On** [comment]
Hello @tabeshforough, such questions should be opened as Discussions - use "new discussion" in [this site](https://github.com/esnet/iperf/discussions).

As for your question, it is strange that ther is no output from iperf3.  Use `-V -d` to get more information from iperf3.  `-p` is used to set the port (the same as for the server).  Example commands:
`iperf3 -c <server ip> -p 89999 -l 1000 -b 8G`
`iperf3 -c <server ip> -p 89999 -l 1000 -b 8G -V -d`

(Please send your response / further questions in a new discussion and not here. Thanks.)

**Comment by tabeshforoughi** [comment]
Please provide a command for measuring the RTT of TCP and UDP with IPV4 and IPV6 using D-ITG-2.8.1-r1023-Win.
Please mention how it can be for IPV4 or IPV6.
Many Thanks

**Comment by davidBar-On** [comment]
@tabeshforoughi, please resend this question a a new **discussion** item as explained above, and **not** as a comment to this issue.
