### ISSUE TITLE
Server is receiving packets but jperf is not showing any traffic

### ISSUE THREAD

**Issue by assafa-aeronautics** [esnet/iperf#925]
Hello
I am using jperf to test UDP traffic. I first run the client to sent UDP packets to a multicast address with a specific port. I then connect another PC to the other end of the network to monitor the packets. I set the jperf as SERVER with the above specific port and set to UDP but no statistics is shown. when I open WireShark on the active adapter I see the packets generated by the client. Firewall is off. all other network adapters are disabled. 
Please help

**Comment by bmah888** [comment]
jperf is a Java implementation of iperf2.  This GitHub project deals with iperf3.  Despite the similarity in name, they're completely separate programs.  You could try posting to the iperf-users list with your question.
