### ISSUE TITLE
Different versions of iperf 

### ISSUE THREAD

**Issue by tuanpm30** [esnet/iperf#927]
Hi 
im running example Lwip TCP perf server on zynq , on pc i run iperf 3.7 client but it should return "iperf3: error - unable to connect to server: Connection refused". 
I change port connect on exam code lwip TCP perf server 5001 to 5201, i run iperf again and it connected but they only sent a few messages then lost the connection. 
 
![image](https://user-images.githubusercontent.com/55055838/68008321-1ef08180-fcb1-11e9-82e8-7feacf5be64b.png)

how can i make it run correctly ? (by change code)
please guide me.
thank you.

**Comment by tuanpm30** [comment]
Hi 
im running example Lwip TCP perf server on zynq , on pc i run iperf 3.7 client but it should return "iperf3: error - unable to connect to server: Connection refused". 
I change port connect on exam code lwip TCP perf server 5001 to 5201, i run iperf again and it connected but they only sent a few messages then lost the connection. 
 
![image](https://user-images.githubusercontent.com/55055838/68008321-1ef08180-fcb1-11e9-82e8-7feacf5be64b.png)

how can i make it run correctly ? (by change code)
please guide me.
thank you.

**Comment by bmah888** [comment]
It looks like lwIP implements iperf2.  iperf2 and iperf3 aren't compatible.  Basically there isn't any way to make this work, sorry.
