### ISSUE TITLE
how to debug iperf source code

### ISSUE THREAD

**Issue by tuanpm30** [esnet/iperf#928]
hi team,
can you give me a guide for debug source code iperf? i complie iperf for Windows using Cygwin, and
tried to use esclipse c++, visual gdb (for debug source code) but they aren't working very well.
Thanks you.

**Comment by bmah888** [comment]
iperf3 is written in C, not C++, and we don't officially support the Windows platform.  I personally have no experience writing or debugging code under any Windows development environment.  You might get better luck asking on the iperf-users mailing list (some developers in the community have done work with Cygwin) or on a Windows development forum of some sort.
