### ISSUE TITLE
Query some Implementation details about iperf3.7

### ISSUE THREAD

**Issue by baolintian** [esnet/iperf#936]
Hi~
Recently I am doing some research about testing network.But when I use iperf3.7(the latest version on github). I have a detailed problem about iperf.
## System
Ubuntu 16.04

when I use the following command:
`iperf3 -c 192.168.179.131 -t 120 -i 1 -p 5001 -b 1m -u -l 1000`
and I capture the packet sent out NIC. I calculated the time interval with two adjacent packets and 90% of the intervals are 7-8 ms. It's quiet an ideal packet sending rate.
I define packet interval as the following formula: 
$$interval time = packet_{i} time stamp-packet_{i-1} time stamp$$
some interval examples:
``` 
7.9750976562
7.9819335938
7.9970703125
7.9809570312
7.9599609375
7.9951171875
7.9689941406
7.9699707031
7.9970703125
7.9599609375
7.9790039062
7.9299316406
7.9750976562
8.0449218750
7.9331054688
7.9580078125
7.9938964844
7.9650878906
7.9780273438
7.9780273438
7.9787597656
7.9780273438
7.9799804688
7.9780273438
7.9780273438
8.0141601562
8.0578613281
7.8730468750
7.9919433594
7.9609375000
7.9770507812
9.0141601562
7.9619140625
8.1330566406
7.8000488281
7.9777832031
```

When I use iperf 3.0.11 and use the same command.
  `iperf3 -c 192.168.179.131 -t 120 -i 1 -p 5001 -b 1m -u -l 1000`  
I capture every packet sent out NIC and iperf3 generates some large adjacent intervals about 100 ms. That's not quiet ideal for testing.
some interval examples: 
```
0.0520019531
0.0510253906
97.6030273438
0.1127929688
0.0541992188
0.0520019531
0.0520019531
0.0520019531
0.0520019531
0.0520019531
0.0520019531
0.0507812500
0.0520019531
0.0510253906
99.0690917969
0.1411132812
0.0559082031
0.0820312500
0.0778808594
```

I have detailedly read the codes between version 3.7+ and 3.0.11, but I can't get the core improvement of 3.7+.

Further works can be improved. When I use the following command in 3.7:
iperf3 -c 192.168.179.131 -t 120 -i 1 -p 5001 -b 10m -u -l 1000
and capture the packet. It can't send out even packet interval again. And I really want to improve this work.
some interval examples:
```
3.9392089844
0.0009765625
0.0009765625
0.0000000000
0.0000000000
3.9460449219
0.0009765625
0.0009765625
0.0000000000
3.9990234375
0.0009765625
0.0000000000
0.0009765625
0.0000000000
3.8540039062
```
Why iperf3.7 can't generate even packet interval under such condition?

Really hope to learn the improvement between `iperf3.7` and `iperf3.0.11` with this aspect. 
Thanks~~

**Comment by bmah888** [comment]
Please refer to the release notes for iperf3:

https://github.com/esnet/iperf/blob/master/RELNOTES.md

iperf-3.2 changed a constant that makes the pacing (the bitrate limitation with `-b`) smoother and less bursty.  iperf-3.1.5 also added an alternative pacing mechanism based on Linux per-socket fair queueing...it is controlled with the `--fq-rate` command-line option.  More details can be found in the release notes or in the manual page.

For your last use case, it might be that you need to adjust the `--pacing-timer` option.  Also note that if you are sending data using TCP, TCP itself has flow control and congestion control algorithms that will affect the rate at which packets are sent (and may contribute to burstiness).  The interactions between the different rate control mechanisms can be somewhat complicated.

Hope this helps.
