### ISSUE TITLE
Crash on iperf_test_free if test is used with SSL parameters

### ISSUE THREAD

**Issue by oleh-yudin-ring** [esnet/iperf#939]
# Context

* Version of iperf3:
3.7

# Bug Report

* Expected Behavior
No crash on call to API iperf_test_free()

* Actual Behavior
API iperf_test_free() call crashes when SSL parameters were used for the test

* Steps to Reproduce
- Init iperf_test with username password rsa_pub via C API. 
- Call iperf_test_free()

* Possible Solution
Add strdup() calls when setting string parameters to iperf_test like 
iperf_set_test_client_password(), iperf_set_test_extra_data(), iperf_set_test_client_username() + maybe others...

**Comment by bmah888** [comment]
That's `iperf_free_test()` but yeah we need to `strdup()` some of those strings.

**Comment by bmah888** [comment]
Started an `issue-939` branch to work on this.  I got the instances I know of, but I guess I really ought to make up some code to test this stuff.  @oleh-yudin-ring If you have a chance could you try your code against the version of the library on the `issue-939` branch and let me know if that works?

**Comment by oleh-yudin-ring** [comment]
Hello @bmah888 
Thanks! Yes, for my purpose I only use username, password and extra_data, so the fix from issue-939 branch solves the crash for me. Please also take a look at reported #940 with my proposed solution. It is also critical for the whole auth mechanism to work properly via C API.

**Comment by bmah888** [comment]
Thanks for testing!  I'll merge that branch to `master`.  I was in the middle of doing some other testing, where I was making the `iperf3` command use the API calls during argument processing.  That worked for testing this bug.  Then I started thinking the regular command should just use the API for everything.  But I think that's a change for another day.  I noticed #940 but I didn't get to look at it yet.

**Comment by oleh-yudin-ring** [comment]
Agree that's world be a nice thing to do if cmd line will work via API wherever possible.
If I may, for the future updates of API I would suggest all strings passed as arguments to API calls to be redesigned for 'const char *' instead of 'char *'. This would make life easier when calling them.
