### ISSUE TITLE
Using iperf to do udp test, but packet loss is always 0

### ISSUE THREAD

**Issue by luoyt14** [esnet/iperf#945]
hi, I want to use iperf to do udp test and get packet loss, but the packet loss is always 0. Can someone solve my problem? Thanks.

In server side, I use `iperf -s -u -i 1` and in client side I use `iperf -u -c 10.0.0.1 -t 10 -b 20m`. I use mininet to define the network and the bandsidth is set to 10m.

The results as follow:
![server](https://user-images.githubusercontent.com/13380504/71344684-33107b00-259e-11ea-9976-c4e32afd35ba.png)
![client](https://user-images.githubusercontent.com/13380504/71344692-37d52f00-259e-11ea-96d2-68a56bc730d6.png)

**Comment by bmah888** [comment]
It looks like you're running iperf2...this GitHub project is for iperf3.  You might try posting a message to the iperf-users mailing list.

I'm not sure off-hand why it's not giving you the results you wanted...if I had to guess it's something to do with the mininet environment.
