### ISSUE TITLE
Reported bitrate is higher than line speed

### ISSUE THREAD

**Issue by vondrous** [esnet/iperf#951]
iperf 3.7
APU2 platform / OpenWRT / TCP - 3 stream / host to host communication over gigabit line

In some reported interval we observerd that bitrate is not corred, this is often in tha case of the very first reportetd interval (which can be easily discarded from data set), but what is more important we observerd that incorect bitrate is sometimes reported in different intervals.

Incorect bitrate is higher tnan connection speed (in our case more than 1 Gbps on 1 Gbps line)

We observed this isue in JSON output with reporting interval set to 0.1 s. (in this case observed bitrate in one of the intervals was  1.8 Gbps). Bitrate in other intevals (600 intervals total) do not exceeds line speed.

The problem is probably caused by timing of intervals as previous reported interval was longer than expected and the interval causing troubles is much shorter than expected. The amount of reported transmited data is the same. Expected duration of inteval is 0.1 s in this measurement.  

{
			"streams":	[{
					"socket":	6,
					"start":	58.27002,
					"end":	58.304763,
					"seconds":	0.034742999821901321,
					"bytes":	2621440,
					"bits_per_second":	603618573.7415787,
					"retransmits":	0,
					"snd_cwnd":	1317212,
					"rtt":	7230,
					"rttvar":	1254,
					"pmtu":	1500,
					"omitted":	false,
					"sender":	true
				}, {
					"socket":	8,
					"start":	58.270035,
					"end":	58.304777,
					"seconds":	0.034742001444101334,
					"bytes":	2621440,
					"bits_per_second":	603635919.87475,
					"retransmits":	0,
					"snd_cwnd":	1286676,
					"rtt":	7806,
					"rttvar":	1132,
					"pmtu":	1500,
					"omitted":	false,
					"sender":	true
				}, {
					"socket":	10,
					"start":	58.270038,
					"end":	58.30478,
					"seconds":	0.034742001444101334,
					"bytes":	2621440,
					"bits_per_second":	603635919.87475,
					"retransmits":	0,
					"snd_cwnd":	1408820,
					"rtt":	6502,
					"rttvar":	1132,
					"pmtu":	1500,
					"omitted":	false,
					"sender":	true
				}],
			"sum":	{
				"start":	58.27002,
				"end":	58.304763,
				"seconds":	0.034742999821901321,
				"bytes":	7864320,
				"bits_per_second":	1810855721.2247362,
				"retransmits":	0,
				"omitted":	false,
				"sender":	true
			}
		},

**Comment by bmah888** [comment]
This isn't a bug really, it's just a transient effect at the start of the tests...I'd guess that a bunch of packets are getting sent from the iperf3 client (so they count in the statistics) but they're still sitting in the sender-side socket buffers or maybe the buffers for the network interface.  I'd guess that if you weren't using such short measurement intervals you might not see this effect.  For the subsequent intervals the system has time to get into a steady state so it produces more intuitive rates.

You can cause the first few measurement intervals to get discarded from the total statistics by using the `-O` (or `--omit`) flag.
