### ISSUE TITLE
iperf3 json output unparsable with bidir option set

### ISSUE THREAD

**Issue by blaines** [esnet/iperf#952]
# Context

* Version of iperf3: iperf 3.7 (cJSON 1.5.2)

* Hardware: Darwin Kernel Version 19.2.0

* Operating system (and distribution, if any): macOS 10.15.2 (19C57)

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

* Other relevant information (for example, non-default compilers,
  libraries, cross-compiling, etc.):

_Please fill out one of the "Bug Report" or "Enhancement Request"
sections, as appropriate._

# Bug Report

* Expected Behavior

Parsable JSON for bidirectional test with unique keys.

* Actual Behavior

This JSON cannot be processed:
<img width="439" alt="Screen Shot 2020-01-10 at 1 18 55 AM" src="https://user-images.githubusercontent.com/47128/72141581-fab3bf80-3347-11ea-8a48-7903d64f5c28.png">

Note duplicate keys `sum`, `sum_sent`, `sum_received` in the above JSON.

* Steps to Reproduce

`iperf3 -c hostname --bidir -J`

* Possible Solution

Perhaps a client -> server "TX" key, and a server -> client "RX" key?

**Comment by bmah888** [comment]
This is a real bug...someone sent an issue on this awhile back.  I'm trying to find the original instance of this bug being reported.

**Comment by pmankad96** [comment]
I recently ran into this bug. It is doing the right thing by reporting sum_sent and sum_received from client and server perspective. But it is being entered as duplicate entry. 

I was able to fix it by creating a list (sum) of dictionaries (dict1: sum_sent, sum_received, dict2: sum_sent, sum_received) and it worked. 

- Example with a work around:

>>> for key in x['end']:
...     print(key)
...
streams
sum
cpu_utilization_percent
sender_tcp_congestion
receiver_tcp_congestion
>>> type(x['end']['sum'])
<class 'list'>
>>> len(x['end']['sum'])
2
>>> x['end']['sum'][0]
{'sum_sent': {'start': 0, 'end': 10.000019, 'seconds': 10.000019, 'bytes': 11913396224, 'bits_per_second': 9530698870.872145, 'retransmits': 10, 'sender': True}, 'sum_received': {'start': 0, 'end': 10.038197, 'seconds': 10.038197, 'bytes': 11912034654, 'bits_per_second': 9493365913.420507, 'sender': True}}
>>> x['end']['sum'][1]
{'sum_sent': {'start': 0, 'end': 10.000019, 'seconds': 10.000019, 'bytes': 11916017664, 'bits_per_second': 9532796018.887564, 'retransmits': 1, 'sender': False}, 'sum_received': {'start': 0, 'end': 10.038197, 'seconds': 10.038197, 'bytes': 11913275632, 'bits_per_second': 9494354918.119259, 'sender': False}}
>>>

- Example without the work around:

>>> file2 = 'bidirStream2.json'
>>> y = fp.jsonParser(file2)
>>> for key in y['end']:
...     print(key)
...
streams
sum_sent
sum_received
cpu_utilization_percent
sender_tcp_congestion
receiver_tcp_congestion
>>>

**Comment by bmah888** [comment]
I'm definitely convinced that there's a bug here, and I know there are several alternatives for fixing it.  My main issue is trying to figure out the best way to fix it (get both tx and rx statistics) while at the same time not breaking backward compatibility with programs that were successfully reading the JSON for single-direction tests before.  Perhaps if an endpoint is doing only one direction we do the old format but if it's doing a bidirectional test we use an array that can handle the data for both directions.

**Comment by omrisaba** [comment]
When there will be new version availble with this fix?

**Comment by bmah888** [comment]
> When there will be new version availble with this fix?

There's no particular timeline for fixing it at this point.  It's not a difficult fix but it requires a bit of thought before jumping into implementation.
