### ISSUE TITLE
Checking received IP.DSCP value

### ISSUE THREAD

**Issue by bartoszwieczorek** [esnet/iperf#961]
I can check sent ip.dscp value in json logfile. However, can i check somehow received value? This value might be changed somewhere in a network.

**Comment by bmah888** [comment]
I don't think there's a way to see the received DSCP values on received packets, at least not with the standard BSD sockets interface.  They're not necessarily meaningful on the end host (as you indicated this field could be changed in the network).  If I needed to see this value, I'd probably use some packet capture mechanism such as tcpdump to see the header.  (I know that's not the same as having iperf3 just print the value, but that's all I can think about right now.)  Wish I could be of more help with this.
