### ISSUE TITLE
Update documentation on website to reflect new payload size default behavior

### ISSUE THREAD

**Issue by antiduh** [esnet/iperf#963]
The documentation located at https://iperf.fr/iperf-doc.php#3doc
does not reflect the changes to the defaults for the -l parameter, as discussed in #496, and #498

The page currently says:
"The length of buffers to read or write. iPerf works by writing an array of len bytes a number of times. Default is 128 KB for TCP, 8 KB for UDP. See also the -n, -k and -t options."

Instead, iperf now calculates the mss from the network adapter settings.

**Comment by bmah888** [comment]
The actual iperf3 manual page and help text (as distributed in the source code) correctly reflect the fact that the default UDP sending size is determined dynamically based on the path MTU (if known).  The Web site https://iperf.fr/ is not controlled by ESnet, and we have no control over the content displayed there, so unfortunately there isn't much we can do about it.  Multiple attempts to contact the site maintainer have failed.
