### ISSUE TITLE
Iperf3 Prompting for Password Despite IPERF3_PASSWORD Variable Present

### ISSUE THREAD

**Issue by ag100** [esnet/iperf#965]
Hello,

Sorry if I'm missing something here, but have been trying to get Iperf3 working with the IPERF3_PASSWORD environment variable, but it is not recognized by Iperf3 and it continues to prompt for a password.  I see the correct password when I echo the variable and the relevant check seems to be in the iperf_api.c file in the source.  I've also tried running the command with strace, but didn't see anything that stood out (or calls to the variable).

Apologies in advance if I'm a dolt and missed something obvious.

# Context

* Version of iperf3: 3.6 (built from source)

* Hardware: Raspberry Pi 4

* Operating system (and distribution, if any): Raspbian Buster Lite

_Please note: iperf3 is supported on Linux, FreeBSD, and macOS.
Support may be provided on a best-effort basis to other UNIX-like
platforms.  We cannot provide support for building and/or running
iperf3 on Windows, iOS, or Android._

# Bug Report

* Expected Behavior
Iperf3 should not prompt for password

* Actual Behavior
Iperf3 prompts for password

* Steps to Reproduce
Attempt to provide authentication credentials to client with IPERF3_PASSWORD variable set.

**Comment by bmah888** [comment]
Having the actual command lines you typed might be helpful but I'll take a guess at the problem (and I did test this, and it works for me).  On shells such as `/bin/sh` and `/bin/bash`, if you set an environment variable, you'll need to export that variable to child processes in order for them to see that value.  If you don't export it, the value of that variable effectively disappears in the child process, which might produce results like what you described.  So for example you would need to do something like this:
```
$ export IPERF3_PASSWORD='fubar'
$ iperf3 --client server.example.com --rsa-public-key-path publickey.pem --username bmah
```
Let me know if that helps.  If not, please send me some more information, in particular the shell commands you typed and the output (including error messages) you got back.

**Comment by ag100** [comment]
Thanks!  I was exporting the variable (tried on the command line, and in the bash profile).  Not sure if I was using single or double quotes or if that would matter.  I never got any errors, it just kept asking for the password when executing from the client.  Of course, yesterday, I rebuilt the iperf box, so I need to get everything setup again.  I hope to get that done over the weekend and will post back when done and testing again.  Thanks again!

**Comment by ag100** [comment]
Hello,

Sadly, still not having much luck.  Below are the commands I used and output.   I tried with the debug and verbose options, but didn't get additional data.  Thanks again for any thoughts.  I'm going to run another strace with the command tonight and see if I missed anything the first time around.  

Running: 
iperf3 -v
iperf 3.6 (cJSON 1.5.2)
Linux hostname 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

pi@host:~ $ export IPERF3_PASSWORD='fubar'
pi@host:~ $ echo $IPERF3_PASSWORD
fubar
pi@host:~ $ iperf3 --client iperf_server --rsa-public-key-path publickey.pem --username user
Password:

**Comment by ag100** [comment]
Hello,

While no closer to resolving the issue, it seems that the issue is specific to the Raspberry Pi (or my build/configuration).  I built the same version of iperf3 from source on a Debian system and it's not prompting for a password with the same command.  I'll continue to troubleshoot on my end, but it doesn't look like a problem with the code, so unless there are other troubleshooting steps you might have, I'll close this out.  Thanks again.

**Comment by bmah888** [comment]
I don't have any other insights at this point, unfortunately.  I was wondering a bit about the output from `iperf3 -v` in your comment a couple posts up...there should also have been a line about `Optional features available:` that includes something about `authentication`.  My dev tree compiles to something like this:
```
bmah-centos7:iperf% src/iperf3 --version
iperf 3.7+ (cJSON 1.5.2)
Linux bmah-centos7.localdomain 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64
Optional features available: CPU affinity setting, IPv6 flow label, SCTP, TCP congestion algorithm setting, sendfile / zerocopy, socket pacing, authentication
```

Just want to be sure that the version running on your rpi has that compiled in.  But if it didn't, iperf3 would have choked on the command-line options having to do with authentication, so I seriously doubt that's the problem.

**Comment by ag100** [comment]
Hey - Thanks for the response and help.  Yeah, authentication is compiled in as you said it probably is.  Lost on this one so will probably set it aside for now and see what else I can do to ensure only correct clients run against the server.  Thanks again for the help.

**Comment by bmah888** [comment]
OK.  I'm going to close this issue for now...we can re-open later if necessary.
