### ISSUE TITLE
Add option to run continuously with periodic short tests

### ISSUE THREAD

**Issue by brianjmurrell** [esnet/iperf#967]
# Context

* Version of iperf3: 3.7

* Hardware: OpenWRT router

* Operating system (and distribution, if any): OpenWRT

# Enhancement Request

* Current behavior

iperf runs a continuous bandwidth test reporting at intervals

* Desired behavior

iperf to run continuously, running time-limited tests at intervals.  For example, test bandwith for 2 seconds, sleep for 10, test for 2, sleep for 10, etc. only ending on SIGINTR (for example).

**Comment by bmah888** [comment]
I'm going to pass on this feature request.  I totally get the usefulness of this feature, but the timing and repeating behavior is probably best done by a shell script or a program such as pScheduler from the perfSONAR suite.  There's no particular reason it actually has to live inside iperf3.  Thanks for the suggestion!
