### ISSUE TITLE
Android and IOS support

### ISSUE THREAD

**Issue by lealog** [esnet/iperf#974]
# Enhancement Request
iperf3 Android and IOS support

* Current behavior
Can you plese add support for Android and IOS?

* Desired behavior
Android and IOS are natively supported

**Comment by bmah888** [comment]
There exist implementations of iperf3 on both the iOS App Store and Google Play Store.  You can find them fairly easily with a standard Web search.  Note that those mobile apps are created by third parties, derived from the iperf3 code base.  ESnet cannot of course provide support by third-party versions of iperf3.

We have at this time no plans to make any mobile-specific implementations of iperf3.
