### ISSUE TITLE
Missing a fundamental client option: the interface to use

### ISSUE THREAD

**Issue by mutluit** [esnet/iperf#976]
I have 5 NICs in my system, each has its own routing table, ie. fully independent, and need to start 5 clients at the same time to remote iperf3-servers.
This is basically to test the performance of the local NICs as a whole.
But it seems not possible to specify which local interface/IP an instance shall use.
As an example: the ping utility has for this the -I option where one can specify the local IP to use.
Such an option is needed in iperf and iperf3 too.

**Comment by lealog** [comment]
Yes. You can use the "-B" option.

Example:
- iperf3 -c 10.240.0.11 -B 192.168.1.65 -p 5001 -t 120 -b 0 -u --omit 2 -J --get-server-output

**Comment by mutluit** [comment]
Thanks everybody, yes in the newer iperf3 versions this luckily works indeed.
I had tested iperf and iperf3 on old Debian 8 boxes from the OS repository, and there somehow it didn't work, and research on the net indicated that according to the doc it should work, but in practice it doesn't.
Ok, the solution is to use the latest version, if necessary to compile it myself (just did this in fact, and yes it works fine).
