### ISSUE TITLE
iperf3: error - the server is busy running a test. try again later

### ISSUE THREAD

**Issue by mutluit** [esnet/iperf#980]
It seems multiple clients cannot connect at the same time as it then brings this error:
iperf3: error - the server is busy running a test. try again later

But imagine this situation:
a server has a 10G NIC attached to a 10G switch which has also many Gigabit ports.
Now, say 10 Gigabit clients shall connect at the same time to this 10G NIC to see the overall performance of the 10G NIC (ie. the sum of the 10 Gigabit clients).
Can this scenario not be tested with iperf3?

**Comment by mutluit** [comment]
Solved! The solution is to use iperf2 as iper3 is single-thread only, whereas iperf2 is multithread...

**Comment by terrancewong** [comment]
But isn't iperf3 a successor to iperf2?

**Comment by WatcherOfTheSkies** [comment]
> Solved! The solution is to use iperf2 as iper3 is single-thread only, whereas iperf2 is multithread...

I don't know whether it would have solved your issue but iperf3 >= version 3.16 is multi threaded.

**Comment by davidBar-On** [comment]
> I don't know whether it would have solved your issue but iperf3 >= version 3.16 is multi threaded

As far as I know, the difference is that a single iperf2 server can support several clients in parallel.
