### ISSUE TITLE
Additional TCP_INFO items

### ISSUE THREAD

**Issue by bmah888** [esnet/iperf#99]
_From [bltierney@es.net](https://code.google.com/u/117296441546344075535/) on November 04, 2013 15:06:22_

Explaination of new feature Currently we are using TCP_INFO to display TCP retransmission information.

There are other fields we might want to consider including as well. Perhaps in "verbose mode".

Here is the full list of fields:

```
        tcp_info.tcpi_last_data_sent,
        tcp_info.tcpi_last_data_recv,
        tcp_info.tcpi_snd_cwnd,
        tcp_info.tcpi_snd_ssthresh,
        tcp_info.tcpi_rcv_ssthresh,
        tcp_info.tcpi_rtt,
        tcp_info.tcpi_rttvar,
        tcp_info.tcpi_unacked,
        tcp_info.tcpi_sacked,
        tcp_info.tcpi_lost,
        tcp_info.tcpi_retrans,
        tcp_info.tcpi_fackets
```

I suggest we add the following:
            tcp_info.tcpi_snd_cwnd,
            tcp_info.tcpi_sacked,

Anything else folks would like added?

_Original issue: http://code.google.com/p/iperf/issues/detail?id=99_

**Comment by bmah888** [comment]
After some discussion with @bltierney we'd like to see if the SACK statistics are meaningful now (?).

**Comment by bltierney** [comment]
duplicate

**Comment by bmah888** [comment]
Commentary:  We'll file separate bugs for specific items from TCP_INFO that we want to see incorporated, as the need arises.

**Comment by bltierney** [comment]
reopen, as there is probably other stuff we could be able to add to the JSON.

**Comment by bmah888** [comment]
Need more clarity on what parts of TCP_INFO we really need.

**Comment by bltierney** [comment]
created new issue #569 to track this, so closing.
